### ISSUE TITLE
Recipient Creation with Token procured through Stripe.js

### ISSUE THREAD

**Issue by adamjzeuske** [jaymedavis/stripe.net#182]
Wonderful library!

I want to be able to use Stripe.js to get a bank account token, and then use it to create a recipient.  The following link suggests it should be possible to have the bank_account be a token (string) instead of the child collection of three account fields.  This would allow me to not post bank account information to my server.

https://stripe.com/docs/tutorials/sending-transfers

In looking at the code, I was thinking a new base class BankAccountToken and then perhaps a RecipentTokenCreateOptions, with the service knowing to just serialize the token instead of the child object, as seen in the API.

What are your thoughts?

Respectfully,
Adam

**Comment by jaymedavis** [comment]
Sorry this has been lingering for so long - 

It looks like with all the changes now, the class needs a StripeBankAccount and StripeCard or something similar. I think the BankAccountOptions might not work here anymore, or there is definitely a way to clean it up.

**Comment by jaymedavis** [comment]
This has been fixed in 2.7.0. When creating/updating a recipient, both options are now supported (card and bank account).
