### ISSUE TITLE
StripeInvoiceUpdateOptions - Require Application_Fee parameter

### ISSUE THREAD

**Issue by jmuker** [jaymedavis/stripe.net#204]
We would like to update an invoice with the correct application_fee amount, but the StripeInvoiceUpdateOptions does not have the property for "application_fee"

See the "invoices" section in the link below
https://stripe.com/docs/connect/collecting-fees

Is it possible to provide this property so that we can update the invoice?

StripeInvoiceService sis = new StripeInvoiceService();
sis.Update(stripeInvoice.Id, new StripeInvoiceUpdateOptions { Closed = true });

**Comment by jaymedavis** [comment]
this was fixed in the last release.
