### ISSUE TITLE
StripeDateTimeConverter does not round-trip through Json.Net serialization/deserialization

### ISSUE THREAD

**Issue by mattha** [jaymedavis/stripe.net#242]
When serializing to JSON, the converter writes out the DateTime in the Microsoft format, e.g. "\/Date(<epoch seconds>)\/". However, when deserializing, it only handles a bare integer (as returned by the Stripe API) or a format understood by DateTime.Parse.

I'm hitting this trying serialize and later deserialize a StripeCharge (the Created property is wrong after deserialization), but it appears to be generic to all Stripe entities that use StripeDateTimeConverter on DateTime properties.

**Comment by jaymedavis** [comment]
"Scenario: I'm trying to serialize the charge into my own DB, so I don't have to query Stripe for it later. However, upon reading it later, I get the wrong Created date." ... is it possible you could just use Stripe.net's stuff for deserialization? If not, I'm really not sure what to do about this pull request. You shoudl be able to serialize it as is, then just call StripeDateTimeConverter.ReadJson in some way to get your date back out. Closing this for now - if you come up with a way to fix it, feel free to submit a pull request.

**Comment by mattha** [comment]
I ended up using an anonymous type to capture the fields I wanted to serialize, which took the StripeDateTimeConverter out of the picture.
