### ISSUE TITLE
Add "metadata" property to StripeInvoiceUpdateOptions

### ISSUE THREAD

**Issue by ianschmitz** [jaymedavis/stripe.net#246]
The "metadata" property is missing from StripeInvoiceUpdateOptions, which means that I can't modify any metadata entries after an invoice has been created.

**Comment by jaymedavis** [comment]
Thanks for logging.

**Comment by jaymedavis** [comment]
this was missing a bunch of stuff, and had some obsolete properties. it will be out in the next release.

**Comment by ianschmitz** [comment]
Great to hear. Thanks for the hard work Jayme!
