### ISSUE TITLE
Support ACH charges!

### ISSUE THREAD

**Issue by jaymedavis** [jaymedavis/stripe.net#247]
Comments about this can also be found in #237.

(from email)

Hi Jayme,
Are you aware of Stripe's efforts to release ACH payments soon? My company is part of the private beta program for this. We use your Stripe.NET library, but need support for ACH. I have forked your library and am planning to make some additions/changes for this. I just wanted to know if you already knew about this and had done or planned to do some work to support it any time soon? If not, I'd like to discuss a few things about your library to make sure I implement this correctly, so that it can be pull requested in the future.

Thank you.

**Comment by kspearrin** [comment]
Referencing the gist link provided in #237, https://gist.github.com/raycmorgan/166e899cbb359768ad29

We will need to add support for `BankAccountOptions` and `CreditCardOptions` in `StripeCustomerCreateOptions`. Any suggestions on implementation of this? Right now you have them as two abstract classes that are inherited where needed. Do we need an additional `BankAccountCreditCardOptions` abstract class that can be used for things that accept both (like customer creation)?

**Comment by jaymedavis** [comment]
At one point in time, i think I inherited from both and it worked like a champ. Need to locate when/where i did this. 

StripeCustomerCreateoptions : CreditCardOptions, BankAccountOptions   ... I think.

**Comment by kspearrin** [comment]
You can't inherit from multiple abstract classes in C#.

**Comment by kspearrin** [comment]
I've got a working version of this going for our product. The Bank Account APIs are still very incomplete to officially pull request it into this library any time soon. It really needs to come out of beta before doing anything official. I'll be sure to pull request when satisfactory.

**Comment by jaymedavis** [comment]
Thanks @kspearrin.

**Comment by jaymedavis** [comment]
https://stripe.com/docs/api#create_customer ... looks like the BankAccount no longer exists in the docs (make sure your API is updated to the latest on your console, stripe.net will force you down anyway). Since this is beta and matches docs, I'm going to close for now. Feel free to re-open with a pull request. :)
