### ISSUE TITLE
Getting the subscription items on an invoice

### ISSUE THREAD

**Issue by benwmills** [jaymedavis/stripe.net#249]
I'm completely stuck on this after a ton of searching and I'd really appreciate some help.  I hope I'm missing something obvious.

I'm (amazingly) upgrading from Stripe API version 2011-11-17 and version 1.2.0 of Stripe.net.  In version 1.2.0, I could use the StripeInvoice.StripeInvoiceLines.StripeInvoiceSubscriptions property to get a list of the invoice line items that were created for subscriptions.  I dig into these to get the period that the invoice is paying for, which is actually different to the period specified on the invoice

In version 2.3.4, I don't have a StripeInvoiceSubscriptions property.  I just have the StripeInvoiceLines.  I believe this is a collection of StripeInvoiceItems, which are just the ad hoc items that you can add to the invoice.  Does it now include the invoice lines created from subscriptions?  It doesn't look like it.  I guess the question is, how do I access these:

https://stripe.com/docs/api#invoice_line_item_object

as opposed to these:

https://stripe.com/docs/api#invoiceitems

**Comment by benwmills** [comment]
I see that StripeInvoiceSubscription was removed based on API changes:

https://github.com/jaymedavis/stripe.net/commit/edd919e20b8bc8e97d9332013b1dd0cce2870466

but I still think there's a difference between the invoice line items (type = subscription or invoice item):

https://stripe.com/docs/api#invoice_line_item_object

and pure invoice items:

https://stripe.com/docs/api#invoiceitems

It's very confusing in the documentation.

I don't know if it helps explain the issue, but I have a web hook for successful charges.  My code pulls the invoice and looks at the subscription item that was paid in the invoice.  The subscription item references a period and I get the end date of the period to determine when my customer's account will expire.

I think I have a workaround where I can instead pull the upcoming invoice and use the date on that invoice.  It's a little icky, but I think it will work.

If you want to give me a little up front direction on this one, then I could try and create a branch.  First, do you agree there's an issue?  Second, what would you want to call the new object?  InvoiceLineItem?

**Comment by jaymedavis** [comment]
I see your problem - I had the same confusion in the documentation. It's because stripe appears to have two, but really there is just one. I fixed it in the most recent update (minus the period and type properties which will go out with the next release). 2.4.0 should contain more of what you expect.

**Comment by benwmills** [comment]
Thanks Jayme.  I can see that I'll have what I need with the type and period properties.  They really need to work on that section of the documentation.

**Comment by jaymedavis** [comment]
Agreed. :)

**Comment by intergleam** [comment]
so how do I pull subscription object from the webhook `InvoicePaymentSucceeded` or `ChargeSucceeded`?
