### ISSUE TITLE
Redirect when using Stripe connect

### ISSUE THREAD

**Issue by hsmith825** [jaymedavis/stripe.net#252]
Hi Jayme,
I am testing Stripe Connect.  I ran into one bump.  
I am trying to get authorization to connect to one of my customers account (me).  I submit the authorization URL, I approve the authorization with the correct scope.  My user is returned to the correct redirect.  I do not get a QueryString.  Here is the details:
My user is on an iPhone.
My backend is asp.net MVC
Request: https://connect.stripe.com/oauth/authorize?response_type=code&client_id=.............&state=36&scope=read_write
Everything looks OK when I am directed to Stripe.
I approve the request
I am returned to my redirect page.
The code snippet on the ASP.net server to parse the QueryString  is as follows:
            if (!string.IsNullOrEmpty(Request.QueryString["error"]))
            {
                [My code]
            }
            if (!string.IsNullOrEmpty(Request.QueryString["code"]))
            {
                [My code]
            }
I do not receive a QueryString.

Any help is appreciated.
Thanks for this library!  Easy to use!
Howard

**Comment by hsmith825** [comment]
My problem.  I had a Response.Redirect in the path anad I did not forward the Request.QueryString I received from Stripe.  The Request.QueryString from Stripe is correct.

**Comment by jaymedavis** [comment]
Thanks for letting us know.
