### ISSUE TITLE
How to know that card is the default card

### ISSUE THREAD

**Issue by harshchandra1984** [jaymedavis/stripe.net#255]
Hello 

I have two questions.

1) In StripeCardService, retrieved all the cards for the customers. There is no property in Json to tell if the card is default card. Does the API support it?

2) Same for adding a new card - StripeCardCreateOptions dont give any way to indicate that this new card is the default card.

Thanks

**Comment by jaymedavis** [comment]
It may be available, but not supported through stripe.net yet. Ask Stripe if this is possible first, then we are most likely missing something.

**Comment by harshchandra1984** [comment]
I figured it out from documentation. You have to use CustomerService and
set the default card id . May not be a very efficient way, but still works
for me.
           /* To make a particular as the custome default card */
            var userService = new StripeCustomerService(_privateKey);
            userService.Update(customerId, new StripeCustomerUpdateOptions
{ DefaultCard = cardId });

In case you are retrieving all the cards and wants to check if it is
default, I did following -

            var cardService = new StripeCardService(_privateKey);
            var userService = new StripeCustomerService(_privateKey);
            var user = userService.Get(customerId);
            return cardService.List(customerId).Select(c => new
            {
                CardId = c.Id,
                Name = c.Name,
                Brand = c.Brand,
                Last4 = c.Last4,
                ExpirationMonth = c.ExpirationMonth,
                ExpirationYear = c.ExpirationYear,
                IsDefault = user.StripeDefaultCardId == c.Id,
            });

Thanks for your help

**Comment by jaymedavis** [comment]
Thanks for documenting!
