### ISSUE TITLE
Retrieving your account, more fields needed

### ISSUE THREAD

**Issue by hsmith825** [jaymedavis/stripe.net#257]
In missing accounts their are a couple of fields that would be very helpful to us.  The fields are available in the Account object and they are as follows:
business_name
business_url
support_phone.

The account api is very helpful if you manage customers Stripe accounts.

We would appreciate it if you would add these fields.

Thanks!
hsmith825

**Comment by jaymedavis** [comment]
It looks like with my version I wont be able to add these fields just yet until I upgrade the API (I need this to happen soon for some other pull requests). there were a couple of others broken items on account i fixed though - will have an update out soon. Leaving this open though, it's not done yet.
