### ISSUE TITLE
Add Meta data to charges

### ISSUE THREAD

**Issue by hsmith825** [jaymedavis/stripe.net#258]
I use Stripe Connect.  I need a way to track my strike connect customers charges.  The only way I see to do that is by adding information to meta data.  I would appreciate it if you could add meta data to charges APIs.

Thanks!
hsmith825

**Comment by jaymedavis** [comment]
thanks for logging.

**Comment by jaymedavis** [comment]
meta data should have been included on the last releases StripeCharge entity, closing :)

**Comment by hsmith825** [comment]
Thanks!

 

Howard
