### ISSUE TITLE
Missing "Period" & "Type" property in StripeInvoiceLineItem

### ISSUE THREAD

**Issue by Chizzl** [jaymedavis/stripe.net#259]
StripeInvoiceLineItem is missing the "Period" and "Type" property.

https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Entities/StripeInvoiceLineItem.cs <> https://stripe.com/docs/api#invoice_line_item_object

You need this property if you would like to show the paid period for the upcoming invoice after a trial period of 14 days for example.

**Comment by jaymedavis** [comment]
Thanks for reporting!

**Comment by jaymedavis** [comment]
fixed - it'll make it to the next release.

**Comment by Chizzl** [comment]
Thanks! :)
