### ISSUE TITLE
Can't add Tax_Percent while adding a subscription to customer

### ISSUE THREAD

**Issue by Sachin4dotnet** [jaymedavis/stripe.net#260]
Hello,

First of all, <b>THANK YOU</b> so much for such a wonderful work.. It is very nice and very very easy to learn.

Now my question is regarding adding a subscription after a customer is created. I have used the DLL in my project, everything is running very smoothly. I can create a plan, create a new customer with that plan. 
<ul>
<li>My first question is "Can we create a customer with more than one plan? " I can see only one plan id is available for creating a new customer.
</li>
<li>
My second question is "How can we give tax_percent while creating a new subscription?". I can see there is an option for adding Quantity in the StripeSubscriptionCreateOptions even there is "ApplicationFeePercent" but there is no "<b>tax_percent</b>". 
</li>
</ul>

**Comment by Sachin4dotnet** [comment]
Ok Sorry, I have not seen that you already have updated that before some days..

You are genius man, Thanks so much..

**Comment by jaymedavis** [comment]
Your comment gave me a big :smile:. Thanks man. :)
