### ISSUE TITLE
Cannot deserialize the current JSON array for Stripe Events

### ISSUE THREAD

**Issue by raphlo** [jaymedavis/stripe.net#269]
Upgrading to version 2.5, the `Stripe.Mapper<StripeCharge>.MapFromJson` fails when converting to object.

Error is:
`Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Stripe.StripeRefundList' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'refunds', line 49, position 15.`

The Charge object sent from Stripe has a property refunds, but declared as an Array. Is this possible that could be the cause of the problem?

`{
  "id": "evt_15TDr62x7fc53h4bb9rOAX5W",
  "created": 1423235836,
  "livemode": false,
  "type": "charge.succeeded",
  "data": {
    "object": {
      "id": "ch_15TDr62x7fc53h4b5lc0wPTi",
      "object": "charge",
      "created": 1423235836,
      "livemode": false,
      "paid": true,
      "amount": 565,
      "currency": "cad",
      "refunded": false,
      "captured": true,
      "balance_transaction": "txn_15TDr62x7fc53h4bJHbPaMfT",
      "failure_message": null,
      "failure_code": null,
      "amount_refunded": 0,
      "customer": "cus_5eWuwyivH3yzsO",
      "invoice": "in_15TDr62x7fc53h4bH1ZdEDhy",
      "description": null,
      "dispute": null,
      "metadata": {},
      "statement_descriptor": null,
      "fraud_details": {},
      "receipt_email": null,
      "receipt_number": null,
      "shipping": null,
      "refunds": [],
      "statement_description": null
    }
  },
  "object": "event",
  "pending_webhooks": 1,
  "request": "iar_5eWuEuTPaUuN0c",
  "api_version": "2013-10-29"
}`
(I removed the card object from my example)

I'm using the same code example you provide here https://github.com/jaymedavis/stripe.net#receiving-events-from-stripe

Thanks

**Comment by raphlo** [comment]
In Entities/StripeCharge.cs, if I modify 
`[JsonProperty("refunds")]
public StripeRefundList StripeRefundList { get; set; }`
 to 
`
[JsonProperty("refunds")]
public List<StripeRefund> StripeRefundList { get; set; }
`
conversion works again. Why is that? What's the purpose of Entities/StripeRefundList.cs?

**Comment by jaymedavis** [comment]
That shouldn't work according to the documentation: https://stripe.com/docs/api#charge_object. There should be a few properties and then a 'data' property that actually contains the list. Perhaps it's because stripe.net forces you into an older version - none the less thanks for reporting, I'll get this patched asap.

**Comment by jaymedavis** [comment]
If you could post some json of a test object that you are seeing coming back, that would help clear it up (my guess is it wont match the newest docs)

**Comment by jaymedavis** [comment]
Actually, the stripe.net version is passed that update. Have you updated your API in the stripe console?

**Comment by jaymedavis** [comment]
Oh, whoops! This is my mistake!

i have the latest version in stripeconfiguration set to: "2014-07-22"

It should be set to "2014-07-26"

That change was this:

*Change refunds property on application fee responses from an array to a sublist object, which contains the total_count, has_more, url and data parameters. This makes application fee refunds consistent with charge refunds.* ... which is exactly what you are running into.

**Comment by jaymedavis** [comment]
Yeah, you must have to update your stripe api version, this is fine for me:

in the debugger running "when_refunding_a_charge":

![screen shot 2015-02-13 at 6 13 46 pm](https://cloud.githubusercontent.com/assets/171522/6196927/0817fc2a-b3ac-11e4-82b2-20d985f49e33.png)  

![screen shot 2015-02-13 at 6 14 11 pm](https://cloud.githubusercontent.com/assets/171522/6196934/15d2d8f8-b3ac-11e4-9e29-79f1bd83c451.png)

**Comment by raphlo** [comment]
Oh my god, I'm terribly sorry. You were right, I didn't update my Stripe version. In fact, I didn't know about that setting at all... I was still running on the 2013-10-29 version. Thanks to you, I wouldn't have noticed that! Now it's working like a charm! Great work by the way! You can close my dumb issue now :)

**Comment by jaymedavis** [comment]
No problem, glad it was no big deal! :)
