### ISSUE TITLE
How does this track w/ Stripe API version

### ISSUE THREAD

**Issue by kurtschindler** [jaymedavis/stripe.net#270]
At the time of writing this, stripe.net is v2.5.1 and the latest Stripe API version is 2015-01-26. How do I know this library is compatible w/ a particular API version?

**Comment by kurtschindler** [comment]
Answered my question after digging through previous issues and requests. For reference:

https://github.com/jaymedavis/stripe.net/pull/159
https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Infrastructure/StripeConfiguration.cs

I see the version is hard-coded in StripeConfiguration.cs (2014-07-22, as of writing) and that stripe.net is configured to send this version number in all requests, which serves to override whatever API version you have set in the Stripe dashboard.

I'll keep this issue open since I just created it and someone may wish to add additional comments... but feel free to close.

**Comment by jaymedavis** [comment]
That's correct - I'll leave this open for now so it can be documented in the readme. You aren't the first to ask. :)

**Comment by jt000** [comment]
Question: The StripeConfiguration says it supports 2014-07-22, but there have been changes for future api versions. Specifically StatementDiscriptor which was added in [version 2014-12-17](https://stripe.com/docs/upgrades#2014-12-17) substituting for statement_discription. Should the ApiVersion be updated? Better yet, should stripe.net be kept in sync with the current version of Stripe or was 2014-07-22 selected to provide back-compat or something? (I'd be willing to help out with this, but just not sure if its something that was intended for the API)

**Comment by jaymedavis** [comment]
added to the readme:
*Stripe.net forces a version of the Stripe API for which it was designed. You can find out the latest version support by viewing StripeConfiguration.cs under the Infrastructure folder.*
