### ISSUE TITLE
Recipient and a debit card

### ISSUE THREAD

**Issue by Cromathaar** [jaymedavis/stripe.net#276]
Hi. Is there currently a way to attach a debit card to recipient? As far as I see Stripe.NET uses BankAccountOptions as a base class for recipient entities, though I need to transfer money to recipient's debit card other than bank account.

**Comment by jaymedavis** [comment]
This is related to #239. This still needs to be developed.

**Comment by jaymedavis** [comment]
Fixed in 2.7.0.
