### ISSUE TITLE
Stripe Transfer Options only recipient bank account avaiable. No option to transfer to debit card.

### ISSUE THREAD

**Issue by Giovani-Brady** [jaymedavis/stripe.net#280]
Unable to commit transfers to recipients debit cards, lacking property via stripe api on the StripeCreateTransfersOption. (https://stripe.com/docs/api#create_transfer)

**Comment by Giovani-Brady** [comment]
addressed in 281

**Comment by Giovani-Brady** [comment]
#281

**Comment by jaymedavis** [comment]
closing - will handle there.
