### ISSUE TITLE
Create Charge: What happend to *cardId* string?

### ISSUE THREAD

**Issue by Giovani-Brady** [jaymedavis/stripe.net#282]
When Creating a Charge, how is the *cardId* passed to the Card property? Currently assigning a string data type to the Card object type property throws a compilation error.s

**Comment by jaymedavis** [comment]
You mean a token?

**Comment by jaymedavis** [comment]
I have updated the documentation - https://github.com/jaymedavis/stripe.net#creating-a-charge

Does that help?

**Comment by Giovani-Brady** [comment]
I don't think so, are the TokenId and the CardId interchangeable in the Card property?

myCharge.Card = new StripeCreditCardOptions() {
    TokenId = *tokenId*,  // this is the token, I understand that
 // other data 
};

myCharge.Card = *cardId*;  <--- *cardId* not the token Id but the stripe card ID string

**Comment by jaymedavis** [comment]
Oh I see, yeah - that's confusing. I need to add CardId back. Any other spots you can recall that cardid can also be passed, in addition to the full card or token?

**Comment by jaymedavis** [comment]
I've added 'CardId' back to StripeChargeCreateOptions. I'll do a patch tonight. Thanks so much for all of your help!!

**Comment by jaymedavis** [comment]
That looks like the only one I missed.

**Comment by Giovani-Brady** [comment]
I'd suggest just making the Card property dynamic, but if your method works as well great. Yeah I'll keep updating if any other issues arise. Thanks for the response today. Appreciate the support.

**Comment by jaymedavis** [comment]
Thank you so much for the help. It's tough doing a big release and wondering how it's going out there. :) ... I had someone on twitter help inform me my examples were all wrong now, so I got that fixed too.

**Comment by Giovani-Brady** [comment]
Best of luck to you. I understand, the struggle is real friend.

**Comment by jaymedavis** [comment]
:)

Done. 2.7.1 is live - I also snuck in your smaller pull request of the two! :+1:
