### ISSUE TITLE
Semantic Versioning....

### ISSUE THREAD

**Issue by niemyjski** [jaymedavis/stripe.net#283]
We've updated this package over the last few months and it seems like everytime we update to a minor version we have breaking changes that require us to modify code. Can we please update the major version any time that happens so we know we'll have to update code...

**Comment by jaymedavis** [comment]
It changes so often I would be at 11.0. :)

I will try to reduce the amount of breaking changes, but they are bound to happen. Sorry for the inconvenience - the documentation is updated for you to convert your code and I wouldn't estimate the code change taking very long. I like to reserve the majors for bigger things.

**Comment by niemyjski** [comment]
I agree, but that's the whole point of major versions :). Any breaking change in code is a major.

**Comment by jaymedavis** [comment]
I just read more about semantic versioning. I can go with that. Thanks for pointing it out.

**Comment by niemyjski** [comment]
Thanks for supporting/developing this project it's greatly appreciated.

**Comment by jaymedavis** [comment]
No problem. I put a note on the readme about versioning in the future: https://github.com/jaymedavis/stripe.net/blob/master/readme.md. 

Jayme
