### ISSUE TITLE
Tax field on StripeInvoice not nullable

### ISSUE THREAD

**Issue by akashbad** [jaymedavis/stripe.net#284]
It looks like the Tax property on the StripeInvoice class is not a nullable int? type like the other numeric properties on this class. The result is that running the following code returns the following exception if a customer's invoice doesn't have any applicable tax:
```
invoice = invoiceService.List(new StripeInvoiceListOptions()
                    {
                        CustomerId = stripeCustomer.Id
                    }).FirstOrDefault();
```
Exception:
```
Error converting value {null} to type 'System.Int32'. Path 'tax', line 67, position 14.
```
Currently this is preventing us from being able to list out customer invoices, which is a component of our subscription logic.

**Comment by akashbad** [comment]
I was able to get around this error by reverting to version 2.3.5 where the Tax property is not present on the StripeInvoice class. This prevents our code from failing but it would be great to use the most up to date version!

**Comment by jaymedavis** [comment]
Fixed, just pushed 2.7.2 - enjoy!

**Comment by akashbad** [comment]
Awesome, you're the best!

**Comment by troylanigan** [comment]
That's great! Thanks @jaymedavis :) It's bizarre that this issue came up as 2.6.0 was not throwing this exception for me yesterday. Was there a change on Stripe's end to make tax a nullable field?

**Comment by jaymedavis** [comment]
You're welcome. :)

If you were running an older version, I upgraded the api a lot over the past week, so I caught up with a lot of updates. They probably updated it at some point over that time frame and it's just now being noticed.
