### ISSUE TITLE
Hard to unit test, no interfaces

### ISSUE THREAD

**Issue by mouseflow** [jaymedavis/stripe.net#285]
Hi,

Thanks for creating this Stripe client. It's more complete than the ones from Xamarin and ServiceStack. However it's unnecessarily difficult to unit test any classes using this client because it doesn't use any interfaces and promotes newing up implementation objects such as "new StripePlanService()".

Have you considered making the library more mockable and TDD-friendly?

**Comment by jaymedavis** [comment]
Please search previous issues - this conversation has came up many times. :)
