### ISSUE TITLE
StripeCard object and CustomerID

### ISSUE THREAD

**Issue by janessaallen** [jaymedavis/stripe.net#286]
Hi, the StripeCard object does not appear to have the property for customer id. TIA!

**Comment by jaymedavis** [comment]
Hi - this does have Customer, which is an expandable property: https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Entities/StripeCard.cs ... it will either have an ID or the entire entity if you choose to expand it. Is this what you are referring to?

**Comment by janessaallen** [comment]
This has it but my version does not (2.3.0.0) I will check to see if I’m behind in versions. Thanks!

**Comment by jaymedavis** [comment]
Cool - re-open this if you still have trouble. :)
