### ISSUE TITLE
Problems updating an invoice

### ISSUE THREAD

**Issue by dabster** [jaymedavis/stripe.net#292]
Thanks for the great api client! I have run into a problem trying to use the new tax_percent field on invoices.  I am trying to update an invoice with a tax percent (see below):

            invoice.Taxes = taxes.ToList();
            invoice.TaxPercent = taxes.Sum(t => t.Rate)*100m;

            try
            {
                var options = new StripeInvoiceUpdateOptions()
                {
                    TaxPercent = invoice.TaxPercent
                };

                _invoiceService.Update(invoice.ExternalId, options);
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to add tax percent to invoice {0}", invoice.ExternalId);
            }

I am getting api error:

Stripe.StripeException was caught
  _HResult=-2146232832
  _message=Cannot forgive but also reopen invoice
  HResult=-2146232832
  IsTransient=false
  Message=Cannot forgive but also reopen invoice
  Source=Stripe.net
  StackTrace:
       at Stripe.Requestor.ExecuteWebRequest(WebRequest webRequest)
       at Stripe.Requestor.PostString(String url, String apiKey)
       at Stripe.StripeInvoiceService.Update(String invoiceId, StripeInvoiceUpdateOptions updateOptions)

In the stripe logs from the dashboard I am seeing this:

Parsed Request Query Parameters
{
closed: "False"
forgiven: "False"
tax_percent: "13.00"
}

Response Body
{
Error:
{
type: "invalid_request_error"
message: "Cannot forgive but also reopen invoice"
param: "forgiven"
}
}

The invoice is not closed or forgiven.  It seems like there is some validation in the api the closed and forgiven fields.  They are always included in the request as they are not nullable.  Am I doing something wrong?  Or is this a real issue.

Thanks

**Comment by jaymedavis** [comment]
Have you tried stripe support yet?

**Comment by dabster** [comment]
I just sent them a message, but couldn't this be solved by not including closed and forgiven attributes in the update request unless they have been set?

**Comment by jt000** [comment]
In the Stripe.NET the closed & forgiven properties aren't nullable, so they'll both be passed regardless if they are set or not. Apparently, Stripe gets confused when they're both passed as False (might be a bug on their end)

**Comment by dabster** [comment]
I talked to support this the response i was given:

The issue is ultimately that you are passing both `closed` and `forgiven` as parameters. These are not allowed to both be passed at the same time. If you wish to open the invoice, you will pass `closed: false`. If you wish to forgive the invoice, you should pass `forgiven: true`, but you should not be passing both (regardless of the values).

**Comment by jaymedavis** [comment]
Thanks for the info, closing this.

**Comment by dabster** [comment]
Can closed and forgiven fields be changed to nullable?  Otherwise updating an invoice will always result in an error.

**Comment by jaymedavis** [comment]
Oh, i'm sorry- i thought this was just a mis-understanding.

**Comment by dabster** [comment]
I had put in a pull request with the changes and a small unit test a month ago.  Think It might get reviewed soon?

https://github.com/jaymedavis/stripe.net/pull/296

**Comment by jaymedavis** [comment]
The only reason this didn't make the last release was it's a breaking change, so it has to wait for 3.0. I plan on doing all of the breaking changes in the next release. For now, I would recommend forking the latest codebase and adding the change to compile locally.

Closing this issue, will address in #296.

**Comment by jaymedavis** [comment]
#325 will need to be completed with this as well - and there may be more places around invoices that needs to be updated. I'll get it addressed during the next release.

**Comment by Giovani-Brady** [comment]
#325 addresses both Stripe Invoice scenarios (updating & creating) and is ready for code review.
