### ISSUE TITLE
You cannot use a Stripe token more than once

### ISSUE THREAD

**Issue by psmds** [jaymedavis/stripe.net#293]
I'm creating the customers using below code. 

var myCustomer = new StripeCustomerCreateOptions();
                myCustomer.Email = userModel.email;
                  myCustomer.Description = userModel.description;
                myCustomer.Card = new StripeCreditCardOptions()
                {
                    TokenId = userModel.AccountToken //stripeToken.Id
                    
                };
               var customerService = new StripeCustomerService();
               StripeCustomer stripeCustomer = customerService.Create(myCustomer);

after I created customer i try to create recipient using the same card token using below code 

var myRecipient = new StripeRecipientCreateOptions();
          myRecipient.Name=userModel.CardName;
           myRecipient.Type = userModel.type;                                      
  
                                                   
         myRecipient.Email = userModel.email;                            
          myRecipient.Description = userModel.description;  

myRecipient.Card = new StripeCreditCardOptions()
{
    
    TokenId = userModel.AccountToken

   
  
};

var recipientService = new StripeRecipientService();

StripeRecipient stripeRecipient = recipientService.Create(myRecipient);

i'm getting this error while executing this code "You cannot use a Stripe token more than once".

What I did wrong? Can you help me to solve this out.

**Comment by jt000** [comment]
The error code is right. You can't use the token generated by Stripe.JS more than once. Once you set it to a customer, then it cannot be reused for a recipient. You also won't be able to use the same card object for both a recipient & customer. You'll have to submit the card data 2x to get 2 tokens.

**Comment by psmds** [comment]
Hi jt000,

Thanks, Is this possible to create a recipient using "publishable key"?

I created a customer and associate a debit card using token(card). Now I want to credit to my customer card how to achieve this?

**Comment by jt000** [comment]
If I understand your situation, you want your application to broker charges between 2 people.

```
[Payer] -> $$$ -> [Your Service] -> $$$ -> [Payee]
```

If so, there is a couple different ways to handle this:

**The easy** way is to use (Stripe Connect)[https://stripe.com/connect] and let Stripe do all the dirty work for you. This flow would look something like:

```
[Payer] -> $$$ -> [StripeConnect] -> $$ -> [Payee]
                             |
                             +------> $ -> [Your Account]
```

This way both the Payer & Payee setup stripe accounts that they manage on their own & you simply connect the 2 parties & potentially take an "application fee".

**The hard way** is to do what it looks like you're starting to work out. That is to do all the charges to your stripe account and do manual transfers. This involves a lot of leg work & I wouldn't suggest doing it unless you're ready to set up a lot of systems to allow your users to handle charges, refunds, failed charges, invoicing, transfers, transfer fails, transfer cancels, and all the UI to show status. Not to mention all the additional legal work in writing up your terms & services... Trust me, don't go down this road unless you have to... :smile:

**Comment by psmds** [comment]
Thanks, In your library how to create  a charge using "source" i.e bitcoin Reciever ID?

**Comment by jt000** [comment]
**Note: Just to be clear, this isn't my library. @jaymedavis owns this repository. I'm just helping out where I can...**

Bitcoins aren't charges, they're a totally different way to get money into your balance. [Stripe's Bitcoin Guide](https://stripe.com/docs/guides/bitcoin) should get your started here.

**Comment by jt000** [comment]
*Note: Just to be clear, this isn't my library. @jaymedavis owns this repository. I'm just helping out where I can...*

Bitcoins are pretty new to Stripe & I don't think they've been added to Stripe.NET just yet.

**Comment by jaymedavis** [comment]
assuming this is resolved, closing
