### ISSUE TITLE
Using a token to make a charge, receipt same time?

### ISSUE THREAD

**Issue by artfulhacker** [jaymedavis/stripe.net#295]
Without passing the email around, can I issue a charge and send a receipt in one swoop?

The charge object should have an email in Source-> Name but is this property exposed inside your StripeCharge object?

**Comment by jaymedavis** [comment]
If it's in the stripe docs, you could link to those to save a little time. It's probably just missing and needs to be added. :)

**Comment by artfulhacker** [comment]
Happy to do that, but have you ever seen "name" populated with more than an email?

The API says cardholder name: https://stripe.com/docs/api#card_object

**Comment by jaymedavis** [comment]
Honestly, I haven't paid attention enough. :)

Name is exposed in StripeCard.

**Comment by jaymedavis** [comment]
closing this - not sure if anything is needed. :)
