### ISSUE TITLE
Unrecognized request URL (GET: /v1/charges/)

### ISSUE THREAD

**Issue by tytanmcbride** [jaymedavis/stripe.net#298]
I'm not sure if I'm doing something wrong, but I read your code to retrieve a charge, and it still isn't working. The code I have is:

Dim stripeCharge As Stripe.StripeCharge = chargeService.Get(My.Settings.ChargeID)

But when executed, I get an error message saying "An exception of type 'Stripe.StripeException' occurred in Stripe.net.dll but was not handled in user code. Additional information: Unrecognized request URL (GET: /v1/charges/).  Please see https://stripe.com/docs or we can help at https://support.stripe.com/."

Am I doing something wrong? I'm working with VB.Net.

EDIT: As soon as I replace "My.Settings.ChargeID" with the actual charge ID, it works fine.

**Comment by jaymedavis** [comment]
Thanks for the update - good luck on your app!
