### ISSUE TITLE
Silly question: Can this be built for .NET 1.1

### ISSUE THREAD

**Issue by jeveloper** [jaymedavis/stripe.net#303]
Thank you

I do have a legacy product.

**Comment by nate-fr** [comment]
I might be mistaken, but the JSON parser this project uses, doesn't even supports .NET 1.1

**Comment by jaymedavis** [comment]
Yikes, supporting 3.5 was a bit of work, 2.0 is a maybe. 1.1 ... I really doubt it. :(

Check this out, maybe it can be of some help:
http://stackoverflow.com/questions/5425841/calling-a-net-4-0-component-by-net-1-1
