### ISSUE TITLE
Support for Stripe Marketplaces

### ISSUE THREAD

**Issue by dazbradbury** [jaymedavis/stripe.net#307]
Hi,

Just thought I'd mention Stripe are soon to bring marketplaces out of beta - wondering if anyone has already implemented the new features into stripe.net?

Docs: https://stripe.com/docs/marketplaces

Thanks,
Daz.

**Comment by ryanulit** [comment]
+1 - Wondering that as well.  With recipients being deprecated, we would need to be able to create a managed account using the StripeAccountService, which currently doesn't exist.

**Comment by Giovani-Brady** [comment]
Recipients are being deprecated for all future versions of the Stripe API. This library targets the 02-10-2015 change log update specifically and the recipient object is still valid.

This should be updated to keep track of the latest Stripe API version.

**Comment by dcomcto** [comment]
+1 I need marketplace/connect functionality.

**Comment by causio** [comment]
We need to add Connection functionality to our platform, so I wanted to check if anyone is working on this and we could help, or if no one is working on it, we're going to start on it in the next week or so, so we'll be happy to contribute any of our changes.

**Comment by dcomcto** [comment]
Thomas - we have started the development for marketplace support today. If you think it makes sense to collaborate let me know. We also want to contribute it back to the project. Our fork is located here:

https://github.com/DemocracyVenturesInc/stripe.net

**Comment by jaymedavis** [comment]
Thanks all!

**Comment by causio** [comment]
We're happy to help with development if you need it, or just QA of the new code once it's ready. Do you have an internal timeline that you guys are aiming for?

**Comment by mathieukempe** [comment]
+1 for stripe connect

**Comment by Blakomen** [comment]
another +1 for stripe connect / managed accounts - https://stripe.com/docs/api#create_account

**Comment by jaymedavis** [comment]
Looks like the code from @dcomcto (went to your repo) has all the relevant work for managed accounts. Any chance you could rebase stripe.net and submit a pull request? :)

Are you using your version today @dcomcto in production and/or a tested environment?

**Comment by dcomcto** [comment]
We are using a version of it in production. It is a little messy. We are going to clean it up and push it over either late this week or early next. Sorry we are swamped.

**Comment by jaymedavis** [comment]
No need to apologize. Thanks much for the help!

**Comment by mathieukempe** [comment]
I've finished the work started by https://github.com/DemocracyVenturesInc/stripe.net

You can create / update accounts and upload documents (identity verification).
We are currently using the code on production but it's a bit messy too as it was pieced together quickly.

**Comment by jaymedavis** [comment]
Nice. that's a lot for one pull request, but it certainly can be a good example of how to implement it. Thanks for dropping a note.

**Comment by davidareddingJBS** [comment]
Any chance Connect will be added to the library on nuget in the next day or two?

**Comment by jaymedavis** [comment]
Nope. :)

**Comment by Giovani-Brady** [comment]
@jaymedavis 
I've returned, consider me on the case for the Connect expansion

**Comment by jbarker4682** [comment]
Hi everyone... I too am interested in Managed Accounts for Stripe.Net.  Anything I can do to help?

**Comment by jaymedavis** [comment]
I am practically finished with #348 to support stripe connect. The one bump I have is when I actually connect an account, then do the oauth dance, I get the access_token back. I then try to access the other account with the Stripe-Account header using that access token, but it keeps telling me unauthorized. If anyone has ran into this, I would appreciate the help.

**Comment by jaymedavis** [comment]
closing this, it will be handled with #348 (full connect support) and releasing very soon. I've created a new ticket for managed accounts #367 to be completed and referenced this ticket for the links above for links to where managed accounts are implemented.
