### ISSUE TITLE
Invoice Create - multiple parameter support

### ISSUE THREAD

**Issue by Chizzl** [jaymedavis/stripe.net#315]
At the moment we van only pass in the customer parameter to create an invoice immediately

https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Services/Invoices/StripeInvoiceService.cs

But Stripe can have multiple parameters > https://stripe.com/docs/api#create_invoice

E.g. I can not set a correct tax % on the invoice I want to create after plan change.

**Comment by jaymedavis** [comment]
this will be fixed with the next release (addressed in the pr)
