### ISSUE TITLE
Creating recipient SSN missing

### ISSUE THREAD

**Issue by psmds** [jaymedavis/stripe.net#319]
Hi,

I'm creating Recipient using Stripe.net but I unable to pass last four digits as SSN for "individual". It throws an error taxId should be 9 digits.

**Comment by Giovani-Brady** [comment]
As per:

https://stripe.com/docs/api#create_recipient

the TaxId property must be the full SSN for an "individual" and a full EIN for a "corporation" so the error is valid.

Also just a note the TaxId is Optional.

**Comment by jaymedavis** [comment]
Closing this, assumed @Giovani-Brady's answer was what you needed.
