### ISSUE TITLE
Is there a way to set the API version?

### ISSUE THREAD

**Issue by stjmarin** [jaymedavis/stripe.net#320]
I've been using the Stripe.Net.DLL (v1.6.1) against a Stripe account for about 2 years, and have recently been asked to use the same code for another Stripe account that was recently created.  Because the API versions are different, my code does not work with the new Stripe account, and Stripe support explained that there is a way to set the API version.

Does v 1.6.1 have functionality to set the API version?

**Comment by jaymedavis** [comment]
The api versions are hard coded in StripeConfiguration for what version the library was built for.

**Comment by stjmarin** [comment]
sorry for posting this, i found this answer after poking around the issues list.  I will upgrade to a version that contains the hard-coded version in the configuration.
