### ISSUE TITLE
Stripe.net unable to set application fee

### ISSUE THREAD

**Issue by psmds** [jaymedavis/stripe.net#326]
Unable to add application fee in StripeChargeCreateOptions. It throws an error Stripe.StripeChargeCreateOptions doesnot contain definition for an ApplicationFeeInCents and AmountInCents.

Can you please help me to solve this?

**Comment by Giovani-Brady** [comment]
Update the version of the Stripe.Net package you are using and update the integration code as per the latest documentation. https://github.com/jaymedavis/stripe.net reply if the update does not resolve this issue.

**Comment by psmds** [comment]
Thank you.
