### ISSUE TITLE
How do we update subscriptions? 

### ISSUE THREAD

**Issue by martynchamberlin** [jaymedavis/stripe.net#327]
This is looking like a great library—thanks!

At https://github.com/jaymedavis/stripe.net#updating-a-subscription I am not in clear understanding how we are supposed to update the subscription. 

At https://stripe.com/docs/guides/subscriptions#upgrading-or-downgrading-plans, for all of the libraries / languages you retrieve the subscription, change its plan, then save it. What's the equivalent here in C#?

**Comment by eigenheerc** [comment]
This is how I did it:
var cid = " [CustomerId]";
var sid = " [SubscriptionId]";
var pid = "[PlanId]";
StripeSubscriptionService ss = new StripeSubscriptionService();
StripeSubscriptionUpdateOptions uo = new StripeSubscriptionUpdateOptions();
uo.PlanId = pid;
var myUpdatedSubscription = ss.Update(cid, sid, uo);

**Comment by martynchamberlin** [comment]
Thanks, eigenheerc. This works perfectly for us!
