### ISSUE TITLE
Support for Stripe-Account header for connected accounts

### ISSUE THREAD

**Issue by sandeep-at-airlift** [jaymedavis/stripe.net#328]
As of now in Stripe.net the [suggested way](https://github.com/jaymedavis/stripe.net/pull/43#issuecomment-10903921) to support connected accounts for a platform is to use access_tokens for the connected account.

This can be cumbersome to manage for many connected accounts. Also could be a security hole if the access token is presentable by itself (have **not** verified this).

Stripe documentation [recommends](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header) using the platform secret key along with the Stripe-Account header set to the account id of the connected account. 

I could see adding a property to `StripeService` for the Stripe-Account id and then in `Requestor::GetWebRequest()` where the `WebRequest` is created set the header if this property is set. 

Only problem is there will be a proliferation of overloads on all services and new methods on `Requestor` as we can't support api-key and/or  Stripe-account-id as optional parameters.

Thoughts on how to fix this?

**Comment by jbarker4682** [comment]
I would create a RequestOptions class of some type, with these properties and then replace all references to any optional parameters with this class instead (ex: Foo(string apiKey, string accountId = null) becomes Foo(RequestOptions options) { ... }

**Comment by jaymedavis** [comment]
The one I'm floating around right now is having each service have properties like    UseConnectedAccountId = ... UseIdempotencyKey = .... 

With that said, I think this is a great idea and I will definitely experiment with that or a combination of the two. For this pull request, I'm going to close it in favor of managing the work on PR# #348
