### ISSUE TITLE
charging a new customer: there is no token with id card_

### ISSUE THREAD

**Issue by Eonasdan** [jaymedavis/stripe.net#331]
I'm running into an issue with creating a new customer using a token from stripe.js and creating a charge.

If I go back to the invoice and click submit using the same card (after a page refresh) it works just fine.

I can look at the Stripe Dashboard and see that the card ID does it exist. Is this an issue with your wrapper, Stripe, or my code?

```
// this has been stripped down 
//cardId = res.id (token) from stripe.js

var myCustomer = new StripeCustomerCreateOptions { Card = new StripeCreditCardOptions{ TokenId = cardId }};

var customerService = new StripeCustomerService();
var stripeCustomer = customerService.Create(myCustomer);
cardId = stripeCustomer.StripeDefaultCardId;

//stuff

ChargeCustomer(stripeCustomer.Id, invoice, cardId)
}


... void ChargeCustomer(string customerId, Invoice invoice, string cardId) {
var chargeOption = new StripeChargeCreateOptions
{
	Amount = (int)(invoice.GrandTotal * 100),
	Currency = "usd",
	CustomerId = customerId,
	CardId = cardId
};

var charge = new StripeChargeService();
var stripeCharge = charge.Create(chargeOption); //<-- fails with "There is no token with ID card_..."

//stuff

}
```

![image](https://cloud.githubusercontent.com/assets/1006516/7329470/c9451d1e-eaad-11e4-9c79-f86bfc1617ac.png)

![image](https://cloud.githubusercontent.com/assets/1006516/7329472/ce10f7fa-eaad-11e4-8d73-5dcfb1b7e0e0.png)

(This is in test mode so the card numbers are fake)

**Comment by jt000** [comment]
Maybe I'm overlooking it, but where did you set ```customerId```? It needs to be the id of the customer that owns the card (i.e. ```myCustomer.Id```)

**Comment by Eonasdan** [comment]
you mean `chargeOption` needs the customer Id?

**Comment by jt000** [comment]
If you set the card (now called source in the documentation) to a cardId associated to a customer, then you need to provide the customer Id as well. If you set it directly to the token (i.e. don't assign it first to a customer), then you don't need a customer assigned to it.

From [docs](https://stripe.com/docs/api#create_charge): *replace 'source' with 'card' for this version of the API*

> A payment source to be charged, such as a credit card. If you also pass a customer ID, the source must be the ID of a source belonging to the customer. Otherwise, if you do not pass a customer ID, the source you provide must either be a token, like the ones returned by Stripe.js, or a dictionary containing a user's credit card details, with the options described below. Although not all information is required, the extra info helps prevent fraud.

**Comment by Eonasdan** [comment]
ah ok.

**Comment by Eonasdan** [comment]
oops! Had a brain fart. I am passing in `customerId`. I've updated my example code in the original post

**Comment by jt000** [comment]
The exception doesn't make a lot of sense. It sounds like Stripe is expecting a token rather than a card id. Can you verify that customerId is correctly set & is the customer that contains the card in your stripe dashboard.

Another thing you can try is setting the cardId via the Card property rather than the CardId (if this works, then there's likely a bug in Stripe.NET)

```c#
var chargeOption = new StripeChargeCreateOptions
{
    Amount = (int)(invoice.GrandTotal * 100),
    Currency = "usd",
    CustomerId = customerId,
    Card = new StripeCreditCardOptions() { TokenId = cardId }
}
```

**Comment by Eonasdan** [comment]
Still getting an error:

```
var card = new StripeCreditCardOptions { TokenId = cardId };
if (String.IsNullOrEmpty(user.StripeCustomerId))
{
	var myCustomer = new StripeCustomerCreateOptions { Card = card };

	var customerService = new StripeCustomerService();
	var stripeCustomer = customerService.Create(myCustomer);

	user.StripeCustomerId = stripeCustomer.Id;
	
	cardId = stripeCustomer.StripeDefaultCardId;
}
else if (cardId.Contains("tok_")) //new card
{
	var myCard = new StripeCardCreateOptions { Card = card };
	var cardService = new StripeCardService();
	var stripeCard = cardService.Create(user.StripeCustomerId, myCard);
	cardId = stripeCard.Id;
}

ChargeCustomer(user.StripeCustomerId, invoice, card);


private void ChargeCustomer(string customerId, Invoice invoice, StripeCreditCardOptions card)
{
	var chargeOption = new StripeChargeCreateOptions
	{
		Amount = (int)(invoice.GrandTotal * 100),
		Currency = "usd",
		CustomerId = customerId,
		Card = card
	};

	var charge = new StripeChargeService();
	try
	{
		var stripeCharge = charge.Create(chargeOption); //fails token cannot be used twice
```

**Comment by jt000** [comment]
Looks like you set the card.TokenId to a token & then set cardId to the cardId, but yo never passed it to ChargeCustomer(...)

**Comment by Eonasdan** [comment]
I know. I changed the function to pass in the card instead of the cardId per your last recommendation.

I'm trying to create a customer if they don't already exist in Stripe and then charge that person with the card they just provided. As I understand the docs, a customer can be created with a token (which includes the CC).

Charging the customer takes a tokenId or a cardId. Since I'm using the token to create a customer I was using `cardId = stripeCustomer.StripeDefaultCardId;` to get the default card which in the case of a new customer is the only one they have on file.

My current issue is, with the latest API and Stripe.Net I cannot charge a **new** customer since it acts like the cardid doesn't exist.

If I change the code to use a `Card` instead I get `Token cannot be used twice`

If I include a `Card` ojbect on the `chargeOption` and use the `cardId`

```
var chargeOption = new StripeChargeCreateOptions
{
	Amount = (int)(invoice.GrandTotal * 100),
	Currency = "usd",
	CustomerId = customerId,
	Card = new StripeCreditCardOptions { TokenId = cardId }
};
```

I get:

`There is no token with ID card_15wDuJ2qgV2WIfVVCg9YeZL6`

**Comment by Eonasdan** [comment]
figured it out! even though I looked at that code block a hundred times in the last few days I missed the one line where I didn't assign the customerId back to the user in one place.

Thanks for your help
