### ISSUE TITLE
source_transaction missing from StripeTransfer

### ISSUE THREAD

**Issue by ronytesler** [jaymedavis/stripe.net#333]
I want to use the 'source_transaction' field, as described here:
https://stripe.com/docs/api?lang=ruby#create_transfer

**Comment by ronytesler** [comment]
I guess it's this class - StripeTransferCreateOptions

**Comment by jaymedavis** [comment]
Looks like there is a few things missing from this class according to the docs. Feel free to submit a PR or I will update it when I have the chance. Thanks!

**Comment by cwoolum** [comment]
This can be closed now

**Comment by jaymedavis** [comment]
Thanks!
