### ISSUE TITLE
StripeRefund object is missing the unique ID

### ISSUE THREAD

**Issue by geofili** [jaymedavis/stripe.net#334]
You are missing the unique id of the Stripe Refund object.

A typical refund object returned by stripe:

    "refunds": {
        "object": "list",
        "total_count": 1,
        "has_more": false,
        "url": "/v1/charges/ch_161YxkDoLougQZ637fPuTn7G/refunds",
        "data": [
          {
            "id": "re_161a9WDoLougQZ63J0xc0Lk4",
            "amount": 995,
            "currency": "usd",
            "created": 1431424698,
            "object": "refund",
            "balance_transaction": "txn_161a9WDoLougQZ63W00yNGaP",
            "metadata": {},
            "charge": "ch_161YxkDoLougQZ637fPuTn7G",
            "receipt_number": null,
            "reason": null
          }
        ]
      }

Note the unique ID of the refund object is: "id": "re_161a9WDoLougQZ63J0xc0Lk4",

This property is missing from the Stripe.NET refund object.

Maybe you could add....

    namespace Stripe
    {
        public class StripeRefund : StripeObject
        {
            [JsonProperty("id")]
            public string id { get; set; }

            ....etc...
        }
    }

**Comment by jt000** [comment]
That is defined in [StripeObject](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Entities/StripeObject.cs#L8). Is it not getting populated for you?

**Comment by geofili** [comment]
Sorry, my mistake.

I was parsing the JSON refund data directly into a StripeRefund object.

I now realize that I should parse the JSON data it into a StripeCharge object and then get the data from the child properties.

Therefore please ignore this issue request.

Thanks for the excellent work!
