### ISSUE TITLE
How to use Idempotency-Key 

### ISSUE THREAD

**Issue by fisherv1** [jaymedavis/stripe.net#341]
Hi,
Is it any way to use Idempotency-Key attribute via Stripe.Net?

I find this Idempotency-Key in Stripe official documentation, but can I use this feature via Stripe.Net?

Regards,
Matthew

**Comment by agrogan** [comment]
Matthew, did you ever figure this out?  I'm wondering the same thing.

**Comment by fisherv1** [comment]
Hi, 
It needs to modify the Stripe.Net project,  create a new method like GetWebRequestWithIdempotency in Requestor.cs
add the following line:
request.Headers.Add("Idempotency-Key", uniqueKey);

That solved my problem.

**Comment by jaymedavis** [comment]
Thanks for letting us know!

**Comment by fisherv1** [comment]
Thank you to make this project. It saves lots of my time when integrating the Stripe API to my project.

**Comment by agrogan** [comment]
Yes, thanks a bunch to both of you!
