### ISSUE TITLE
Just Received the Following While Deserializing a Charge Event

### ISSUE THREAD

**Issue by janessaallen** [jaymedavis/stripe.net#343]
Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Stripe.StripeList`1[Stripe.StripeRefund]' because the type requires a JSON object (e.g. {&quot;name&quot;:&quot;value&quot;}) to deserialize correctly.<br>To fix this error either change the JSON to a JSON object (e.g. {&quot;name&quot;:&quot;value&quot;}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List&lt;T&gt; that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.

Was there possibly a change to their API?

**Comment by janessaallen** [comment]
I'm checking with Stripe now, because this is an event in the test environment and I'm checking with them to see if it is formatted correctly.

**Comment by jt000** [comment]
Could you post some code? Is this using the ChargeService or do you have a JSON string that you're deserializing? *If the latter can you post the JSON scrubbed of [PII](http://en.wikipedia.org/wiki/Personally_identifiable_information)*

**Comment by janessaallen** [comment]
This is the webhook:

{
            "id": "evt_165JcV2CCxXm1lxq4oVP7g0b",
            "created": 1432314459,
            "livemode": false,
            "type": "charge.succeeded",
            "data": {
                "object": {
                    "id": "ch_165JcU2CCxXm1lxqMTZHrSeW",
                    "object": "charge",
                    "created": 1432314458,
                    "livemode": false,
                    "paid": true,
                    "status": "paid",
                    "amount": 6421,
                    "currency": "usd",
                    "refunded": false,
                    "source": {
                        "id": "card_165GRg2CCxXm1lxqaKYrTA6h",
                        "object": "card",
                        "last4": "4242",
                        "brand": "Visa",
                        "funding": "credit",
                        "exp_month": 5,
                        "exp_year": 2019,
                        "fingerprint": "mK55pA7kTC2aL2Na",
                        "country": "US",
                        "name": "Janessa B Allen",
                        "address_line1": "8923 Darcy Hopkins Dr.",
                        "address_line2": null,
                        "address_city": "Charlotte",
                        "address_state": "North Carolina",
                        "address_zip": "28277",
                        "address_country": null,
                        "cvc_check": null,
                        "address_line1_check": "pass",
                        "address_zip_check": "pass",
                        "dynamic_last4": null,
                        "metadata": {},
                        "customer": "cus_6HVGZbiamLeDry",
                        "type": "Visa"
                    },
                    "captured": true,
                    "card": {
                        "id": "card_165GRg2CCxXm1lxqaKYrTA6h",
                        "object": "card",
                        "last4": "4242",
                        "brand": "Visa",
                        "funding": "credit",
                        "exp_month": 5,
                        "exp_year": 2019,
                        "fingerprint": "mK55pA7kTC2aL2Na",
                        "country": "US",
                        "name": "FirstName LastName",
                        "address_line1": "Address",
                        "address_line2": null,
                        "address_city": "Charlotte",
                        "address_state": "North Carolina",
                        "address_zip": "28277",
                        "address_country": null,
                        "cvc_check": null,
                        "address_line1_check": "pass",
                        "address_zip_check": "pass",
                        "dynamic_last4": null,
                        "metadata": {},
                        "customer": "cus_6HVGZbiamLeDry",
                        "type": "Visa"
                    },
                    "balance_transaction": "txn_165JcV2CCxXm1lxqBOAQXjQp",
                    "failure_message": null,
                    "failure_code": null,
                    "amount_refunded": 0,
                    "customer": "cus_6HVGZbiamLeDry",
                    "invoice": "in_165HIy2CCxXm1lxqUrexdcsa",
                    "description": null,
                    "dispute": null,
                    "metadata": {},
                    "statement_descriptor": null,
                    "fraud_details": {},
                    "receipt_email": "test@test.com",
                    "receipt_number": null,
                    "shipping": null,
                    "destination": null,
                    "application_fee": null,
                    "refunds": [],
                    "statement_description": null
                }
            },
            "object": "event",
            "pending_webhooks": 1,
            "request": null,
            "api_version": "2014-03-28"
        }

and then it's failing on the creation of the charge in the code block below:

public void ChargeEvent(StripeEvent stripeEvent)
        {
            StripeCharge charge = Stripe.Mapper<StripeCharge>.MapFromJson(stripeEvent.Data.Object.ToString());
            ProfileModel profile = unitOfWork.ProfileRepository.Get(x => x.CustomerId == charge.CustomerId).FirstOrDefault();
            if (profile != null)
            {
                InvoiceModel invoice = unitOfWork.InvoiceRepository.Get(x => x.InvoiceId == charge.InvoiceId).FirstOrDefault();
                if (invoice != null)
                {
                    invoice.Last4 = charge.StripeCard.Last4;
                    invoice.Brand = charge.StripeCard.Brand;

                    unitOfWork.InvoiceRepository.Update(invoice);
                    unitOfWork.Save();
                }
            }
        }

**Comment by jt000** [comment]
Please scrub the PII (personally identifiable information). I doubt Janessa would like her address posted on the web like this...

Also, if you surround it with \``` characters, then it will be formatted correctly. [Click here for explanation of markdown](https://help.github.com/articles/github-flavored-markdown/).

-------

A couple of suggestions:

**First:** *(likely unrelated, but important)* Don't use the object that is in the event. Instead refetch the object from the server. This is because if an event is delayed or resent, then it may contain stale data. 

**Second:** Your issue might be due to the Stripe API version. Looks like it is returning an event for API version "2014-03-28" while Stripe.NET is supporting version "2015-02-10". You can update your API version in your [Stripe Dashboard](https://dashboard.stripe.com/account/apikeys).

**Third:** You can just use JObject.ToObject<StripeCharge>() to deserialize. Not sure if the Mapper was intended to be used in this way or not...

``` C#
var jObject = (JObject)stripeEvent.Data.Object;
charge = jObject.ToObject<StripeCharge>();
```

**Comment by janessaallen** [comment]
That's  me but I'll edit.

**Comment by janessaallen** [comment]
Thanks. It's probably the API update that is required.

**Comment by janessaallen** [comment]
Thank you! That was it. I didn't realize that the versions had to be controlled on the dashboard. Thanks again for all the info and feedback.
