### ISSUE TITLE
Add subscription ID to StripeInvoiceItemCreateOptions

### ISSUE THREAD

**Issue by westaj** [jaymedavis/stripe.net#344]
Stripe API now has an option to specify the subscription when adding an invoice item. This is useful if an invoice item needs to be added to an upcoming invoice when the user has multiple subscriptions.

Can you please add this property to StripeInvoiceItemCreateOptions?

Thanks

**Comment by westaj** [comment]
Also, it would be helpful if the subscription ID was also added to the StripeInvoice entity object.

**Comment by jaymedavis** [comment]
both of these are fixed for the next release (Which I happen to be working on right now) :)

**Comment by westaj** [comment]
Awesome! Thanks Jayme.

**Comment by jaymedavis** [comment]
You're welcome, sir. :)
