### ISSUE TITLE
Destination parameter for Create a charge

### ISSUE THREAD

**Issue by hsmith825** [jaymedavis/stripe.net#345]
We desperately need to control the charges that appear on our customers credit card statements.  This is accomplished with the destination parameter of Create a charge. Although it is a parameter in the Stripe's API, it is not in this supported in this library.  How can I use the destination parameter with this library.

**Comment by mmalone120** [comment]
See here:  https://github.com/jaymedavis/stripe.net/pull/338/files?diff=split

Took a couple minutes to add and it's working great for me.

Btw, thanks Jayme!  Great work.

**Comment by hsmith825** [comment]
Thanks Jayme!  It worked!  Outstanding!

**Comment by jaymedavis** [comment]
Glad things are well! Thanks!

**Comment by shivam145** [comment]
link is not working, 404 error

**Comment by remi-stripe** [comment]
@shivam145 You should talk to our support team directly: https://support.stripe.com/email

**Comment by jaymedavis** [comment]
https://github.com/stripe/stripe-dotnet/pull/338/files?diff=split

Replace any links containing *jaymedavis/stripe.net* with *stripe/stripe-dotnet*
