### ISSUE TITLE
StripeInvoiceItemCreateOptions still missing Subscription attribute

### ISSUE THREAD

**Issue by westaj** [jaymedavis/stripe.net#347]
Hi. With the latest updates I can retrieve the subscription ID from the invoice but the attribute is not available to set this when creating InvoiceItems (as per Stripe API documentation).

Thanks.

**Comment by lmcnearney** [comment]
:+1:

**Comment by jaymedavis** [comment]
You're all set.

**Comment by westaj** [comment]
Awesome. Thank you so much!




On Sat, Jul 11, 2015 at 3:55 PM -0700, "Jayme Davis" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #347<https://github.com/jaymedavis/stripe.net/issues/347>.

-
