### ISSUE TITLE
StripeChargeCreateOptions Card and CardId share same JsonProperty name "card"

### ISSUE THREAD

**Issue by shantali** [jaymedavis/stripe.net#350]
In the StripeChargeCreateOptions class, Card and CardId share the same JsonProperty("card") name. 

I serialize the class for logging purposes, and serialization errors with "A member with the name 'card' already exists on Stripe.StripeChargeCreateOptions."

**Comment by jaymedavis** [comment]
I believe the CardId property should be removed in favor of using Token on the CreditCardOptions object. However, the entire thing needs to be reworked to make it 'source' for Stripe's latest api anyway. That would probably be an ideal time to fix it.

**Comment by jaymedavis** [comment]
this was fixed with the latest release - it's now just 'Source'
