### ISSUE TITLE
Reactivating a canceled subscription that hasn't hit the end of current billing period.

### ISSUE THREAD

**Issue by bfelda** [jaymedavis/stripe.net#352]
After a subscription is canceled with the CancelAtPeriodEnd bool set, reactivating should just take an update to set the CancelAtPeriodEnd back to false.  From what I understand, this means that the CancelAtPeriodEnd bool should be available in the StripSubscriptionUpdateOptions for updating a subscription.

**Comment by lubos** [comment]
No, you don't need that option.

Have a look at this Stripe answer
https://support.stripe.com/questions/how-can-i-resume-a-subscription-after-it-has-been-canceled

It means if you want to reactivate subscription, use `Update` method and in `StripeSubscriptionUpdateOptions` set `PlanId` (PlanId can be the same so you are not really updating anything)

I know it's a bit strange but I just tested it and it worked.

**Comment by jaymedavis** [comment]
That option actually isn't available according to the docs - https://stripe.com/docs/api#update_subscription. Thanks @lubos for helping out!
