### ISSUE TITLE
Add the possibility to specify subscriptionPlanId when reterieving an upcoming invoice

### ISSUE THREAD

**Issue by AndrewKaplanovsky** [jaymedavis/stripe.net#354]
We really need the possibility to specify a Stripe plan ID when retrieving an upcoming invoice:

Stripe/Services/Invoices/StripeInvoiceService.cs

public virtual StripeInvoice Upcoming(string customerId, string subscriptionId = null, string subscriptionPlanId = null)
{
     var url = string.Format("{0}/{1}", Urls.Invoices, "upcoming");
     url = ParameterBuilder.ApplyParameterToUrl(url, "customer", customerId);
     
     if(!String.IsNullOrEmpty(subscriptionId))
          url = ParameterBuilder.ApplyParameterToUrl(url, "subscription", subscriptionId);
     
     if (!String.IsNullOrEmpty(subscriptionPlanId))
          url = ParameterBuilder.ApplyParameterToUrl(url, "subscription_plan", subscriptionPlanId);

     var response = Requestor.GetString(url, ApiKey);

     return Mapper<StripeInvoice>.MapFromJson(response);
}

**Comment by AndrewKaplanovsky** [comment]
Sorry, I was unable to create a pull request, got an error "No access". I specified the code above.

**Comment by jaymedavis** [comment]
Thanks - this looks pretty simple. I'll get it added asap. I'll take a deeper look later, but it looks like the added parameter is all that was changed.

**Comment by jaymedavis** [comment]
It looks like lots of other fields have been added to Upcoming. This actually will need to be refactored to have a StripeUpcomingInvoiceOptions. The only required field is customer, so I would like to move subscription ID to this object, they plan id you added, and all of the other properties documented on stripe's site. https://stripe.com/docs/api#retrieve_customer_invoice

**Comment by AndrewKaplanovsky** [comment]
Got it. Jayme, thank you very much!

**Comment by jaymedavis** [comment]
Closing - done a long time ago. :)
