### ISSUE TITLE
Charge source property missing

### ISSUE THREAD

**Issue by jaredthomas1** [jaymedavis/stripe.net#357]
Where is the option to set the charge source rather than the customer id? StripeChargeCreateOptions does not have a source property, as shown on the stripe api documentation  https://stripe.com/docs/api/node#create_charge
This causes a "Must provide source or customer." when paying with a token.

**Comment by jaymedavis** [comment]
stripe.net has not been updated to support source yet, it is on an api version behind that release. However, I have completed the upgrade for source and that release will be coming soon.

**Comment by jaymedavis** [comment]
for now, set Card instead - and make sure your stripe api version matches the version in StripeConfiguration.cs

**Comment by jaymedavis** [comment]
btw - this is live now in 4.0.0 :)
