### ISSUE TITLE
Updating Card

### ISSUE THREAD

**Issue by Jacobus75** [jaymedavis/stripe.net#358]
Hi There, previous version you could update card with token which was great as we are not using the card on our server (for cpi reasons). The new source implementation I noticed there is no token option. I use the repository with my VB project and works great, thanks!

**Comment by jaymedavis** [comment]
Are you on Customer/Charge/Card? code exmaple?

CardId is no longer available alongside Card. You will have to access item.Source.Token

also - download 4.0.1 asap, 4.0 had an issue I had to fix.

**Comment by jaymedavis** [comment]
assume you are good here - closing

**Comment by Jacobus75** [comment]
Hey Jayme, sorry for the delay. I am implementing the upgrade and will use item.Source.Token. We are still using the V2.00 of your repository and working well, but going to upgrade to V4.01. Thanks for your feedback
