### ISSUE TITLE
Creating a charge with a token id results in invalid request

### ISSUE THREAD

**Issue by matthijskoopman** [jaymedavis/stripe.net#359]
When creating a charge with a token id, the requested created doesn't include the token id, but results in:
https://api.stripe.com/v1/charges?amount=2000&currency=usd&source=Stripe.StripeSourceOptions&description=test&capture=True 

Using this code:

```
var charge = new StripeChargeCreateOptions()
    {
        Amount = paymentInfo.Amount,
        Currency = paymentInfo.Currency,
        Description = paymentInfo.Description,
    };

charge.Source = new StripeSourceOptions()
        {
            TokenId = paymentInfo.Token,
        };

charge.Capture = true;
```

**Comment by jaymedavis** [comment]
can you paste whatever builds paymentInfo.Token?

**Comment by matthijskoopman** [comment]
It's a class instance being populated with `[FromBody]`
This is the class def:

```
public class StripePayment
{
    #region Properties

    public string Token { get; set; }
    public string Currency { get; set;}
    public string Description { get; set; }
    public int Amount { get; set; }

    #endregion
}
```

**Comment by jaymedavis** [comment]
I have the problem duplicated, I have no idea why my tests did not catch this. I'm working on it now.

**Comment by matthijskoopman** [comment]
Thanks!

**Comment by jaymedavis** [comment]
I've got this particular problem figured out, but I'm trying to fix some more issues with the tests. For some reason, my test runner decided to pass everything even when it failed. Good times.

**Comment by jaymedavis** [comment]
4.0.1 pushed - still a couple of tests failing, but it's around DefaultSource (and I don't have time to fix this morning, I have to work) :) 

Your issues should be resolved. 4.0.1 on nuget.

**Comment by trnelson** [comment]
Good stuff Jayme, working now for me too. I was hoping I wasn't using the new API wrong. Thanks for fixing so fast, and for the great tool!

**Comment by jaymedavis** [comment]
You're very welcome. Thanks for the kind words. :)

**Comment by matthijskoopman** [comment]
Thanks, I'll give it a try later on today.
