### ISSUE TITLE
The source hash must include an 'object' key indicating what type of source to create.

### ISSUE THREAD

**Issue by DarrylGlb** [jaymedavis/stripe.net#360]
Hello,

When I try to create a new customer using the example on the main page I get the following error:

"The source hash must include an 'object' key indicating what type of source to create."

I'm not sure if I'm missing an attribute or if this is a bug.  I just installed stripe.net from Nuget a few hours ago (Stripe.net.4.0.2).  

Thank you for your help!

**Comment by jaymedavis** [comment]
This is telling you to specify the type of object for the source. 

For example, if this is a credit card, you will need to set myCustomer.object =  'card', I believe.

Let me know if this solves your problem!

**Comment by DarrylGlb** [comment]
You nailed it; I needed to add that line for the customer's credit card.  Thank you for your help!!

**Comment by jaymedavis** [comment]
Glad to help - I'm going to reopen this as a reminder to get it in the documentation.

**Comment by ghandlin** [comment]
I landed here from the "object" issue as well, and setting it to "card" got me beyond that. However, now I'm getting an error saying the expiration year is invalid. Well, 2018 certainly is not. I'm going against my test api key using the "42...42" credit card number.

I've successfully created plans, so I know I'm connecting correctly. Thx for any help - and what a wonderful library you've put together.

**Comment by jaymedavis** [comment]
Verify with stripe you are using correct test #'s first. Some test #'s have specific exp dates you have to use.

**Comment by ghandlin** [comment]
Got it ... thank you. I searched for test cards and the problem was actually that I wasn't sending in the CVC code. Seems stripe has a bad error message on that one. Anyway, thx again!

**Comment by lreb** [comment]
Thank you for your help!

**Comment by matthieunelmes** [comment]
Hate to be a stickler but this is still missing from the documentation along with a missing semicolon after specifying the StripeSourceOptions

**Comment by jaymedavis** [comment]
I've been out of town for work for 2 weeks - submit a PR and I can merge from my phone.

**Comment by vishnutm** [comment]
```
function createCustomerAndSubscription(requestBody) {
  return stripe.customers.create({
    source: requestBody.stripeToken,
    email: requestBody.customerEmail,

  }).then(customer => {
    stripe.subscriptions.create({
      object: customer.object,
      customer: customer.id,

      items: [
        {
          plan: requestBody.planId
        }
      ],
      collection_method: 'send_invoice',
      days_until_due: 30
    });
    console.log("customerDetails ", customer);
  });

}
```
when I tried to create customer and subscription using the above function I got the same error. my payment method card number is 4242 4242.etc

error Response:
"subscription err=  Error: The source hash must include an 'object' key indicating what type of source to create." something like this" . i don't know what is happening..?. Help needed.
