### ISSUE TITLE
WARNING: 3.5 SUPPORT TO BE DROPPED

### ISSUE THREAD

**Issue by jaymedavis** [jaymedavis/stripe.net#362]
I am looking to drop 3.5 support from the library. With features like async #237, it is difficult and cumbersome in the code to manage.

If you have any feedback, please feel free to respond. Thanks!

**Comment by jaymedavis** [comment]
For anyone following this issue, I've emailed stripe support to see if we can specify a user agent for 3.5 to gather usage statistics in the coming months. This is important for implementing #237 (async support) without the code becoming a mess.

**Comment by adaam2** [comment]
Is there any update on 3.5 usage? I would quite like to implement the async methods.
