### ISSUE TITLE
Token Id does not exist (migrating to 4.1.0 from 2.3.4)

### ISSUE THREAD

**Issue by artemlos** [jaymedavis/stripe.net#363]
Hi!

I tried to upgrade from v. 2.3.4 to the latest version (v.4.1.0) and got the error that the `TokenId` no longer exists in `StripeChargeCreateOptions`. The implementation I'm using is:
```
  var myCharge = new StripeChargeCreateOptions
  {
      Amount = (int)(model.Amount * 100),
      Currency = model.Currency, 
      Description = model.Item,
      TokenId = model.Token   
  };
```

Does anyone know if there is a different way of passing the `TokenId` to Stripe.NET to process a payment? The reason why it is needed here is because I'm using an implementation that uses both Stripe.js and Stripe.NET (the server side never gets hold of credit card information).

Thank you in advance!

/Artem

**Comment by jaymedavis** [comment]
Please review the README. Token is now on StripeCreditCardOptions.
