### ISSUE TITLE
API Description actualization

### ISSUE THREAD

**Issue by vs-krasnov** [jaymedavis/stripe.net#364]
Noticed that API description refers to not existing method StripeChargeService.Refund():
https://github.com/jaymedavis/stripe.net#refunding-a-charge

What is a proper way to perform refund?

**Comment by mexner** [comment]
I just discovered this yesterday too. Here is how I solved it,
```
/// <summary>
        /// If you do not specify an amountInCents, the entire charge is refunded. The StripeCharge entity has properties for "Refunded" (bool) and RefundedAmountInCents.
        /// </summary>
        /// <param name="chargeId"></param>
        /// <param name="amtInCents"></param>
        /// <returns></returns>
        public StripeRefund ChargeRefund(string chargeId, int? amtInCents)
        {
            try
            {
                var refundService = new StripeRefundService(_apiKey);
                var refundOptions = new StripeRefundCreateOptions {Amount = amtInCents};
                var stripeRefund = refundService.Create(chargeId, refundOptions);

                return stripeRefund;
            }
            catch (StripeException excStripe)
            {
                var m = excStripe.StripeError.Message;
                throw excStripe;
            }
        }```

**Comment by vs-krasnov** [comment]
Thank you, would be great to update readme.md

**Comment by jaymedavis** [comment]
Thanks for pointing this out, it seems that entire service is not documented and the old version is still there. Sorry for the confusion!

**Comment by jaymedavis** [comment]
a lot of documentation updates are coming very soon - I will be sure this and every other service is added (complete overhaul into a site, the readme is just too large now)

**Comment by mpoincare** [comment]
I would like to know how can I get, based on the sample code provided by mexner, the chargeId so that I can pass it to the method?

**Comment by jaymedavis** [comment]
Reopening for docs
