### ISSUE TITLE
Add support for managed accounts

### ISSUE THREAD

**Issue by jaymedavis** [jaymedavis/stripe.net#367]
see #307 for additional comments on managed accounts

**Comment by ryanulit** [comment]
Hello Jayme,

Any update on the release of managed accounts?  I may try to roll my own because I am going to need this soon, but just wanted to check in on your progress.

Thanks for a great API!

**Comment by jaymedavis** [comment]
You're welcome. :)

There's actually a few folks who have implemented this, but it never made it back to me as a pull request :(

I will need to either implement it from scratch, or go and pull/reference their code to get it implemented. This is definitely something I would love to have. 

If you feel like helping out, search this repo for managed accounts and you will find references to other users who have forked and implemented it. Big bonus for forking stripe.net and getting a PR back to me!

In the meantime, I am curious about getting async implemented, which will drastically be made simpler by removing support for 3.5. The only thing I am holding out for here is I don't want to leave anyone dead in the water.

It's definitely going to make it at some point, but there are a couple of things to come before. That's subject to change, though! :+1:

**Comment by ryanulit** [comment]
Appreciate the update.  This fork from from Democracy Ventures referenced in the connect support issue looks promising:  

https://github.com/DemocracyVenturesInc/stripe.net/blob/master/src/Stripe/Services/Account/StripeAccountService.cs.

Hopefully I can test this soon.  I'll let you know if I get something working and worthy of a PR.

**Comment by jaymedavis** [comment]
Anything helps! Appreciate you looking into that!

**Comment by matthewcorven** [comment]
I've incorporated mathieukempe's Managed Account elements from his fork (https://github.com/mathieukempe/stripe.net), which was originally forked from Democracy Ventures.

See pull request #390

**Comment by jaymedavis** [comment]
Thank you! Will get to asap.

**Comment by lferreiraIsf** [comment]
Hello Jayme,

I have a problem with Requestor: 'Stripe.Requestor' is inaccessible due to its protection level.

Could you help me, please
![error](https://cloud.githubusercontent.com/assets/12401175/9946638/8130c82a-5d62-11e5-8082-1fec726f7ae7.PNG)
?

**Comment by jaymedavis** [comment]
Can you post this in a new issue? It's not related to this thread.

**Comment by lferreiraIsf** [comment]
No, sorry, it works now.

**Comment by alantrick** [comment]
Has this been looked at recently? I'm definitely interested in getting #390 merged.

**Comment by jaymedavis** [comment]
This is not in the next release. You can track current items by looking at the develop branch.

**Comment by PsyTae** [comment]
Definitely want to see this incorporated soon.

**Comment by cwoolum** [comment]
What's the status of this? Doesn't look like Pull request #390 has been looked at.

**Comment by jaymedavis** [comment]
finding more time to work on this library: hopefully in the very near future that will happen.

**Comment by jaymedavis** [comment]
This is going to be handled in PR #414, where most of the work has been completed. I'm closing this and will work from there.

**Comment by matthewcorven** [comment]
Sorry to see that 367 didn't make the cut.  Looking forward to keeping tabs on this project in any case, it's a great piece of work.

**Comment by jaymedavis** [comment]
it made the cut and will be implemented - just from a different ticket. :)

**Comment by jaymedavis** [comment]
and thanks!

**Comment by jaymedavis** [comment]
#390 is still open - I am using elements from that as well. I like some of the naming from that PR more - like StripeBirthDay. Makes more sense than StripeDob. It's just a lot of PR's for the same things and I'm trying to merge the best of all together.

**Comment by mgibas** [comment]
:+1:
waiting for this feature :heart_eyes:
