### ISSUE TITLE
Customer.DefaultSource is NULL when retrieving customer

### ISSUE THREAD

**Issue by kurtschindler** [jaymedavis/stripe.net#370]
When retrieving a customer who has a default payment source, the Stripe.net Customer instance has a valid `DefaultSourceId` property, but `DefaultSource` is NULL.

One can fetch the default Source object by matching the DefaultSourceId with an item in the `SourceList` collection, which as far as I can tell is what one would have to do when interacting with the Stripe customer object (not the stripe.net object)

So I guess my question is, what is `DefaultSource` for? Whether it's a legacy Stripe.net property or a convenience property, it looks like it isn't functioning.

**Comment by jaymedavis** [comment]
Hey Kurt - this is an [Expandable Property](https://github.com/jaymedavis/stripe.net#expandable-properties). You can specify to ExpandSource on your service and it will get hydrated.
