### ISSUE TITLE
Web AppSettings when using Stripe Checkout

### ISSUE THREAD

**Issue by janessaallen** [jaymedavis/stripe.net#377]
Just noticed that when using the customized form for Stripe Checkout (the embedded form), it will not work when the Stripe Api Key value is placed in the web.config. Considered a bad request and token is not returned. ???

**Comment by janessaallen** [comment]
That wasn't the issue! Sorry about that.

**Comment by jaymedavis** [comment]
No worries, glad you got it worked out. :)

**Comment by janessaallen** [comment]
Well, there may be a clash. I’m not sure. I’m using the public test key for the checkout form, but I get the token error (there is no token with ID). Could that be due to putting the secret key in the web.config?

**Comment by janessaallen** [comment]
Oh, I think I may be misunderstanding tokens. It can be used either or?  Create customer OR charge? I was using it for both. That may be the issue.
