### ISSUE TITLE
Add raw JSON property to entities

### ISSUE THREAD

**Issue by lancefisher** [jaymedavis/stripe.net#378]
I like using stripe.net to create customers and make charges. I would also like to store the raw JSON response from these requests for logging purposes. It would be great if each service request would return the raw JSON as well as the parsed entity.

**Comment by jaymedavis** [comment]
I agree, there is definitely a good need for logging. In addition to this, I would love to log the request being sent to stripe - it would help with debugging a lot.

**Comment by zijiji** [comment]
Agreement here too.  Would be extremely useful.

**Comment by pradt** [comment]
Hi not sure if this has progressed, I'm wanting to log all communication between stripe and responses from stripe  - specifically for logging and audit purposes. Has there been progress on this by any chance ?

**Comment by jaymedavis** [comment]
It has not, but the demand has certainly been growing, so I will look into this. Thanks for bumping.

**Comment by jaymedavis** [comment]
There is a new property that will be present on all entities called `StripeRawJson` that will have the full json that Stripe returned. It's on master now and will go out with the next release.
