### ISSUE TITLE
Add StatementDescriptor to StripeCharge entity

### ISSUE THREAD

**Issue by lancefisher** [jaymedavis/stripe.net#379]
Stripe charges have a `statement_descriptor` property. This is how the charge will appear on bank statements. See the example response: https://stripe.com/docs/api#create_charge

`StripeCharge` should have a `StatementDescriptor` property.

**Comment by lancefisher** [comment]
See: https://github.com/jaymedavis/stripe.net/pull/373

**Comment by jaymedavis** [comment]
will be released soon, closing this and addressed in the PR
