### ISSUE TITLE
Upcoming Invoice - StripeInvoiceLineItems has 10 line items at most

### ISSUE THREAD

**Issue by PaulParker** [jaymedavis/stripe.net#381]
I can reproduce the issue by creating a subscription, and then changing the plan a bunch of times, to create a lot of prorated line items.  When I call in to get the upcoming invoice, only 10 of the line items are returned in the StripeInvoiceLineItems list, even if there are more than 10 in stripe.

I'm not sure if the issue applies more generally, to all invoices, or just to the upcoming invoice.

**Comment by jaymedavis** [comment]
It's probably upcoming only. Listing invoices supports a [StripeListOptions](https://github.com/jaymedavis/stripe.net#stripelistoptions-paging) as an optional parameter. Upcoming probably does too.

**Comment by PaulParker** [comment]
Thanks, on closer inspection of the object I do see that StripeInvoiceLineItems.TotalCount exceeds StripeInvoiceLineItems.Data.Count() (also .HasMore=true).  It doesn't appear that the current implementation of StripeInvoice.Upcoming() takes the StripeListOptions object - do you mean that the limit arg is supported by stripe but not yet by this Stripe.net library?

**Comment by jaymedavis** [comment]
That's my guess (haven't checked code yet).

**Comment by jaymedavis** [comment]
Viewing the Stripe docs, there is nothing additional offered with upcoming and listing more invoice items. So it looks like you would have to use the StripeInvoiceItemService to retrieve the invoice/invoice items and then you can page through. If you want to follow up with Stripe to see if I'm wrong, let me know and I will reopen this as something this library needs to do. :)
