### ISSUE TITLE
Charge a card

### ISSUE THREAD

**Issue by jhallam3** [jaymedavis/stripe.net#382]
Hi, 

I have multiple cards assigned to a customer 

I want to charge a specific card for that customer. 

Can you please advice how I can do this please?

**Comment by DmitriyVetrov** [comment]
Same challenge

**Comment by jhallam3** [comment]
Hey Dmitriy,

I got it working with the following code. 

get card that is selected...

foreach (var _c in card)
                {
                    if (_c.Fingerprint == preArrival.Card)
                    {
                        cardcode = _c.Id;
                    }

                }

then use cardcode below, 



                var myCharge = new StripeChargeCreateOptions();
                myCharge.Amount = Convert.ToInt32(order.Deposit)*100;
                myCharge.Currency = "GBP";
                myCharge.CustomerId = _customer.StripeID;
                
                
                myCharge.Capture = true;
                myCharge.Description = "Deposit Ref: " + order.Ref;
                
                StripeSourceOptions sso = new StripeSourceOptions();
                
                 sso.TokenId = cardcode;
                myCharge.Source = sso;
                

                var chargeservice = new StripeChargeService("<<<<<YOUR API KEY>>>>>");
                

                StripeCharge stripeCharge = chargeservice.Create(myCharge);

**Comment by jhallam3** [comment]
closing this issue

**Comment by jhallam3** [comment]
Did the code I put up help?

Regards

Jon Hallam


On 15 Sep 2015, at 14:45, Dmitriy <notifications@github.com> wrote:

Same challenge

—
Reply to this email directly or view it on GitHub
<https://github.com/jaymedavis/stripe.net/issues/382#issuecomment-140398833>
.

**Comment by DmitriyVetrov** [comment]
In your code:
>foreach (var _c in card)
>{
>if (_c.Fingerprint == preArrival.Card)
>{
>cardcode = _c.Id;
>}

How do you generate variable **cardcode.Id** that it can be used for **sso.TokenId** ?
>StripeSourceOptions sso = new StripeSourceOptions();
>sso.TokenId = cardcode;

**Comment by DmitriyVetrov** [comment]
Resolved issue!
If I need charge by specific customer card then need to Update Customer with assign this specific card to DefaultSource :)

**Comment by jhallam3** [comment]
In my MVC project I have a controller that gets the Card Details for the logged in user.

as shown below. 

StripeCardService service = new StripeCardService("YOUR STRIPE API");
            var card = service.List(stripeID);
            List<StripeCard> ListStripeCard = new List<StripeCard>();

            foreach (var _c in card)
            {
                

                int month = Convert.ToInt32(_c.ExpirationMonth.ToString());
                int Year = Convert.ToInt32(_c.ExpirationYear.ToString());
                int nowmonth = DateTime.Now.Month;
                int nowyear = DateTime.Now.Year;
                if ((month >= nowmonth) && (Year >= nowyear))
                {
                    ListStripeCard.Add(_c);
                }
                else
                {

                }
            }
            ViewBag.Cat = ListStripeCard.ToList();
            return View();

The User then views their cards that are available and are valid for month and year. 

I display the card last4 like this "xxxx-xxxx-xxxx" + card.last4 + "Exp " + month+ year.....

then when they click purchase the card finger is the ID of the selected drop down print for that "xxxx-xxxx-xxxx" + card.last4  is used to work out which card they have selected. 

Thats then used. 
PreArrival data is passed with the .card data that is the finger print of the card. 
as shown below 
StripeCardService service = new StripeCardService("YOUR API ID");
                var card = service.List(stripeID);
                var cardcode = "";
                List<StripeCard> ListStripeCard = new List<StripeCard>();

                foreach (var _c in card)
                {
                    if (_c.Fingerprint == preArrival.Card)
                    {
                        cardcode = _c.Id;
                    }

                }

                
                var myCharge = new StripeChargeCreateOptions();
                myCharge.Amount = Convert.ToInt32(order.Deposit)*100;
                myCharge.Currency = "GBP";
                myCharge.CustomerId = _customer.StripeID;
                
                
                myCharge.Capture = true;
               
                
                StripeSourceOptions sso = new StripeSourceOptions();
                sso.TokenId = cardcode;
                myCharge.Source = sso;
                

                var chargeservice = new StripeChargeService("URL API KEY");
                

                StripeCharge stripeCharge = chargeservice.Create(myCharge);
                
then it will charge that customers specific card.
