### ISSUE TITLE
Nuget 4.2 doesnt have StripeCardService class

### ISSUE THREAD

**Issue by avatart0ph** [jaymedavis/stripe.net#383]
![sc1](https://cloud.githubusercontent.com/assets/3780000/9736685/c26b5f66-5610-11e5-9e30-d1690b2ed6ac.png)

Just wondering if the latest files can get pushed to Nuget?
i know i can just download the project, compile and update my dlls.
But i prefer all 3rd party libraries under nuget so i can keep track.

OR, there really is something wrong with my copy? I get an error when i access that class. i already reinstalled the new stripe.net though. same error.

thank you

**Comment by jaymedavis** [comment]
I haven't heard anyone else mention this. I would guess something is wrong with your copy. We can see if anyone else has had this issue.

**Comment by avatart0ph** [comment]
I apologize. i shouldve tried also deleting the files. this fixed it.

**Comment by jaymedavis** [comment]
No worries, it happens. :)
