### ISSUE TITLE
Stripe Connect don't work as it is described in the doc

### ISSUE THREAD

**Issue by heyanctil** [jaymedavis/stripe.net#385]
I've encountered a problem when I tried using Stripe Connect. I've added the code in a HttpHandler. When the API trys to create the token, I've got an error: No such API key: Bearer / invalid_client. I've found a way to get around by adding the Api key in the stripeOAuthTokenService.ApiKey property:

    var stripeOAuthTokenService = new StripeOAuthTokenService();
    stripeOAuthTokenService.ApiKey = WebConfig.AppSettings.StripeSecretApiKey;

    var stripeOAuthTokeCreateOptions = new StripeOAuthTokenCreateOptions()
    {
        ClientSecret = WebConfig.AppSettings.StripeSecretApiKey,
        Code = request.QueryString["code"],
        GrantType = "authorization_code"
    };

    var stripeOAuthToken = stripeOAuthTokenService.Create(stripeOAuthTokeCreateOptions);

What is the good implementation?

**Comment by jaymedavis** [comment]
Interesting ... this may be a bug - needs to be investigated.

**Comment by jaymedavis** [comment]
Did you ever have the api key set anywhere else? The code appears to be fine...?

**Comment by BhavJain** [comment]
i m getting same error how should i resolve..?

**Comment by heyanctil** [comment]
@BhavJain it works fine for me. Can you provide some code sample of how you implemented that?

**Comment by BhavJain** [comment]
i have use following code snippet.
 if (!string.IsNullOrEmpty(Request["code"]))
            {
                _code = Request["code"].ToString();
                _stripeOAuthTokenService = new StripeOAuthTokenService();
                _stripeOAuthTokeCreateOptions = new StripeOAuthTokenCreateOptions()
                {
                    ClientSecret = "sk_xxxxxxx.....",
                    Code = _code,
                    GrantType = "authorization_code"
                };
                _stripeOAuthToken = _stripeOAuthTokenService.Create(_stripeOAuthTokeCreateOptions);
            }

I used "_code" which is return(redirect) by stripe and used development keys in every places.
i.e ClientSecret => Test Secret key
code = code is return by stripe site
GrantType = "authorization_code"

Please suggest where i m wrong

**Comment by BhavJain** [comment]
Not it's working i forget to initialize API key into constructor

**Comment by heyanctil** [comment]
Ok great!

**Comment by jaymedavis** [comment]
Thanks for the help @heyanctil :+1:

**Comment by mmusket** [comment]
Can this be added to the docs? I came across this problem too

**Comment by jaymedavis** [comment]
which part of the issue was your solution?

**Comment by mmusket** [comment]
Manually setting the apikey before the request 

var stripeOAuthTokenService = new StripeOAuthTokenService();
stripeOAuthTokenService.ApiKey = WebConfig.AppSettings.StripeSecretApiKey;

**Comment by jaymedavis** [comment]
How do you set your API key for the rest of the app? This should work the same way.

**Comment by mmusket** [comment]
Hmmm it does. 
In my case I skipped the first part of the documentation and went straight to the connect part  as that was the section I was interested in. 
Forget about my request. Thanks for this awesome api wrapper! :)

**Comment by jaymedavis** [comment]
Ah. No worries, can't say I'm not guilty of the same thing. :)
