### ISSUE TITLE
Apple Pay

### ISSUE THREAD

**Issue by hsmith825** [jaymedavis/stripe.net#386]
Do you support the apple pay option of stripe?

**Comment by jaymedavis** [comment]
not yet :)

**Comment by matthewarkin** [comment]
Apple pay works just like a token (charge token / create customer and adds a card/source). There is no reason why the library wouldn't already support it

**Comment by hsmith825** [comment]
Problem solved.

**Comment by hsmith825** [comment]
Thanks but the problem was solved months ago.  This library does not didrrectly support Apple Pay.  You are right, after you get a token from Apple Pay you can use that token here.

**Comment by jaymedavis** [comment]
Thank you guys for updating the thread.
