### ISSUE TITLE
raised in error

### ISSUE THREAD

**Issue by TonyB333** [jaymedavis/stripe.net#389]
I have a standalone account connected (via Stripe Connect) to my master account. I want to apply a charge for a customer that goes into the standalone account.

I use Stripe Checkout to get a Token for the card details and then create a customer with that token that appears in my master account.
If  I make a charge to the customer for the master account then it’s all fine.
If I try to use the same customer with a connected Standalone account then I get the error “No such customer”

The code is as follows:

var myCharge = new StripeChargeCreateOptions();

myCharge.Amount = 1000
myCharge.Currency = "gbp"
myCharge.Description = "charge account"
myCharge.CustomerId = <customer token>
            
var chargeService = new StripeChargeService(<master account secret key>);
var chargeItem = chargeService.Create(myCharge, new StripeRequestOptions() { StripeConnectAccountId = <account key for standalone> });

**Comment by TonyB333** [comment]
Please note that I have also tried creating the customer and passing the Connect account key via the StripeRequestOptions i.e.

            var stripeService = new StripeCustomerService(secretKey);
            var stripeTokenOptions = new StripeCustomerCreateOptions();

            stripeTokenOptions.Description = "Tony B Credit Card Details";
            stripeTokenOptions.Source = new StripeSourceOptions()  {TokenId = <customer Token };
            StripeCustomer stripeCustomer;
            stripeCustomer = stripeService.Create(stripeTokenOptions, new StripeRequestOptions() { StripeConnectAccountId = accountKey });

The attempt to create the customer in this way fails with "You must provide a value for 'cvc'."

**Comment by jaymedavis** [comment]
Anything to note here that might help someone else? :)
