### ISSUE TITLE
OAuth DeAuthorize

### ISSUE THREAD

**Issue by mexner** [jaymedavis/stripe.net#394]
I don't see it, but thought I'd verify and ask. Does this API support the OAuth deauthorize call?
https://stripe.com/docs/connect/reference#post-deauthorize

Thanks for all you do making this api awesome.

**Comment by jaymedavis** [comment]
You're welcome :smile: 

It's not available, it should be pretty simple to add to the service.

**Comment by mzurba** [comment]
Hi Jayme,

Thank you for your efforts to make this awesome package, it really makes our life easy. Regarding to this issue, the `Deauthorize ` and `DeauthorizeAsync` methods do not send the client_id parameter to Stripe api and always throw an exception.

Deep looking to the code:
`var url = ParameterBuilder.ApplyParameterToUrl(Urls.OAuthDeauthorize, "client_id", clientId);
 url = ParameterBuilder.ApplyParameterToUrl(Urls.OAuthDeauthorize, "stripe_user_id", stripeUserId);
`
at the 2nd line, the url variable rested with the  Urls.OAuthDeauthorize and stripe_user_id only, so client_id has been overwritten.

Thanks.

**Comment by jaymedavis** [comment]
ClientID should not be overwritten based on this code - the apply parameter method does an append, it doesn't replace what is already there. None the less, I will investigate - thanks. Have you used anything to spy on the URL being sent, such as fiddler?

**Comment by jaymedavis** [comment]
Also - when you wrap this call in a try/catch, what are you seeing as the error back from Stripe?

**Comment by mzurba** [comment]
Thanks Jayme, here's the Exception -> StripeError details:
- Error: invalid_request.
- ErrorSubscription: client_id failed validation: Required field.

I am sure that I am sending the client id correctly. And to make sure, I have debugged the source code, and based on what the `ApplyParameterToUrl ` helper does, i think you just need to replace the `Urls.OAuthDeauthorize` in the 2nd line above with the `url ` it self. i.e,
`url = ParameterBuilder.ApplyParameterToUrl(url , "stripe_user_id", stripeUserId); `

**Comment by scurk1415** [comment]
I have exactly the same error as @mzurba, so it would kinda appreciate if this gets fixed quickly

**Comment by jaymedavis** [comment]
Yes, @mzurba's fix looks correct to me. I'll patch this real quick and do a release for you @scurk1415.

**Comment by jaymedavis** [comment]
6.3.5 should take care of you. available now - sorry this bug got away from me - I should have re-opened the issue and marked it as a bug. There are many features I simply don't have time to implement, but I do shoot for bug free.

**Comment by VadimPestryanin** [comment]
Strange but i got same error in 6.3.5.
The code i've used is:

  StripeOAuthTokenService oAuthTokenService = new StripeOAuthTokenService(_apiKey);
            var oAuthToken = oAuthTokenService.Deauthorize(_clientId, connectedAccountId);
