### ISSUE TITLE
Issues with Newtonsoft.json and stripe.net

### ISSUE THREAD

**Issue by J0N353Y** [jaymedavis/stripe.net#397]
Since newtonsoft.json v7 has been released, I'm finding it impossible to get stripe.net working in an existing project. I've even gone to the extent of removing all references and also dependent references which rely on newtonsoft.json. Installing stripe.net through Nuget brings down v7 of newtonsoft.json and ive checked all project references, and they are all up to the current version, yet, I still get this.

Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

This is blocking development now and could do with knowing what to do.

**Comment by jaymedavis** [comment]
there is an existing PR to upgrade that library. I will prioritize getting it in the next release. You can try pulling down the code locally, adding the new lib and compiling to see if that fixes your issue.

**Comment by J0N353Y** [comment]
Thanks, for now I’ve got your source and built and referenced that and it works again. I’ll keep an eye out for the updated stripe.net version.

**Comment by janoserdelyi** [comment]
i have run into this exact same issue. pulling!

**Comment by jaymedavis** [comment]
Thanks for letting me know. I'll get to this asap.

**Comment by jaymedavis** [comment]
closing - this was fixed
