### ISSUE TITLE
Strip Payment gateway token number mapping with customer

### ISSUE THREAD

**Issue by sankettiger** [jaymedavis/stripe.net#398]
Hi James,
    I am trying to map newly created token id to the new customer as I am trying to provide card details at the time of token creation. but I am not able to do the same. It is throwing the error. here I have attached error screen. kindly suggest me for the same.

Thanks
Sanket
![stripeerror](https://cloud.githubusercontent.com/assets/14972964/10274592/107de064-6b5d-11e5-94b1-ecc8868a3fc3.png)

**Comment by jaymedavis** [comment]
This is a problem with stripe itself.

**Comment by sankettiger** [comment]
Hi James,
    also invoice no facility is not there with the payment. so how the particular payment details can be stored with the uniqueness?

waiting for your reply ASAP.

**Comment by jaymedavis** [comment]
I hope you have resolved these issues - let me know if not or if there is a specific stripe.net issue.
