### ISSUE TITLE
Cannot Cancel or Get Subscription For a customer

### ISSUE THREAD

**Issue by jfox14** [jaymedavis/stripe.net#401]
Hi everybody,

New to Stripe.Net.

I've been having an issue canceling--or even getting-- an existing subscription. I've quadruple checked to ensure that the parameters I have hardcoded are correct. My Stripe dashboard confirms that I have a customer with the ID, subscribed to the Plan.

Code:

 protected void cancelSubscription()
    {
        var subscriptionService = new StripeSubscriptionService();
        StripeSubscription stripeSubscription = subscriptionService.Get("cus_76KjtTdcgkagfO", "BronzePlan");
    }

error message :  Customer cus_76KjtTdcgkagfO does not have a subscription with ID BronzePlan

Again, I have checked multiple times and tried with a few other plans, as well as  subscribed customers. Any thoughts?  I am using a test api key- and yes BronzePlan is the plan ID and not the name.

Any thoughts?
-Jon

**Comment by PsyTae** [comment]
Is bronzeplan the id or the name of the subscription?

**Comment by jfox14** [comment]
it is the id.

"-and yes BronzePlan is the plan ID and not the name."

**Comment by jaymedavis** [comment]
Is your stripe dashboard set to test mode as well since you are using the test key?

**Comment by Pheonixforce** [comment]
I realize this is old but....
StripeSubscription stripeSubscription = subscriptionService.Get("cus_76KjtTdcgkagfO", "BronzePlan"); 
instead of BronzePlan shouldn't it be sub_19823kjashdfkah or the like?

**Comment by jaymedavis** [comment]
Good catch. Thanks for searching first!

**Comment by jaymedavis** [comment]
I assume this is resolved - as @Pheonixforce said, you should be passing the ID for sub_*.
