### ISSUE TITLE
Access to Stripe Request Ids from within the library?

### ISSUE THREAD

**Issue by reedyrm** [jaymedavis/stripe.net#402]
Is there a way to access the request Ids that are being sent back in the response headers?  I was reading about them on the API as a way to correlate requests to their API to their logs when getting help and I was hoping to start logging them out in my system to help with debugging later on.

https://stripe.com/docs/api/curl#request_ids

Does the library support this yet?

**Comment by jaymedavis** [comment]
It does not. It will need to be added - thanks.

**Comment by jaymedavis** [comment]
This is now added - check the docs for the StripeResponse property available on all entities now.
