### ISSUE TITLE
Trying To Create Card With Metadata Causes Exception

### ISSUE THREAD

**Issue by rmcohen** [jaymedavis/stripe.net#403]
I have the following code:

	Stripe.StripeCardCreateOptions CardCreateOptions = new Stripe.StripeCardCreateOptions();
	CardCreateOptions.Source = new Stripe.StripeSourceOptions();
	CardCreateOptions.Source.TokenId = PaymentId;
	CardCreateOptions.Source.Metadata = new Dictionary<string, string>();
	CardCreateOptions.Source.Metadata["parentUserId"] = Id;
	Stripe.StripeCardService CardService = new Stripe.StripeCardService();
	Stripe.StripeCard Card = CardService.Create(StripeCustomerId, CardCreateOptions);

It always produces the following exception:

"Error while talking with one of our backends. Sorry about that! We have been notified of the problem. Please contact support@stripe.com if you have any questions."

If I comment out the two lines creating the card metadata, everything works properly.

Any ideas here?

**Comment by jaymedavis** [comment]
Could possibly be your dictionary requiring strings - have you tried Id.ToString()?

**Comment by rmcohen** [comment]
(I responded via email but am repeating here in case that didn't make it to you):

1)  Id is already a string.

2)  The following code precedes the code above and does work fine:

```
Stripe.StripeCustomerCreateOptions CustCreateOptions = new Stripe.StripeCustomerCreateOptions();
CustCreateOptions.Email = SessionProfile.Email;
CustCreateOptions.Description = SessionProfile.FirstName + " " + SessionProfile.LastName;
CustCreateOptions.Metadata = new Dictionary<string, string>();
CustCreateOptions.Metadata["parentUserId"] = Id;
CustCreateOptions.Metadata["appEventId"] = Action.CmdId;
Stripe.StripeCustomerService CustomerService = new Stripe.StripeCustomerService();
Stripe.StripeCustomer Customer = CustomerService.Create(CustCreateOptions);
```
3)  Just creating the Metadata object inside the CardCreateOptions.Source crashes on creating the card.  I don't have to actually make an entry.

**Comment by rmcohen** [comment]
Any ideas on this one?

**Comment by rmcohen** [comment]
(Didn't mean to close it out)

**Comment by jaymedavis** [comment]
Is there anymore detail on the StripeError? I will need to write a test and try to reproduce this.

**Comment by rmcohen** [comment]
The code that I use is above and this is the message and call stack that obtains:

<code>
Error while talking with one of our backends. Sorry about that! We have been notified of the problem. Please contact support@stripe.com if you have any questions.



at Stripe.Requestor.ExecuteWebRequest(WebRequest webRequest) 

at Stripe.StripeCardService.Create(String customerId, StripeCardCreateOptions createOptions, StripeRequestOptions requestOptions) 

at AppCommon.User.PostUpdate[T](User Actor, ClientAction Action, TContext ActionContext) in C:\Users\Bob\Documents\Visual Studio 2015\Projects\Tabula\AppCommon\User.cs:line 334
</code>

**Comment by jaymedavis** [comment]
Is this returning a StripeError? Wrap your code in a try catch and inspect the StripeError (see the bottom of the readme). You might get more info that way

**Comment by rmcohen** [comment]
Yes, it is a StripeException.  The HTTPStatus Code is "InternalServerError" and the error type is "api_error".  HResult = -2146232832.

Other than that the error message and call stack as are above.

**Comment by jaymedavis** [comment]
I've got nothing. This will need a test (or a modification on the existing ones) to figure this out.

**Comment by rmcohen** [comment]
So you can create a metadata object on a card OK?  If so, then perhaps there are settings at Stripe that I need to look at?

**Comment by rmcohen** [comment]
Stripe's suggestion was to do a Card Update after the card was created.  Creating a CardUpdateOptions.Metadata dictionary and adding items to it works OK.

This is workable, but not quite the best solution.  Is there any update on using the CardCreateOptions?

**Comment by jaymedavis** [comment]
Looking at this again, you probably need to set the CardCreateOptions.Source.Object to 'token'... if you haven't resolved this by now.

**Comment by descorp** [comment]
maybe off-top, but I want to share:
NuGet 6.0.1

Metadata or description in StripeSourceOptions leads to "Error while talking ..." exception when requesting create new customer or new card.
Charging existing customer cause no problem.

**Comment by rmcohen** [comment]
Yes, thanks.  That's what I ended up doing.  It works OK, although it's less aesthetically pleasing than being able to do it at creation time.

**Comment by jaymedavis** [comment]
I wasn't aware description was causing a problem. There is an open issue now for metadata - I'm aware of that bug. Can you give me a small example for description being broke @descorp? I don't want to assume what you're doing. :)

**Comment by jaymedavis** [comment]
As for

**Comment by jaymedavis** [comment]
As for metadata, this will be resolved when #427 is fixed.

**Comment by rmcohen** [comment]
Great!  Thanks.  I'll keep an eye out for that one.

**Comment by rmcohen** [comment]
I just installed the latest version (6.2.1) but am still not understanding how to insert metadata at the time the card is created.  Here's my code:

Stripe.StripeCardCreateOptions CardCreateOptions = new Stripe.StripeCardCreateOptions();
						CardCreateOptions.SourceToken = PaymentId;
						CardCreateOptions.SourceCard = new Stripe.SourceCard();
						CardCreateOptions.SourceCard.Metadata = new Dictionary\<string, string\>()
						CardCreateOptions.SourceCard.Metadata["OwnerId"] = Id;
						CardCreateOptions.SourceCard.Metadata["appEventId"] = Action.CmdId;
						Stripe.StripeCardService CardService = new Stripe.StripeCardService();
						Stripe.StripeCard Card = CardService.Create(StripeCustomerId, CardCreateOptions);

but here's the error I get back from Stripe:

"Invalid request (check your POST parameters): unable to determine value for parameter: source. For assistance, please email support@stripe.com.

at Stripe.Requestor.ExecuteRequest(HttpRequestMessage requestMessage) 

at Stripe.StripeCardService.Create(String customerId, StripeCardCreateOptions createOptions, StripeRequestOptions requestOptions) "

**Comment by jaymedavis** [comment]
You cannot set a source token AND a source card - it's one or the other. That's why the code examples are separate.

**Comment by jaymedavis** [comment]
Hope that fixed you up! ;)

**Comment by gauravupadhyay** [comment]
@jaymedavis your answer helped me. Thanks.
