### ISSUE TITLE
Status list for the customer, charge and the invoice

### ISSUE THREAD

**Issue by sankettiger** [jaymedavis/stripe.net#404]
Hi,
   Can you please tell me the list of the different status for the customer/charge/invoice creation/updation.
means different error messages for all the above.
i want the list so I can give the respective messages to the real time users.

Thanks
Sanket

**Comment by jaymedavis** [comment]
This is stripe specific, stripe.net does not alter any errors sent back from Stripe. You can contact them to find out your answer. :)
