### ISSUE TITLE
Update Stripe card returns missing param source error

### ISSUE THREAD

**Issue by shanew44** [jaymedavis/stripe.net#406]
I have the following code to update a stripe card.  I am getting a "invalid_request_error" missing required param:source. I am using a test account and I am able to add and delete a card without any problems.

        private static void UpdateStripeCard(CreditCard card, UserAddress addr)
        {
            int expiresMonth = (int)card.ExpiresMonth;
            var myCard = new StripeCardUpdateOptions
            {               
                Name = card.Name,
                ExpirationYear = card.ExpiresYear.ToString(),
                ExpirationMonth = expiresMonth.ToString(),
                AddressLine1 = addr.Address1,
                AddressLine2 = addr.Address2,
                AddressCity = addr.City,
                AddressState = addr.State,
                AddressZip = addr.ZipCode                
            };
            var cardService = new StripeCardService();
            try
            {
                StripeCard stripecard = cardService.Update(card.StripeCustId, card.StripeCardId, myCard);
            }
            catch (StripeException exception)
            {
                card.Error = exception.StripeError;
            }
        }

**Comment by shanew44** [comment]
Found the issue in my code, everything is working as expected.

**Comment by jaymedavis** [comment]
Anything that might help someone else searching? :)

**Comment by shanew44** [comment]
No, just a stupid mistake on my part.  The cardId was not being set in the calling procedure and was coming in as null and that was the reason for the error.

**Comment by smooney1234** [comment]
Where did you need to set your card id?

**Comment by zainnadeem** [comment]
Hi @shanew44, I'm having the same issue - where are you setting the card id? My default source is coming up null.

**Comment by ekeyte** [comment]
> Found the issue in my code, everything is working as expected.

Thanks, buddy.

**Comment by jandog8990** [comment]
Again, where are you setting the card id? Many people having this problem
