### ISSUE TITLE
Assigning Card to existing customer via token (from checkout.js) results in api_error

### ISSUE THREAD

**Issue by janoserdelyi** [jaymedavis/stripe.net#409]
I'm very new to stripe and stripe.net but i've been reading and searching and i cannot seemt o get past an issue i'm having so here i am - 

what i am attempting to do is assign a card to an existing customer.
the card in this case is from a token received from the checkout.js front-end library.

my test api token has been confirmed to be working by way of creating a user using stripe.net.

here's the barebones code : 

```
string token = "tok_123abc";

var scs = new StripeCustomerService();
StripeCustomer customer = scs.Get("cus_123abc");
var update = new StripeCustomerUpdateOptions();
update.Source = new StripeSourceOptions()
{
	Object = "token",
	TokenId = token
};
try {
	scs.Update(customer.Id, update);
} catch (StripeException oops) {
	Console.WriteLine("oops, there has been an error : " + oops.Message);
}
```

the StripeException gets caught every time -
it's an "api_error" with code -2146232832

i am using the latest nuget package and i have not yet requested that stripe downshift my api version to match the version in the nuget package.

am i just doing something plainly wrong?

**Comment by janoserdelyi** [comment]
oh yes i forgot to mention  - the "tok_123abc" token (changed to protect the innocent) is from the overall token response id from checkout.js - it is not the card object's id of "card_somestuffhere"

**Comment by jaymedavis** [comment]
Did you get this squared away? I have no idea what that error code is, that would be something to check with Stripe about.
