### ISSUE TITLE
Stripe Connect for managed account

### ISSUE THREAD

**Issue by trietphamvm** [jaymedavis/stripe.net#410]
I just wonder when this feature will be available?

**Comment by drewid** [comment]
I am going to be using the capability for myself and am interested in possibly contributing it to the API.  @jaymedavis What is your preferred way for handling code contributions?  I am not that familiar with github contributions to projects.  Any pointers or good overviews on contributing are also appreciated.

**Comment by drewid** [comment]
I forked the project to [drewid\stripe.net](https://github.com/drewid/stripe.net) and added all the required entities and created placeholders in services.

I have a few questions...

**StripeManagedAccount Structure:**
1) StripeAccount was created I believe before Managed/Connected Accounts were added/

2) The ManagedAccount has "many, many" more fields than Account but does have all the field in Account.  It could be viewed as a superset.  There are a few options:

a) Update the contents of Account with the fields from Managed Account (not sure if all the fields are necessary for retrieving just a single account)
b) Totally separate entities: StripeAccount and StripeManagedAccount
c) StripeManagedAccount to inherit from StripeAccount.

Having separate entities may be more straight forward, but not sure if there is a need for both?  They do have separate URLs for submission:  /account vs /accounts.

**StripeExternalAccount**
In the API for Account, the field external_accounts is a list and for the object has a field called "data" which is an array with the following description:
>The list contains all external accounts that have been attached to the Stripe account. These may be bank accounts or cards.

How does one represent an array of different objects/classes??  How can I do an array that can either be a BankAccount or a CreditCard?

Thanks!

**Comment by mikecousins** [comment]
1. My vote is make them separate entities: StripeAccount and StripeManagedAccount.

2. I'd do a base class called Source/Account/whatever and have BankAccount and CreditCard inherit from that. Then make it an array of Source.

**Comment by johntco** [comment]
Is this new capability going to be ready soon? I need to use the new Connect Managed Accounts. Thanks,

**Comment by jaymedavis** [comment]
No, this will take awhile to get pulled in to the library. Checkout the pull request @drewid has submitted - while it's probably all good, I have to be a little slower about what I introduce to the library, and that pull request has lots of other changes on it as well (a big reason I prefer small pull requests that are focused on a single concern). His branch is probably usable for managed accounts, but I have not tested it.

**Comment by jaymedavis** [comment]
As for the account object, I don't want to split them into a StripeAccount and a StripeManagedAccount. The Stripe documentation has them listed together as "Stripe Account", so I try to stick as close as possible to their API. This prevents thousands of questions to my inbox. :)

**Comment by jaymedavis** [comment]
This doesn't mean you need to worry about this with your pull request @drewid - I can change things as I go,

**Comment by drewid** [comment]
Sorry I have been absent for a while @jaymedavis.  Definitely whatever you prefer is OK by me - I can and will adapt to any changes - no issue with whatever makes sense.  I just was making sure that it could and was going to work out and was available to do some heavy lifting for a while.  Your integrating things is probably best (though sorry for the work).  Is a fantastic project.

**Comment by jaymedavis** [comment]
thanks :)

there is a lot of great work here, I just have to bite off small chunks at a time to reduce potential issues. working on the account entities now - will get that released first then move on to more.

**Comment by hhlevnjak** [comment]
Hi,

I'm not sure if this is a question for @jaymedavis or @drewid , will there be an option to use managed accounts merged into the real version, if not, has anyone tested the branch by drewid if it is functional?

Thanks,
Hrvoje

**Comment by jaymedavis** [comment]
Yes, it will absolutely be merged into the master branch - but it requires my time to go through the various parts of the code and implement tests and verify Stripe documentation. With Stripe being such a fast moving target, in a matter of a week or two things can go stale.

There are a few things that were incorrect on the PR related to the account entity - most were minor, and will probably still get you 95% of the way there for now. @drewid or others can comment on their use of this branch. 

Other than my last small release, my focus is pretty much managed accounts (that seems to be what the people want! :smiley: ), With all of the entity work done (and live in the codebase), I'm hoping there's not much left to do here. There are a few other changes @drewid made (for example how the post body is sent to stripe), but that won't block the release of managed accounts (and it won't close this PR either because I don't want to lose the additional work). Keep up with the release notes to see what's available. :)

**Comment by hhlevnjak** [comment]
Thanks, it's great you're still working on this to keep it up to date. I'll check for your next release. :)

In the meantime, I got the version from the PR working, was missing a property to connect the bank account to the managed account, but easily resolved.

**Comment by jaymedavis** [comment]
If you wouldn't mind, would you check the code in master and make sure this is resolved? If not, I'd appreciate a PR or even just let me know the change. Thanks!

**Comment by hhlevnjak** [comment]
I edited it in his branch,don't know if I should add it there, but the only actual difference I made was to add a property to his StripeManagedAccountCreateOptions class like this:

[JsonProperty("bank_account")]
public string BankAccountToken { get; set; }

I create a token for the bank account using Stripe.js and add the token here when creating an account. It does not support the full API with all external account options.
