### ISSUE TITLE
Missing update method in StripeChargeService

### ISSUE THREAD

**Issue by oystehei** [jaymedavis/stripe.net#412]
I'm trying to find a way to update existing charges in Stripe with some metadata information. Looking at the Stripe API Reference it should be possible to update the *description*, *fraud_details*, *metadata*, *receipt_email* and *shipping* parameters of existing charges ([Link](https://stripe.com/docs/api#update_charge)). But the StripeChargeService is missing an update method, so I'm not able to set these parameters on existing charges.

Is there any particular reason for not including this method?

**Comment by jaymedavis** [comment]
It just hasn't made it in the library yet. Feel free to submit a PR.

**Comment by oystehei** [comment]
Added pull-request #415 to introduce the missing update method

**Comment by jaymedavis** [comment]
will handle this in the #415 PR, closing this issue
