### ISSUE TITLE
Stripe Webhook not working

### ISSUE THREAD

**Issue by skhizerabass** [jaymedavis/stripe.net#413]
My Stripe webhook is not working it just goes in pending with error (500) 
I followed all the steps u have given .
stripehandler.ashx 
Handler.cs
and providing it in Stripe API . 

i am confuse about something where should i provide the stripe api in the above two files . 
Secondly if it doesn't solve my issue how would i solve it 

![image](https://cloud.githubusercontent.com/assets/15678235/10981437/9df5b2fc-8429-11e5-8a68-c236d2013ec8.png)

![image](https://cloud.githubusercontent.com/assets/15678235/10981911/31a95aa6-842c-11e5-8d07-35076d85410c.png)

![image](https://cloud.githubusercontent.com/assets/15678235/10981941/67c98b1a-842c-11e5-8df3-48d3fdbd0d31.png)

![image](https://cloud.githubusercontent.com/assets/15678235/10981979/9af0dff2-842c-11e5-90f0-2929fc9ab9b4.png)

And if there is anyway of testing it on localhost it would be very helpful thanks please reply asap

**Comment by skhizerabass** [comment]
![image](https://cloud.githubusercontent.com/assets/15678235/10982184/a3a7e82e-842d-11e5-9a35-a892b9c60733.png)

this is the image i got from Webhook Test Response

**Comment by jaymedavis** [comment]
You need to turn errors on, this is the generic asp.net error page

**Comment by skhizerabass** [comment]
how would i make it sir ? i know this is off the topic but if you can help me out . may be i made a blunder in uploading the project . or something because it is my first time . thanks alot

**Comment by jaymedavis** [comment]
The directions are in that page you posted. You need to set CustomErrots mode off in your config.

**Comment by andysinclair** [comment]
I'm using the new Stripe WebHook Handler from the .net team:

https://github.com/aspnet/WebHooks

Stripe handler here:

https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Receivers.Stripe/Extensions/HttpConfigurationExtensions.cs

It's working really well and does a lot of the heaving lifting such as checking that the message originated from Stripe. It works really well in conjunction with this library.

**Comment by jaymedavis** [comment]
Thanks @andysinclair.

**Comment by skhizerabass** [comment]
![image](https://cloud.githubusercontent.com/assets/15678235/11015026/d6b2b01c-856f-11e5-90c3-36cfdb658c23.png)

I have resolved the previous issues now it isn't creating the handler . I don't know what i am missing Below is the code of my handler

![image](https://cloud.githubusercontent.com/assets/15678235/11015028/04c5a7de-8570-11e5-9581-ad7234b3047f.png)

![image](https://cloud.githubusercontent.com/assets/15678235/11015029/0fc10e94-8570-11e5-8e77-88ad083124eb.png)

**Comment by skhizerabass** [comment]
Finally made it . Thanks for the Help .
