### ISSUE TITLE
No support for .NET 4.5?

### ISSUE THREAD

**Issue by francisrath** [jaymedavis/stripe.net#418]
I have added stripe.net to a project built against .NET 4.5.2, but I get a warning that says
```
The primary reference "Stripe.net, Version=5.1.1.0, Culture=neutral, processorArchitecture=MSIL" 
could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. 
This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".
```

Is this on purpose? It seems strange to target 4.6 only? I will try to upgrade my project to 4.6, but it would be nice with support for at least 4.5+ :)

**Comment by jaymedavis** [comment]
I was waiting for feedback if I should/needed to drop the version to 4.5. :)

I upgraded TLS to try for 1.2 for better security. I believe that is available in 4.5 though. I will try to fix this for you this evening so it is available.

**Comment by francisrath** [comment]
Wow! That was quick :)

The project I am working on right now moved really well to 4.6, so it is not critical for me, but I guess it is best to target the lowest framework version that has the required feature set?

**Comment by jaymedavis** [comment]
exactly - I should have done that in the first place. :)
