### ISSUE TITLE
How do i create a token using an existing customers card?

### ISSUE THREAD

**Issue by brentdavid2008** [jaymedavis/stripe.net#419]
Based on the stripe api docs, i should be able to create a charge using an existing card on someones customer account.  However, i don't ever want this always be the default card.  I tried creating a token using the token service, but the classes require me to send new card information.  The stripe docs say to pass a single string id of the card id, but your classes want all of it.  I want to pick a single card id from the customer and charge them once. How do i accomplish this?

**Comment by jaymedavis** [comment]
this is a good question. a similar one was asked the other day. perhaps see if you can find that issue (I think it's open) and see if they are related. I'm not sure what the answer is, but I would contact Stripe to find out how to do this in their API - once the logic for how it works is apparent, it might make it more obvious in stripe.net.

**Comment by SoftwareByBrent** [comment]
I'm assuming you're referring to #391.  While this is close, Stripe assumes you want the default card here.  In my case i do not. i want to show all the cards that someone has on their customer account, let them pick one and use it to charge it. I was on 2.3.x and it had a Card and CardId property on the charge object.  since updating, this is gone, and i'm trying to figure out how to do the same thing that i had before.  Stripe support says that i should be able to pass both a full object and/or an Id on that token request for "card", as does their api docs. Is this something that needs changed in the project?

**Comment by jaymedavis** [comment]
this is still supported, but you don't pass parameters the same way. give the readme a quick look

**Comment by SoftwareByBrent** [comment]
I'll keep looking but ran into something else. Stripe.StripeException: Missing required param: id when creating a plan.  the stripe api docs do show the Id is required, but the readme says it'll return one for me. (most of stripe's objects do i'm surprised they chose not to do this with this one). Just letting you know. :)

**Comment by jaymedavis** [comment]
interesting - my test all pass for plans, I shouldn't be having this issue.

**Comment by codeplay87** [comment]
From the api docs i presumed you would pass the CardId that was on 2.3.* as the Source.Id https://stripe.com/docs/api#create_charge-source. Also interested in this case as described by @brentdavid2008 with using a non default card in the charge.

**Comment by brentdavid2008** [comment]
on the stripesourceoptions even though it says tokenId, i've used it as the card id when creating the token.  
so i do something like this

public StripeToken CreateCardToken(string customerId, string cardId) {
            var options = new StripeTokenCreateOptions() {
                Card = new StripeCreditCardOptions() { TokenId = cardId},
                CustomerId = customerId,
            };
            return TokenService.Create(options);
        }


i use stripe connect though, and i had to create the token *WITHOUT* the customer ID attached, then, "create the card" with the token as the ID of the source and no card details. that attached to the the customer. after that i could "create a charge" like i normally would, using the connected accounts api key as if it was a regular api key

**Comment by jaymedavis** [comment]
Thanks @brentdavid2008. I need to investigate this further and see if the CreditCardOptions property should be renamed to TokenOrCardId ... seems like that would clear this up.

(the plan id on this thread was solved - it did need to have that added to the readme)

**Comment by jaymedavis** [comment]
the latest version cleaned up this mess (StripeTokenOrExistingCardId) on StripeCharges.

Checkout the new charge documentation to explain this (it was sort of a mess before)
