### ISSUE TITLE
On Plan create: Missing required param: id.

### ISSUE THREAD

**Issue by Eonasdan** [jaymedavis/stripe.net#420]
I'm trying to programmatically create a new plan if a plan by that name doesn't exists, however the following code results in `Missing required param: id.`

```
var stripePlanService = new StripePlanService();
StripePlan stripePlan;
try
{
	stripePlan = stripePlanService.Get(Name);
}
catch (StripeException exception) when (exception.Message.Contains("No such plan"))
{
	stripePlan = stripePlanService.Create(new StripePlanCreateOptions
	{
		Amount = (int) (Price*100),
		Currency = "usd",
		Interval = "month",
		Name = Name
	});
}
```

**Comment by jaymedavis** [comment]
there was another issue with this recently and I'm not sure what's going on. you might want to confirm with stripe that no Id needs to be passed for this. also, try to piggy back off the existing issue with this when you find it

**Comment by Eonasdan** [comment]
yup. looks like you're correct: https://stripe.com/docs/api#create_plan-id

Might want to update your docs/example

thanks

**Comment by jaymedavis** [comment]
the fix here was to add an id? reopening for documentation purposes

**Comment by Eonasdan** [comment]
Yes. Looks like it's just a string value and only shows up in the API or the Dashboard.

![image](https://cloud.githubusercontent.com/assets/1006516/11670732/8b1da9fc-9dd1-11e5-9a5e-ee3b4ae47e99.png)


```
stripePlan = stripePlanService.Create(new StripePlanCreateOptions
    {
        Amount = (int) (Price*100),
        Currency = "usd",
        Interval = "month",
        Name = Name,
        Id = "1"
    });
```

**Comment by Eonasdan** [comment]
Aside: might be nice to make Interval an Emun of possible values.

**Comment by jaymedavis** [comment]
thx

**Comment by jaymedavis** [comment]
this must be new - all of my tests never had a problem before, and since I'm forcing the API version, this sounds like a stripe bug if they changed that

**Comment by Eonasdan** [comment]
also, the `StripePlanService.Get` uses the Id instead of the Name

**Comment by jaymedavis** [comment]
thx

**Comment by Eonasdan** [comment]
hmm new problem.

I'm getting an error trying to cancel the subscription: `"Customer cus_7VEHv7fJzuJAAV does not have a subscription with ID 1"`. I also tried this with "Membership"

![image](https://cloud.githubusercontent.com/assets/1006516/11697870/d5906d4a-9e89-11e5-94f6-55bcc585c655.png)

**Comment by jaymedavis** [comment]
be sure to check out the tests in the project for doing these things. that can help serve as documentation for what works. the plan thing really surprises me - I've only heard from two people having this problem. you may want to email stripe and make sure your API version matches the version in StripeConfiguration.cs

**Comment by Eonasdan** [comment]
Account API is on `2015-10-16 (latest)` and I'm using the 5.1.2 nuget package

**Comment by Eonasdan** [comment]
insert faceplam on the cancellation. Needs the sub Id NOT the plan id

**Comment by jaymedavis** [comment]
well at least that's easy enough to fix. :)

I'll look into the plan issue when I get a chance.

**Comment by jaymedavis** [comment]
Yeah, my test did generate a unique identifier for the plan, this is just a readme update. will close when I push up the changes.
