### ISSUE TITLE
Can't Create a New Card After Creating a Customer

### ISSUE THREAD

**Issue by crikong** [jaymedavis/stripe.net#421]
I can't create a new card for a customer that I just created. Here is the code I am using below. I am getting "Your Card Was declined" error. Does anyone know why?

 StripeCardService NewStripeCardService = new StripeCardService(StripeLiveScretKey);

                  //Setting up the card
                    StripeCardCreateOptions NewStripeCardCreateOptions = new StripeCardCreateOptions();
                    NewStripeCardCreateOptions.CardNumber = CreditCardNumber;
                    NewStripeCardCreateOptions.CardExpirationYear = ExpirationYear;
                    NewStripeCardCreateOptions.CardExpirationMonth = ExpirationMonth;
                    NewStripeCardCreateOptions.CardNumber = CreditCardNumber;
                    NewStripeCardCreateOptions.CardCvc = CVCCode;
                 
                   

                    StripeCard TheStripeCard = NewStripeCardService.Create(TheStripeCustomer.Id, NewStripeCardCreateOptions);

**Comment by jaymedavis** [comment]
view the code under my test data folder for .valid() card data. make sure you are testing with a card that will pass.

**Comment by crikong** [comment]
I have verified that the card data are valid. The only thing is there is no money in the card I am using. Well there is less than a dollars in it. It is a test card. Does Stripe verifies the amount that is in the card before adding it ?

**Comment by crikong** [comment]
I have also filled the address properties like you did in test_data but no luck

**Comment by crikong** [comment]
I have checked my log in stripe and all the parameters I passed get to stripe properly I am a little bit confused

**Comment by crikong** [comment]
I think the library changed and that is why my code stopped working. Even previous app stopped working

**Comment by jaymedavis** [comment]
most places put a $1 hold charge to verify a card that comes off later. try with a card that has money

**Comment by jaymedavis** [comment]
assume this is fixed. closing.
