### ISSUE TITLE
How to charge customer by getting invoices in C#

### ISSUE THREAD

**Issue by srinivas1612** [jaymedavis/stripe.net#422]
From my stripe account I create customer and generate invoices to him. Now when customer login into my application i will display all invoices of customer based on CustomerId. From here How can i charge him based on the invoices and entering his card details.

**Comment by jaymedavis** [comment]
I'm not sure I understand the question - do you want him to pay all invoices at once from his credit card on file, or a new credit card? 

I will close this issue for now - I would work with Stripe to find out what the logic is for solving this problem (I don't know the solution). If you determine after that that the library is lacking the necessary features to accomplish the goal, feel free to reopen this issue.
