### ISSUE TITLE
StripeCardCreateOptions.Source.Metadata error

### ISSUE THREAD

**Issue by HankSmith22** [jaymedavis/stripe.net#427]
Getting "error: type: "api_error", message: "An unknown error occurred" when using StripeCardCreateOptions.Source.Metadata and declaring new Dictionary<string, string>(); and adding two simple text items causes the error.

The metadata received message by the API:
    metadata: "System.Collections.Generic.Dictionary`2[System.String,System.String]"

The stripe api as of 1/8/16 was accepted these card creations with this meta data, but after that started rejecting with the generic error.

Commenting out the metadata lines for this fixed the issue.

The metadata on all other items appear to be functioning correctly. Whereas the StripeCardCreateOptions.Source.MetaData is appearing as the ToString() it looks like.

Also StripeCardUpdateOptions.Source.MetaData works correctly. So it appears to just be StripeCardCreateOptions.Source.Metadata

Using 5.1.3

**Comment by jaymedavis** [comment]
This looks like a bug - 

Where StripeSourceOptions has this value as the JsonAttribute "source[metadata]" where as every other attribute simply has "metadata".  The ApplyAllParameters function in ParameterBuilder needs to account for this on line 27. 

Thanks.
