### ISSUE TITLE
The type or namespace name 'Stripe' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by abdulfawad** [jaymedavis/stripe.net#433]
Last i am working with Stripe 1.7.7.0 But due to some project changes i have upgrade the Stripe.net new .dll but its cause an error. "The type or namespace name 'Stripe' could not be found (are you missing a using directive or an assembly reference?)" i have also tried with fully qualified path to each class like Stripe.StripeCustomer. I have found by click on any class its reference and definition is correct. Class appear in light blue color which found correct but don't know why its appear with this error. i have download Stripe Source and check the reason but found no issue. Please help me how can i will resolve this issue. i am using VS 2013

**Comment by jaymedavis** [comment]
what version of .net are you using?

**Comment by jaymedavis** [comment]
have you fixed this? Did cleaning your bin folder/reinstalling take care of this? Closing - assuming this is fixed.

**Comment by victorkani** [comment]
I am getting this error when i tried to upgrade from version 5.1.1 to 5.3.0. Since Stripe requires TLS 2.0 i have upgraded from 5.1.1 to 5.3.0. I have followed your suggestion [Did cleaning your bin folder/reinstalling take care of this]
