### ISSUE TITLE
Decimal not supported in Application Fee Percent

### ISSUE THREAD

**Issue by heyanctil** [jaymedavis/stripe.net#437]
I've got this error **_Invalid decimal: 0,6; must contain at maximum two decimal places._** when I tried to set ApplicationFeePercent on a new Subscription:

    var stripeSubscriptionOptions = new StripeSubscriptionCreateOptions
    {
        ApplicationFeePercent = applicationFeePercent
    };

I dig the problem a little bit. In the Stripe documentation, there is that explanation:
_**When creating or updating a subscription, you can specify an application_fee_percent parameter as an integer between 1 and 100.**_

But I found this discussion that seem to open a door:
https://groups.google.com/a/lists.stripe.com/forum/#!topic/api-discuss/oFF-zoFkPZU

**Comment by heyanctil** [comment]
I remark that there is a comma in the number pass to Stripe: 0,6. Maybe the problem has something to do with the culture.

**Comment by jaymedavis** [comment]
I'm assuming this is because you want 6% of 1%? The value in Stripe.net is a decimal, so you should be able to pass 0.6 with no problems.

**Comment by jaymedavis** [comment]
If you really want to use the comma, I'm sure you could find a way using decimal.Parse or CultureInfo, or some combination of that.

**Comment by heyanctil** [comment]
I already set ApplicationFeePercent to **(decimal?) 0.6**.

I think the library should prevent this type of error by using something like «CultureInfo.InvariantCulture» when casting to a string.

**Comment by jaymedavis** [comment]
I'd be fine with this if there are no other issues with it - feel free to submit a PR. :). It would be nice to have a test verifying it works (copying an existing one is fine), and of course making sure the rest of the tests pass.
