### ISSUE TITLE
STRIPE.NET USERS - PLEASE PROVIDE FEEDBACK TO HELP STRIPE.NET BECOME GREAT!

### ISSUE THREAD

**Issue by jaymedavis** [jaymedavis/stripe.net#439]
This issue is intended to be a place for everyone to post their comments or feedback about using Stripe.net. Things that were difficult to figure out (such as perhaps setting an object type to `card`). Feel free to add comments. No comments are 'stupid' and I welcome all feedback. No trolling please.

1) What was painful to figure out, what was easy to figure out?
2) What is difficult to understand or was documented poorly? Is the documentation too cumbersome? Too little?
3) What do you think could be changed to make things easier? (such as a list for object type instead of specifying `card` as mentioned above)

Thank you in advance-
Jayme

**Comment by heyanctil** [comment]
I had to figure out how to implement Stripe with Connect. To finally get it work, I had to dig into closed issue and bother you on twitter :)

I went through a long road to get it work!

I think some kind of demo project (with best practices) could be helpful.

**Comment by jaymedavis** [comment]
Thanks @heyanctil. I've had a few users report the issue with loading Stripe.dll that you had - did cleaning your bin directory fix that? Also, did you follow the documentation for connect on the readme, and could you explain where it was lacking?

Good idea on the demo - thanks!

**Comment by SeanFarrow** [comment]
Hi,

It would be nice to have interfaces for the corresponding service classes to help with dependency injection. I'm happy to do this if it's something you'd want.
Cheers
Sean.

**Comment by jaymedavis** [comment]
Hey Sean -

This topic has came up a few times. There shouldn't be any reason you cannot inject the classes (assume you mean services) into your project. You simply need a private property and to set that property via your constructor. Every major DI framework supports working with classes directly as well, as does every major testing library if you are interested in mocking. My stance on this is pretty much inline with googling "should I use an interface for every class in c#". I personally believe this practice is cargo cult programming, and interfaces are designed to be used for the purpose of a contract that has multiple implementations (see MSDN). If you have a specific struggle with something, I'd be happy to help work through it.

**Comment by aramayowa** [comment]
Thanks a ton for all your hard work, it's very much appreciated.

One thing i can think of is implementing some of the [best security practices](https://stripe.com/docs/webhooks) around WebHooks out of the box. For example, retrieving the event from the API based on the ID in the webhook event and not trusting any of the other details in the json payload.  

Doing something like that might help allay fears about the endpoints being open to the internet.

In any case, thanks again.

**Comment by jaymedavis** [comment]
Appreciate it @aramayowa.  Webhooks definitely need some integration love!

**Comment by jaymedavis** [comment]
Closing this - thanks all

**Comment by tstivers1990** [comment]
> Hey Sean -
> 
> This topic has came up a few times. There shouldn't be any reason you cannot inject the classes (assume you mean services) into your project. You simply need a private property and to set that property via your constructor. Every major DI framework supports working with classes directly as well, as does every major testing library if you are interested in mocking. My stance on this is pretty much inline with googling "should I use an interface for every class in c#". I personally believe this practice is cargo cult programming, and interfaces are designed to be used for the purpose of a contract that has multiple implementations (see MSDN). If you have a specific struggle with something, I'd be happy to help work through it.

Interfaces come into play when unit testing. Yes, you can override virtual members. But you don't always want to mark methods virtual. And getting into the habit of marking things virtual for the sake of unit testing has more drawbacks than the zero drawbacks that come with using interfaces. Then there's the fact you can't always mark something virtual when you may need to, in order to facilitate unit testing. But you can always put it behind an interface.
