### ISSUE TITLE
Getting Balance Transaction object when creating a charge

### ISSUE THREAD

**Issue by Robert-Coulston** [jaymedavis/stripe.net#441]
I wanted to retrieve Stripe's fee from the API when making a charge a charge. The response I got from Stripe.com support was :

Here's an example to do this in PHP, using our latest bindings.

echo \Stripe\Charge::create(array(
  "amount" => 500,
  "currency" => "usd",
  "source" => $token->id, // obtained with Stripe.js
  "description" => "Charge for test@example.com",
** ** "expand" =>array("balance_transaction")****
));

The expand property is supposed to retrieve the balance_transaction object in the response which contains the fees.

I cannot see how to set this property?

**Comment by willous** [comment]
This may be an alternative option; you could calculate the fee prior to making the charge. 

https://support.stripe.com/questions/can-i-charge-my-stripe-fees-to-my-customers

Otherwise, I suspect you'll have to retrieve the balance transaction separately after the charge is made.

**Comment by jaymedavis** [comment]
Expanding a balance transaction is actually the example I used for the readme: https://github.com/jaymedavis/stripe.net#expandable-properties

When you create the charge service, you need to set the balance transaction to expand so you get that object.

**Comment by Robert-Coulston** [comment]
Thank you

**Comment by jaymedavis** [comment]
No problem :)

**Comment by harshalone** [comment]
an easy way is to add expand in your current request

```
$charge = \Stripe\Charge::create(array(
				  "amount" => $totalAmount,
				  "currency" => $currency_code,
				  "source" => $stripeToken,
				  "transfer_group" => $orderId,
				  "expand" => array("balance_transaction")
				));
```
