### ISSUE TITLE
Managed Accounts 

### ISSUE THREAD

**Issue by mhollas** [jaymedavis/stripe.net#442]
Great work! 
I implemented managed account a couple weeks ago on my project. Just as I realized that the source I had needed some work for updating accounts, I come here and BAM! 4 days ago you posted exactly what I was looking for. 

I have noticed a couple things so far. ParameterBuilder.cs needs to manage the new StripeAccountBankAccountOptions in order to add a bank account to the connect account as an account update. 

` else if (property.PropertyType == typeof(StripeAccountBankAccountOptions))
                        {
                            var bankAccountOptions = (StripeAccountBankAccountOptions)value;
                            
                            newUrl = ApplyNestedObjectProperties(newUrl, bankAccountOptions);
                        }  `

However there is a read only property in there that works its way into the url so it fails, I'm working in a fix now, maybe just get rid of the read only?

Second, and I looking into it right now, StripeExternalAccountConverter errored out becasue WriteJson was in not implemented. when using AccountService Get method for retrieving connect. account

**Comment by jaymedavis** [comment]
Thanks for the feedback!

I tried with the object property to automatically set Card/Bank Account to their value stripe accepts (to take this off the user). Would you ever have a bank account where the value isn't "bank_account"?

I will check out your first suggestion as a fix - I'm surprised I missed that, I tested pretty thoroughly. I guess I only covered managed accounts directly - not using connect.

Thanks again, and please let me know anything else you find!

**Comment by jaymedavis** [comment]
So the first part of this is actually in the parameter builder - there shouldn't be any issues with this. Also, if you are using the bank account, you want that read only property in there to tell Stripe it is a bank_account, are you still having this issue?

Please re-open this if you are - I do not see anything wrong with the code as is.
