### ISSUE TITLE
StripeExternalAccountConverter.cs

### ISSUE THREAD

**Issue by mhollas** [jaymedavis/stripe.net#443]
Hi,
I mentioned this in a previous post here are more details
there is a error thrown in the StripeExternalAccountConverter.cs WriteJson method when trying to return a StripeAccount object through a Web API controller. 

a StripeList<object> is being passed into the WriteJson method. there is no stack information so I'm a little lost.

**Comment by jaymedavis** [comment]
Can you post some sample code so I can recreate this?

**Comment by mhollas** [comment]
Sure thing. I just simplified a GET method I was using but this should trigger it

` public class CustomerController : ApiController
    {

        public StripeDetails Get()
        {
            var Id = "accountId"
            return GetStripeAccont(id);
        }
 private Stripe.StripeAccount GetStripeAccount(string id)
        {
            return new StripeAccountService()
                .Get(id);;        
        }
}`

**Comment by jaymedavis** [comment]
Are you sure the account id is correct? What kind of account is it? Managed/Standalone/ via connect?

If it's connect, I believe you need to pass the StripeRequestOptions to the service (details on the readme). Finally - can you wrap the code inside a try/catch(StripeException) and post the details for that?

**Comment by jaymedavis** [comment]
Here is the integration test in stripe.net: https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.Tests/account/when_retrieving_an_account.cs

This test passes for me

**Comment by mhollas** [comment]
Yeah the account data is being retrieved from stripe fine. the error fires when the controller returns the data to the UI. I think it has something to do with the controller trying to serialize Json for the api response.

**Comment by jaymedavis** [comment]
Ah - so I don't think this is actually a stripe.net issue then - what is StripeDetails?
