### ISSUE TITLE
Problem creating a charge with CustomerId

### ISSUE THREAD

**Issue by danielcamargo** [jaymedavis/stripe.net#444]
This is the test method to replicate the problem:
        ```
[TestMethod]
        public void TestMethod1()
        {
            const string StripeKey = "sk_test_*****";
            StripeConfiguration.SetApiKey(StripeKey);
            var chargeService = new StripeChargeService();
            var stripeCharge = chargeService.Create(ValidCard());
            Assert.IsNotNull(stripeCharge);
        }

        public static StripeChargeCreateOptions ValidCard()
        {
            var cardOptions = new StripeSourceOptions()
            {
                AddressCountry = "US",
                AddressLine1 = "24 Beef Flank St",
                AddressLine2 = "Apt 24",
                AddressCity = "BIGGIE",
                AddressState = "NC",
                AddressZip = "27617",
                Cvc = "1223",
                ExpirationMonth = "10",
                ExpirationYear = "2021",
                Name = "Joe Meatballs",
                Number = "4000000000000077",
            };

            return new StripeChargeCreateOptions()
            {
                Source = cardOptions,
                Description = "Joe Meatball Charge",
                StatementDescriptor = "Joe Meatball Sub",
                Amount = 5253,
                Currency = "usd",
                CustomerId = "cus_****",
                Metadata = new Dictionary<string, string>
                {
                    { "A", "Value-A" },
                    { "B", "Value-B" }
                }
            };
        }
```
From Code:
Additional information: Invalid string: {"number"=>"400000******0077", "exp_month"=>"10", "exp_year"=>"2021", "cvc"=>"****", "name"=>"Joe Meatballs", "address_line1"=>"24 Beef Flank St", "address_line2"=>"Apt 24", "address_city"=>"BIGGIE", "address_zip"=>"27617", "address_state"=>"NC", "address_country"=>"US", "object"=>"card"}

From Stripe:

Request:
{
amount: "5253",
currency: "usd",
customer: cus_7xMp6V2dHMPzAd,
source:
{
number: "************0077",
exp_month: "10",
exp_year: "2021",
cvc: "****",
name: "Joe Meatballs",
address_line1: "24 Beef Flank St",
address_line2: "Apt 24",
address_city: "BIGGIE",
address_zip: "27617",
address_state: "NC",
address_country: "US",
},
description: "Joe Meatball Charge",

metadata:
{
A: "Value-A",
B: "Value-B",
},
statement_descriptor: "Joe Meatball Sub"
}

Respose:
{
error:
{
type: "invalid_request_error",
message: "Invalid string: {"number"=>"400000******0077", "exp_month"=>"10", "exp_year"=>"2021", "cvc"=>"****", "name"=>"Joe Meatballs", "address_line1"=>"24 Beef Flank St", "address_line2"=>"Apt 24", "address_city"=>"BIGGIE", "address_zip"=>"27617", "address_state"=>"NC", "address_country"=>"US", "object"=>"card"}"
}
}

**Comment by jaymedavis** [comment]
It might be trying to think your source object is a token - try setting object = "card" on your StripeSourceOptions - let me know if that fixes it.

**Comment by danielcamargo** [comment]
Hi @jaymedavis, first of all, thank you for your time. I've modified the code as you suggested but the result was the same. It's important to mention that the test passes when I remove the CustomerId field.

**Comment by jaymedavis** [comment]
Did you get this resolved? Try removing metadata if not - perhaps it's related to that? The code looks good - re-open with more info if this is not solved, or please let me know how you solved it. :)

**Comment by jaymedavis** [comment]
I believe this may be a bug with metadata - I just marked another issue as a bug for this same issue. (i think)

**Comment by danielcamargo** [comment]
The problem still persists. I've created a work around storing the information in Metadata.

**Comment by jaymedavis** [comment]
Metadata on the Charge, or elsewhere? Any code samples you could share so I can make sure my fix is right? (re-opening as it may be something else)

**Comment by danielcamargo** [comment]
In my scenario, when a client buys a product license, he/she pays 25% of the license and divides the rest in 11 payments. In terms of steps this is what I do:

1. Create a customer.
2. Create a charge informing the customer ID (this is where the work around is).
3. Create a subscription for that client in a plan (with one month trial to avoid the first payment of the subscription) to charge the other 11 payments once a month.

My need is to relate the payment of the first charge to the subscription.

Thank you!

**Comment by jaymedavis** [comment]
It may be that when you set the CustomerId, it's expecting you to pass an existing card and not a new card. In that case, you would pass the existing card ID as the 'token' (I know this is funky - there's a blurb on the readme about how I am fixing this soon). Are you sure this is supported by stripe? To create a charge with a customer id and add a new card at the same time?

**Comment by jaymedavis** [comment]
there is also another update coming very soon that pushes the content of the request to the post body instead of the URL - so the error messages will be A LOT more easy to debug. Re-open this if the next version of Stripe.net does not make it obvious what the problem is. :)

**Comment by danielcamargo** [comment]
Thank you @jaymedavis, I will update it as soon as possible and let you know of any unexpected results.
