### ISSUE TITLE
UWP profile not suported

### ISSUE THREAD

**Issue by chaitanyakale** [jaymedavis/stripe.net#446]
Not able to install stripe.net in UWP app

**Comment by jaymedavis** [comment]
This is currently an active PR and will be completed soon. You are welcome to pull down the code, switch to the portable branch, and build the library - everything should work.

**Comment by jaymedavis** [comment]
Which particular platform are you wanting to test on? Have you tried the branch?

**Comment by chaitanyakale** [comment]
Using it through PCL with Universal Windows app and planning to use with Xamarin (now Microsoft) Android and iOS apps.

Thanks for such a quick response.
I haven't got a chance to try the branch, as there are other pending work items as well, getting it via NuGet, if almost there, would be great. If it will take more than 2 weeks, then I may build myself.

**Comment by jaymedavis** [comment]
I can send you a dll to test with. The hold up is testing this, I can get it in NuGet, but not until I can verify against other platforms.

**Comment by chaitanyakale** [comment]
Sure, I'll test it today then.

**Comment by jaymedavis** [comment]
Send me an email and I can shoot it over. jaymedavis at gmail
