### ISSUE TITLE
Stripe Verification - File Upload

### ISSUE THREAD

**Issue by pradt** [jaymedavis/stripe.net#448]
I noticed that the file upload process is not built for Stripe.net, could I please make a feature request for this? 

As well as updating the StripeAccountCreateOptions to be updated with a field to accept the token ? 

Thanks

**Comment by jaymedavis** [comment]
File uploads do need to be completed - tokens are accepted already though. Create either a bank account or a credit card options and the token is on that object.

**Comment by pradt** [comment]
Sorry I meant for the token for the upload of the file. I was looking to upload the file, get the token and then execute StripeAccountService.Create. The entity and the shared entity for Account create do not appear to have a token field to include.

**Comment by jaymedavis** [comment]
BusinessLogoFileId? Or another property? What's the name of the Stripe property for the token?

**Comment by pradt** [comment]
hi from https://stripe.com/docs/connect/identity-verification it sez that it should be withing legal_entity.verification.document ...

**Comment by jaymedavis** [comment]
Check out the latest release notes - managed accounts was released, but there are a few properties left. Legal Verification being one of them.

**Comment by jaymedavis** [comment]
All of this is on the way later today for StripeAccount stuff - the only thing yet to be implemented is additional owners. Expect this in the release later this evening. :)

**Comment by Pradi01988** [comment]
can you please tell whether we can upload verification document while we are creating bank account ? Please its bit urgent.. Thank you

**Comment by jaymedavis** [comment]
I am working on the file upload feature this week, along with StripeDisputes. It is not available right now. There is a JavaScript workaround you can ask Stripe about in IRC or support in the meantime if you'd like.

**Comment by Pradi01988** [comment]
I am trying to integrate stripe upload api using c# httpwebrequest. I am stuck with the type of data to pass for "file" parameter. And also not sure what ContentType have to use for sending data to upload api. Can you please help me out. Thank you..
