### ISSUE TITLE
.NET Core 5 Package?

### ISSUE THREAD

**Issue by Chaddeus** [jaymedavis/stripe.net#451]
Any chance to get a .NET Core 5 compatible package of this?

**Comment by jaymedavis** [comment]
In the works on #435. Needs to be tested - could you pull down that branch, compile, and test Stripe.Portable.dll? Please feel free to comment on that PR as the hold up is testing that it works now (just pushed latest bits last night).

**Comment by jaymedavis** [comment]
(see #435  for updates to this)

**Comment by jaymedavis** [comment]
done
