### ISSUE TITLE
Missing Newtonsoft.Json

### ISSUE THREAD

**Issue by kbugala** [jaymedavis/stripe.net#452]
I've installed the stripe.net via the nuget, I can see that the Newtonsoft.Json is installed but I'm getting the following error when using the stripe.net:

`Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Here is the packages.config:

`  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />`

web.config:

`<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>`

**Comment by kbugala** [comment]
Sorry, it was an old newtonsoft.json.dll in my dll directory.

**Comment by jaymedavis** [comment]
Thanks for updating with the fix! I'm sure someone else will come along and find help from this.
