### ISSUE TITLE
Xamarin Support

### ISSUE THREAD

**Issue by MagicalMaya** [jaymedavis/stripe.net#454]
We are planning to use this in a Xamarin project, but we are getting compatibility issues if we try to build in Xamarin. Saw your comment in one of the Xamarin forums, that you are planning to make it Xamarin compatible. 

https://forums.xamarin.com/discussion/30824/no-valid-ios-code-signing-keys-found-in-keychain-when-trying-to-debug-using-iphonesimulator

Could you let me know when is Xamarin compatible Stripe.net library release planned? Thanks.

**Comment by jaymedavis** [comment]
This is pretty much down to just configuring the nuget package to target Xamarin. If you are able to test this for me, I can send you a nuget package you can manually import to test out. 

I have been waiting to deploy this to the xamarin store until I can verify it works (just recently received my xamarin open source license).

**Comment by jaymedavis** [comment]
Let me know if you have some time - I am at work today, so it will be after 5pm est.

**Comment by MagicalMaya** [comment]
Could you share the nuget package, I can test it tomorrow morning India
Time, and revert?

Thanks.

**Comment by jaymedavis** [comment]
Yes @MagicalMaya - I will try to put this together for you this evening and post a link here.

**Comment by jaymedavis** [comment]
I released 6.0.1 which might take care of this. Let me know.

**Comment by MagicalMaya** [comment]
Great, thanks. will integrate & test it & share the results.

**Comment by MagicalMaya** [comment]
@jaymedavis, it works.

   - Built the Stripe portable project after resolving the nuget packages
   dependency in Visual Studio.
   - Imported the generated dll (release mode) in Xamarin project and
   - We were able to successfully test it both on Android/ iOS platforms.
   Tested mainly the card related functionality.

Could you update here once you publish it in Xamarin Marketplace, so we
could use the released package in our project?

Thank you!!

**Comment by jaymedavis** [comment]
I opened ticket #456 for discussion about adding this to the Xamarin Marketplace - be sure to leave a comment there and tell your friends. :) .... the more I see the need, the faster I can prioritize it to get done. I'm so glad your issues are resolved - I had to fix UWP at the same time, so I knew something was globally wrong. 

Thanks for the help and for opening this issue!
