### ISSUE TITLE
System.IO.FileNotFoundException' in mscorlib.ni.dll when running on UWP project

### ISSUE THREAD

**Issue by th30dor** [jaymedavis/stripe.net#455]
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.ni.dll 
 
Additional information: Could not load file or assembly 'Stripe.net.Portable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

I got the above error when running a Windows 10 UWP project with the newest Stripe 6.0.0 library from Nuget. I tried re-adding the Stripe package a couple of times. I also pulled the source, and ran build.cmd then loaded the nupkg file manually. But every time, I get the above error. 

I only get this at runtime.

**Comment by jaymedavis** [comment]
This must be something to do with the fact that I build the project as that dll, then deploy it to nuget by renaming it. I believe I just need to compile it with a new name. I will fix this tonight. 

In the meantime, you can pull down the codebase, compile the project, and change the Stripe.Portable project to output the file as Stripe.net - that will probably take care of it. If it does, I'll have a new nuget package for you this evening. Got some time to try that?

**Comment by th30dor** [comment]
Yeah, I'll try it now.

**Comment by th30dor** [comment]
So I changed the Assembly Name in the Stripe.Portable project to Stripe.net. I also modified the the build.cmd script to use the newly renamed Stripe.net file, but nothing changed. 

I'm thinking I didn't change the name where you wanted it to be renamed?

**Comment by jaymedavis** [comment]
There is a lot of information here: https://github.com/jaymedavis/stripe.net/pull/435 (long thread). 

There were a few users that had this working with UWP. That might mean something else is required in your particular setup - search for 'project.json' in that thread and see if that might help. Also, Windows Universal 10 seems to be an option that should be in that list. That is using Profile259 - there may be something else that needs to be done to get this to support Windows 10.

**Comment by jaymedavis** [comment]
I'm not sure if I can modify the existing portable project, or if I will need to copy/pasta the Stripe.Portable project compile includes under a different project. I would start by creating a new project that has all of the types you need, open Stripe.Portable in notepad, copy over all the compile includes to the project you just created (in notepad), then compile that project. That might do it. I can take a look this afternoon.

**Comment by th30dor** [comment]
I'll try and take a look tomorrow and see if I can make it work. It's getting pretty late here.

**Comment by jaymedavis** [comment]
No worries - I'll try to get it fixed tonight. Can you give me a few instructions or email me a sample project to test with? jaymedavis @ gmail.

**Comment by th30dor** [comment]
I sent you a sample project, although all I did was to create a new UWP project, install Stripe via nuget, and call Stripe initialization.

**Comment by jaymedavis** [comment]
Thanks

**Comment by dwdickens** [comment]
This error has appeared for me as well yesterday (was working fine before). The only change I can see in my source code is the version of the dependency for Newtonsoft.Json increased from 7.0.1 to 8.0.2 but I'm not sure if this happened when I (unsuccessfully) reinstalled all the packages to try and fix this problem.

**Comment by jaymedavis** [comment]
Are you on UWP as well @dwdickens? What's your target lib?

**Comment by jaymedavis** [comment]
Ok, give this a shot again. I was able to get a UWP app running on my end.

**Comment by th30dor** [comment]
Working fine now, thanks!!

**Comment by jaymedavis** [comment]
No problem!
