### ISSUE TITLE
Stripe Connect - Account Verification: Missing minimum verification requirement fields

### ISSUE THREAD

**Issue by brakok** [jaymedavis/stripe.net#457]
Hi, I'm currently trying to create a managed account with Stripe .net and I can't find how to add the minimum verification requirements to create an account.

I see that there's an AccountVerification property on StripeAccount with some missing fields, but when creating it with the StripeAccountService and with the StripeAccountCreateOptions, I can't find a way to map the required fields to the missing required fields to have a valid account (nor with the StripeAccountUpdateOptions).

Missing required fields:

legal_entity.dob.day
legal_entity.dob.month
legal_entity.dob.year
legal_entity.first_name
legal_entity.last_name
legal_entity.type
tos_acceptance.date
tos_acceptance.ip

Am I missing something or this has not yet been implemented?

**Comment by jaymedavis** [comment]
Yes - there are a few properties I have not yet implemented. Checkout StripeAccountSharedOptions - it's the base class of the one you mentioned (create and update share properties on Stripe). You will see the few that are missing and need to be implemented in the comments.

Thanks for letting me know you need this so I can put it on the radar.

**Comment by brakok** [comment]
Ok, I see. That's what I thought, because Stripe Connect is still young (beta). Keep up the good work and I will be watching the next versions for this.

**Comment by jaymedavis** [comment]
All of this is on the way - everything except additional_owners. Expect a checkin later today. :)
