### ISSUE TITLE
Stripe charge - Exception when ReceiptEmail  property has a value.

### ISSUE THREAD

**Issue by doronavin** [jaymedavis/stripe.net#465]
I'm getting the following error when trying to create a charge, only when setting the receiptEmail property(When the property is not being set, everything works fine).

The error:

"Additional information: Error while talking with one of our backends. Sorry about that! We have been notified of the problem. Please contact support@stripe.com if you have any questions."
 

The code:

```
var charge = new StripeChargeCreateOptions
            {
                Amount = amountInCents,
                Currency = "usd",
                Description = string.Format("{0} services", category.new_name),
                Source = new StripeSourceOptions()
                {
                    // set this property if using a token
                    TokenId = token.Id,
                    ReceiptEmail = token.Livemode ? payment.ReceiptEmail : null
                },
                Capture = true
            };
StripeCharge stripeCharge = stripeChargeService.Create(charge);
```

I'm using stripe 5.3.0.0, 

Did any of you guys came across this issue? 
I need a fix asap (I know there is a new version, but I wish to avoid updating right now)

Thanks.

**Comment by jaymedavis** [comment]
If you set a Token, you cannot set anything else. Checkout the very top of the readme for the changes that are coming soon to remedy the confusion with this. :)

**Comment by doronavin** [comment]
Thank you so much for the quick reply!!!
Do you know if there's a way to use the email to generate the token
(I couldn't find in the documentation), using the android/ios sdk,
or must I use the version without the token to use the email.
I need stripe to send them the invoice via email.

Thanks again

**Comment by jaymedavis** [comment]
Not sure which library you are using for tokens - that would be a better question for Stripe. Please feel free to report back whatever you find out. :)
