### ISSUE TITLE
Still Having Trouble With Metadata

### ISSUE THREAD

**Issue by rmcohen** [jaymedavis/stripe.net#488]
Per your suggestion I changed to the SourceCard model for creating cards with metadata.  Here's the code:

StripeCardCreateOptions CardCreateOptions = new StripeCardCreateOptions();
						CardCreateOptions.SourceCard = new SourceCard();
						CardCreateOptions.SourceCard.Name = Actor.SessionLogin.Profile.ToString();
						CardCreateOptions.SourceCard.ReceiptEmail = Actor.SessionLogin.Profile.Email;
						CardCreateOptions.SourceCard.Description = "Credit Card Submission";
						CardCreateOptions.SourceCard.Number = Action.QueryParts["ccnumber"];
						CardCreateOptions.SourceCard.ExpirationMonth = Action.QueryParts["ccexpiry"].Substring(0, 2);
						CardCreateOptions.SourceCard.ExpirationYear = Action.QueryParts["ccexpiry"].Substring(3);
						CardCreateOptions.SourceCard.Cvc = Action.QueryParts["cccvc"];
						CardCreateOptions.SourceCard.Metadata = new Dictionary<string, string>();
						CardCreateOptions.SourceCard.Metadata["OwnerId"] = Id;
						CardCreateOptions.SourceCard.Metadata["AppEventId"] = Action.CmdId;

I get this error message:

“Invalid metadata: metadata must be a set of key-value pairs”

Here's what shows up in the Stripe logs:

o object: "card"
o number: "************4242"
o exp_month: "11"
o exp_year: "22"
o cvc: "***"
o name: "Bob Cohen"
o description: "Credit Card Submission"
o metadata: "System.Collections.Generic.Dictionary`2[System.String,System.String]"
o receipt_email: "robertmcohen@outlook.com"

**Comment by jaymedavis** [comment]
try new Dictionary<string, int>() -- assuming your ID is an int.

**Comment by jaymedavis** [comment]
< string, int > remove spaces - GitHub edited me

**Comment by jaymedavis** [comment]
Dictionary< string, int > ()

**Comment by jaymedavis** [comment]
Look in here https://github.com/jaymedavis/stripe.net/blob/16354c8ee882d41050d4cbb1c3910821936d8b44/src/Stripe.Tests/customers/test_data/stripe_customer_create_options.cs. This is where I create metadata and validate it.

**Comment by rmcohen** [comment]
Everything is string so Dictionary\<string,string\>() ought to work with my data.

BTW, I'm OK creating metadata with *customer* create , but not *card* create.  Do you have any tests I can look at that create metadata with the SourceCard option of CardCreateOptions?

**Comment by rmcohen** [comment]
I notice that StripeCustomerCreateOptions uses the attribute [JsonProperty("metadata")] while the SourceCard object uses the attribute [JsonProperty("source[metadata]")].

Is there any possibility that this second level of indirection is not being Jsonized correctly?

**Comment by rmcohen** [comment]
As far as I can tell, the problem is in ParameterBuilder.cs, in the ApplyNestedObjectProperties method.  I don't believe it's properly differentiating between simple and complex structures, such as Dictionaries.  It always calls the ApplyParameterToUrl method which pretty much assumes we're dealing with simple objects.

**Comment by jaymedavis** [comment]
hmm.. I'll write a test later to match your code and see if I can duplicate.

**Comment by rmcohen** [comment]
This may be a little hacky for you, but I changed ApplyNestedObjectProperties as follows:

```
private static string ApplyNestedObjectProperties(string newUrl, object nestedObject))
{
	foreach (var prop in nestedObject.GetType().GetProperties(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance)
	{
		var val = prop.GetValue(nestedObject, null);
		if (val == null) continue;

		foreach (var attr in prop.GetCustomAttributes(typeof(JsonPropertyAttribute), false).Cast<JsonPropertyAttribute>())
		{
			if (prop.PropertyType.Name.Contains("Dictionary"))
			{
				var metadata = (Dictionary<string, string>)val;

				foreach (string key in metadata.Keys)
				{
					newUrl = ApplyParameterToUrl(newUrl, string.Format("metadata[{0}]", key), metadata[key]);
				}
			}
			else
				newUrl = ApplyParameterToUrl(newUrl, attr.PropertyName, val.ToString());
		}
	}
	return newUrl;
}

```

It works.

**Comment by jaymedavis** [comment]
Metadata is killing me, lol

Thanks for all of your research!

Dictionary unfortunately wont work, as there are types (fraud_details) that use dictionary's as well - not just metadata. 

Seeing as your earlier explanation was some have `source[metadata][key]` instead of `metadata`... i was thinking this:

```
                        if (attribute.PropertyName.ToLower().Contains("metadata"))
                        {
                            var metadata = (Dictionary<string, string>)value;

                            foreach (string key in metadata.Keys)
                            {
                                newUrl = ApplyParameterToUrl(newUrl, string.Format("metadata[{0}]", key), metadata[key]);
                            }
                        }
```

could be changed instead of hardcoding the string.Format("metadata[]", key), to getting the json attribute value and using that in string.Format instead. Does that make sense? That way it would write out source[metadata] or metadata[] as needed. This is off the top of my head...

Your solution would work, if it wasn't for the other Dictionary values... 

You could try this hack too to see if this is right... 

under...

```
                        if (attribute.PropertyName.ToLower().Contains("metadata"))
                        {
                            var metadata = (Dictionary<string, string>)value;

                            foreach (string key in metadata.Keys)
                            {
                                newUrl = ApplyParameterToUrl(newUrl, string.Format("metadata[{0}]", key), metadata[key]);
                            }
                        }
```  before fraud_details, add:

```
                        if (attribute.PropertyName.ToLower().Contains("source[metadata]"))
                        {
                            var metadata = (Dictionary<string, string>)value;

                            foreach (string key in metadata.Keys)
                            {
                                newUrl = ApplyParameterToUrl(newUrl, string.Format("source[metadata[{0}]]", key), metadata[key]);
                            }
                        }
```

**Comment by jaymedavis** [comment]
I'll start whipping up a test to recreate this. Thanks again for all of your research to get to the root problem - it's never too hacky if it shows/fixes the problem. We can always clean up code, finding the problem is the hard part. :)

**Comment by jaymedavis** [comment]
Yep - looks lie your fix is this issue. It's when it gets INSIDE source card, it tries to apply simple types and doesn't notice the metadata type. I think I can abstract out the metadata into a private method up top, and call it from there and below and fix it - let you know soon.

**Comment by rmcohen** [comment]
OK.  Let me know when you want me to test it out.

**Comment by jaymedavis** [comment]
I pretty much took your fix, and just encapsulated it into a method to share with the above check for metadata- you can view here. https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Infrastructure/ParameterBuilder.cs

This is live, I just pushed 6.2.2. Hope this solves your problem! Thanks again for the help!

**Comment by rmcohen** [comment]
Looks good!

Thanks!

**Comment by jaymedavis** [comment]
Thank you! Glad it's fixed.
