### ISSUE TITLE
Order and Product Support

### ISSUE THREAD

**Issue by tgourley** [jaymedavis/stripe.net#489]
Is there any immediate plan to add Stripe Relay API functionality? (i.e. orders, SKUs, products)

Stripe Relay API
https://stripe.com/docs/relay

Order Docs
https://stripe.com/docs/api#order_object

**Comment by jaymedavis** [comment]
I was informed recently that a Stripe field engineer would be working on this in Stripe.net soon. I don't have anymore information at his time, though.

**Comment by tgourley** [comment]
Thanks.  I look forward to this functionality being added.

**Comment by jaymedavis** [comment]
I have not heard from them on the status of this, yet. If I don't hear from them soon, let me know what features (in particular) you need. Thanks!

**Comment by tgourley** [comment]
We are using Stripe to handle payments, but we do have to manage an inventory of digital resources that are purchased with those payments.  I have never actually used Relay before (always handled it in-house,) so I was curious if it would work better as a more incorporated way to let Stripe handle reporting.

Looks like there are three objects: Product, SKU, and Order.  I can imagine my use case being... 

We have 8 products and 8 SKU (no variety for us).  When a person wants to purchase an item, an order is created with that customer and selected SKU.  It is then processed.  Stripe then handles all the reporting of the individual items that are purchased, allowing us to have the most accurate reporting on our side.

Does this help or did I miss anything?

**Comment by jaymedavis** [comment]
This helps. I will pass this along. Thanks!

**Comment by daniel-cohen** [comment]
We are also looking into publishing an digital product catalog to stripe with different SKUs and creating orders. 
I think 3 service endpoints will be involved: Orders, Products, SKUs.

Would appreciate this feature as well. Thanks!

**Comment by dherbe** [comment]
Definitely as must have in Stripe.net.
Also very appreciated with the availability of this feature.
Thank you

**Comment by jaymedavis** [comment]
@daniel-cohen created PR #534 - will manage getting this implemented from there.
