### ISSUE TITLE
The type or namespace name 'Stripe' could not be found

### ISSUE THREAD

**Issue by jordanhammond** [jaymedavis/stripe.net#491]
I have the latest version of Stripe.net (5.3.0) that NuGet detects for my version of .NET on this project (4.0). When I try to reference the Stripe namespace I get the error in the title.

I have tried clean & rebuild but nothing seems to work.

Issue https://github.com/jaymedavis/stripe.net/issues/433 did not provide a solution

**Comment by jaymedavis** [comment]
Is there anyway you can upgrade to 4.5? It should be a fairly easy upgrade - that version was a long time ago, and 4.0 is not supported anymore. :(

Feel free to contact me via email if you need to get a version working and cannot upgrade to 4.5.
