### ISSUE TITLE
Prefer async Task methods over async void methods

### ISSUE THREAD

**Issue by cartickn** [jaymedavis/stripe.net#492]
Generally `async void` methods are reserved for event handlers.

For instance `public virtual void Delete` method in `StripeCardService` class is not awaitable since it returns `void` instead of a `Task`.

This may cause the following run time error. `[InvalidOperationException: An asynchronous module or handler completed while an asynchronous operation was still pending.]`

**Comment by jaymedavis** [comment]
Thanks for pointing this out. I will need to see what the delete response returns - do you have a recommendation on how to handle this?

**Comment by cartickn** [comment]
I just sent a pull request to address this. I'd just change the signature of `DeleteAsync` to return Task instead of `void` so it's awaitable.

**Comment by jaymedavis** [comment]
Gotcha. Thanks - looks like I will need to change these everywhere. How bad of a breaking change will this be for you to update in your codebase?

**Comment by cartickn** [comment]
I went through your code base and I believe this is the only Async function that returns void. I switched back to the non-Async version of this function in my client code base for now. I prefer to wait for the nuget update instead of the forked version.

**Comment by jaymedavis** [comment]
Cool, that makes things easier! I'll get it in for the next release (hopefully before Monday).

Thanks again.
