### ISSUE TITLE
Make necessary changes to support SHA-2 and TLS 1.2

### ISSUE THREAD

**Issue by davidpeden3** [jaymedavis/stripe.net#495]
https://stripe.com/blog/upgrading-tls

**Comment by jaymedavis** [comment]
Stripe pinged me about this sometime ago - it is handled in the .NET version of this library in Requestor.cs:

```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
```

I'm not sure how to handle this yet, or if it's an issue, for the PCL/Xamarin. But it's covered in .NET 4.5
