### ISSUE TITLE
Charge list options doesn't have filter for payment source

### ISSUE THREAD

**Issue by awiahmad** [jaymedavis/stripe.net#497]
As per [Stripe API reference guide](https://stripe.com/docs/api/curl#list_charges), list of all charges can be filtered by source. but i don't see that filter being provided in "StripeChargeListOptions" of Stripe.Net. Is it there but using some other way or it's just not added yet?

**Comment by jaymedavis** [comment]
I'll take a look at this - it must be fairly new. Thanks!

**Comment by awiahmad** [comment]
Thanks, and great work by the way :+1:

**Comment by drgrieve** [comment]
Hopefully this is right, I'm new to stripe but you also have other filters that are not in stripe.net

/v1/transfers?source_transaction=ch_182DHYIRktHwk0hcFY442NvA
v1/balance/history?transfer=tr_186TEAKHWD4CA9GqtRLUeZju
v1/balance/history?source=tr_186TEAKHWD4CA9GqtRLUeZju

Some of these are not well documented in stripes api documentation. Sort of stumbled across them trying to replicate features in the dashboard (for connected accounts). Most of these I've needed to do manually.
I also couldn't see a way to file uploads (for authorizing connected accounts) in stripe.net so I needed to that manually.

One more thing is getting a balance history by id doesn't return the sourced_transfers collection which I use to get the destination_payment id

**Comment by drgrieve** [comment]
For the last one I've created a pull request as it was very simple to add. I'm using this in my project now instead of calling api manually with restsharp.

**Comment by jaymedavis** [comment]
Thanks

Would you mind sharing your code for file uploads as well? There are some other examples in various branches, but I wouldn't mind seeing someone else's snippet. You can email the guts at jaymedavis @ gmail if you don't mind.

**Comment by drgrieve** [comment]
I was starting to write the code for

v1/balance/history?transfer=tr_186TEAKHWD4CA9GqtRLUeZju
v1/balance/history?source=tr_186TEAKHWD4CA9GqtRLUeZju

And I see that they are already in Stripe.Net in balanceservice.list, doh at the time I only looked at .Get I think.
