### ISSUE TITLE
Full Example Solution

### ISSUE THREAD

**Issue by enkodellc** [jaymedavis/stripe.net#499]
I did some searching and I could not find if anyone has created a full solution of the stripe.net library that includes all or most of the functionality in the readme. Sort of like a demo asp.net solution that you can download and update your keys to test run. Is there one of these somewhere and I just cannot find it?

**Comment by jaymedavis** [comment]
This is a fantastic idea, and something I hope to do in the future. The examples are fine and all, but seeing it in an app would help a lot. I'm going to leave this issue open awhile in case someone spots it and wants to open source their app.

**Comment by enkodellc** [comment]
Thanks, I am using web forms and was able to get a start on it.  The major hurdle I have have is using the stripe.js or checkout.js since there is no example of how you can use those scripts to save the customeid and then charge again. -> "For production usage, you'll almost always want to create tokens with either stripe.js or Checkout, but it can be useful to create tokens with Stripe.net for testing."  There is not much out there on how to do this in asp.net?

**Comment by enkodellc** [comment]
So far not impressed by Stripe. Authorize.net is not very fun to use but at least I can completely customize it and do dynamic charges. Using checkout.js at least seems very restrictive. I really like Stripe's Dashboard and features but their developer support for ASP.net is very lacking.

**Comment by jaymedavis** [comment]
Yes, I agree this is a big problem with Stripe, and I'd like to think about a way to solve it. Please email me jaymedavis @ gmail - I'd love your feedback and to chat about this.

**Comment by nhwilly** [comment]
A little hard to believe that there isn't anything for the MS stack, given how big C# is and Asp.net.  So far this library is filling in nicely for me.

**Comment by jaymedavis** [comment]
Closing this for now - it's a great idea, I just don't have time atm :(
