### ISSUE TITLE
There is no more support from modernhttpclient please remove the dependency

### ISSUE THREAD

**Issue by Jagadeesh-Govindaraj** [jaymedavis/stripe.net#500]
look at this issue please aware of this issue

https://github.com/mattleibow/square-bindings/issues/2

Also there is workaround merged to master but not yet release the new package don't use modernhttpcleint

https://github.com/paulcbetts/ModernHttpClient/pull/177

**Comment by jaymedavis** [comment]
What issue were you having and what platform?

I can remove this, but it will require a lot of testing on various platforms.

**Comment by jaymedavis** [comment]
and thanks.

**Comment by sunsided** [comment]
An issue: We're currently trying to use this library in a DNX/dotnet CLI ( `project.json`) based project on mono; It fails with a `TypeInitializationException` in the `Requestor` static constructor, the reason being the modernhttpclient reference.

**Comment by jaymedavis** [comment]
gotcha. I'll get rid of this. I believe it will still work on various platforms, but the intent was to get the native http library on each platform.

Is this blocking you, or do you have a fork right now? If you want to fork and start that way, I can have NuGet updated soon (on vacation next week though). The code in Requestor is basically one line you will remove I believe.

**Comment by sunsided** [comment]
I have that fixed in a private fork, so it's not super urgent. There are TLS 1.2 issues on Mono anyway, so I had to additionally open up the `Urls` in order to make the endpoints `set`able. (I'm basically doing an unsecured connection to a forward proxying `nginx` that speaks HTTPS for me.)

**Comment by jaymedavis** [comment]
There are a few issues/PRs open on ModernHttpClient, but the reviews (xamarin) look terrific. The last activity was on Jan 22nd, though. @paulcbetts - can you confirm if this library is still maintained or if you've moved on? Are the existing PRs/issues just not critical things?

**Comment by paulcbetts** [comment]
You should instead let people provide their own HttpClient factory instead of including MHC as a dependency

**Comment by jaymedavis** [comment]
The dependency was removed. If there is an issue with the httpclient, I will deal with it then. Hope this takes care of your issue @sunsided and @Jagadeesh-Govindaraj. Thanks.

**Comment by sunsided** [comment]
Thank you a lot!

**Comment by sunsided** [comment]
The nuspec file still contains modernhttpclient by the way: 
https://github.com/jaymedavis/stripe.net/blob/5aca7157f1cd24f37260af94fc520a135a88cb7f/build/Stripe.net.nuspec#L25

**Comment by jaymedavis** [comment]
Yes - sorry about that, will get it removed next release.
