### ISSUE TITLE
Deleting an Account's external_account

### ISSUE THREAD

**Issue by nomorechickenstrips** [jaymedavis/stripe.net#502]
I'm trying to delete an Account's payout method (external_account) - Debit card or Bank account.  Api docs show it should be here: 

https://stripe.com/docs/api#account_delete_card

However I don't see a way to do it through Stripe.NET.

**Comment by jaymedavis** [comment]
To delete a card on an external account, checkout the documentation for the StripeRequestOptions you can optionally pass on the card service. You want to delete the card, but do it in the managed accounts behalf using StripeRequestOptions. The same applies for any other service.

**Comment by nomorechickenstrips** [comment]
Thanks man.

________________________________

**Comment by apschlee** [comment]
@jaymedavis quick question about this.

The first field for the BankAccountService.Delete() function says it's supposed to be the customerId but if you are removing an external account from a Connect (managed) account what would you pass in? Would the code just looking something like:

`public void RemoveBankAccount(StripeBankAccount acct, User userInfo)
{
     BankAccountService BAS = new BankAccountService();
     StripeDelete result = BAS.Delete(userInfo.stripeAccountId, acct.Id, new StripeRequestOptions () { 
         StripeConnectAccountId = userInfo.stripeAccountId
     });
}`

**Comment by jaymedavis** [comment]
If you are issuing the request on behalf of the `userInfo.stripeAccountId`, then both of the parameters passed to Delete (customer and account), should be a customer and account id from `userInfo.stripeAccountId`

**Comment by apschlee** [comment]
Awesome, thank you Jayme!

**Comment by jaymedavis** [comment]
You're welcome :)

**Comment by NDN84** [comment]
Hey, sorry i don't understand how we can to delete external bank account information without customer Id, when we have only accountId and bank account Id. (https://stripe.com/docs/api?lang=php#account_delete_bank_account). Thanks!
