### ISSUE TITLE
Adding multiple cards for a customer stripe.net

### ISSUE THREAD

**Issue by jerrylouis** [jaymedavis/stripe.net#504]
Is there a way I can add multiple cards for a customer using stripe.net, I know that we need to retrieve the customer and add a new card using the source object as shown here(https://stripe.com/docs/api#create_card). But with the stripe.net I cant seem to figure how to do this, any pointers will be great help.

**Comment by nhwilly** [comment]
OK, me too on this one.  I can add a bank account, but each time I try to update the customer with a new card token, it just replaces the old one.  I agree that the Stripe docs look like you can send a collection of them, but I don't see how that happens with Stripe.Net.

**Comment by nhwilly** [comment]
I'm not really all that good at this, but it looks like the CustomerUpdateOptions would have to be supporting a list of sources.  I can't seem to find that anywhere.  I can't figure a workaround, so for now, I'll assume that Stripe.Net limits us to one card per customer.

**Comment by jaymedavis** [comment]
Yeah, updating the default source will replace it. That is Stripe's logic. There is nothing in Stripe.net that it does on it's own - it's all pass through. It would be best to contact support and figure out the proper way to add additional sources just via curl requests or something - then I can use that to build something.

**Comment by nhwilly** [comment]
My original take on this (last night) was that it was going to be an edge case anyway.  How many customers would want to store multiple cards on a single merchant?  Well, this morning I discovered shared customers and that's what we've been after all along.  Now multiple cards on a single customer is a much more likely scenario.  

I'll ask for an example from Stripe support and get back to you.

**Comment by jaymedavis** [comment]
I will add a note to go through this card with Stripe after we gather more information to determine the best solution. Thank you again for gathering data.

**Comment by nhwilly** [comment]
Ahem...

My reading [the documentation ](https://stripe.com/docs/api#create_card)would be awesome for everyone else....

I was approaching this thinking about adding a card to the customer object and then saving the customer, somehow, or just adding it directly to the customer.  Their stuff doesn't work like that when you want to add an additional card.

They want you to create the card in it's own right and reference the customer Id when you do it, and then they make the connection internally.  I just did this with the existing StripeCardService and it worked great.

You can close this.  Sorry to waste your time.

p.s. You should have a "Donate" or "Send Beer" button somewhere here so boneheads like me can apologize effectively.  I'd do it.  Seriously.

**Comment by nhwilly** [comment]
Oh, one more thing.  You can only have one bank account on a customer.  Per Stripe support.

**Comment by jaymedavis** [comment]
hahaha. My PayPal is jaymedavis@gmail.com, but that's really not necessary: you helped @jerrylouis figure out what to do, thus helping me close this issue. I sort of knew that would work in the back of my head, but I was wondering if here was another way - and you cleared that up too. Not a bonehead in the slightest - very helpful and I appreciate it! Hope this helps you too @jerrylouis!

**Comment by jaymedavis** [comment]
also - thanks for the one bank account, I'm actually reopening this issue to get that in my documentation. That will help.

**Comment by TheSharpieOne** [comment]
Adding to this, Stripe will let you add the same card (same card details) to the same customer over and over again. I halfway expected stripe to throw an error about adding a card that already exists with the user.
![image](https://cloud.githubusercontent.com/assets/664714/15591367/b916da12-236a-11e6-8598-95f98c1692c6.png)

Another "gotcha"... subscriptions: multiple cards do nothing, only the default source is used. Supplying a new card when creating a subscription will replace the existing default (replacing the card marked as defaultSource, not replacing the actual source).

**Comment by jaymedavis** [comment]
Thanks @TheSharpieOne. This is good to know. The same card details is a bit.. odd. :)

**Comment by nhwilly** [comment]
I think I saw somewhere that they don't store the CVV, just a bit to indicate it passed the bank check.  If that's the case, maybe they can't guarantee a duplicate check if the same card is entered twice.  The second one could have all the same detail except the CVV, which they wouldn't know. It would look like a duplicate when it wouldn't be.

Or, I could be high.

**Comment by jaymedavis** [comment]
clsoing, thanks everyone for your contributions - this is great documentation to have archived.
