### ISSUE TITLE
Allowing StripeTokenCreateOptions to accept CardId in addition to Card

### ISSUE THREAD

**Issue by nhwilly** [jaymedavis/stripe.net#510]
On shared accounts in Stripe Connect, the platform account stores the customer and card information, instead of each individual connected account containing their own customers.  This allows a customer to enter their card information one time for all connected accounts that use the app.  Very handy.

Charges can be made on behalf of a connected account, but it requires creating a token that has the **card Id**, the platform customer Id and the connected account Id.  

StripeTokenCreateOptions doesn't support this as it only allows for **card**.  

The relevant documentation is [here](https://stripe.com/docs/connect/shared-customers).

I've tried to download the repo and make changes locally - just to experiment - but this is a DNX project and I've descended into some hopeless conflicts and can't get anything to work at the moment.  :(

This actually lends more importance to the ability to store multiple cards on a single customer.

**Comment by nhwilly** [comment]
Well I tried to download the package, compile it and update my NuGet packages, but it all went to hell after that.  Clearly don't know what I'm doing and with the rapid changes in Asp.Net, I'm on the struggle bus.

So I restored everything, and attempted to just directly write the code for the one call with an HttpClient, just so I could see how it was going to work.  I just keep getting 400 errors and it's not clear to me why.  So I'm punting on that.

Now that the multiple cards thing has been sorted, this is a pretty important architectural decision for our project.  I'll try not to flood your repository with questions.

**Comment by nhwilly** [comment]
OK, I downloaded the entire project, make one small change to it and it's working great.  I have no idea how to contribute back up to you.  I don't want to make a mess of this repo with  my dabbling around. :)

**Comment by nhwilly** [comment]
Actually, this is the only change I made to StripeTokenCreateOptions:
`        [JsonProperty("card")]`
`public string CardId { get; set; }`

**Comment by jaymedavis** [comment]
Easy enough. I'll take care of getting this written along with a test. Thanks!

**Comment by nhwilly** [comment]
Awesome.  My thanks is in the mail. :)

**Comment by nhwilly** [comment]
FWI, events fired for a shared customer transaction on behalf of a connected account show the customer as null in the payload.  Weird.

**Comment by nhwilly** [comment]
I have an email into Stripe support on the null customer business.

**Comment by jaymedavis** [comment]
If you are using webhooks, have them change the version of your API to match the version in StripeConfiguration.cs. And yes! Thank you much!

**Comment by nhwilly** [comment]
Thought that might have been the cause of the null customer Id's, but it's not, the versions on their end and in the configuration class match at 2015-09-08.

**Comment by jaymedavis** [comment]
is customer id populated? you might have to set ExpandCustomer to true on the service itself if it's an expandable property (search readme for expandable property)

**Comment by jaymedavis** [comment]
oh you said id's - nevermind, doh'

**Comment by jaymedavis** [comment]
and it's a Webhook not a service call, sheez I'm tired. lol

**Comment by jwolinsky** [comment]
StripeTokenCreateOptions should also support Bank Account ID (in addition to Card ID) per the Stripe shared customers documentation (https://stripe.com/docs/connect/shared-customers)

> Make a create token API request, passing in the customer ID (and optionally, the card or bank account ID)

This allows a platform account to charge a specific source (indicated by the Card or Bank Account ID) of a platform customer on behalf of a connected account. Without the Card ID or Bank Account ID as part of the StripeTokenCreateOptions, Stripe will charge the platform customer's default payment source.

**Comment by jaymedavis** [comment]
Thanks @jwolinsky.

**Comment by dcraigen** [comment]
Just trying to implement this in my app, cannot send a previously saved cardid for a customer in a token request,  any idea if and when this might get fixed?

Great package by the way!

**Comment by qBeto** [comment]
First of all, this is a GREAT package! I'm building a marketplace site with multiple vendors and without this I would be lost. Regarding this issue, I was able to download the master branch, perform the update that @nhwilly made (adding the CardID property to StripeTokenCreateOptions) and it worked like a charm. Thanks @nhwilly ! One thing though is that the build from the master branch seems to be slightly different from the downloaded NuGet package (v7.0.3). Example: the customer object does not have a SourceList attribute but rather a Sources attribute). Could anyone point me in the right direction?

**Comment by jaymedavis** [comment]
Well - it has a property of type SourceList, named Sources. That's master and 7.0.3

**Comment by jwolinsky** [comment]
@jaymedavis Thanks for adding TokenId to the StripeCreditCardOptions. Any plans to add TokenId to the BankAccountOptions as well?

**Comment by jaymedavis** [comment]
```SourceToken``` is on BankAccountCreateOptions. 👍

**Comment by jwolinsky** [comment]
@jaymedavis `BankAccountCreateOptions` is for creating a bank account. What we're talking about here is charging a platform customer on behalf of a connected account. In order to charge a platform customer on behalf of a connected account we need to create a shared token using `StripeTokenCreateOptions` and add the `CustomerId` and optionally the **Card Id** or **Bank Account Id** to be charged (without either one, Stripe will charge the customer's default payment source, see https://stripe.com/docs/connect/shared-customers#making-tokens). Currently, `StripeTokenCreateOptions` allows `Card.TokenId` but it does not allow `BankAccount.TokenId`. We need a `TokenId` parameter in the `BankAccountOptions` similar to the `TokenId` parameter in `StripeCreditCardOptions`.
