### ISSUE TITLE
.Net Core RC2 Bug

### ISSUE THREAD

**Issue by XcoderTeam** [jaymedavis/stripe.net#511]
Hi @jaymedavis 

I using Stripe.Net on asp.net core rc1 with no issue, when performing upgrade from rc1 to rc2 I have an issue in my application. It detect that the System.Net.Http is using old version=1.5.0.0

My code
`var content = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("api_user",""),
                new KeyValuePair<string, string>("api_key", ""),
                new KeyValuePair<string, string>("from", string.IsNullOrEmpty(from) ? "" : from),
                new KeyValuePair<string, string>("to", to),
                new KeyValuePair<string, string>("subject", subject),
                new KeyValuePair<string, string>("html", html),
            });
            dynamic response = await RestHelper.PostAsFormAsync(_url, _mailsend, content);
            var json = JsonConvert.DeserializeObject<dynamic>(response);
            return json.message == "success" ? true : false;`

Error

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'.	Job.Services..NETCoreApp,Version=v1.0	C:\+Beta\Job\src\Job.Services\Email\SendGridProviderService.cs	41	Active
`
When I remove the dependency of stripe.net "FormUrlEncodedContent" it work, so when you plan to support asp.net core.

**Comment by jaymedavis** [comment]
I have an RC2 .net core project I am using Stripe.net on as well. I haven't came to the point of getting this going yet, but I will look into it. .net core is already supported. so this might be a bug or related to my recent change of removing modernhttpclient. Are you in the latest version?

**Comment by jaymedavis** [comment]
This doesn't look like stripe.net code - it looks like you are doing everything manually?

**Comment by jaymedavis** [comment]
What is on SendGridProviderService line 41?

**Comment by jaymedavis** [comment]
I might just need to upgrade my dependencies, perhaps they are outdated. I can try to squeeze this in soon if you have time to test.

**Comment by XcoderTeam** [comment]
`var content = new FormUrlEncodedContent(new[]`

I realized that the FormUrlEncodedContent is point to old System.Net.Http

**Comment by jaymedavis** [comment]
I need to figure out which versions the portable assembly is using for the NuGet packages. If you want to try to see if this fixes it, download the stripe.net code, update all of the NuGet packages, compile it, and see if the assembly works.

**Comment by jaymedavis** [comment]
Just make sure you grab the assembly from the portable project bin and not the .net bin directory. There's nothing else you need to do, no special build steps. Just download, update NuGet libs in the portable project only, compile, try dll.

**Comment by jaymedavis** [comment]
Closing - feel free to comment or re-open if you are still having this issue.
