### ISSUE TITLE
StripeSubscriptionCreateOptions should accept SourceToken

### ISSUE THREAD

**Issue by TheSharpieOne** [jaymedavis/stripe.net#513]
`StripeSubscriptionCreateOptions` should accept `SourceToken` [string] in addition to [to be used instead of] the `Card` it currently accepts.

https://stripe.com/docs/api/node#create_subscription-source

> The source can either be a token, like the ones returned by our Stripe.js, or a object containing a user's credit card details...

**Comment by jaymedavis** [comment]
Thanks, this needs to be resolved. Internally, the code uses StripeCreditCardOptions as well, while everything else has been updated to use SourceCard/SourceBankAccount in the _sources folder. That will probably need to change, I would like to obsolete StripeCreditCardOptions to use the same source object everywhere. This is more for my notes and not necessarily related to your issue.

I can get an additional token on subscriptions. What I need to confirm, as I believe I've heard this before, subscriptions can actually take a card, a token, or a customer id and an existing card id on that customer... 

I will confirm with Stripe if this is possible, if so it will be similar to charges:

```csharp
        [JsonProperty("source")]
        public string SourceTokenOrExistingSourceId { get; set; }

        [JsonProperty("source")]
        public SourceCard SourceCard { get; set; }
```

**Comment by rlightner** [comment]
Any traction on this one?
