### ISSUE TITLE
SubscriptionService Methods - without CustomerId

### ISSUE THREAD

**Issue by TheSharpieOne** [jaymedavis/stripe.net#514]
According to the Stripe API documentation, to do pretty much anything with existing subscriptions, you only need the SubscriptionId. (See https://stripe.com/docs/api/curl#retrieve_subscription) Yet this library requries the customerId.

The method seems to be a leftover from when subscriptions were part of the customer and the way they were retrieved was from the the customer endpoints (https://github.com/jaymedavis/stripe.net/blob/f467706bd0f61c359e4bff09d98cc38402edbda9/src/Stripe/Services/Customers/StripeCustomerService.cs#L63)

The CustomerId can probably be removed from the subscription methods which do not use it. I'd suggest adding an overload which doesn't include the customerId and deprecating the ones which include it but do not need/use it.

**Comment by jaymedavis** [comment]
Closing this - will manage work from #515 - thanks!
