### ISSUE TITLE
Get subcription_id

### ISSUE THREAD

**Issue by takwirira** [jaymedavis/stripe.net#518]
Hi, when I create a new customer with a card and subscription plan how do I return the subscription id that is automatically created by Stripe?

**Comment by jaymedavis** [comment]
Good question, I'm not sure. Check with Stripe to see if this is possible without another query, and post back the response. However their process works should help us figure it out.

**Comment by takwirira** [comment]
Thanks for the quick response. I will send them an email. In the meantime, I noticed create customer returns StripeSubscriptionList with the subscription_id inside it. Do you know how I could get that? Perhaps using IEnumerable?
![subscriptions](https://cloud.githubusercontent.com/assets/16650461/15676394/eafcbcbe-273d-11e6-9499-b5efc0c8ede4.png)

**Comment by jaymedavis** [comment]
Oh sorry, I read this as new 'card with customer' - it's the property StripeSubscriptionList on the customer, it's a list. If this doesn't take care of you, reopen.
