### ISSUE TITLE
proration_date missing from StripeSubscriptionUpdateOptions

### ISSUE THREAD

**Issue by mixtmeta** [jaymedavis/stripe.net#524]
Stripe allows for proration based on a specified date. This option does not appear to be available in the StripeSubscriptionUpdateOptions. Would be great if it was added.

**Comment by jaymedavis** [comment]
Thanks for reporting this.

**Comment by jaymedavis** [comment]
will manage this from #526 as the work is done there - thanks

**Comment by jaymedavis** [comment]
sorry about the annoyances with labels here - I'm using waffle.io/jaymedavis/stripe.net and accidentally grabbed the wrong card.
