### ISSUE TITLE
The error of partially refunding

### ISSUE THREAD

**Issue by ufo818** [jaymedavis/stripe.net#529]
When I was going to partially refund a payment, I got this error "Invalid reason: must be one of duplicate, fraudulent, or requested_by_customer". 

My code is as below.
                StripeConfiguration.SetApiKey(ConfigurationManager.AppSettings["Stripe_API_KEY"]);
                var refundcharge = new StripeRefundCreateOptions();
                refundcharge.Amount = Convert.ToInt32(returnAmount * 100);
                refundcharge.Reason = refundReason;
                StripeRefundService stripeRefundService = new StripeRefundService();
                StripeRefund stripeRefund = stripeRefundService.Create(orderNum, refundcharge);

I have no idea where is wrong. If anyone know how to fix this problem, please let me know.
Thanks in advance.

**Comment by dannyb2100** [comment]
refundReason must be a string containing ether must be one of duplicate, fraudulent, or requested_by_customer

**Comment by ufo818** [comment]
Thank you, dannyb2100. 

I updated my code as below, and it works now.

                StripeConfiguration.SetApiKey(ConfigurationManager.AppSettings["Stripe_API_KEY"]);
                var refundcharge = new StripeRefundCreateOptions();
                refundcharge.Amount = Convert.ToInt32(returnAmount * 100);
                refundcharge.Reason = StripeRefundReasons.RequestedByCustomer;
                refundcharge.Metadata = new Dictionary<string, string>() { { "customer_reason", refundReason } };
                StripeRefundService stripeRefundService = new StripeRefundService();
                StripeRefund stripeRefund = stripeRefundService.Create(orderNum, refundcharge);

**Comment by dannyb2100** [comment]
You're welcome ufo818, happy coding! :)

**Comment by jaymedavis** [comment]
I will get this updated so it's a type in the system... e.h... RefundReasons.Duplicate. (leaving open for this reason)

Thanks for the help @dannyb2100!

**Comment by jaymedavis** [comment]
Whoops, already there.
