### ISSUE TITLE
StripeSubscription does not show created date

### ISSUE THREAD

**Issue by TravyDale** [jaymedavis/stripe.net#533]
I am attempting to use the StripeSubscription object and show when the subscription was created. I see the Stripe API has a 'created' object but it isn't being shown in the Stripe.net object. Is there a different place I can access this value?

**Comment by jaymedavis** [comment]
Looks like it needs a JsonProperty "created" here probably: https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Entities/StripeSubscription.cs

**Comment by TravyDale** [comment]
Is that something you think you will add to your library eventually?

**Comment by jaymedavis** [comment]
Of course, or I would have closed this. :)

**Comment by TravyDale** [comment]
Ok thanks.
