### ISSUE TITLE
Shouldn't StripeCustomerCreateOptions.Source be deprecated

### ISSUE THREAD

**Issue by niemyjski** [jaymedavis/stripe.net#537]
```csharp
// obsolete: Source = new StripeSourceOptions() { TokenId = tokenId }
 SourceToken = tokenId
```

**Comment by jaymedavis** [comment]
marked obsolete, going away in 7.0

**Comment by OllieJones** [comment]
Thanks Jayme. Toi be specific, the Source property of the StripeCustomerUpdateOptions class is obsolete. Instead, there's replacement property SourceToken. It takes a string, which is the value of the token.

One less level of intdirection. Hooray. Thanks again.
