### ISSUE TITLE
Destination is missing from StripeTransferCreateOptions

### ISSUE THREAD

**Issue by asaturg** [jaymedavis/stripe.net#538]
Hi 

I'm trying to transfer money to Stripe Connect account but getting "Must provide destination or recipient". I've take a look at StripeTransferCreateOptions and there is no destination property.

**Comment by ryn0** [comment]
I am seeing this as well. It appears the JSON being sent is not sending it. Stripe seems to be in a transition away from recipients, here is the current API for transfers: https://stripe.com/docs/api#create_transfer

**Comment by jaymedavis** [comment]
Yes, don't use recipients. Use the second parameter of that service call to pass a connect account ID

https://github.com/jaymedavis/stripe.net#striperequestoptions

**Comment by asaturg** [comment]
It's not working

here is my code that will transfer money from connected account to it's
bank account . bellow code is not working

        public static void Transfer(string accountId, decimal amount)

        {

            Error err = new Error();

            try

            {

                StripeConfiguration.SetApiKey(stripeApiKey);


                var stripeAccountService = new StripeAccountService();


                StripeAccount account = stripeAccountService.Get(accountId);

                StripeBankAccount bankAccount =
account.ExternalBankAccounts.First();


                StripeTransferCreateOptions transfer = new
StripeTransferCreateOptions()

                {

                    Amount = (int)(amount * 100),

                    Currency = "usd",

                    Description = "Cablr Partner Payment Statement",

                    StatementDescriptor = "Cablr Transfer",

                    BankAccountId = bankAccount.Id,



                };


                StripeTransferService transferService = new
StripeTransferService();


                StripeTransfer result = transferService.Create(transfer, new
StripeRequestOptions { ApiKey = stripeApiKey , StripeConnectAccountId =
accountId});

            }

            catch (StripeException ex)

            {

                err.LogError("Bank Transfer: " + ex.Message);

            }


        }


*Regards,*
*Asatur Galstyan*
*CEO/Founder at* *Realizeit, LLC* <http://realizeit.co>
