### ISSUE TITLE
When passing '0' quantity when creating a subscription, it defaults to '1'

### ISSUE THREAD

**Issue by shima20** [jaymedavis/stripe.net#539]
I need to create 2 subscriptions per customer.  The first subscription is the main subscription and the second is a subscription for additional users that get added to the system.  When I create the second subscription, I'm setting the quantity to 0, however, it keeps defaulting to 1.

**Comment by jaymedavis** [comment]
Are you using the same service? Can you share your code in a Gist?

**Comment by jaymedavis** [comment]
Also, this may be logic on Stripe's end that I'm unaware of - run it by their support as well. Please leave an update for other users benefit.

**Comment by shima20** [comment]
Here is the code that I'm using.  I talked to the Stripe folks on that chat and they said it should be ok.

```
var service = new StripeSubscriptionService(_apiKey);
            return service.Create(subscription.CustomerId, subscription.StripePlan.Id, new StripeSubscriptionCreateOptions { PlanId = subscription.StripePlan.Id, Quantity = subscription.Quantity });
```

**Comment by jaymedavis** [comment]
This code only shows creating one, and it doesn't show the options object used for that. Can you post all of your code in a gist file (creating both subscriptions and their options objects) and link to that? Also, have you debugged to make sure a 2 isn't getting passed?

**Comment by shima20** [comment]
I'm actually hardcoding the Quantity value to 0.

https://gist.github.com/shima20/25cae29b67c8d4f8b595decd5519d65f

**Comment by jaymedavis** [comment]
If you are adding a subscription to a customer, which it looks like you are doing, it's impossible to set it to 0. It's happening for that customer. I don't understand your dataContext, but you might want to run this by Stripe again, I don't believe you can create a subscription like this with 0 for a quantity.

**Comment by shima20** [comment]
When editing the subscription through the Stripe UI, it seems to let you set the Quantity to 0.

![image](https://cloud.githubusercontent.com/assets/9735056/16994279/8ae6a5ac-4e5b-11e6-863c-3ae5bee7540d.png)

**Comment by jaymedavis** [comment]
I think it's because you are passing a customer id, so it's putting them in the subscription? Did you figure anything else out with this?
