### ISSUE TITLE
StripeAccountService.Get breaking change when upgrading from version 5.2

### ISSUE THREAD

**Issue by desbrowne** [jaymedavis/stripe.net#540]
Thanks for all your great work Jayme. We'd like to upgrade to the latest release but found StripeAccountService.Get has a breaking change (side note: is this meant to happen in a minor revision number?)

In version 5.2 we currently have
var account = accountService.Get();

But 5.3 requires an accountId, e.g.
var account = accountService.Get("acct_...");

I looked through the issues but couldn't find this change addressed, so I'd appreciate if you can point me to the recommended way to upgrade this? We use this for quite a number or customers with connected accounts.

**Comment by jaymedavis** [comment]
Yes, sometimes there are small breaking changes between these revisions. Because I don't do beta releases, this would be Stripe.net 25.5 if I stuck with that convention. :)

With that said, I am trying to get better about this and marking things as deprecated, like I did with StripeSourceOptions. 

https://github.com/jaymedavis/stripe.net/releases - be sure to follow along here, I detail every release.

**Comment by desbrowne** [comment]
Thanks @jaymedavis, I took a look at /releases again. While 5.3 mentions "Managed Accounts support is finally here". It doesn't detail what the changes are or how to upgrade from the previous API.

With regards to versioning & 25.5, no problem. I'm sure this is why Stripe use date versioning instead?

**Comment by jaymedavis** [comment]
I would check out the readme on how to use it now, that will probably clear it up. If that doesn't help, view the commit the release is attached too - then look at the commit before it, that will show you the code from both versions.

From looking at what you stated before Get() probably became List(), as Get() in the library is typically used for getting one account only.

**Comment by jaymedavis** [comment]
Looking at this more, the Stripe docs used to document using `/v1/account` as the endpoint. That changed when they introduced `/v1/accounts` (as it is today) and the previous version isn't documented anymore. I looked at 5.2, so if you want the same functionality you had, you need to get your account id (starting with acct_) and just pass that as a string to the existing Get(). That will give you the same thing you had before. Hope this helps.

**Comment by jaymedavis** [comment]
My failure was on documenting this upgrade, sorry about that.
