### ISSUE TITLE
Getting Error when try to Get Stirpe Plan Details using Its Plan ID

### ISSUE THREAD

**Issue by MudassirAfzal** [jaymedavis/stripe.net#542]
I have a plan in Stripe with ID say "5 Custom Blog Posts /mo (500 Words) stripe monthly subscription".
When i try to get this plan's details using c# application through its PlanID, i get an error which says
"Unrecognized request URL (GET: /v1/plans/5%20Custom%20Blog%20Posts%20/mo%20(500%20Words)%20stripe%20monthly%20subscription). Please see https://stripe.com/docs or we can help at https://support.stripe.com/."
The error occurs because the planId contains a slash ( /  ).
Please Help.
Thank you

**Comment by jaymedavis** [comment]
I would use this as your display name and use another ID. [Lots of web services struggle with the slash](http://stackoverflow.com/questions/1957115/is-a-slash-equivalent-to-an-encoded-slash-2f-in-the-path-portion-of-a) ... Or try %2f maybe.
