### ISSUE TITLE
Migrate the project to new format

### ISSUE THREAD

**Issue by jaymedavis** [jaymedavis/stripe.net#544]
This is a continuation from the conversation in #541 about migrating the project to a new format:

I'm all for moving the project into the new format. I would actually prefer to have one project instead of two.

Why .NET Platform Standard over .NET Standard Library?

'The .NET Platform Standard concept has been replaced by the .NET Standard Library. Check out the .NET Standard Library topic in the .NET Documentation. It provides a good first view into .NET Standard Library.'

**Comment by jaymedavis** [comment]
duped, going to manage on PR

**Comment by jaymedavis** [comment]
going to continue on PR

**Comment by flagbug** [comment]
Nah, I wanted to do this migration in a separate pull request anyway, so let's continue the discussion here!

**Comment by makerofthings7** [comment]
Moving to the new format, I presume, will allow this code to run on an MVC server running on OSX

**Comment by jaymedavis** [comment]
I would love for this to be the case.

**Comment by jaymedavis** [comment]
And I assume so - I have ran it with another project on Mac using vs code and dotnet as a command line client. :)

**Comment by flagbug** [comment]
The new format has nothing to do with where it can run - It's already a PCL that runs pretty much anywhere except for Silverlight

**Comment by jaymedavis** [comment]
I was referring to it running as a project reference and not a NuGet package (compiling). The compiled assembly will run there now @makerofthings7, and that will not change. The main worry I have is supporting TLS 1.2, as that will be something Stripe forces at the end of the year.

**Comment by flagbug** [comment]
>The main worry I have is supporting TLS 1.2, as that will be something Stripe forces at the end of the year.

Everything >= .NET 4.5 should support TLS 1.2, so that shouldn't be a problem, right?

**Comment by nhwilly** [comment]
OK, so I'm starting a greenfield project.  What would you recommend?  I haven't done anything yet, but I don't want to write, then rewrite a bunch of stuff.  it seems various pieces that I plan on using (Xamarin) seem to be moving toward the new approach, too.

TIA

**Comment by jaymedavis** [comment]
So according to [Xamarin](https://developer.xamarin.com/guides/cross-platform/transport-layer-security/) ...

>Currently Mono only supports TLS 1.0; TLS 1.2 support is forthcoming but is still a work in progress. It is possible for Xamarin mobile applications incorporate TLS 1.2 by using the System.Net.HttpClient API and specifying a platform-specific implementation of System.Net.HttpMessageHandler that will leverage the native API's for TLS 1.2. For this reason HttpClient should be the preferred API for Xamarin applications that require secure network communications.

Stripe.net uses HttpClient, but it does not implement a platform specific implementation of HttpMessageHandler. I used to have a dependency on [ModernHttpClient](https://github.com/paulcbetts/ModernHttpClient), but it was not working for many users. I tried contacting the author about it, but my question wasn't answered about the troubles we were having. It's a fantastically easy library to use, I'm just not sure if he's working on it anymore (Jan 22nd last commit).

This does lead me to believe though, that if the native HttpClient doesn't support this in time, there is work that can be done to Stripe.net to make it work - so that's good.

**Comment by flagbug** [comment]
@jaymedavis So I know a few things about `ModernHttpClient`: The library is used by the app developer, not the library developer. What Stripe.NET could expose is an injection point for a custom `HttpClient`, or a custom `HttpMessageHandler` that Stripe.NET then uses

**Comment by jaymedavis** [comment]
This is similar to what the author recommended from that library :)

I think that could be done, but if I can do it for them, I'd rather zero configuration like Stripe.net is today. Is there any reason the library couldn't have a handler that is generic? What would be a use case for someone providing something other than a vanilla handler?

**Comment by jaymedavis** [comment]
For clarification - I mean a handler per platform.

**Comment by makerofthings7** [comment]
Some of this shouldn't be needed anymore. The compiler seems to have support for this
https://developer.xamarin.com/guides/cross-platform/macios/http-stack/






On Wed, Aug 17, 2016 at 6:19 PM -0400, "Jayme Davis" <notifications@github.com> wrote:












For clarification - I mean a handler per platform.

**Comment by jaymedavis** [comment]
closing, will implement with #581 :)
