### ISSUE TITLE
StripeDeleted object for Stripe API calls that return a json object with Id and Deleted properties.

### ISSUE THREAD

**Issue by KirkGamesLLC** [jaymedavis/stripe.net#545]
Some Stripe API calls return a 'deleted' object with an Id string and deleted Boolean property.

`public class StripeDeleted
    {
        [JsonProperty("id")]
        public string Id { get; set; }
        [JsonProperty("deleted")]
        public bool Deleted { get; set; }
    `}``

**Comment by jaymedavis** [comment]
Id is already covered in the base class. Which endpoints are you referring to that are missing the Deleted property?

**Comment by KirkGamesLLC** [comment]
Look at this api documentation page for deleting a customer. The API returns a simple object with Id and Deleted parameters as confirmation. https://stripe.com/docs/api#delete_customer

`{
  "deleted": true,
  "id": "cus_8rblablablalblalbal"
}`

**Comment by jaymedavis** [comment]
Both of these properties are on StripeCustomer.

**Comment by jaymedavis** [comment]
Oh I see - Delete returns nothing now is what you mean

**Comment by jaymedavis** [comment]
Sorry I missed the point - I'll leave this open until it can be resolved.

**Comment by jaymedavis** [comment]
I will be sure this is accounted for in #574 - closing this.
