### ISSUE TITLE
Add StripeDisputeService support

### ISSUE THREAD

**Issue by KirkGamesLLC** [jaymedavis/stripe.net#546]
I built this method on my StripeHelpers class and realized this service was not supported in Stripe.Net.

public StripeDispute DisputeRetrieve( string disputeId, StripeRequestOptions requestOptions = null)
{
          StripeDisputeService service = null;
          StripeDispute target = null;

```
        try
        {
            service = new StripeDisputeService(apiKey);
            target = service.Get( disputeId, requestOptions);
        }
        catch (Exception error)
        {
            throw error;
        }
        finally
        {
            service = null;
        }

        return target;
```

}

**Comment by jaymedavis** [comment]
Yes, this service is incomplete and needs to be updated. Also, I would catch StripeException in your try/catch so you will get information from Stripe on why the request failed.

**Comment by KirkGamesLLC** [comment]
I catch the StripeException specifically in the calling method.
