### ISSUE TITLE
StripeChargeCreateOptions

### ISSUE THREAD

**Issue by manojdivakaran** [jaymedavis/stripe.net#548]
Hi Earlier we could assign card token (which was created earlier) to this Class
using StripeChargeCreateOptions.Card = token
This would assign the already created card token for a user. How can this be done in the version 5.3.0?
Also the latest version does not work in 4.0 framework. Can you please let me know how to achieve the same?

**Comment by jaymedavis** [comment]
4.0 support was dropped, can you upgrade to 4.5, it's relatively small changes and a lot better security.

If you look at the code for this class, you will see the property for a token, or the property for a card - use one or the other - https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Services/Charges/StripeChargeCreateOptions.cs

**Comment by manojdivakaran** [comment]
I am not finding any property for Card or Token in this. I could find a source option but this allows only token (which is the one time token) and not Card Token
Also I am now trying to use 5.1.3 which does not have dependency of 4.5 framework but that also is not working. I am upgrading because of this issue:-https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2 
Therefore I cannot think of Upgrading my project to 4.5 framework at this point of time.

**Comment by manojdivakaran** [comment]
Hi,
I am not finding any property for Card or Token in this. I could find a source option but this allows only token (which is the one time token) and not Card Token
Also I am now trying to use 5.1.3 which does not have dependency of 4.5 framework but that also is not working. I am upgrading because of this issue:-https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2
Therefore I cannot think of Upgrading my project to 4.5 framework at this point of time.

[http://www.aptushealth.com/images/logo/aptushealth-rgb-signature.png]<http://aptushealth.com/>

Manoj Divakaran
Senior Web Developer
w:+912261509318 c: +918652313523
AptusHealth.com

Confidentiality Notice:
This email message, including any attachments, is for the sole use of the intended recipients and may contain confidential and privileged information. Any unauthorized review, use, disclosure, or distribution is prohibited. If you are not the intended recipient, please contact Aptus Health by reply email and destroy all copies of the original message.
