### ISSUE TITLE
Creating a connected account with credit card details

### ISSUE THREAD

**Issue by doronavin** [jaymedavis/stripe.net#550]
Hi, 
I'm trying to create/update an account with a debit card,
but getting the following error:
Requests made on behalf of a connected account must use card tokens from Stripe.js, but card details were directly provided.

I'm using a code similar to the code in the tests:
https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.Tests/account/when_creating_a_managed_account_with_a_card.cs

but cannot pass the details of the card to the server, and I can't find an api with a token to replace the card's details.

Can you help me, please?
Thanks

**Comment by jaymedavis** [comment]
It's possible Stripe turned this off and you need to use Stripe.js. You are not supposed to pass a credit card through your server, that is against PCI compliance. Stripe.js allows you to use javascript to get a credit card, and then you can pass a token to your server (not credit card details). 

I am building a product now called Checkout.net, that will handle all of this for you (it will not be free, and I don't know the cost at this time, but I'm thinking $10 a month). However, you can easily build this yourself.

In the meantime, if your server is PCI Compliant, you can use the StripeToken service to get a token.
