### ISSUE TITLE
Version 5.3.0 of Stripe.net is not listed to have 4.5 framework dependency but does not work

### ISSUE THREAD

**Issue by manojdivakaran** [jaymedavis/stripe.net#551]
Hi,
 I am trying to use 5.1.2/5.1.3/5.2.0/5.3.0 version of Stripe.net which as per https://www.nuget.org/packages/Stripe.net/ does not have dependency on 4.5 framework but still when I use them in the solution it gives the following error:-
Warning	1	The primary reference "Stripe.net" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0"
We will not be able to upgrade to 4.0 as the site is in maintenance phase and upgrading will be a lot of work which may not be approved by the Management

**Comment by jaymedavis** [comment]
There was recently a closed issue where I helped someone else find the latest 4.0 release. Look for that and that will help you find which version to use.
