### ISSUE TITLE
Add Transfer Fee to StripeTransfer

### ISSUE THREAD

**Issue by FlashDeath** [jaymedavis/stripe.net#552]
It seems like there is quite a bit missing from Transfer according to the api.   I am particularly in need of the application fee.  Now that recipients have been depreciated it also seems to be missing the destination parameter.

**Comment by jaymedavis** [comment]
Use the StripeRequestOptions parameter for connected accounts, not destination.

**Comment by FlashDeath** [comment]
Ah yes I see that now, but still not sure how add in the application fee.

**Comment by noahtk** [comment]
I'd also like to know how I would add a lump sum fee to a transfer.  How do I go about doing this?

**Comment by jaymedavis** [comment]
That sounds like a Stripe question. If something is missing from Stripe.net allowing you to do that, let me know.

**Comment by FlashDeath** [comment]
https://stripe.com/docs/api#transfer_object-application_fee
Even their api doesn't seem to have a way to set it though.

**Comment by jaymedavis** [comment]
You are right - closing this. I build this library based on the docs, so there is nothing I can add if they show it not there. Feel free to drop in the IRC room #stripe on free node to ask them about it, or contact their support to see if this is the case. Reopen this issue if it's still an issue. :)

**Comment by dplarina** [comment]
This is covered by their documentation elsewhere https://stripe.com/docs/connect/special-case-transfers#taking-application-fees-from-a-transfer

**Comment by jaymedavis** [comment]
Thanks @dplarina, works for me. Reopened.

**Comment by dplarina** [comment]
Added a pull request for this #568
