### ISSUE TITLE
How to add bank accounts to cards?

### ISSUE THREAD

**Issue by FlashDeath** [jaymedavis/stripe.net#553]
I need add bank accounts and verify before I can begin charging for ach transfers.  My question is how do I add bank account information to a customer? StripeCustomerCreateOptions doesn't seem to have an option to add a source bank account like it does for cards.

**Comment by jaymedavis** [comment]
This does need to have direct support for BankAccounts, but in the meantime - you could always create a bank account via a token. Then, you could pass that token to StripeCustomerCreateOptions.

**Comment by noahtk** [comment]
Great. How do I verify the bank account information that is added via a token to the Customer object?

**Comment by jaymedavis** [comment]
I would use Stripe.js, it's the easiest way, imo. It is also the base library I am using for a new product coming out called Checkout.net (simplifies PCI compliance with Stripe.net and getting client side tokens)

**Comment by jaymedavis** [comment]
Here is a test I just wrote, with comments, to support StripeCharge having a bank account or a card. This pretty much fits your scenario. :+1: 

https://github.com/jaymedavis/stripe.net/blob/bb16b7bd9dd6dad19c031968909b469f477a2649/src/Stripe.Tests/charges/when_creating_a_charge_with_a_bank_account.cs

**Comment by noahtk** [comment]
Thanks!!!!!!!!!!
