### ISSUE TITLE
Integration with c# .Net 3.5

### ISSUE THREAD

**Issue by emkata85** [jaymedavis/stripe.net#554]
Hello,

I am trying to implement stripe.net with .Net 3.5 where I use version of stripe 4.2.1.
Does this version support tokens?
And if ti does which parameter is responsible for the token value?
Could you please show some charge sample for this version of the api?

**Comment by jaymedavis** [comment]
.NET 3.5 is a bit too old to support, I'm sorry :(

With Stripe switching to TLS 1.2, you are going to have to ugprade to 4.5 anyway very very soon. I would take the plunge now.
