### ISSUE TITLE
Failing to create a connected account with credit card token

### ISSUE THREAD

**Issue by doronavin** [jaymedavis/stripe.net#555]
Hi, 
I'm trying to create/update an account with a debit card using a token.

var createOrUpdateOptions = new StripeAccountUpdateOptions
{
 ///...fill all required properties
};

`createOrUpdateOptions.ExternalCardAccount = new StripeAccountCardOptions()
                {                    
                    TokenId = paymentDetails.DebitCard.Token.Id,
                    Currency = StripeConstants.DefaultCurrency
                };`

and I'm getting the following exception in the .net code:

{"Invalid request (check your POST parameters): unable to determine value for parameter: external_account. For assistance, please email support@stripe.com."}

but in stripe's dashboard I only see  a successful post to a v1/tokens api

I can't find a test with such scenario, can someone help me please?

**Comment by doronavin** [comment]
The actual call is StripeAccountService:Update(accountId, createOrUpdateOptions)

**Comment by jaymedavis** [comment]
Have you contacted Stripe support?

**Comment by jaymedavis** [comment]
Try only setting the token without currency too.

**Comment by doronavin** [comment]
I've tried sending without currency - but there was an error stating that currency is required.


Anyway, they did change something, because now I'm able to send the card details as plain text and not use a token.


There is one strange thing when using the token in your sdk:

The parsed request POST Body that stripe logs appears as:

country=US&managed=True&business_name=Foo&external_account[object]=card...


and for all other requests that do work - it is parsed as json

Any idea why this is happening?

**Comment by jaymedavis** [comment]
What version of .net? I fixed a bug recently with the PCL
