### ISSUE TITLE
Delete a subscription discount

### ISSUE THREAD

**Issue by drewf** [jaymedavis/stripe.net#556]
Does Stripe.net current support deleting a subscription discount? I can't seem to find this capability.

[https://stripe.com/docs/api#delete_subscription_discount](https://stripe.com/docs/api#delete_subscription_discount)

Thanks!

**Comment by brentdavid2008** [comment]
#520 is working toward a solution for this

**Comment by jaymedavis** [comment]
this is complete and will be on the next release (tonight)
