### ISSUE TITLE
Add legal_entity.gender

### ISSUE THREAD

**Issue by yamashinya** [jaymedavis/stripe.net#557]
Do you support legal_entity.gender?
https://stripe.com/docs/connect/required-verification-information#JP
I can not find it

Thanks!

**Comment by jaymedavis** [comment]
It's not there. It needs to be added [here](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Services/Account/StripeAccountLegalEntityOptions.cs) to be part of the payload, and then [here](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Entities/StripeLegalEntity.cs) to be parsed in the response. Also, it needs to be added to an existing tests, or just the generic behavior of managed accounts.

I added managed accounts not long ago, and I'm fairly certain this was not here at that time, and I cannot find it in [api upgrades](https://stripe.com/docs/upgrades)

@Brandur - is there a thread or list I can join to find out when small properties like this are added (or removed)?

**Comment by jaymedavis** [comment]
@yamashinya - I hope the info I left you above is enough to modify a local copy and get this field, it should be just a few lines. Please send a PR if you take care of it. If not, I'll get this added when I can!

**Comment by brandur** [comment]
> @Brandur - is there a thread or list I can join to find out when small properties like this are added (or removed)?

Unfortunately we don't have a great solution for this right now. Your best bet might be to subscribe to the repository of one of the other static bindings (probably Go) and see what's going in there.
