### ISSUE TITLE
Joining  new customer to a managed account

### ISSUE THREAD

**Issue by bassem-limem** [jaymedavis/stripe.net#558]
Hi Davis,

Can't find the attribute "stripe_account" in the class StripeCustomerCreateOptions to join  new customer to a managed account.

Here the stripe api doc :
```
Stripe.api_key = PLATFORM_SECRET_KEY
Stripe::Customer.create(
  {:description => "example@stripe.com"},
  {:stripe_account => CONNECTED_STRIPE_ACCOUNT_ID}
)
```
Thanks

**Comment by jaymedavis** [comment]
It is in the StripeRequestOptions, the second parameter to the method- it's documented on the readme.
