### ISSUE TITLE
StripeCustomerCreateOptions and TaxPercent

### ISSUE THREAD

**Issue by btriad** [jaymedavis/stripe.net#559]
I am trying to pass TaxPercent to Stripe but I get the error  "Invalid decimal: 23.0000; must contain at maximum two decimal places". Probably should be sent 23.00,... Any workaround?

**Comment by jaymedavis** [comment]
I haven't heard of this one yet - are you sure your decimal is formatted correctly and/or being set as 23.00?

**Comment by xt0rted** [comment]
If your decimal is initialized with trailing zeros which can happen when coming out of the dB (specifically with the money type I believe) or from a post back then they'll be included when calling `ToString()` which can break some forms of serialization.

If that's what's going on you'll need to call `ToString("G29")`, but that might be out of your control here.

```c#
decimal val1 = 23m;
decimal val2 = 23.0000m;
val1.ToString() != val2.ToString();
val1.ToString("G29") == val2.ToString("G29");
```

> The G format with a number means to format that many significant digits. Because 29 is the most significant digits that a Decimal can have, this will effectively truncate the trailing zeros without rounding.
http://stackoverflow.com/a/17516500/39605

**Comment by btriad** [comment]
xt0rted is correct. The value comes from db. I did used ToString("G29") before setting value to TaxPercent (is type of decimal?) and seems that works fine now. I will run some more tests and will update the thread if needed.

Thanks for the assistance!

**Comment by jaymedavis** [comment]
Awesome, thanks yet again @xt0rted :)

**Comment by xt0rted** [comment]
no problem, happy to help 😄
