### ISSUE TITLE
Stripe Connect - Charge a customer using his bank account

### ISSUE THREAD

**Issue by Tarek-AbdelMaqsoud** [jaymedavis/stripe.net#560]
Hello,
I am trying to charge a connected user using his bank account id using the following code

```
var myCharge = new StripeChargeCreateOptions();
myCharge.Amount = 1000;
myCharge.Currency = payment.Currency.ToString();
myCharge.Source = new StripeSourceOptions();
myCharge.SourceTokenOrExistingSourceId = ConnectedAccountId;

StripeRequestOptions stripeRequest = new StripeRequestOptions();
stripeRequest.ApiKey = "MyAPIKey";
stripeRequest.StripeConnectAccountId = ConnectedAccountId;

StripeCharge stripeCharge = chargeService.Create(myCharge, stripeRequest);
```

the way i developed above, is always failing.
But when i created a new customer, and replaced the following line

`myCharge.SourceTokenOrExistingSourceId = ConnectedAccountId;`

with these ones

```
StripeTokenService stripeTokenService = new StripeTokenService();
stripeTokenService.ApiKey = "MyAPIKey";
var token = stripeTokenService.Create(stripeToken, stripeRequest);
var myToken = token.Id;
myCharge.Source = new StripeSourceOptions();
myCharge.Source.TokenId = myToken;
```

It succeeded, but that required the customer id, and i need the user's card info to create this customer to get the customer id.
and i feel its illogical to ask for the user's card info, while i will never ask him to pay, i just will pay to him on behalf of my platform

Any ideas ?

**Comment by jaymedavis** [comment]
Few things here

StripeSourceOptions has been deprecated awhile, what version are you on? 

Looks like you are passing the connectedAccountId for the token - this should be the id of the bank account source, or a token. Alternatively you can use a StripeSourceOptions - see the readme, they should not both be used.

You do not need StripeSourceOptions at all - just that token. 

You don't have to pass your key again in StripeRequestOptions.

**Comment by Tarek-AbdelMaqsoud** [comment]
i removed it and changed my code to be as following 
```

var myCharge = new StripeChargeCreateOptions();
myCharge.Amount = 1000;
myCharge.Currency = "usd";
myCharge.SourceTokenOrExistingSourceId = connectedAccountId;

StripeRequestOptions stripeRequest = new StripeRequestOptions();
stripeRequest.ApiKey = "MyAPIKey";
stripeRequest.StripeConnectAccountId = connectedAccountId;

var chargeService = new StripeChargeService();
chargeService.ApiKey = "MyAPIKey";

StripeCharge stripeCharge = chargeService.Create(myCharge, stripeRequest);
```

but it says 

> Cannot transfer from an unconnected source account.
While it is already connected, and listed within the connected accounts list in stripe

**Comment by jaymedavis** [comment]
Why are you passing the connectedAccountId as the source Id? I would think you want the bank account id as I mentioned in the above post.

**Comment by jaymedavis** [comment]
Also - there is no need to set the API key in the request unless you aren't using web.config etc. Do you pass the API key in all of your Stripe.net code?

**Comment by Tarek-AbdelMaqsoud** [comment]
Excuse me, i am new to the stripe connect, so i am feeling a little bit confused

i have replaced the connectedAccountId  with the bank account id listed [here, Test bank account numbers](https://stripe.com/docs/testing#how-do-i-test-sending-transfers)

but it failed saying, 

> No such Token

also, i noticed it is mainly used for managed accounts as mentioned in the link above, while i am using standalone accounts 

am i using it the right way ?

**Comment by jaymedavis** [comment]
I would ping Stripe at this point and just explain your logic. Unfortunately, I don't have any tests covering this type of scenario so I'm not sure what the correct answer is. I thought you could just pass a source id and that would work.

**Comment by Tarek-AbdelMaqsoud** [comment]
Thank you so much for your help

**Comment by jaymedavis** [comment]
Sure thing - please update this thread if you wouldn't mind if you get this solved. Let me know if I can help work through it after you talk with Stripe. :)

**Comment by Tarek-AbdelMaqsoud** [comment]
I contacted them and once i get it solved i will post it over here as a comment

I marked this issue as closed to keep it away from the real issues, as i am not sure if it is a real issue or i am doing it the wrong way 

Thank you so much :)
