### ISSUE TITLE
multiple managed bank accounts

### ISSUE THREAD

**Issue by ejongejans** [jaymedavis/stripe.net#562]
Hi there, 

Is there a possibility to be able to better manage multiple bank accounts on the managed accounts? 

Currently i only see the ExternalBankAccounts property in the StripeAccountUpdateOptions object.

So if i get it correctly i can create new bank accounts this way; but doesn't set them to default. 
And how would one delete them? 

kind regards,
Elco

**Comment by jaymedavis** [comment]
You would use the bank account service, and checkout the readme on StripeRequestOptions- it's the second parameter to every service inside Stripe.net. This is how you can perform an action on behalf of a manager account - create, delete, etc. As for the default on a customer, just set that as their source when you update them.
