### ISSUE TITLE
Error On Build: Symbol indexes could not be retrieved.

### ISSUE THREAD

**Issue by joshpierce** [jaymedavis/stripe.net#564]
Getting the following back from our build agent:

2016-08-18T22:50:03.5350786Z ##[error]Indexed source information could not be retrieved from 'C:\a\1\s\xxxxxxxx.Tests\bin\Beta\Stripe.net.pdb'. Symbol indexes could not be retrieved.

Any thoughts on what this could be?

Thanks!!

Josh

**Comment by jaymedavis** [comment]
Are you on an older build? Or latest?

**Comment by joshpierce** [comment]
this is happening on 6.4.0 brought in through nuget package manager

**Comment by jaymedavis** [comment]
Well - I use to deploy the pdb, now I no longer do. Can you try clearing that file from your build agent?

**Comment by jaymedavis** [comment]
Reopen if you are still getting this - thanks.
