### ISSUE TITLE
TransferId property missing from StripeCharge

### ISSUE THREAD

**Issue by dtodaro-ascendle** [jaymedavis/stripe.net#565]
First let me say this is a **fabulous**-looking library. Great work!

We're planning on using your library for Stripe Connect transactions, processed via our platform account. (I.e. using our Stripe key, not the connected account's Stripe key).

We'd like to store the id of the transfer that Stripe will give back to us, if possible. Do you have any plans for adding a TransferId property to StripeCharge to store the **transfer** property returned by Stripe in the [charge object](https://stripe.com/docs/api#charge_object)?

I looked through the open pull requests and didn't see any that include adding this property.

If you have no plans please let me know; maybe we can submit a pull request with this added.

Thanks in advance!

Dave

**Comment by jaymedavis** [comment]
Hi, Dave - thanks!

Plans are to eventually add everything! This should be pretty simple to add, just keep in mind it's an expandable property. There are examples everywhere for how that works.

**Comment by dtodaro-ascendle** [comment]
Thanks!

We will probably start by storing the charge ID and see if we need the transaction ID. We might just retrieve that information manually if we need it via the Stripe dashboard.

Thanks again for an awesome library! We are looking forward to using it as we dig into our monetization features next week.

Thanks,
Dave

**Comment by dtodaro-ascendle** [comment]
Thanks!!!

**Comment by jaymedavis** [comment]
You're very welcome! I hope the upgrade to stripe.net 7.0 goes well - feel free to let me know if you have any trouble at all from something I missed in the release notes.
