### ISSUE TITLE
transfer does not use Recipient anymore

### ISSUE THREAD

**Issue by 5tigerjelly** [jaymedavis/stripe.net#572]
https://stripe.com/docs/api#create_transfer

 Recipients have been deprecated and are no longer available. They have been replaced by managed accounts (see https://stripe.com/docs/connect/managed-accounts), which you should use 

is the error when I try to do a transfer

![image](https://cloud.githubusercontent.com/assets/15973528/17987811/febb387a-6ad6-11e6-8003-56d911b01bfe.png)

**Comment by jaymedavis** [comment]
View Detail on the exception - this is just warning you to use connect instead. StripeRequestOptions is the second parameter to that method, and you would pass the recipient there. Your exception is probably coming from that not being a real recipient...

**Comment by jaymedavis** [comment]
Are you all set here, did you have any trouble getting this going?

I do need to change the example to not use recipients. I am reopening this for that reason.

**Comment by 5tigerjelly** [comment]
I see, however can you add destination in the stripetransfercreateoption?

![image](https://cloud.githubusercontent.com/assets/15973528/17991395/329ee54e-6af3-11e6-8ad3-d467c6881816.png)

**Comment by jaymedavis** [comment]
Change your last line to `transferService.Create(myTransfer, option)`

**Comment by jaymedavis** [comment]
Let me know if that works. Also, would you mind me labeling this issue as an example? Your screenshots really help. :+1:

**Comment by 5tigerjelly** [comment]
no prob also I already tried what you told me eariler.
![image](https://cloud.githubusercontent.com/assets/15973528/17991647/63da3a30-6af5-11e6-8f39-97cf36eab7a1.png)

**Comment by jaymedavis** [comment]
For your purposes, it looks like I do need to just add destination. However - be sure you read the documentation for [Special Case Transfers](https://stripe.com/docs/connect/special-case-transfers). Check out [Creating Payments and Fees](https://stripe.com/docs/connect/payments-fees) as well.

I will get destination added :+1:

**Comment by 5tigerjelly** [comment]
Thank you very much! :+1:

**Comment by 5tigerjelly** [comment]
Thank you so much, I saw your changes,

so how often does these get pushed to the nuget library?

**Comment by jaymedavis** [comment]
It all depends, I still have more work to do on this release, but I'm already many hours deep this week. So probably next week in this case.
