### ISSUE TITLE
CI Server

### ISSUE THREAD

**Issue by jaymedavis** [jaymedavis/stripe.net#576]
I need a CI process that is easier than me rolling releases by hand. Here are the build steps I go through before a release:
- verify all tests pass (right now I have to add a reference to Stripe.net's .net project, run the tests, then add a reference to Stripe.Portable and run the tests)
- bump version in assemblyinfo and stripe.net.nuspec
- compile in release mode
- run build.cmd
- publish nuget build (nuget push package.nupkg)
- publish new github release (this will still have to be by hand)

I'm interested in anything to get this done. I can build a server to be the CI server, or use something like AppVeyor.

A huge win would simply be taking care of the first bullet. Cake (kudos @SharpeRAD) looks very compelling, but will need research how to include mspec support, my favorite test framework! Maybe @einari or @ivanz can point me in the right direction? :)

Thanks in advance for any feedback!

edit: I have ~650 tests with mspec including behaviors, so unless there's a strong reason to switch frameworks, I'd rather stick with mspec. :)

edit2: Stripe has offered me monetary support for this project, so I'm happy to pay for someone's time if we find a good solution.

**Comment by jaymedavis** [comment]
I like to open source every part of this library, so the build process/server config is something I'd like to open source as well. To the extent this is possible. I might have to roll my own server if the process is too custom, but we'll see.

**Comment by ivanz** [comment]
I suggest looking into AppVeyor CI as it can do all of what you need and also works well with mspec tests:

Example 1: https://github.com/machine/machine.specifications/blob/master/appveyor.yml
Example 2: https://github.com/CorrelatorSharp/CorrelatorSharp/blob/master/appveyor.yml

**Comment by jaymedavis** [comment]
Thanks @ivanz. For my issue with removing and adding a reference to both assemblies (I run the same suite of tests against two assemblies), I gather from this I could handle it in the powershell script. However, life would probably be easier to go ahead and convert this solution to a single project that target PCL and net45.

Thanks again for the examples.

**Comment by SharpeRAD** [comment]
Ok so this is just my opinion, other opinions exist :smile: 
- Upgrade the projects to .net core as the "project.json" file makes multi targeting a lot easier, so you could do away with a separate portable project.
- Use Cake as your build script, [here's](https://github.com/SharpeRAD/MailBounceDetector/blob/master/build.cake) one I made earlier for another project that you could pretty much copy and paste once you've upgraded to .net core.
- Use AppVeyor as your build server, this [config](https://github.com/SharpeRAD/MailBounceDetector/blob/master/appveyor.yml) file will get your started.

**Comment by jaymedavis** [comment]
Thanks much @SharpeRAD! Lot of great stuff. 

I 100% agree on .net core.

**Comment by xt0rted** [comment]
👍 for AppVeyor, it's been pretty easy to use on my projects and they've been super responsive any time I've had questions. Here's a [config](https://github.com/xt0rted/Nancy.Validation.DataAnnotations.Extensions/blob/67e4bcb635fd5f98439d18e2557e88068c4525d8/appveyor.yml) I've been using on one of my projects that releases to MyGet & NuGet on tags.

**Comment by jaymedavis** [comment]
Thanks @xt0rted, this looks really simple and probably best fits V1 of CI, seeing as you don't have a build.ps1 or anything. I assume the secrets will be pretty intuitive once I dive in. I will probably implement a git-flow type process and work on a develop branch when this goes live. That way master can always bump a build. I'll just need to figure out how to version it appropriately.

**Comment by jaymedavis** [comment]
Also, I'm going to put this on the Xamarin store just to help a few users out, so the ps1 examples still help a lot! Thanks again to all of you!!

**Comment by xt0rted** [comment]
Once logged you can setup secure strings from your account page.

Taken from https://www.appveyor.com/docs/deployment/nuget/
> Your NuGet API key should be encrypted using this tool: https://ci.appveyor.com/tools/encrypt.

In my project I'm doing a git-flow style where all pushes/merges to master result in a CI build and push to MyGet, then on tags a build also pushes to NuGet. On a different project I tried using two branches but I got tired of the manual process and switched over to this setup.

**Comment by jaymedavis** [comment]
Thanks everyone. @xt0rted - your config is very simple and is probably what I will start with to get this configured sooner rather than later. Over time, I might need more advanced features (like Cake), but I will let them organically be problems before I solve them. 

Thanks again to everyone for all of the help on this, it should make my AppVeyor setup go smooth. If anyone has examples of  1) deploying a readme.txt to be displayed in visual studio on the NuGet download or. 2) an example of preparing a Xamarin package in the build process, that's about the last thing left I need now.

**Comment by jaymedavis** [comment]
@xt0rted -> send me a private email if you get the chance. jaymedavis at gmail. :)

**Comment by xt0rted** [comment]
You can show a readme.txt by including it in the project, setting the build action to none, and then added a hard reference to it in the nuspec.

https://docs.nuget.org/create/creating-and-publishing-a-package#automatically-displaying-a-readme.txt-file-during-package-installation

http://stackoverflow.com/a/34400505/39605

**Comment by jaymedavis** [comment]
Thanks @xt0rted. Figured there might not be much to that. :+1:
