### ISSUE TITLE
Definitive way to retrieve all line items for an invoice

### ISSUE THREAD

**Issue by jasenf** [jaymedavis/stripe.net#578]
What's the proper code for getting ALL InvoiceLineItems from an invoice (in my case, an upcoming invoice).  The _invoice.StripeInvoiceLineItems only retrieves the initial list.  If there are more than the allowed list size, I need to query Stripe for the additional line items for this invoice, but can't find a specific way of doing that.

The only thing I see are ways to query InvoiceLineItems relative to a customer, not a specific invoice or subscription.

**Comment by jaymedavis** [comment]
This is a good question @jasenf. I could not find anything in their documentation that supports this. I have posted this in the Stripe IRC room.

**Comment by jaymedavis** [comment]
There is an invoice-line-item branch now, that I just merged/pushed up. This will be on master and be part of the next release. You will essentially call ListLineItems() from the service. :+1:

**Comment by jaymedavis** [comment]
FYI - there is another PR for upcoming line items, but it appears to be pretty much the same code. Since a user has probably already retrieved the upcoming invoice, I'm not sure it's worthwhile to add an UpcomingLineItems option - 

In your use case, do you retrieve the upcoming invoice first, then you want the line items? Or do you want the line items without ever retrieving the invoice? Thanks much. :smile:

**Comment by jasenf** [comment]
So looking into this a bit as well..

It seems invoice line items are related not to a subscription but a customer.  If you go into stripe and do it manually you actually associated line items to a customer and then when a subscription kicks off an invoice it attaches those line items.  So oddly, the Api and subsequently your wrappers, seem correct.

Bizarre implementing on Stripes part but I think you're golden.

**Comment by jaymedavis** [comment]
I found it a little strange as well (so did the people helping me in IRC). I didn't fully grok the PR from @daniel-cohen at first, but credit to him for implementing this. :)

Also, @circuitrider implemented basically the same thing in #531 for upcoming invoices, I'm just not sure if that is needed when you could just use the ListLineItems and pass the invoice id for the upcoming invoice. It wouldn't hurt to have the separate UpcomingListLineItems though - and it might save developers some time. I welcome your feedback.

I'll try to get a revision out soon for this so you can just pull it from NuGet after the holiday.

**Comment by jaymedavis** [comment]
This has not been released on NuGet yet, but the code is on master. I'll close this when it's available on NuGet. If you want to test by running the code from master, that would definitely be appreciated!
