### ISSUE TITLE
NullReference Exception in Client.GetSystemInformation on iOS - Release Only

### ISSUE THREAD

**Issue by duckwaffle** [jaymedavis/stripe.net#580]
Hi, I encountered this issue when I finally got around to testing iOS/Android builds of my project recently, and thought you should know about it too.

The method where you get the Assembly's Product name when creating the X-Stripe-Client-User-Agent header in every request results in a null reference when running on iOS in release mode. I believe there are some Reflection types that aren't available when running in release mode on monotouch.

I ended up hardcoding a value in that method if that happens, and you can have a look at my solution here https://github.com/duckwaffle/stripe.net/commit/05e9040c1eb1ba8f06e18cb72a6ee2f42226a02d but I'm sure it could be handled more neatly.

Cheers.

**Comment by jaymedavis** [comment]
Grr!!! I tested this out with an example iPhone app, but I did not test release mode. I will fix this before the next release. Anything else blocking you?

**Comment by duckwaffle** [comment]
Haha, yeah the fact that it only shows up in release is pretty sneaky. This should be the last one that's affecting me, apart from https://github.com/jaymedavis/stripe.net/issues/567 . Appreciate all the help!

**Comment by jaymedavis** [comment]
I wasn't able to duplicate this - so if you wouldn't mind testing, I would really appreciate it. You can just check out the code if that's a pain.
