### ISSUE TITLE
Newtonsoft cannot serialize StripeCharge

### ISSUE THREAD

**Issue by davidn04** [jaymedavis/stripe.net#583]
Hi,

I'm currently using 5.3.0 and upgraded to 6.5.0/6.4.0, and when trying to json serialize StripeCharge, it returns Method not implemented.

`string jsonData = Newtonsoft.Json.JsonConvert.SerializeObject(charge);`

**Comment by jaymedavis** [comment]
Can you tell me your environment? .NET/iPhone/version/etc?

**Comment by jaymedavis** [comment]
And are you running 6.4 or 6.5?

**Comment by davidn04** [comment]
Tried on both 6.4.0 and 6.5.0.

Using it on ASP.NET MVC with .NET Framework 4.6

Seems like SourceConverter is being used for Source field json conversion

StripeCharge.cs
`        [JsonConverter(typeof(SourceConverter))]
        public Source Source { get; set; }
`

SourceConverter.cs
`public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }`

**Comment by jaymedavis** [comment]
Hmmm... 6.5 should have fixed this from another user's PR - I need to write a test to cover this. Can you share your code?

**Comment by jaymedavis** [comment]
This shouldn't actually be writing any JSON - only reading for this converter.

**Comment by davidn04** [comment]
```
StripeChargeCreateOptions myCharge = new StripeChargeCreateOptions();
myCharge.Amount = 100;
myCharge.Currency = "aud";
myCharge.StatementDescriptor = "This is a test";
myCharge.Capture = true;
myCharge.Metadata = new Dictionary<string, string>();
myCharge.Metadata.Add("Email", "test@test.com");
myCharge.SourceTokenOrExistingSourceId = stripeToken;
StripeChargeService chargeService = new StripeChargeService(stripeSK);
StripeCharge charge = chargeService.Create(myCharge);
string jsonData = Newtonsoft.Json.JsonConvert.SerializeObject(charge);
```

From [stackoverflow](http://stackoverflow.com/questions/13809997/serialize-property-that-throws-notimplementedexception) if you add
```
var settings = new JsonSerializerSettings();
settings.Error += (o, args) => {
        args.ErrorContext.Handled = true;
};
string jsonData = Newtonsoft.Json.JsonConvert.SerializeObject(charge, settings);
```
in the serialized json Source is null, so you do not get any card details.

**Comment by davidn04** [comment]
{"object":"charge","livemode":false,"amount":1330,"captured":true,"created":"\/Date(1472823028)\/","currency":"aud","paid":true,"refunded":false,"refunds":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/charges/ch_xxxxxxxxxxxxx/refunds"},"Source":null,"status":"succeeded","amount_refunded":0,"BalanceTransactionId":"txn_xxxxxxxxxxx","CustomerId":null,"description":null,"statement_descriptor":"Test","dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"InvoiceId":null,"metadata":{"Email":"test@test.com"},"receipt_email":null,"receipt_number":null,"id":"ch_xxxxxxxxxxxxxx"}

**Comment by jaymedavis** [comment]
Why are you serializing the returned charge? I assume it's working up to this point?

**Comment by jaymedavis** [comment]
I assume it's dying on the line where you serialize it yourself (because I didn't implement a writer). I could do this though. Is your goal just to store the entities json data for logging purposes? Or are you trying to do something else?

**Comment by jaymedavis** [comment]
The reason I ask, is #378 is a ticket for storing the raw JSON response from Stripe. I could work on implementing a way for you to retrieve this as a string, without having to serialize every call manually.

I thought this may be easier - but I'll leave this open. It's probably a good idea to implement the writer on this property anyway. :+1:

**Comment by davidn04** [comment]
Yeah, it was just to do logging.

From the other ticket the raw JSON response/request from Stripe would be great.

**Comment by vIceBerg** [comment]
I have the same issue. And I keep the StripeCharge for logging purpose.

I would like to see the old behavior working, because I'm using a legacy program and I want to minimize code changes as much as I can.
