### ISSUE TITLE
StripeSubscriptionService requires CustomerId

### ISSUE THREAD

**Issue by kraighiersche** [jaymedavis/stripe.net#585]
The Stripe API provides a method to retrieve a subscription with just the subscription id (e.g. https://api.stripe.com/v1/subscriptions/sub_96TbFsPrpntFoC), but Stripe.Net requires a customerId (StripeSubscriptionService .Get).  In my case, I just have the subscriptionId.  Is there anyway to do this with Stripe.Net?

**Comment by jaymedavis** [comment]
At the moment, no. Have you tried passing null for the customer? It will just pass that through to Stripe. (Warning - I have not reviewed code for this)

**Comment by kraighiersche** [comment]
Yeah,  tried that but it fails.  Thanks.  Love what you have done though 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Jayme Davis <notifications@github.com> Date: 9/3/16  1:21 PM  (GMT-08:00) To: "jaymedavis/stripe.net" <stripe.net@noreply.github.com> Cc: kraighiersche <kraig.hiersche@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jaymedavis/stripe.net] StripeSubscriptionService requires
  CustomerId (#585) 
At the moment, no. Have you tried passing null for the customer? It will just pass that through to Stripe. (Warning - I have not reviewed code for this)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jaymedavis/stripe.net","title":"jaymedavis/stripe.net","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jaymedavis/stripe.net"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jaymedavis in #585: At the moment, no. Have you tried passing null for the customer? It will just pass that through to Stripe. (Warning - I have not reviewed code for this)"}],"action":{"name":"View Issue","url":"https://github.com/jaymedavis/stripe.net/issues/585#issuecomment-244567800"}}}

**Comment by jaymedavis** [comment]
Thanks - I'll leave this open and get this fixed. :thumbs-up:

**Comment by ricktheartist** [comment]
I got this working without the customerID - The error stripe returned was that the path was not valid since the request was being sent to "/customers//subscriptions/xxxx" I tried passing in ".." for the customerID and it works.

`subscriptionService.Get("..", "sub_92348675876")`

**Comment by jaymedavis** [comment]
Haha! That's very clever, @ricktheartist! I will get this fixed permanently, but in the meantime, this will actually work with the other service(s?) that needs to be fixed up. 

Thanks for sharing!

**Comment by ricktheartist** [comment]
FYI - I just tested the same hack on updating a subscription and it works too.
`subscriptionService.Update("..", subID, updateOptions, reqopt)`

**Comment by kraighiersche** [comment]
Awesome - thanks!

**Comment by jaymedavis** [comment]
this has been fixed, missed closing this issue
