### ISSUE TITLE
how to cancel subscription and issue refund to customer

### ISSUE THREAD

**Issue by mynk28** [jaymedavis/stripe.net#587]
I want to cancel subscription and refund subscription amount that is charged to customers in some cases.

I'm using stripe.net API for create customer and assign subscription plan. Check "Creating a customer" with card which I'm using for subscription.

Is there any way to issue refund with subscription cancellation?

**Comment by jaymedavis** [comment]
This needs to be documented in the readme, but there is a StripeRefundService you can use.

**Comment by jaymedavis** [comment]
Leaving open to document -

**Comment by mynk28** [comment]
I've checked the "StripeRefundService" but it requires chargeId. I'm using subscription not charge service. So how can I get chargeId in return when payment is done during subscription?

**Comment by jaymedavis** [comment]
I just pushed up a new branch that will not require the charge id any longer. It will be on master soon, and I will close this then.

**Comment by mynk28** [comment]
Ok, thanks for the update. Looking forward for the update.

**Comment by dennypuig** [comment]
I've checked the StripeRefundService and it requires chargeId as a parameter. I am using version 8.4

**Comment by mhrnik** [comment]
@jaymedavis Did you update that updated branch in master?
