### ISSUE TITLE
StripeChargeService no longer has a Refund method in newest Stripe.Net version

### ISSUE THREAD

**Issue by mpoincare** [jaymedavis/stripe.net#591]
I upgraded to the latest version of Stripe.net. I had to make some changes in my code to adjust to the new changes based on the code sample provided at https://github.com/jaymedavis/stripe.net. However I seem to hit a wall because in my code I used the Refund method of the StripeChargeService class that doesn’t seem to exist anymore in the newest version. My online search yielded no result. Could you please tell me in what class is the Refund method or better yet, how to issue a refund on a card following a ‘Capture’ that was set to false. Please see my code below after screen shot.

protected
void btnRefundDeposit_Click(object sender, EventArgs e)
{
try
{
StripeCharge stripeCharge = new StripeCharge();
StripeChargeService chargeService = new StripeChargeService(Constants.StripeAPI_Key);
if (ViewState[SessionVariables.DepositPaymentType].ToString() == "Credit Card")
{
//Get StripeChargeID
string StripeChargeID = ViewState[SessionVariables.StripeChargeID].ToString();
if (!String.IsNullOrEmpty(StripeChargeID))
{
if (!chkApplyExtraChargesAgainstDeposit.Checked)
{
//do a full refund
stripeCharge = chargeService.Refund(StripeChargeID,
Convert.ToInt32(Convert.ToDecimal(txbRentDepositAmountToRefund.Text) * 100));
}
else if (chkApplyExtraChargesAgainstDeposit.Checked && Convert.ToDecimal(txbExtraCharges.Text) == 0)
{
//do a full refund
stripeCharge = chargeService.Refund(StripeChargeID,
Convert.ToInt32(Convert.ToDecimal(txbRentDepositAmountToRefund.Text) * 100));
}
else if (chkApplyExtraChargesAgainstDeposit.Checked && Convert.ToDecimal(txbExtraCharges.Text) > 0)
{
//charge the total amount of the extra charges
stripeCharge = chargeService.Capture(StripeChargeID,
Convert.ToInt32(Convert.ToDecimal(txbExtraCharges.Text)) * 100, null);
}
DeviceRentBLL.UpdateRentDepositWithPartialRefund(Convert.ToInt32(ViewState[SessionVariables.RentHeaderID].ToString()), DepositPayment.PaymentType, StripeChargeID);
//refresh the rent header grid
FillGridRentHeader();
btnCancelDepositProcessing_Click(sender, e);
pnlDepositRefund.Visible =
false;
}
else
{
throw new ArgumentException("Stripe charge ID could not be found.");
}
}
else //Deposit Payment Type is either Check or Cash
{
DeviceRentBLL.UpdateRentDepositPaymentStatus(Convert.ToInt32(ViewState[SessionVariables.RentHeaderID].ToString()));
//refresh the rent header grid
FillGridRentHeader();
btnCancelDepositProcessing_Click(sender, e);
pnlDepositRefund.Visible =
false;
}
}
catch (Exception ex)
{
lblMsgPaymentProcessing.Visible =
true;
lblMsgPaymentProcessing.Text = ex.Message;
}
}

**Comment by CruelMoney** [comment]
Using v. 6.6.0 there's a StripeRefundService. But it is yet to be documented.

**Comment by jaymedavis** [comment]
Correct. I have another issue open to get this done, but I don't have time at the moment to link it, so I'll leave this open. In the meantime, if you want to create a refund @mpoincare, call Create on the service @CruelMonkey mentioned.
