### ISSUE TITLE
How To Tansfer Fund using Connects

### ISSUE THREAD

**Issue by shahdarshit197** [jaymedavis/stripe.net#593]
hi,
  i am trying to tansfer fund using Connecnts but not doing strip.net.dll api'
so what can i do for that ther no any opetion of destinations

**Comment by jaymedavis** [comment]
Destination is available. For connect, read about the second parameter (StripeRequestOptions) on the readme.

**Comment by shahdarshit197** [comment]
but my  dll in not avillble that thing and i serach it but i can't get new one

**Comment by jaymedavis** [comment]
You get the library from NuGet? What version?
