### ISSUE TITLE
application_fee property on the StripeTransfer object is the wrong type

### ISSUE THREAD

**Issue by dplarina** [jaymedavis/stripe.net#595]
https://stripe.com/docs/api#transfer_object
application_fee is `string` and should not be `int?`
This is because the transfer object returns the id of the application_fee object.

application_fee `int?` is correct for StripeTransferCreateOptions however.
https://stripe.com/docs/api#create_transfer

The stripe API appears to use the field with the same name for different purposes.

**Comment by jaymedavis** [comment]
Looks like it's wrong in the StripeInvoice too, probably. It seems all application fee's transfer as integers, but come down as strings? That seems odd.

**Comment by jaymedavis** [comment]
Ah, I see - talked with Stripe in IRC about this. It's because it returns the ID to the application fee object, not the app fee you passed. It's also an expandable object, which is pretty easy to do in Stripe.net if you search for expandable.
