### ISSUE TITLE
RefundService Get Method requires the charge it

### ISSUE THREAD

**Issue by babushyam** [jaymedavis/stripe.net#597]
Is there a possibility to change/add the RefundService.Get method using only the Refund ID? Currently both ChargeID and RefundID are required. 

This is essentially for automatic reconciling of the Stripe Transfer to Bank Statement. To implement this, Transfer and linked Balance Transactions are read. In case of Refunds, only the Refund ID is available of the BalanceTransaction.Source. Hence it now not possible to get the Refund details & and linked Charge details.

**Comment by jaymedavis** [comment]
Yes - I just pushed up a remote branch that I will be merging to master shortly. It takes care of this, will close when on master.

**Comment by babushyam** [comment]
Thank you!

**Comment by jaymedavis** [comment]
You're very welcome :). Will release to NuGet in the next day or so!
