### ISSUE TITLE
No File Upload to Stripe Option available 

### ISSUE THREAD

**Issue by qadirkhan** [jaymedavis/stripe.net#602]
There is an API in Stripe documentation for file upload but I am unable to find option to upload file for identity verification to Stripe in Stripe.net. Kindly let me know when you will implement it. I am stuck with account verification and its asking me to upload verification document id **legal_entity.verification.document**.

**Comment by outersource** [comment]
It appears Jayme is working on this feature this week: [https://github.com/jaymedavis/stripe.net/issues/448](https://github.com/jaymedavis/stripe.net/issues/448) bottom of comments

**Comment by jaymedavis** [comment]
Thanks for the help @outersource :)
