### ISSUE TITLE
Changes in StripeCustomerService.Get?

### ISSUE THREAD

**Issue by lehne** [jaymedavis/stripe.net#603]
When I get a customer, DefaultCustomerBankAccountId is always null when it used to be populated. Now, I have to use Sources, which includes bank accounts, but the list of sources is always a StripeCard, which means I cannot access the bank account. Is this a change in Stripe.Net deserialization?

**Comment by jaymedavis** [comment]
I implemented a Source entity not long ago for StripeCharge. This same change needs to be made to StripeCustomer. I am curious about you seeing that property as null though, as it is mapped directly from Stripe. You can check the attribute over the property and make sure it matches the same string from stripe.com/api/docs. What version did you have previously?

**Comment by jaymedavis** [comment]
Well, it looks like that property just disappeared from the docs and there was a change to customer. I do not see default_bank_account anymore. If you want, check with Stripe support to see if this was removed recently. My guess is it was - did it work in the same version you have now, and then also break in the same version?

I am away right now, but will investigate further when I can.

**Comment by lehne** [comment]
I updated from 6.4 to 6.6. I could swear the property was there just a couple days ago. Could be my upgrade was just coincidental with their changes.

**Comment by jaymedavis** [comment]
Did you manually bump your API version with Stripe by chance?

**Comment by jaymedavis** [comment]
As of right now, the Stripe docs show the source as a card only. However, if you look on the example side of customers on the docs, it shows Sources - and it's a hash, not a dictionary (StripeCard). I've notified Stripe of the issue, and I will fix this in the library so there will be a Sources property that can contain bank account and/or cards. This will be a StripeList of type Source.

I will work on this for this weeks release. If you could revert to 6.4 and tell me if this works, I would appreciate it. Since the API version was updated in that version as well, I would be surprised if it did. :(

This release will have small breaking changes, but they will be simple to fix, and I will document instructions.

**Comment by lehne** [comment]
I did not manually change API version with Stripe. I have it working with 6.6 now. Will try changing back to 6.4 and let you know if that helped. Thank you!

**Comment by jaymedavis** [comment]
You have it working? What was the issue?

**Comment by lehne** [comment]
I just changed my code to use the _default_source_ and look up whether it is a bank account or card. Here is a sample response for get customer that I am getting (some properties removed for clarity). Notice in this response that they are mixing bank accounts and cards in the sources list (only the cards deserialize properly in Stripe.net):

```
{
  "default_source": "ba_23432432SDJFSDFJSD",
  "sources": {
    "object": "list",
    "data": [
      {
        "id": "ba_23432432SDJFSDFJSD",
        "object": "bank_account",
        "account_holder_name": "Test Person",
        "account_holder_type": "company",
        "bank_name": "STRIPE TEST BANK",
        "country": "US",
        "currency": "usd",
        "customer": "cus_9Cqpdf3434343",
        "fingerprint": "fsdfd#$#$##$",
        "last4": "1116",
        "metadata": {
        },
        "routing_number": "110000000",
        "status": "verified"
      },
      {
        "id": "card_123ge234DFH343Deff34",
        "object": "card",
        "address_city": "Test City",
        "address_country": null,
        "address_line1": "add1",
        "address_line1_check": "pass",
        "address_line2": null,
        "address_state": null,
        "address_zip": "45344",
        "address_zip_check": "pass",
        "brand": "Visa",
        "country": "US",
        "customer": "cus_9Cqpdf3434343",
        "cvc_check": "pass",
        "dynamic_last4": null,
        "exp_month": 9,
        "exp_year": 2019,
        "funding": "credit",
        "last4": "4242",
        "metadata": {
        },
        "name": null,
        "tokenization_method": null
      }
    ],
    "has_more": false,
    "total_count": 2,
    "url": "/v1/customers/cus_9Cqpdf3434343/sources"
  }
}
```

**Comment by jaymedavis** [comment]
Only cards serialize for now on Customer - on charges, both can serialize due to a new type called Source (has a type identifier then Card and BankAccount properties where only one is populated). I will be changing Customer soon to have a 'Sources' property for this as well to use Source.
