### ISSUE TITLE
HttpClient Connections stay in CLOSE_WAIT status, they aren't closed

### ISSUE THREAD

**Issue by scanwavecode** [jaymedavis/stripe.net#604]
Hello,

My problem is that my requests are stuck until I receive a TaskCanceledException in GenerateCreditCardToken. This problem started to happen recently so I would say there is nothing wrong with parameters but rather there is some weird HttpClient behaviour.

In lower-level details, in the code-base, it seems the HTTP connections are not being closed and disposed. When I investigate the sockets using netstat, Stripe connection sockets are left in CLOSE_WAIT state. Maybe this has something to do with the problem.

This is happening on mono. Requests timeout with a TaskCancelledException.

Thanks,

Yaser

**Comment by scanwavecode** [comment]
You can dismiss the above issue. I finally found that http client is refusing the TLS certificate of Stripe test platform, but since HttpClient is your implementation seems to be a singleton, the TLS authentication error occurs once and subsequent requests timeout. After modifying the ServicePointManager to skip validation, everything worked as before.

**Comment by jaymedavis** [comment]
You can pass your own HttpHandler via StripeConfiurairon as well. What did you specifically add?

**Comment by codethug** [comment]
In my case, I ran into this error when running Fiddler with HTTPS logging enabled.  I closed Fiddler, and the error went away.

**Comment by paulcsiki** [comment]
I have also ran into this problem by not reusing the same HttpClient across all StripeClients.
