### ISSUE TITLE
Multiple subscription for same customer

### ISSUE THREAD

**Issue by PiyushStv** [jaymedavis/stripe.net#605]
Hi, 

Can we create multiple subscription for same customer using this library. My requirement is to create a subscription when user will register in my application.

We have an option to purchase emails from our application, if user purcheses emails then i want another subscripton to create he will charge for new subscriton as well as old subscription should not expire or overite by new subscription.

How to get more than one active subscription for same customer???

Thanks and regards,
Piyush Srivastava

**Comment by jaymedavis** [comment]
When you retrieve customer's on the StripeCustomerService, there is a StripeList(check docs) of StripeSubscription's.
