### ISSUE TITLE
Update card/bank account using token rather than sending card details to server

### ISSUE THREAD

**Issue by XueYingqi** [jaymedavis/stripe.net#606]
Hi Jayme,

Please advise how to update card/bank account with a stripe token to avoid card/bank account details touching my server (for PCI compliance). 

It seems that different to StripeCardCreationOptions() and BankAccountCreationOptions(), StripeCardUpdateOptions() and BankAccountUpdateOptions() don't have SourceToken property?

Many thanks.
Yingqi

**Comment by jaymedavis** [comment]
Very glad you asked this! You are right - using the built in options are only viable if your server is PCI compliant. Checkout.js would be my personal recommendation for getting a token. Subtracts (my company) has a product being built called Checkout.net that will make getting a token PCI compliant and very simple (targetting MVC users right now). It also uses Checkout.js. 

StripeCardCreateOptions and BankAccountUpdateOptions both have a `SourceToken` property you can use once you have your token. What version are you using?

**Comment by XueYingqi** [comment]
I use Stripe.net 6.4.0.0 in my web project, and use Stripe.js to get token from Stripe server.

For PCI compliant, I need to update card using token - something like the codes in next 4 lines:
var myCard = new StripeCardUpdateOptions();
myCard.SourceToken = *Token*;
var cardService = new StripeCardService();
cardService.Update(*StripeCustomerId*,*StripeSourceId*, myCard)

But I got error for codes in line2, says: 
Stripe.StripeCardUpdateOptions does not contain a definition for SourceToken and no extension method 'SourceToken' accepting a first argument of type Stripe.StripeCardUpdateOptions could be found (are you missing a using directive or an assembly reference?

In References - Stripe.net - StripeCardUpdateOptions, I can't see SourceToken (yes, SourceToken is available in StripeCardCreateOptions). See the attached screenshot. 

![stripenet_cardupdatebysourcetoken](https://cloud.githubusercontent.com/assets/22305697/18787822/6423c6d8-819c-11e6-959e-6e89bc9357e9.png)

**Comment by jaymedavis** [comment]
At the time these services were last updated, you cannot pass a token when updating a card - check the Stripe docs, but I doubt that's changed. If you want a new card for a customer you will need to Create it.

**Comment by XueYingqi** [comment]
It seems they have 'update cards using token' now. See the link below:
https://stripe.com/docs/recipes/updating-customer-cards 

Really helpful to have this added in Stripe.net too. For the moment I have to do a fake updating - delete existing card and re-create as a new card, which is not ideal.

**Comment by brentdavid2008** [comment]
I could be wrong but that article talks more about updating a default card _after_ the card is already created on the customer rather than the actual card details itself.  To change the expiration date or anything else about the card, the token isn't supported as per the API (which is what stripe.net uses to make it's requests) 

[https://stripe.com/docs/api#update_card](url)

Based on the API docs, you have to update the card via stripe.js or have the server be PCI compliant. 

Are you trying to just update the default card source on a customer? or are you actually wanting to change the card details?  

If I'm wrong feel free to point out where I may have missed!

Thanks!

**Comment by XueYingqi** [comment]
Dear Jayme and Brett,
Thank you so much for the advice. I contacted Stripe and found out that only card number and CVC are the sensitive information that should not be stored/sent through my server. Saving or processing other card information on server side should be fine.
In terms of updating card details, you are right, it can be done by updating a customer's default card. See the email below.
Many thanks again for all your advice, very helpful!
Cheers,Yingqi Xue



Hey Yingqi,Thanks for reaching out to us, I'm happy to help you with this!Essentially CVC and card number are the two pieces of information you want to avoid storing. https://support.stripe.com/questions/what-information-can-i-safely-store-about-my-users-payment-informationYou'll note that these two pieces of information are not things you can update on a card object, so you're safe passing other details directly if need be. https://stripe.com/docs/api#update_cardIf you'd like to add a new card to an existing customer you can easily do that. Jayme's library provides an example to do this (the first example uses a token, pass the existing customer id as *customerId*), https://github.com/jaymedavis/stripe.net#creating-a-cardWhen you've added a new card you can set that card as 'default_source' if you'd it to be the default source to charge on a given customer. https://stripe.com/docs/api#customer_object (Instead of adding a new card on a customer you could also update a customer passing the sourceToken which would replace the existing, default card --- https://github.com/jaymedavis/stripe.net#updating-a-customer)I hope this helps and please let me know if you have any other questions!All the best,
Dexter
On Oct 1, 10:24, yq_x wrote:
I am using Stripe.js and Stripe.net to handle card payment on my webiste.For PCI compliance, please advice what information can't touch/be stored in my server , e.g. Card holder name, exp MM/YY, CVC, Billing address. etc.?My second question is that:
When creating a new card, Stripe.js sends card details to Stripe directively without touching my server and returns a SourceToken. Then this SourceToken is being used with Stripe.net to create new card. But when updating an existing card (if not the default payment source of a customer), there isn't a way to update using SourceToken like creating a new card does. I've checked with Jayme Davis, the author of Stripe.net, and he said it's because Stripe api doesn't have SourceToken argument in updating a card. According to https://stripe.com/docs/api#cards, it seems customer's default card can be updated by token. But it's in PHP. Can you please advice how to achieve this in Stripe.net and if it works for non-default cards. Many thanks,
Yingqi 

   

 On Tuesday, 27 September 2016, 14:21, Brent David <notifications@github.com> wrote:
 

 I could be wrong but that article talks more about updating a default card after the card is already created on the customer rather than the actual card details itself. To change the expiration date or anything else about the card, the token isn't supported as per the API (which is what stripe.net uses to make it's requests) https://stripe.com/docs/api#update_cardBased on the API docs, you have to update the card via stripe.js or have the server be PCI compliant. Are you trying to just update the default card source on a customer? or are you actually wanting to change the card details? If I'm wrong feel free to point out where I may have missed!Thanks!—

**Comment by jaymedavis** [comment]
Thanks for the update, @XueYingqi! I'm glad this issue was opened, and I appreciate your concern with handling customer data the *right* way. 

My company, Subtracts, is building a product called Checkout.net which will make this a lot easier. We are building drag-and-drop PCI compliance, using stripe.js and jQuery behind the scenes, and offering a nice UI and integration with Stripe.net. Checkout from Stripe is a great product, but it's not designed to work specifically with Stripe.net. We are starting with MVC, but forms support will work (just not documented yet), and I hope this makes a lot more users move towards PCI compliant solutions. We are still figuring out pricing, but thinking of going with a small monthly fee for a subscription, so we can continue to add features and support for other things like bank accounts and themes for beautiful forms. :)  Do you mind my asking - what would this service have been worth to you, knowing what is involved with rolling your own solution?

Thanks again for spending the time to make sure you are following PCI compliance rules.

**Comment by jaymedavis** [comment]
THANKS!

**Comment by Dinesh-Net** [comment]
Hi,
I have a application in which i am using stripe.Net for payment. I would like to add User's Bank account details so that i can transfer fund into that account.
I am not able to create using BankAccountCreationOptions(), beoz SoureToken.
How may i get SourceToken.
var bankAccountOptions = new BankAccountCreateOptions()
                {
                    SourceToken = "pk_test_lOMq82LDuL89wrZsV9JA9Jfu",
                    SourceBankAccount = new SourceBankAccount()
                    {
                        AccountNumber = "Test123456987",
                        Country = "USD",
                        Currency = "United States",
                        BankName = "HDFC Bank Ltd",
                    },
                };
                var bankAccountService = new BankAccountService();
                CustomerBankAccount bankAccount = new CustomerBankAccount();
                bankAccount = bankAccountService.Create("cus_BvfDRStyCGgnjb", bankAccountOptions);

please help.

**Comment by ob-stripe** [comment]
@Dinesh-Net At the moment, the .NET library has limited support for managing external accounts for custom accounts (cf. #980). You can only add an external account when creating or updating the custom account, e.g.:

```c#
var accountService = new StripeAccountService(Cache.ApiKey);

var accountCreateOptions = new StripeAccountCreateOptions
{
    Type = StripeAccountType.Custom,
    ExternalBankAccount = new StripeAccountBankAccountOptions()
    {
        RoutingNumber = "110000000",
        AccountNumber = "000123456789",
        Country = "US",
        Currency = "usd",
        AccountHolderType = "individual",
        AccountHolderName = "Jenny Rosen"
    }
};

var account = accountService.Create(accountCreateOptions);
```

You can also tokenize the bank account client-side using [Stripe.js](https://stripe.com/docs/stripe-js/reference#collecting-bank-account-details) (here's a basic [example form](https://jsfiddle.net/ywain/L2cefvtp/)), and pass a token in your server-side code:

```csharp
var accountService = new StripeAccountService(Cache.ApiKey);

var accountCreateOptions = new StripeAccountCreateOptions
{
    Type = StripeAccountType.Custom,
    ExternalBankAccount = new StripeAccountBankAccountOptions()
    {
        TokenId = "btok_..."
    }
};

var account = accountService.Create(accountCreateOptions);
```

If you need more help, you should write to support using the form at https://support.stripe.com/email.
