### ISSUE TITLE
StripeEventListOptions not filtering on dates

### ISSUE THREAD

**Issue by smulldino** [jaymedavis/stripe.net#607]
Hey Jayme - as per email...

I need to get all Stripe events that occurred after a certain date.  Example:

stripeRequestOptions.ApiKey = API_Key;
StripeEventListOptions eventListOptions = new StripeEventListOptions { Limit = 100 , Created = new StripeDateFilter { GreaterThanOrEqual = DateTime.Parse("2016-Sep-20 11:00") } };
var eventService = new StripeEventService();
IEnumerable<StripeEvent> nextPage = eventService.List(eventListOptions, stripeRequestOptions);

Stripe gives me back all events - going back 30 days - every time.

I can get around it by just breaking out of the loop once my target date is reached, but would be good to have it a bit cleaner.

Thanks a lot - the project has been a great help.

**Comment by jaymedavis** [comment]
I looked through the code for this to make sure the date was being converted to a unix timestamp, which it is. I will need to write a test for this to see what is going on. Thanks for opening this.

**Comment by jaymedavis** [comment]
Did you ever work around this @smulldino?

**Comment by smulldino** [comment]
Hi Jayme.  Yes I just break out of the loop when my target date is reached.
I get 30 days of data every time so if I only want the last 40 minutes I
just check the time stamp and breakout.

Paul

**Comment by jaymedavis** [comment]
The date filter might actually be working now - there was an issue with how it was parsing stripe dates for non-us dates. If you upgrade, hopefully it should work. Sounds like your work-around works, though!
