### ISSUE TITLE
Working with .NET Core in an ASP.NET app?

### ISSUE THREAD

**Issue by nhwilly** [jaymedavis/stripe.net#609]
Jayme - 

I'm still working on my project and it looks like I'll have to migrate to .NET Core for my server side ahead of schedule.  I imported the project and did some silly stuff and it didn't fall over.

Will this work?  

I figured you might know one way or the other and save me a lot of testing/two stepping.

TIA

**Comment by jaymedavis** [comment]
Yeah - you should be good to go - what problems are you having?

**Comment by nhwilly** [comment]
Not having any yet.  I've just gone down a lot of dead ends lately with trying to get the platform settled.  So many little broken pieces of things that you don't find out until you are neck deep in it.  

I was looking at switching to .Net Core to clear some up and then I thought you might just say "nope, forget it".

Good to know.  Hope all is well...

Thanks.

**Comment by jaymedavis** [comment]
> So many little broken pieces of things that you don't find out until you are neck deep in it.

I feel ya! I've struggled with the same things. 

You should be just fine with everything in .NET Core - Stripe.net will be moving to .NET Core soon itself, thanks to @flagbug and #581. I just have to clear up the old PR's first, but I'm eager to move!

All is well - same to you @nhwilly!!
