### ISSUE TITLE
Stripe has an easy pay with card button. I want to update it so I can pass a custom amount to it. (It defaults to 2000)  

### ISSUE THREAD

**Issue by sanjaykumarpushadapu** [jaymedavis/stripe.net#611]
Stripe has an easy pay with card button. I want to update it so I can pass a custom amount to it. (It defaults to 2000)

I need the customer to be able to put in however much they want to pay. Whether this is in the pop-up after they click the button, or on the page next to the button doesn't matter much. I'd prefer it to be in the pop-up however.

is it possible in asp.net with jquery or js 

 Thanks!

**Comment by jaymedavis** [comment]
I don't believe this is a Stripe.net issue, or something that is on the API? Re-open and provide a few links if that's not the case.
