### ISSUE TITLE
Cant get receipt email to work

### ISSUE THREAD

**Issue by Seichis** [jaymedavis/stripe.net#613]
Hi,

From what I have understood, in order to send an email receipt when I charge a customer I only need to have a the email in the ReceiptEmail field of the charge. But this does not seem to work. I can see that the charge has been made in the dashboard and I can see that the customer I created has been charged.
Ofc I have enabled the email option in the settings of Stripe but I do not receive anything. I have tested the email from the Stripe dashboard and it works fine. 

So what do I miss?
Thank you in advance, KM

**Comment by jaymedavis** [comment]
Please check with Stripe support - this does not appear to be an issue with Stripe.net (I do not know the answer)

**Comment by Seichis** [comment]
OK found it. FYI, Stripe does not send receipt emails for test mode. Only for live mode. 

https://support.stripe.com/questions/why-am-i-not-receiving-confirmation-receipt-notification-emails-from-stripe

**Comment by jaymedavis** [comment]
Ah! Thanks so much for updating!!!

**Comment by littlemountainman** [comment]
Awesome searched ages for it. 👍
