### ISSUE TITLE
Stripe.net is a sync/async .NET 4.5+

### ISSUE THREAD

**Issue by DannyWave** [jaymedavis/stripe.net#614]
Hello, at first I want to thank you for your development! I'm really glad to have your library for our projects! Now we have a serious issue:
> Hello!
> 
> My name is Brandur and I'm an engineer at Stripe.
> 
> In 2017, we'll be deprecating some of the older security protocols (TLS 1.0, TLS 1.1, and SHA-1) used to make connections with Stripe's APIs. I'm reaching out to give you an early heads up because your Stripe integration might be impacted.
> 
> Here are some of the key upcoming dates:
> 
> * On January 1, 2017, we'll drop support for TLS 1.0 connections and SHA-1
>   certificates.
> * On May 1, 2017, we'll drop support for TLS 1.1 connections.
> 
> We've noticed that your Stripe integration appears to be using TLS 1.0, so you'll want to follow the steps in this upgrade guide [1] to ensure that your Stripe integration isn't interrupted in the next year. 

Unfortunately we're using .NET Framework 4.0, not 4.5:

> "If you are using Stripe.net to communicate with Stripe, and you have version 5.1.1 or lower installed, you will need to update this package." 

Stripe.NET 5.1.2 is already .NET Framework 4.5, therefore we can't update anymore.
Since I don't understand why you updated to 4.5 anyhow, I was wondering if there are chances to make a working 4.0 version to stay with you guys for the next years as well.

**Comment by jaymedavis** [comment]
.NET 4.0 does not support TLS 1.2. There isn't a way to make a working 4.0 version.

I would highly recommend an upgrade in your stack.
