### ISSUE TITLE
StripeSourceOptions alternative

### ISSUE THREAD

**Issue by aaboyd** [jaymedavis/stripe.net#615]
Currently I am using `StripeSourceOptions` but that appears to be deprecated.  I was wondering how I would create a card from a Stripe Token and associate `MetaData`.  Is there a better option other than `StripeSourceOptions`, if not is there a plan to address this before `StripeSourceOptions` is removed.

Sorry for the blank request, hit enter and github submitted the issue before I typed anything.

**Comment by jaymedavis** [comment]
?

**Comment by aaboyd** [comment]
@jaymedavis that was scary fast ...

**Comment by jaymedavis** [comment]
:)

Check out the example here - it is already replaced. 

https://github.com/jaymedavis/stripe.net/blob/master/readme.md#cards

**Comment by aaboyd** [comment]
`StripeCardService` has methods to know create using a token or `StripeSourceCard`, but the method that takes in a token only allows you to pass in a token.

Here is the snippet I am looking for a replacement for 👍 
```
var cardCreateOptions = new StripeCardCreateOptions();
cardCreateOptions.Source = new StripeSourceOptions() {
    TokenId = request.StripeToken,
    Metadata = new Dictionary<string, string>()
};
cardCreateOptions.Source.Metadata[Constants.STRIPE_CARD_NICKNAME_KEY] = request.Name;
var card = await _stripeCardService.CreateAsync(currentUser.StripeId, cardCreateOptions);
```

In your example I would have to do `_stripeCardService.CreateAsync` and then make another call `_stripeCardService.UpdateAsync` to attach the `Metadata`.

**Comment by jaymedavis** [comment]
Ah, I see - the metadata can be passed with the token. Will get this fixed.
