### ISSUE TITLE
Issue adding DefaultSource to Customer

### ISSUE THREAD

**Issue by FlashDeath** [jaymedavis/stripe.net#618]
Since I can't add a default source on creation of I customer, I create a customer and then try to use the update options to add a default source to it.  I can successfully create a customer, but when I try to retrieve the default source that should have been added to it, it always returns null.

For Example:

                StripeCustomerCreateOptions options = new StripeCustomerCreateOptions();
                options.Email = email;
                options.SourceCard = new SourceCard() {
                    // Card Info
                };
                StripeCustomer customer = new StripeCustomerService().Create(options);

                StripeCardCreateOptions card = new StripeCardCreateOptions();
                card.SourceCard = new SourceCard() {
                    // Card Info
                };
                StripeCard defaultCard = StripeCardService().Create(customerId, card);

                StripeCustomerUpdateOptions updateOptions = new StripeCustomerUpdateOptions();
                updateOptions.DefaultSource = defaultCard.Id;
                StripeCustomerService().Update(customer.Id, updateOptions);

Is this all I should need to do?

**Comment by FlashDeath** [comment]
After looking through a bunch of the old issue I found someone else who mentioned the same thing that I must have missed before.  Looks like I need to set the StripeCusomerService's ExpandDefaultSource to true.  Is there a reason this isn't defaulted to true?  Might also want to add a note that you have to do this under where you have the snippet showing how to set the default source in the readme.

**Comment by jaymedavis** [comment]
Yes, this is covered under [Expandable Properties](https://github.com/jaymedavis/stripe.net#expandable-properties) on the readme. The reason they aren't set by default, is it will create a bigger payload (taking more time) when a lot of users don't need it. This is how Stripe does it behind the scenes - it is null except for the ID, unless you explicitly tell it to expand the property. Glad you found it!
