### ISSUE TITLE
Not CLS-compliant?

### ISSUE THREAD

**Issue by xecrets** [jaymedavis/stripe.net#620]
It appears the assembly is not marked CLS-compliant, which causes warnings for consumers which are. Off-hand I can see no reason why it shouldn't or couldn't be CLS-compliant.

It just requires a [assembly: CLSCompliant(true)] attribute.

Am I missing something obvious?

**Comment by jaymedavis** [comment]
Sure, I can add this easy enough. Nobody has ever asked for this before, however - can you give me a screenshot of where you are seeing this?

**Comment by xecrets** [comment]
Returning a strip.net type from a method or interface in a CLS-compliant assembly gives you this:

![image](https://cloud.githubusercontent.com/assets/5602123/19123530/44e5f9f2-8b2f-11e6-820b-7e45adbc63e9.png)

And this:

![image](https://cloud.githubusercontent.com/assets/5602123/19123588/819e5cae-8b2f-11e6-8a13-426476d9f848.png)

There are other warnings you get in similar situations.

**Comment by jaymedavis** [comment]
Is IStripePayment your own type?

**Comment by xecrets** [comment]
Yes, but that's not really relevant. I have lots of types of my own ;-) The thing is that any method in any type that returns one of the stripe.net types will get the warning about not being CLS-compliant.

**Comment by jaymedavis** [comment]
May seem like a nonsense question to you, but I receive support requests all the time from people not even using Stripe.net.

**Comment by xecrets** [comment]
:-) I get it. I have support on my stuff too. You can reproduce it easily enough by marking a consuming assembly with [assembly: CLSCompliant(true)] attribute and then declare a public type with a public method that has one of your stripe.net types as a return value type.

**Comment by jaymedavis** [comment]
It seems the consuming assembly would have to be marked CLS-compliant as well, or this error would not come up. That's my guess why I haven't seen this until now - that CLS-compliant attribute must not be used very often - but it seems beneficial to me... it might help me on my new mission to force coding styles and spacing, etc. on myself. I will read more into this later - but as long as the compiler lets me know if I have any issues, I don't see any problem with having it - seems like a good thing.

May I ask your reason for using it in your library? I'm just curious more than anything at this point.

**Comment by xecrets** [comment]
Exactly, it's when the consuming assembly is marked CLS-compliant it's triggered!

It's just good coding practice to be CLS-compliant, since it means your assembly can be consumed by anything else that is, which includes other .NET languages for example. It's just good form. It's also something that static code analysis aka FxCop will compain about and suggest you fix. It delcares your promise that you won't break a number of rules. For example, if you're CLS-compliant you don't run the risk of naming things so they can't be consumed by other language systems, even if the name is legal in your current environment. Naming a public type to start with an _ is not CLS-compliant (why you'd ever want to do that is beyond me, but it's just an example) because some languages can't use it then.

I use static code analysis on my code all the time, and it's been really helpful, and also quite instructive. The explanations of the warnings are often good and I've learned quite a bit from it.

Here's what static code analysis has to say about CLS-compliance: https://msdn.microsoft.com/en-us/library/ms182156.aspx .

As for forcing coding style on yourself, may I suggest a light-weight Visual Studio extension called Code Maid. One of the really nice features in this context is you can have it perform a 'Format Document' every time you save a file. That's how I keep my code consistently formatted. This also helps with source control merges and commits, since changes tend to be just around those lines that actually matter since all else is consistent.
