### ISSUE TITLE
StripeChargeCreateOptions.Shipping property doesn't match the Stripe API spec

### ISSUE THREAD

**Issue by timabbott83** [jaymedavis/stripe.net#623]
Hi Jayme, 

I've been looking at using the nuget package to create charges with Stripe and have noticed that the StripeChargeCreateOptions.Shipping property doesn't seem to match the current Stripe API spec.  The C# property is a dictionary with string keys and values, which when serialised will produce JSON similar to block below.

```
  "shipping": {
    "line1": "*first line of the address*",
    "line2": "etc..."
  }
```

The spec however seems to indicate there should be a sub-property of "shipping" called "address" (amongst others) which then contains the various address fields.  See https://stripe.com/docs/api#charge_object

```
  "shipping": {
    "address": {
      "line1": "*first line of the address*",
      "line2": "etc..."
    },
   "carrier": "etc..."
  }
```

Many thanks,
Tim

**Comment by jaymedavis** [comment]
This needs to be fixed - shipping used to be a dictionary, but it was changed at some point.

**Comment by iwstom** [comment]
Hi, is this on your radar anytime soon?

**Comment by jaymedavis** [comment]
1) The StripeChargeCreateOptions object needs all the properties from here (shipping): https://stripe.com/docs/api#charge_object-shipping 
2) A test(s) needs to be written to confirm that whatever shipping information is sent, is also returned correctly.
3) Build the project and run all of the tests.. You can run "build-and-test.bat" in the src directory to do everything for you. 

These are notes for myself or anyone else that comes along to submit a PR. I am not working on Stripe.net atm, but I would be happy to work on this as soon as I am able. 👍

**Comment by varunbabu008** [comment]
Hi . I was wondering if this was fixed. I am getting a stripe exception "Invalid Hash" when Shipping(dictionary) property of StripeChargeCreateOptions was specified.
