### ISSUE TITLE
Getting charges for connected account always returns 0 results

### ISSUE THREAD

**Issue by malako** [jaymedavis/stripe.net#625]
When getting charges filtered by accountId, the result is always 0. Removing the requestOptions part returns transactions as expected.

```
            var chargeService = new StripeChargeService(<apikey>);
            var options = new StripeChargeListOptions();

            var requestOptions = new StripeRequestOptions();
            requestOptions.StripeConnectAccountId = "acct_xxxxxxxxxxxx";
            requestOptions.ApiKey = <apikey>;

            List<StripeCharge> charges = chargeService.List(options, requestOptions).ToList();
```

**Comment by jaymedavis** [comment]
You don't need to set the API key on the request options. It's already set on the charge service. I'm not sure if that's the issue - but it's not necessary to be there

**Comment by malako** [comment]
I've tried with and without requestOptions.ApiKey, so that is not the issue. I will download the source when i have time and debug to see what api query is generated.

**Comment by jaymedavis** [comment]
Can you post your list options?

**Comment by jaymedavis** [comment]
I just saw it was a new instance - try passing null there. This is a connected account that is managed by you? I would share the account id with stripe support, and make sure you can list the charges there

**Comment by malako** [comment]
Yes, the main account is managed by me and i can access the managed accounts' dashboards and see charges via Stripe admin GUI.
`
var chargeService = new StripeChargeService(<apikey>);
var requestOptions = new StripeRequestOptions();
requestOptions.StripeConnectAccountId = "acct_xxxxxxxxxxxx";
chargeService.List(null, requestOptions);
`
This still returns 0 results.

**Comment by jaymedavis** [comment]
Is this solved? I haven't heard of any other issues with this.
