### ISSUE TITLE
Card expiration month & year are returned as strings instead of integers

### ISSUE THREAD

**Issue by xt0rted** [jaymedavis/stripe.net#626]
When getting a card's information the expiration month & year are returned as strings ([StripeCard.cs#L16-L20](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Entities/StripeCard.cs#L16-L20)), while in the API docs it shows them [as integers](https://stripe.com/docs/api#card_object-exp_month). Is there a reason for them being strings or can those properties be updated?

**Comment by jaymedavis** [comment]
Was this a Stripe recent update? I don't recall them ever using int's. I will research this more - thanks for reporting.

**Comment by xt0rted** [comment]
I'm not sure. I noticed they were strings when checking if there was a property indicating if the card was expired or not.

**Comment by jaymedavis** [comment]
Well, talking to Stripe about it in the IRC room, it seems they have always been ints. I'll ask around a little more tomorrow to verify, but it's highly possible I just got it wrong and it's always worked as is. However - you are right. If they are integers on Stripe, they should be integers here. 👍

**Comment by jaymedavis** [comment]
better late then never 👍
