### ISSUE TITLE
Instant Transfer

### ISSUE THREAD

**Issue by hsmith825** [jaymedavis/stripe.net#627]
When are you planning on supporting instant transfer?

Thanks!
Howard

**Comment by jaymedavis** [comment]
Link to Stripe docs?

**Comment by hsmith825** [comment]
Instant is an option of method for Create Transfer as described on this page: https://stripe.com/docs/api#create_transfer

Thanks!!!

**Comment by jaymedavis** [comment]
Gotcha - thanks!
