### ISSUE TITLE
Can't update to 6.8

### ISSUE THREAD

**Issue by cadilhac** [jaymedavis/stripe.net#629]
Because of the TLS change in Stripe, I have to update to a recent Stripe.Net version before the end of the year. I updated to the latest one (6.8), which automatically updated Newtonsoft.Json to 9, and I get this at runtime:

Could not load file or assembly 'Newtonsoft.Json, Version=4.5.0.0

It fails when the code calls WebApiConfig.Register(GlobalConfiguration.Configuration);

Is my asp.net MVC 4 project tied to a previous version of newtonsoft.json (4.5) and I can't update Stripe.Net because of this?

**Comment by cadilhac** [comment]
Sorry for the trouble. I had to uninstall and reinstall WebApi (exact same version) to fix the issue.

**Comment by cadilhac** [comment]
Oh, sorry, I talked too soon. The issue is not fixed. I imagine that when I uninstalled WebApi, then installed latest Stripe.Net and then reinstalled WebApi, several versions of NewtonSoft were available in some bin folders.
But when I cleaned bin/obj folders, the issue reappeared.

**Comment by jaymedavis** [comment]
I would clean and reinstall Stripe.net - it sounds like your bin might be in a rut. I would consider removing all of your dependencies as well, and letting visual studio redownload them from nuget. As far as I know, there should not be any issues running two different versions of json.net.

I would google around [things like this](http://stackoverflow.com/questions/21498074/how-can-i-fix-assembly-version-conflicts-with-json-net-after-updating-nuget-pack) this see if you can get that cleaned up. Re-open if you have a Stripe.net specific error and this doesn't resolve it.
