### ISSUE TITLE
Document upload return unsupported file typ

### ISSUE THREAD

**Issue by Cuias** [jaymedavis/stripe.net#630]
I'm using an HttpPostedFileBase that I'm sending to my method as a Stream. Is there something you should do before simply passing an HttpPostedFileBase as Stream?

HttpPostedFileBase file ....
UploadVerificationDocument(file.FileName, file.InputStream);

void UploadVerificationDocument(string filename, System.IO.Stream filestream)
{
	try
	{
		var fileService = new StripeFileUploadService(privateApiKey);
		var fileUpload = fileService.Create(filename, filestream, StripeFilePurpose.IdentityDocument);
		
But I'm receiving the following error, no matter what kind of file I'm giving it (JPG or PNG):
We don't currently support that file type. Try uploading a file with one of the following mimetypes: image/jpeg, image/png

**Comment by jaymedavis** [comment]
What is the exact filename you are passing?

**Comment by Cuias** [comment]
Thanks for replying!

_85730600_monkey2.jpg
_85730600_monkey2.jpeg
452974-monkey.jpeg
452974-monkey.png

**Comment by Cuias** [comment]
Hi Jayme,

Were you able to reproduce this, or is there anything I can do to help you find the problem? It's kind of a blocker for me, since I don't know exactly if I'm doing something wrong that produces a wrong error message, of if there is simply a bug.

**Comment by jaymedavis** [comment]
Sorry this got lost - we need to make sure the correct mimetype is being passed on this request (the bulk is handled in Requestor.cs). This error isn't coming from me, so stripe doesn't like something about it.

**Comment by jaymedavis** [comment]
[This test](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.Tests/fileuploads/when_creating_a_file_upload.cs) is running fine, the only difference is the type being passed.

**Comment by Cuias** [comment]
OK, and the functionality is the same for verification documents?
I'll try to go through the steps in the test method, and see if there's anything there that can help me!

**Comment by jaymedavis** [comment]
It works the same, yes. If you view the Stripe docs, all that does is pass a different purpose. [The code around mime types](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Infrastructure/MimeTypes.cs) all works the same. 

Try to upload it as a business logo and see if it fails. Also debug your file name and make sure it's passing what you are expecting.

**Comment by jaymedavis** [comment]
Did you get anywhere with this? Re-open if there is still an issue, or drop a comment if you found the issue. 👍

**Comment by Cuias** [comment]
Hi,
Sorry, forgot to follow up. I ended up saving the HttpPostedFile physically, and then use the exact same methods from the unit tests, which worked fine. So there must have been something wrong with the conversion I did.

**Comment by jaymedavis** [comment]
Thanks for the update- probably the value just going in wrong. Could step through to that method in the debugger to see what it was passing, but sounds like you're good!
