### ISSUE TITLE
Question: What to store?

### ISSUE THREAD

**Issue by innopal** [jaymedavis/stripe.net#633]
Hi Jayme,

When I create a managed account, what do I need to store?
I don't want to store all my customers bank account info and rest of the details.
Isn't it just enough to store the account id and created (external) bank account id(s)?
...or do I need to store everything (in generated StripeAccount)?

Thank you @jaymedavis :)

Cheers

**Comment by domialex** [comment]
Only store what you need to access the Stripe information, and what is necessary if this information is deleted and important ;).

**Comment by jaymedavis** [comment]
Storing the generated ID is enough. You can always retrieve anything else you need from Stripe by using this. Definitely don't store any bank account/cc information. Specifically on credit cards, the CVC and number are off limits (PCI Compliance). I would make sure you understand how to retrieve the data again first (review the Get() calls), and just store that.

Of course this is only a guideline - it's hard to say without understanding your use case.

**Comment by innopal** [comment]
Thank you @domialex and @jaymedavis.

Good advice Jayme! One thing confuses me though is that when you make a transfer you pass the managed account id as destination. On the other hand, a managed account can have multiple (external) bank accounts. How does stripe know which bank account they should transfer the money to?

It seems like destination should be bank account id and not the managed account id.

Any thoughts?

Cheers
