### ISSUE TITLE
StripeExternalAccountConverter.cs write function is not implemented

### ISSUE THREAD

**Issue by goneneren** [jaymedavis/stripe.net#635]
I'm receiving the following error message while trying to serialize **StripeAccount** object.

`{
  "Message": "An error has occurred.",
  "ExceptionMessage": "The 'ObjectContent 1 type failed to serialize the response body for content type 'application/json; charset=utf-8'.",
  "ExceptionType": "System.InvalidOperationException",
  "StackTrace": null,
  "InnerException": {
    "Message": "An error has occurred.",
    "ExceptionMessage": "The method or operation is not implemented.",
    "ExceptionType": "System.NotImplementedException",
    "StackTrace": "   at Stripe.Infrastructure.StripeExternalAccountConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
  }
}`

**Comment by jaymedavis** [comment]
This might be a matter of implementing the writer the same as it was done [here](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Infrastructure/SourceConverter.cs). I hope to build an internal property on all entities eventually so there's no need to serialize - and you can just access save the raw request/response. But for now - the same thing probably just needs a WriteJson on this class.

**Comment by jaymedavis** [comment]
This should be fixed now. However, there is a new property that will be present on all entities called `StripeRawJson` that will have the full json that Stripe returned. It's on master now and will go out with the next release. I would recommend using that instead. 👍
