### ISSUE TITLE
Verify Documentation?

### ISSUE THREAD

**Issue by drod516** [jaymedavis/stripe.net#644]
is there any Verify function Examples? I am trying to figure it out but having a hard time

**Comment by jaymedavis** [comment]
more context, please?

**Comment by drod516** [comment]
I mean in general. There is no Documentation or examples in the readme unless I am missing something

**Comment by jaymedavis** [comment]
Are you talking about Verifying a bank account?

Check out [this test](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.Tests/bank_accounts/when_verifying_a_bank_account.cs) and the [Stripe docs](https://stripe.com/docs/api#customer_verify_bank_account)

**Comment by jaymedavis** [comment]
I'll get something in the docs for this 👍

**Comment by drod516** [comment]
Yes sorry i meant verifying a bank account.
 awesome! thank you
