### ISSUE TITLE
Customer doesn't exist error

### ISSUE THREAD

**Issue by innopal** [jaymedavis/stripe.net#645]
Great work Jayme and the crew!

I am trying to create a transfer (charge) for a managed account, but I get a customer doesn't exist error!!!

Any helpful ideas greatly appreciated.

Here is my code:

```
var stripeCustomerService = new StripeCustomerService([Platform API Key]);
var stripeTokenOptions = new StripeCustomerCreateOptions { SourceToken = [Token generated by Stripe.js from a Credit card], };
var customer = stripeCustomerService.Create(stripeTokenOptions, new StripeRequestOptions {
	 StripeConnectAccountId = [ Recipient's Managed account Id ]
});

var stripeTokenService = new StripeTokenService([Recipient's secret key received when creating recipient's managed account]);
var tokenOptions = new StripeTokenCreateOptions
{
	CustomerId = customer.Id,
};

// The line below throws an error that customer with the id cust_blahblah doesn't exist.
var stripeToken = stripeTokenService.Create(tokenOptions);


hostChargeOptions = new StripeChargeCreateOptions()
{
	SourceTokenOrExistingSourceId = stripeToken.Id,
	Amount = 1000,
	Currency = chargeCurrency,
	Description = paymentDescription,
	Destination = [ Recipient's Managed account Id ]
};

var chargeService = new StripeChargeService();
            
var hostStripeCharge = chargeService.Create(hostChargeOptions);


```

**Comment by jaymedavis** [comment]
I would try just initializing the token service with your api key. Then, when you are calling service.Create(tokenOptions), pass a `new StripeRequestOptions` just like you did for creating the customer.

**Comment by jaymedavis** [comment]
Also, your charge would be using a token from the other account the way you have it setup now. When it looks for the token, it won't find it - because you are doing the charge from your account. Make sense?

**Comment by innopal** [comment]
Thank you @jaymedavis,

I am still getting the same error (No such Customer: cust_bluhbluh) on the same line.
My new code is:

var stripeCustomerService = new StripeCustomerService([Platform API Key]);
var stripeTokenOptions = new StripeCustomerCreateOptions { SourceToken = [Token generated by Stripe.js from a Credit card], };
var customer = stripeCustomerService.Create(stripeTokenOptions, new StripeRequestOptions {
     StripeConnectAccountId = [ Recipient's Managed account Id ]
});

var stripeTokenService = new StripeTokenService([Platform API Key]);
var tokenOptions = new StripeTokenCreateOptions
{
    CustomerId = customer.Id,
};

// The line below throws an error: "No such customer: cust_blahblah".
var stripeToken = stripeTokenService.Create(tokenOptions, new StripeRequestOptions {
     StripeConnectAccountId = [ Recipient's Managed account Id ]
});

Did I not understand your comment?

Cheers

**Comment by innopal** [comment]
I figured this out @jaymedavis.

I don't really need to create a token, so instead I used the CustomerId for charge options.

Thanks for your help.

**Comment by jaymedavis** [comment]
Where did you pass the customer id? SourceTokeOrExistingSource?  ... sorry, I wasn't even thinking about this looking at your code, could have maybe saved you some time :/

Glad you got it!!

**Comment by innopal** [comment]
No worries man.
Yes exactly! Instead of setting SourceTokeOrExistingSource I'm setting CustomerId directly and removed the whole token creation part.

Thanks Again.
