### ISSUE TITLE
StripeError.ErrorSubscription should be ErrorDescription

### ISSUE THREAD

**Issue by KirkGamesLLC** [jaymedavis/stripe.net#646]
namespace Stripe
{
    public class StripeError
    {
        [JsonProperty("error_description")]
        public string ErrorSubscription { get; set; }
    }
}

should be

```
    [JsonProperty("error_description")]
    public string ErrorDescription { get; set; }
```

**Comment by jaymedavis** [comment]
Haha. Oops.

Thanks!
