### ISSUE TITLE
No metadata in Stripe when creating a subscription

### ISSUE THREAD

**Issue by omarraman** [jaymedavis/stripe.net#650]
The following code 

                        var customer = new StripeCustomerCreateOptions()
                        {
                            Email = user.Email,
                            SourceToken = pvm.stripeToken,
                            PlanId = pvm.PlanId,
                            Description = plan.Name,
                            Quantity = 1,
                            Metadata = metadata

                        };

when trying to create a subscription works but when i check the Stripe dashboard for related payments or subscription there is no metadata. When i inspect "metadata" i can see that it is a populated dictionary.

By contrast the following, when just creating a one off payment works fine for metadata

                    var chargeOptions = new StripeChargeCreateOptions()
                    {
                        ReceiptEmail = user.Email,
                        Amount = (int)(plan.Price*100),
                        Currency = "gbp",
                        SourceTokenOrExistingSourceId = pvm.stripeToken,
                        Description = plan.Name,
                        Metadata = metadata
                    };

and i see the associated metadata in the dashboard.

Below is a short listing with those snippets in context. Basically the associated view returns a model, containing a planId. The plan id within my application represents some sort of "payment plan" where it could be a subcription, or just a one off payment.

Any help would be appreciated.

        public ActionResult Create(PaymentViewModel pvm)
        {
            try
            {
         
                var user = _dataRepository.UserProfiles.Find(WebSecurity.CurrentUserId);

                var metadata = new Dictionary<string, string>() { { "Username", user.UserName } };

                var plan = _dataRepository.PaymentPlans.Find(pvm.PlanId);

                if (plan.IsSubscription)
                {
                    if (String.IsNullOrEmpty(user.StripeCustomerId))
                    {
                        var customer = new StripeCustomerCreateOptions()
                        {
                            Email = user.Email,
                            SourceToken = pvm.stripeToken,
                            PlanId = pvm.PlanId,
                            Description = plan.Name,
                            Quantity = 1,
                            Metadata = metadata

                        };

                        StripeCustomer stripeCustomer = new StripeCustomerService().Create(customer);

                        user.ActiveUntil = DateTime.Now.AddYears(plan.Years).AddMonths(plan.Months).AddDays(plan.Days);
                        user.StripeCustomerId = stripeCustomer.Id;
                        user.PlanId = pvm.PlanId;
                        _dataRepository.SaveChanges();

                    }
                    else
                    {
                        var stripeSubscription = new StripeSubscriptionService().Create(user.StripeCustomerId, pvm.PlanId);

                    }

                }
                else
                {
                    var chargeOptions = new StripeChargeCreateOptions()
                    {
                        ReceiptEmail = user.Email,
                        Amount = (int)(plan.Price*100),
                        Currency = "gbp",
                        SourceTokenOrExistingSourceId = pvm.stripeToken,
                        Description = plan.Name,
                        Metadata = metadata
                    };
                    var chargeService = new StripeChargeService();
                    var stripeCharge = chargeService.Create(chargeOptions);

                }

**Comment by jaymedavis** [comment]
It looks like you are looking for related metadata in payments or the sub, but it looks like you are creating it on the customer. See if you have this metadata there.

**Comment by omarraman** [comment]
that was it, many thanks for your time.
