### ISSUE TITLE
DisabledReason in 

### ISSUE THREAD

**Issue by pradt** [jaymedavis/stripe.net#652]
Hi, 
This is just a feature request, it would be great if the StripeAccountVerification.DisabledReason was a enum instead of a string. 

This would make it easier to apply logic based on this field instead of each developer ensuring that the strings are correct. 

Based on the api documentation there are a only limited number of values : 
rejected.fraud, rejected.terms_of_service, rejected.listed, rejected.other, fields_needed, listed, or other

Thanks

**Comment by jaymedavis** [comment]
I've considered making lots of things like status, etc use enums. The entities could be bound with a custom json converter. The concern is maintenance and breaking changes. Thanks for bringing this up -

**Comment by NeoHub** [comment]
Hey guys,

I know this issue is closed. But did you already add an enum for `StripeAccountVerification.DisabledReason`?
