### ISSUE TITLE
StripeToken model missing properties

### ISSUE THREAD

**Issue by mortenmoulder** [jaymedavis/stripe.net#653]
Great "wrapper" is the first thing I'm going to say. Very good documentation and very easy to guess the method names! Thanks a lot.

When I fill out a form and send it to my backend, the frontend model has an email attribute on the StripeToken, however, the backend StripeToken does not.

Here's some example response data from Stripe:

```
{
    "id": "tok_TEST",
    "object": "token",

    "card": {
        "id": "card_TEST",
        "object": "card",
        "address_country": null,
        "address_line1": null,
        "address_line1_check": null,
        "address_line2": null,
        "address_state": null,
        "address_zip": null,
        "address_zip_check": null,
        "brand": "Visa",
        "country": "US",
        "cvc_check": "pass",
        "dynamic_last4": null,
        "exp_month": 12,
        "exp_year": 1234,
        "funding": "credit",
        "last4": "1234",
        "metadata": {},
        "name": "MY_EMAIL@GOES.HERE",
        "tokenization_method": null
    },

    "client_ip": "192.168.1.1",
    "created": 1477480453,
    "email": "MY_EMAIL@GOES.HERE",
    "livemode": false,
    "type": "card",
    "used": false
}
```

However, the StripeCard from this project does not contain `email` as a property.. same goes for `ip`. Is this simply something missing or could it be because my form (copied from their site) contains more than it should?

**Comment by jaymedavis** [comment]
Thanks! Wrapper is right - really, it's a typed string builder - no need to bring complexity into that. :). Thanks for the kind words, I have tried hard to make it easy to use. I have a product coming called Checkout.net that will handle all the client/server comm for $10. I can't wait to release - I hope it's easy too. It will be 2-3 lines of code and is designed for Razor out of the gate. 

I've got some things to do with Stripe.net to make sure all this token stuff is covered - so thanks for bringing this up. I will look into it.

**Comment by jaymedavis** [comment]
Email seems like it should be there, IP maybe not ... I'll have to check the server side token json (something else users are asking for a lot, so probably very soon)

**Comment by mortenmoulder** [comment]
@jaymedavis Sounds very cool with the new Checkout.net! Unfortunately I can't use it, as I'm not using ASP.NET MVC as my frontend :(

I think the model on frontend and backend should the same..? So that whatever Stripe sends back as a response, I can parse directly to my backend, and they should include the same amount of information.

**Comment by jaymedavis** [comment]
That would make sense - I'll have to check stripe.com/api/docs for tokens, and then see if maybe some props are missing from the docs.

What is your frontend?

**Comment by mortenmoulder** [comment]
@jaymedavis I'm using Angular with TypeScript. Works pretty nicely together with ASP.NET backend!

**Comment by jaymedavis** [comment]
I bet! I've built sites in angular, but not typescript yet. I do admit I'm jealous - I really like where typescript is heading.

**Comment by mortenmoulder** [comment]
@jaymedavis Yeah I know right! I'm currently still learning TypeScript and Angular, but I'm together with a really good team, who definitely knows how to do it!

Although finding an Angular wrapper (like `angular-stripe`) and then finding typings for it (otherwise TypeScript can't compile)... that's pretty tough. I constantly have to find alternative wrappers which have matching typings, otherwise I'd have to write my own typings (which requires you to understand every single aspect of that wrapper). But overall it's great! haha

**Comment by jaymedavis** [comment]
So, I've stepped through some tests, and checked out the full StripeResponse, but I'm only seeing the ip. The email isn't on the [docs](https://stripe.com/docs/api#create_card_token), as far as I can tell. Can you tell me a little more about how your client sets this up so I can try to replicate?

**Comment by mortenmoulder** [comment]
@jaymedavis Hmm that's odd. I'm simply using their [custom checkout](https://stripe.com/docs/checkout#integration-custom). When the button is clicked and the `handler.open()` is called, the "pay now" popup shows up. It looks like this:

<img src="http://i.imgur.com/TIWRE26.png" />
(sorry about the Danish, I couldn't get it to change language)

Per default it has the "Email address" input at the top. The:

    token: function(token) {
    }

`token` has the information I wrote in the first post.

**Comment by jaymedavis** [comment]
What does your server side code look like where you convert this to a token?

**Comment by jaymedavis** [comment]
I could probably add email - I don't think it would hurt anything. But it might be ideal to make a StripeClientToken that inherits from token to keep it a little cleaner (again, I'm going to have to do this anyway for Checkout.net)

**Comment by mortenmoulder** [comment]
@jaymedavis I simply implement this into my API controller. The token received by Stripe is then caught.
The token received by the backend vs the one sent from frontend is not the same. The backend one (from your library) doesn't match up with the one sent from frontend (the one in OP).

**Comment by jaymedavis** [comment]
Would you mind sharing your controller? I'm curious how you pass the object to your controller - does your controller actually accept a StripeToken and it's parsed for you, or do you use Mapper?

This is more for my learning experience and not so much the issue you are having. As for the email issue, 8 will ping Stripe and ask about it.

**Comment by jaymedavis** [comment]
controller action, obviously not the entire thing :)

**Comment by mortenmoulder** [comment]
@jaymedavis I'll see what I can pull from the project first thing in the morning! As far as I remember, the controller takes a StripeToken yeah.

**Comment by mortenmoulder** [comment]
@jaymedavis I just heard from my friend who was working on it, that he has changed the flow. Instead of receiving a StripeToken in the backend controller, we simply receive a Stripe token ID. Then we send that off to Stripe to grab the token from an id. Something among the lines of `var token = StripeService.GetAsync(tokenId)`.

Apparently the issue was: When we send the frontend token (which we can see includes the data from the first post), the serialization and deserialization of the JSON doesn't go well. However, if we send the same data using something like Postman directly to the backend controller, the data is received fine. I have a feeling this MIGHT be because of a frontend issue, but I highly doubt it, as we can see the raw data is the same as the frontend data, when we receive it in the backend controller.

**Comment by jaymedavis** [comment]
Gotcha, thanks! I'll keep this open until I can dig in to the email field more.
