### ISSUE TITLE
Missing charges within a transfer

### ISSUE THREAD

**Issue by trufun202** [jaymedavis/stripe.net#655]
I'm trying to fetch all of the charges for a given transfer; however, the number of records retrieved in code does not match the number of records I see when exporting the transfer from the Stripe dashboard.

To fetch the charges, I'm doing the following:

```
var hasMore = true;

while (hasMore)
{
    var lastTransactionId = transactions.ToList().Last().Id;

    if (!string.IsNullOrEmpty(lastTransactionId))
    {
        transactionOptions.StartingAfter = lastTransactionId;

        transactions = _BalanceService.List(transactionOptions);                                

        hasMore = transactions.ToList().Count > 0 ? true : false;
    }
    else
    {
        hasMore = false;
    }

    allTranactions.AddRange(transactions.ToList());
}
```

In my case, allTransactions.Count is 448, but there are 547 in Stripe's export.

I thought that maybe I was making too many requests in a short amount of time, but even adding a 30 second sleep between fetches did not help.

Am I missing something?

Thank you!

**Comment by jaymedavis** [comment]
I'm confused when you mention a transfer - is it possible with Stripe to pass a transfer id for the source? That might shoot your list down a tad - do you have more code around this you can share?

**Comment by trufun202** [comment]
I'm fetching the transfers for the current day, then iterating through them:

```
var transferOptions = new StripeTransferListOptions();
transferOptions.Date = new StripeDateFilter() { EqualTo = DateTime.Today };
transferOptions.Limit = 100;

var allTranactions = new List<StripeBalanceTransaction>();

foreach (var transfer in _TransferService.List(transferOptions))
{
	var transactionOptions = new StripeBalanceTransactionListOptions();
	transactionOptions.TransferId = transfer.Id;
	transactionOptions.Limit = 100;
	var transactions = _BalanceService.List(transactionOptions);
	
	var hasMore = true;

	while (hasMore)
	{
		var lastTransactionId = transactions.ToList().Last().Id;

		if (!string.IsNullOrEmpty(lastTransactionId))
		{
			transactionOptions.StartingAfter = lastTransactionId;
			
			transactions = _BalanceService.List(transactionOptions);                                

			hasMore = transactions.ToList().Count > 0 ? true : false;
		}
		else
		{
			hasMore = false;
		}

		allTranactions.AddRange(transactions.ToList());
	}
```

When I compare my list of charges with the Stripe export charges, the first 448 charges are there and the remaining are all missing...   So, it doesn't appear to be certain charges that are being filtered out - it looks like _BalanceService stops returning items.

**Comment by trufun202** [comment]
Nevermind, I figured it out.  I needed to AddRange() to allTransactions for the first fetch.

```
var transactions = _BalanceService.List(transactionOptions);
allTranactions.AddRange(transactions.ToList());  //<--ding ding ding
var hasMore = true;

while (hasMore)
{
...
```

**Comment by jaymedavis** [comment]
Man - it would be nice to build something in to grab the entire list for people. This seems like a lot of work and a bit complicated just to retrieve everything. Nothing against your code at all - just the concept in general.

**Comment by trufun202** [comment]
That would be awesome!
