### ISSUE TITLE
StripeException when providing only token for StripeAccountBankAccountOptions

### ISSUE THREAD

**Issue by phl3x0r** [jaymedavis/stripe.net#660]
I'm not able to update a managed account using only a token for external_account, as defined by the Stripe API

Excepton message: {"Missing required param: external_account[country]."} 

Stacktrace:
   at Stripe.Requestor.ExecuteRequest(HttpRequestMessage requestMessage)
   at Stripe.Requestor.PostString(String url, StripeRequestOptions requestOptions)
   at Stripe.StripeAccountService.Update(String accountId, StripeAccountUpdateOptions updateOptions, StripeRequestOptions requestOptions)
   at JAWService.Models.RequestHandlers.ProfileRequestHandler.UpdateStripeAccount(UpdateStripeAccountRequest req, UserProfile profile) in C:\Users\wisps\Source\Repos\job-auction-app\JAWS\JAWService\Models\RequestHandlers\ProfileRequestHandler.cs:line 284

**Comment by jaymedavis** [comment]
These errors don't come from Stripe.net, they just pass through from Stripe - did you try passing the country again?

**Comment by jaymedavis** [comment]
I would check with Stripe about this one - I don't throw any errors, anywhere. I just report the ones Stripe throws.

**Comment by phl3x0r** [comment]
You should be able to update an account with *either* full information *or* a token. Stripe does not return any errors like this, when called with say, curl (I have verified this).

From https://stripe.com/docs/api#update_account

external_account
optional dictionary
A card or bank account to attach to the account. You can provide either a token, like the ones returned by Stripe.js, or a dictionary as documented in the external_account parameter for either card or bank account creation.

**Comment by jaymedavis** [comment]
You are able to do this with accounts - token and not, to my knowledge. What are you unable to pass?

**Comment by jaymedavis** [comment]
Can you paste your equivalent curl and stripe.net code? (Remove your API key of course)

**Comment by jaymedavis** [comment]
I do not throw any errors in Stripe.net at all - the only way you would get this error is if Stripe throws it.

**Comment by phl3x0r** [comment]
Sure, here you go:

Curl:
curl -X POST -H "Authorization: Bearer <KEY HERE>"  -d 'external_account=<TOKEN HERE>' "https://api.stripe.com/v1/accounts/<ACCOUNT HERE>"

C#:
new StripeAccountService().Update("ACCOUNT_ID", new StripeAccountUpdateOptions()
            {
                ExternalBankAccount = new StripeAccountBankAccountOptions()
                {
                    TokenId = "TOKEN_GOES_HERE"
                }
            });

**Comment by phl3x0r** [comment]
I rolled my own method for the purpose using Rest.Sharp, if you're interested:
`public static StripeUpdateAccountResponse AttachBankAccountFromToken(string accId, string token)
        {

            var client = new RestClient();
            client.BaseUrl = new Uri("https://api.stripe.com/");
            client.Authenticator = new OAuth2AuthorizationRequestHeaderAuthenticator(ConfigurationManager.AppSettings["StripeApiKey"], "Bearer");
            var request = new RestRequest("v1/accounts/{id}", Method.POST);
            request.AddUrlSegment("id", accId);
            request.AddParameter("external_account", token);
            IRestResponse response = client.Execute(request);
            if(response.StatusCode != System.Net.HttpStatusCode.OK)
            {
                throw new StripeException(response.StatusCode, new StripeError(), "Response from Stripe: " + response.ErrorMessage);
            }
            return JsonConvert.DeserializeObject<StripeUpdateAccountResponse>(response.Content);            
        }`

**Comment by jaymedavis** [comment]
Ok, if rolling your own worked, it must be something to do with Stripe.net - probably bank accounts and tokens for some reason. I will dig in to this and thanks for all the troubleshooting.

**Comment by jaymedavis** [comment]
I added a test to see if this was an issue, I could not reproduce your error. See the test [here](https://github.com/jaymedavis/stripe.net/commit/b8e4cbeae93b41952faeaf8b0086fb911a2e8366).

**Comment by phl3x0r** [comment]
Hmm, this is really strange. I  can't reproduce the error anymore with the exact same code. Could this have been a temporary bug in the Stripe API? I don't know...

Anyways, it seems to have disappeared now, so I guess you can close this issue. Sorry for the inconvenience.

**Comment by bradleylinger** [comment]
I'm getting the same error from stripe but not when using tokens.  It's when I try to create the LegalEntity and ExternalBankAccount/ExternalCardAccount objects first and then associate them with the StripeAccountCreateOptions and StripeAccountUpdateOptions. The data for these objects is the same regardless of whether I'm updating or creating. 

Here's the code that pitches the error


` StripeAccount sourceAccountInfo = new StripeAccount();


                    StripeAccountLegalEntityOptions LegalEntity = new StripeAccountLegalEntityOptions()
                    {
                        FirstName = merchAccount.AccountRepresentative.FirstName,
                        LastName = merchAccount.AccountRepresentative.LastName,
                        BirthDay = Convert.ToDateTime(merchAccount.AccountRepresentative.DOB).Day,
                        BirthMonth = Convert.ToDateTime(merchAccount.AccountRepresentative.DOB).Month,
                        BirthYear = Convert.ToDateTime(merchAccount.AccountRepresentative.DOB).Year,
                        AddressLine1 = merchAccount.AccountRepresentative.Address.Street,
                        AddressLine2 = "",
                        AddressCity = merchAccount.AccountRepresentative.Address.City,
                        AddressState = merchAccount.AccountRepresentative.Address.State,
                        AddressPostalCode = merchAccount.AccountRepresentative.Address.Zip,
                        AddressTwoLetterCountry = merchAccount.AccountRepresentative.Address.Country,
                        SSNLast4 = merchAccount.AccountRepresentative.SSNLast4,
                        Type = merchAccount.IsBusiness ? "company" : "individual",
                        BusinessName = merchAccount.IsBusiness ? merchAccount.BusinessName : "",
                        BusinessTaxId = merchAccount.IsBusiness ? merchAccount.BusinessTaxID : ""
                    };

                    StripeAccountBankAccountOptions ExternalBankAccount = new StripeAccountBankAccountOptions();
                    StripeAccountCardOptions ExternalCardAccount = new StripeAccountCardOptions();

                    switch (merchAccount.FinancialSource)
                    {
                        case MerchantFinancialSources.Bank:
                             ExternalBankAccount = new StripeAccountBankAccountOptions()
                            {
                                AccountNumber = merchAccount.BankAccountNumber,
                                RoutingNumber = merchAccount.BankRoutingNumber,
                                Country = "US"
                            };
                            break;
                        case MerchantFinancialSources.DebitCard:
                             ExternalCardAccount = new StripeAccountCardOptions()
                            {
                                Currency = "usd",
                                Number = merchAccount.DebitCardNumber,
                                ExpirationMonth = Convert.ToDateTime(merchAccount.DebitCardExpiration).Month.ToString(),
                                ExpirationYear = Convert.ToDateTime(merchAccount.DebitCardExpiration).Year.ToString(),
                                AddressCountry = "US"
                            };
                            break;
                        default:
                            break;
                    }




                    //Create Mode
                    if (string.IsNullOrEmpty(merchAccount.ID))
                    {
                        #region Create the account at stripe

                        var accountOptions = new StripeAccountCreateOptions();
                        //account.Email = "jayme@yoyoyo.com"; [  // this is required if it is not a managed account. the user is emailed on standalone accounts,
                        // it's only used for reference on managed accounts
                        accountOptions.Managed = true; // set this to true if you want a managed account (email is not required if this is set to true)
                        accountOptions.TosAcceptanceDate = DateTime.Now;
                        accountOptions.TosAcceptanceIp = HttpContext.Current.Request.UserHostAddress;

                        // a few optional settings
                        accountOptions.Country = "US"; // defaults to your country

                        accountOptions.LegalEntity = LegalEntity;
                        accountOptions.ExternalBankAccount = ExternalBankAccount;
                        accountOptions.ExternalCardAccount = ExternalCardAccount;

                        var accountService = new StripeAccountService();

                        sourceAccountInfo = accountService.Create(accountOptions);

                        merchAccount.ID = sourceAccountInfo.Id;
                        merchAccount.StripeAccount = sourceAccountInfo;

                        #endregion
                    }`

Here's the code that works

`//Create Mode
                    if (string.IsNullOrEmpty(merchAccount.ID))
                    {
                        #region Create the account at stripe

                        var accountOptions = new StripeAccountCreateOptions();
                        //account.Email = "jayme@yoyoyo.com"; [  // this is required if it is not a managed account. the user is emailed on standalone accounts,
                        // it's only used for reference on managed accounts
                        accountOptions.Managed = true; // set this to true if you want a managed account (email is not required if this is set to true)
                        accountOptions.TosAcceptanceDate = Convert.ToDateTime(merchAccount.TermsOfServiceAcceptanceDate);
                        accountOptions.TosAcceptanceIp = merchAccount.TermsOfServiceIP;
                        // a few optional settings
                        accountOptions.Country = "US"; // defaults to your country

                        accountOptions.LegalEntity = new StripeAccountLegalEntityOptions()
                        {
                            FirstName = merchAccount.AccountRepresentative.FirstName,
                            LastName = merchAccount.AccountRepresentative.LastName,
                            BirthDay = Convert.ToDateTime(merchAccount.AccountRepresentative.DOB).Day,
                            BirthMonth = Convert.ToDateTime(merchAccount.AccountRepresentative.DOB).Month,
                            BirthYear = Convert.ToDateTime(merchAccount.AccountRepresentative.DOB).Year,
                            AddressLine1 = merchAccount.AccountRepresentative.Address.Street,
                            AddressLine2 = "",
                            AddressCity = merchAccount.AccountRepresentative.Address.City,
                            AddressState = merchAccount.AccountRepresentative.Address.State,
                            AddressPostalCode = merchAccount.AccountRepresentative.Address.Zip,
                            AddressTwoLetterCountry = merchAccount.AccountRepresentative.Address.Country,
                            SSNLast4 = merchAccount.AccountRepresentative.SSNLast4,
                            Type = merchAccount.IsBusiness ? "company" : "individual",
                            BusinessName = merchAccount.IsBusiness ? merchAccount.BusinessName : "",
                            BusinessTaxId = merchAccount.IsBusiness ? merchAccount.BusinessTaxID : ""
                        };

                        switch (merchAccount.FinancialSource)
                        {
                            case MerchantFinancialSources.Bank:
                                accountOptions.ExternalBankAccount = new StripeAccountBankAccountOptions()
                                {
                                    AccountNumber = merchAccount.BankAccountNumber,
                                    RoutingNumber = merchAccount.BankRoutingNumber
                                };
                                break;
                            case MerchantFinancialSources.DebitCard:
                                accountOptions.ExternalCardAccount = new StripeAccountCardOptions()
                                {
                                    Currency = "usd",
                                    Number = merchAccount.DebitCardNumber,
                                    ExpirationMonth = Convert.ToDateTime(merchAccount.DebitCardExpiration).Month.ToString(),
                                    ExpirationYear = Convert.ToDateTime(merchAccount.DebitCardExpiration).Year.ToString()
                                };
                                break;
                            default:
                                break;
                        }

                        var accountService = new StripeAccountService();

                        sourceAccountInfo = accountService.Create(accountOptions);

                        merchAccount.FullAccountInfo = sourceAccountInfo;

                        #endregion
                    }`

It's not a show stopper for me but it's interesting that Stripe can't see my country when I create child objects first.
