### ISSUE TITLE
The proration line items do not seem to be populated along with the Invoice LineItems

### ISSUE THREAD

**Issue by pravse** [jaymedavis/stripe.net#663]
It shows correctly on Stripe itself. However, via Stripe.Net, I only get the Subscription lineitems and not the  proration lineitems corresponding to the billing period. Has anyone else run into this?

**Comment by jaymedavis** [comment]
Can you share your code? Are you paging? Is there any special options Stripe has in the docs to return prorated and regular line items?

**Comment by pravse** [comment]
Code is ultra simple. 

            var stripeInvoice = new StripeInvoiceService().Get(invoiceId);

The invoice should have exactly 1 subscription lineitem and 1 proration lineitem. Both show on Stripe's UI. But the stripeInvoice.StripeInvoiceLineItems.Data has only 1 item (the subscription lineitem).  HasMore is false.

**Comment by jaymedavis** [comment]
Have you attempted the line item service and listing from there to see if it's different?

**Comment by pravse** [comment]
Yes. I tried this as a workaround.

            var lineItemOptions = new StripeInvoiceItemListOptions
            {
                CustomerId = stripeInvoice.CustomerId
            };
            var stripeInvoiceItems = new StripeInvoiceItemService().List(lineItemOptions);

I get back only 1 line item. It is _not_ the subscription line item in the stripeInvoice. Instead, it is a proration line item which is from a previous month. I would expect to get back all the invoice line items across multiple invoices.

**Comment by jaymedavis** [comment]
I would verify with stripe that using their API list endpoint is supposed to return prorated items first. If it is, I will write a test to figure this out.
