### ISSUE TITLE
Currency property missing in StripeCreditCardOptions

### ISSUE THREAD

**Issue by gm-prateekbahl** [jaymedavis/stripe.net#665]
In order to associate a card to a managed account as an external account, currency is required.  The only way to add multiple debit cards is to generate the card token, and assign it to the managed account.

**Comment by jaymedavis** [comment]
Are you sure you're not using `StripeCardCreateOptions`? StripeCreditCardOptions is for recipients - and I really need to clean this up 😞

**Comment by gm-prateekbahl** [comment]
I'm using `StripeTokenService` to get the card token.  The service uses `StripeTokenCreateOptions` object which has a property `Card` [Type: `StripeCreditCardOptions`].

I thought `StripeCardCreateOptions` is for recipients since that gets used with `StripeCardService` which only deals with customers, and recipients.

**Comment by jaymedavis** [comment]
This is on master - it will go out with the next release.
