### ISSUE TITLE
Re-parsing of dates.

### ISSUE THREAD

**Issue by 0xdeafcafe** [jaymedavis/stripe.net#668]
Stripe returns UNIX timestamp dates, but the `StripeDateTimeConverter` outputs the date in the `\Date(unix)\` format. 

I pass the raw model from this library out of the API, so when I try and parse it back on another service it has issues reading the date back in, causing all the dates to be wrong. Would you be open to the possibility of outputting the raw Unix timestamp like stripe does to skirt this issue?

**Comment by jaymedavis** [comment]
Read about the StripeResponse on the readme - the raw Stripe output is passed back to you on every entity.

**Comment by jaymedavis** [comment]
You can parse the entire thing as json, then just grab the property if you want - that would probably be easiest.

**Comment by 0xdeafcafe** [comment]
Ah right. I didn't notice that, thank's for the heads up, works perfectly.

**Comment by jaymedavis** [comment]
Great! What other service are you using out of curiosity?

**Comment by 0xdeafcafe** [comment]
Oh sorry, slight misunderstanding I think. I was talking about micro-services architecture, and our billing service returns the raw json from stripe. That then get's parsed into your Stripe.net models when requested from another service.
