### ISSUE TITLE
Can not change card for Account

### ISSUE THREAD

**Issue by hsmith825** [jaymedavis/stripe.net#670]
Hi Jayme,

In UpdateAccount, I tried to change the ExternalCardAccount.  When I attempt to change I get the error message: "Invalid request (check your POST parameters): unable to determine value for parameter: external_account".  Stripe ducumentation says I should be able to make the change.  This is a Managed account.
Here is my c# snippet:
var myAccount = new StripeAccountUpdateOptions();
myAccount.ExternalCardAccount = new StripeAccountCardOptions()
                {
                    TokenId = card_token,
                    Currency = defaultcurrency
                };
            }
            StripeAccount response;
            try
            {
                var accountService = new StripeAccountService();
                response = accountService.Update(Accountid, myAccount);
            }

I even tried to change using Cards but that only creates a new customer card.  Stripe's documentation even says I should be able to make the change this way.  My Account were all created wiwth either Bank accounts are cards using accountService.Create and other parameters are updated without a problem.

Suggestions are appreciated.

Thanks!
Howard

**Comment by hsmith825** [comment]
This item should really be titled "No external accountas outlined at https://stripe.com/docs/api/curl#external_accounts.  Speccifically, for managed accounts I use create cards for accounts.
Thanks!

**Comment by jaymedavis** [comment]
Have you tried this without passing the currency? Maybe pass currency when creating the token?

**Comment by jaymedavis** [comment]
Also, is this a managed account?

**Comment by jaymedavis** [comment]
I'm working with Stripe on this - something is wrong. Will update after, I was able to duplicate the problem in a test.

**Comment by jaymedavis** [comment]
Ok, check out this [commit](https://github.com/jaymedavis/stripe.net/commit/39ca17ffe870b85c62d44043eaeeff29dfa690a4), I wrote a test that shows you how to do this properly. The tricks are this:
1) When you set the currency, you need to set this on you token, not on the account update. The only thing you want on your account update is the TokenId.
2) You have to use a debit card.

You should be all set!

**Comment by hsmith825** [comment]
Yes, I have tried this without the currency.  In answer to another email, this is a managed account.  I discovered I need to use External Account APIs (https://stripe.com/docs/api/curl#account_create_card).  This is not implemented in Stripe.neetm so I implemented with  Webrequest with the end point https://api.stripe.com/v1/accounts/{ACCOUNT_ID}/external_accounts <https://api.stripe.com/v1/accounts/%7bACCOUNT_ID%7d/external_accounts> .  Stripe has a bug that will not accept currency but will flag it when added as ab illegal parameter.  I sent them this information last night.

 

Anotherr topic.  I am having trouble contacting bountySource.  Can you help with the email of a contact their.  I sent an email to support@bountysource.com <mailto:support@bountysource.com> .

 

Thanks!

Howard

**Comment by hsmith825** [comment]
Hi Jayme,

 

Thanks!!!

 

Your solution worked.  There is one other issue relating to the solution that you may be able to help with.  Currently Stripe.js does not provide a way to set currency on the token.   Can you mention this to your contacts at Stripe. I had to use .net Token feature on my server.

 

Thanks!

Howard

**Comment by hsmith825** [comment]
stripe.js now has currency as an option

**Comment by jaymedavis** [comment]
awesome - was this a new release, or did you find when it became available?

**Comment by hsmith825** [comment]
I think they just put it in.  It is not documented and I did not work when I tried it a couple of days ago.

 

One question, when will you support method on transfer so users of managed accounts can use instant?  https://stripe.com/docs/api#create_transfer

 

Thanks!
