### ISSUE TITLE
Adding Stripe.net as Nuget Package on Xamarin Studio

### ISSUE THREAD

**Issue by chrux** [jaymedavis/stripe.net#671]
I'm trying to add Stripe.net on XS and I have not been able, I receive this error

```Attempting to gather dependency information for package 'Stripe.net.6.11.0' with respect to project '', targeting '.NETPortable,Version=v4.5,Profile=Profile259'
Attempting to resolve dependencies for package 'Stripe.net.6.11.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Stripe.net.6.11.0'
Resolved actions to install package 'Stripe.net.6.11.0'
For adding package 'Stripe.net.6.11.0' to project '' that targets 'portable45-net45+win8+wp8+wpa81'.
Install failed. Rolling back...
Package 'Stripe.net.6.11.0' does not exist in project ''
Package 'Stripe.net.6.11.0' does not exist in folder '~/-xamarin/packages'
Could not install package 'Stripe.net 6.11.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Any idea why?

I am using XS 6.1.1 (build 17)

**Comment by jaymedavis** [comment]
hmm... this may be due to stripe.net using profile 111. Any reason you are using 259, specifically? None the less, I believe this problem (and many others) will be solved when the project is converted to .net standard. Adding @flagbug, as he can probably help with this one - or offer an explanation. :)

**Comment by flagbug** [comment]
Yeah, Profile 111 and 259 aren't compatible.

@chrux Are you targeting Windows Phone 8.0? If not, you should be able to change your target to Profile111

**Comment by chrux** [comment]
I managed to overcome the issue, but I have to manually enter the lib in the `packages.config` file, if I use the package window did not work.
