### ISSUE TITLE
Invalid source data returned from List Functions on Cards and Probably bank accounts

### ISSUE THREAD

**Issue by brentdavid2008** [jaymedavis/stripe.net#675]
I'm not sure when this got added but stripe now requires a query string to get the correct objects back from their api

For bank accounts: https://stripe.com/docs/api#customer_list_bank_accounts
For Credit Cards: https://stripe.com/docs/api#list_cards

You have the URLs right it looks like, but it's no longer just one url with {allTheOtherStuff}/Sources

it should be {allTheOtherStuff}/Sources?object=card or {allTheOtherStuff}/Sources?object=bank_account.

I can work around this by doing my own where clause, but it's still improper. :)

![cardservice](https://cloud.githubusercontent.com/assets/7902547/20347574/6d036ff6-abc7-11e6-83bd-b17309cd6081.PNG)
![bankaccount](https://cloud.githubusercontent.com/assets/7902547/20347575/6d03cd16-abc7-11e6-954b-22d1df4f5174.PNG)

**Comment by brentdavid2008** [comment]
This is also related to #649 with it being the incorrect type, but it didn't look like that fixed actually returning the wrong object from the wrong List Calls. if it does, feel free to close this.

**Comment by jaymedavis** [comment]
It's not fixed in 6.11. Thanks for the detail, I need to add a note to the readme requesting everyone post the Stripe doc links for their question.

I wasn't aware of this change - did this recently pop up for you?

**Comment by brentdavid2008** [comment]
I just noticed it to day as i was testing a new implementation in one of our apps where I update an existing card and not just blindly create new ones each time.  It was a customer that only had a bank account, and i found it curious that it had one item in the list, and after seeing what you see in the screenshots, i submitted this.  I was on an api version from clear back in march, so it would seem this has been there a while.

I also attempt to match on 'last 4' of card to last 4 provided, and update it based on that.  I don't know much about banking, but i would assume that someones last for of a bank account could eventually collide with the last 4 of a credit card.  Odds of the _same customer_ having both the bank account and credit cards with last 4 being the same are slim, but still...you know how it goes...the code currently allows for something like that to happen. lol

This might be better solved in the future integration test, so the build fails if the 'list' functions don't return all the same type you requested from stripes actual API.  Then you'd at least know the API changed.  Unfortunate there's no other 'nice' way of knowing what changes _they've_ made vs code that just has a bug in it.
