### ISSUE TITLE
Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later.

### ISSUE THREAD

**Issue by srinivas1612** [jaymedavis/stripe.net#678]
Getting following exception.
 "Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later."

I Followed all the steps which stripe support mentioned [here ](https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#dotnet). But still facing issue.  Thank You

**Comment by jaymedavis** [comment]
This is all server related and account related, there's nothing I can do. :(

Contact Stripe.
