### ISSUE TITLE
NuGet package 6.11.0 contains assembly for 6.10.0

### ISSUE THREAD

**Issue by Lemonadegit** [jaymedavis/stripe.net#679]
The Stripe.net NuGet package for 6.11.0 (https://www.nuget.org/packages/Stripe.net/) contains the assembly for 6.10.0 and has not been updated.

**Comment by jaymedavis** [comment]
Yep, I noticed this mistake too. I'm doing a lot of work on the build server so this will never happen again - I'm going to fix it by pushing a small 6.12, I don't believe I can edit existing deploys?

**Comment by Lemonadegit** [comment]
Yeah you can't edit an already added package. Even if you could, not sure you would want to as that would cause fragmented versions. Pushing out 6.12.0 would be best.

**Comment by jaymedavis** [comment]
Good eye. :)
