### ISSUE TITLE
Retrieving token returns null bank account fields

### ISSUE THREAD

**Issue by PengyuanZhao** [jaymedavis/stripe.net#680]
The following code returns a token object but all the bank account fields are NULL, while calling the Stripe API directly returns correct values.

```
var tokenService = new StripeTokenService();
StripeToken stripeToken = tokenService.Get(*tokenId*);
```

Thanks for any help.

**Comment by PengyuanZhao** [comment]
Used `StripeResponse` as a work-around.

**Comment by jathomas9** [comment]
I am still seeing this issue. Will this be fixed, or are we just to use Stripe-Response as a work around.
