### ISSUE TITLE
Support for .NET core

### ISSUE THREAD

**Issue by daigok** [jaymedavis/stripe.net#681]
Support using Stripe.net from applications built for .NET Core.

**Comment by jaymedavis** [comment]
Working on this now. Should have something soon.  #581

**Comment by jaymedavis** [comment]
actually - have you tried dropping in 

  "dependencies": {
        "Stripe.net": "6.11.1",

? Seems to be fine for me today.

**Comment by jaymedavis** [comment]
this is all done 👍
