### ISSUE TITLE
Error: New-line characters in header values must be followed by a white-space character.

### ISSUE THREAD

**Issue by Logismico** [jaymedavis/stripe.net#682]
I'm receiving this error every time I try to call any Strip.Net function:

                var myCustomer = new StripeCustomerCreateOptions();
                myCustomer.Email = customer.OwnerEmailAddress;
                myCustomer.Description = customer.OwnerFullName + " - " + customer.TeamName;

                myCustomer.PlanId = Constants.GetEnumValueFromDescription<SubscriptionPlans>(ConfigurationManager.AppSettings["SubscriptionPlanKey_Default"].ToString()).ToString();

                var customerService = new StripeCustomerService(ConfigurationManager.AppSettings["StripeApiKey"].ToString());

                StripeCustomer stripeCustomer = customerService.Create(myCustomer);

**Comment by jaymedavis** [comment]
what platform are you on?

**Comment by Logismico** [comment]
ASP.Net, Windows.

Stefanos Tsesmetzis
Logismico LLC
stefanos.tses@logismico.com
917-214-0938

**Comment by jaymedavis** [comment]
Well, this is new to me - have never heard this before. Perhaps a culture issue? What culture are you using in code? What version of asp.net?

**Comment by Logismico** [comment]
I'm using asp.net 4.5.2 in US.

I suspect Newsoft Json.

Once I updated from nuget I had other issues too.

Stefanos Tsesmetzis
Logismico LLC
stefanos.tses@logismico.com
917-214-0938

**Comment by Logismico** [comment]
Jayne,

I downgraded to Stripe.Net 6.4 and it works fine again. 6.11 has the issue.


Stefanos Tsesmetzis
Logismico LLC
Software Development, IT Consulting & Support

e: stefanos.tses@logismico.com
c: 917-214-0938
w: www.logismico.com

**Comment by Logismico** [comment]
Jayne,

Any chance that can be fixed.

I don't want to risk get dependent on an old version of Stripe.Net.

Thanks,

**Comment by jaymedavis** [comment]
Absolutely - I'm working on a netcore build of Stripe.net now, so I think it _might_ help solve your issue. NuGet is on the latest version possible. Are you using NuGet elsewhere? Stripe.net operates off their last release.

**Comment by jaymedavis** [comment]
If you want to help, can you upgrade version by version and tell me which version it first breaks in? That would help me narrow it down, possibly.

**Comment by Logismico** [comment]
I just did that. It breaks on any version above 6.4.

I'm using NuGet on my application.

Thanks,
Stefanos

**Comment by wislon** [comment]
At the risk of a "me too"... I'm running Stripe.net 6.8, and I'm seeing the same exception, but not all the time. I only seemed to crop up within the last couple of days tho, which made me think it might be related to Stripe... 

* If I run nuget version __6.6.0__ on  Windows (10, targeting .net 4.5) it works perfectly. I did a test creating 50 customers with credit cards. it worked every single time, without complaint. This was in a LinqPad script.

* Run exactly the same code with Stripe.net nuget version __6.8.0__ on __Windows__ (IIS Express web service api application, windows 10, targeting .net 4.5), it works perfectly every single time too.

* If I publish that IIS web service application to __Azure__ (into an app service), it fails intermittently with this error. Not every time tho, which has made it very difficult to track down what and why it occurs. 

I thought maybe the Stripe guys had changed something at their end and the error was bubbling back up through your library somehow.

The only thing I can say for sure is that on Azure it's flaky, but on regular Windows it isn't. 

Exception message: `New-line characters in header values must be followed by a white-space character.`

Here's a stack trace:
```
at System.Net.Http.Headers.HttpHeaders.CheckInvalidNewLine(String value)
at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)  at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
 at Stripe.Requestor.GetRequestMessage(String url, HttpMethod method, StripeRequestOptions requestOptions, Boolean useBearer)
 at Stripe.Requestor.PostStringAsync(String url, StripeRequestOptions requestOptions, CancellationToken cancellationToken)
    at Stripe.StripeCustomerService.<CreateAsync>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                at Payment.Services.CreditCard.Stripe.StripeService.<RegisterCreditCardForUser>d__8.MoveNext() in C:\\projects\blah

```

**Comment by jaymedavis** [comment]
Thanks for all the research! Could you try the same test with 6.12.0? Since it's netstandard and not a PCL, I'm curious if it will solve the problem. If not, perhaps I just need a space after any new lines in my headers. :)

**Comment by Logismico** [comment]
I'll test it.

Meanwhile, put that space there just in case. 8-)

Stefanos

**Comment by Logismico** [comment]
Sorry man. Same error...

Stefanos Tsesmetzis
Logismico LLC
Software Development, IT Consulting & Support

e: stefanos.tses@logismico.com
c: 917-214-0938
w: www.logismico.com

**Comment by mscrivo** [comment]
I can also reproduce this problem reliably with 6.12.0.  With the previous version we were using (5.3) it works perfectly.

**Comment by last1here** [comment]
I was having the same issue as explained above, I managed to figure out the cause in my case and it was down to changing the `JsonConvert.DefaultSettings` and setting `Formatting = Formatting.Indented` removing this resolved my issue.

**Comment by Logismico** [comment]
I confirm it works.

Thanks Ashley.

Stefanos Tsesmetzis
Logismico LLC
Software Development, IT Consulting & Support

e: stefanos.tses@logismico.com
c: 917-214-0938
w: www.logismico.com

**Comment by jaymedavis** [comment]
This is probably something to do with the client.cs file.

**Comment by wislon** [comment]
...and I've just confirmed this works for me too. 

Seems I was getting it intermittently because I had a routine which turned the `Formatting.Indented` ON at some point (non deterministically). So my Stripe registrations would work until this other thing ran.

Thanks so much @last1here and everyone 👍

**Comment by mscrivo** [comment]
Should this really have been closed?  The above is a workaround only, not really a fix.  What if we really want the default formatting to be Indented and it's set at a high level like WebApiConfig?  That would mean we'd have to temporarily turn it off for any stripe.net code and then back on afterwords, which can lead to a hacky mess.

**Comment by jaymedavis** [comment]
yeah, that's fair. what is your stack/environment? I need to reproduce this.

**Comment by mscrivo** [comment]
WebApi project using latest version of WebApi (2.x) on .NET 4.6.2.  In app_start folder we have a WebApiConfig.cs that calls something like this:

```C#
        public static void Register(HttpConfiguration config)
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                Formatting = Formatting.Indented
            };
        }
```

let me know if that's enough to go on

**Comment by richardlawley** [comment]
Having problems building the source at the moment and not enough time to fix that, but looking through the source I guess this was probably introduced by 1bbbfd73d050bbcc26c17111ffd0deb99a72e5f8 - the value for `X-Stripe-Client-User-Agent` is now serialized by Json.Net using the global options - if global options are Formatting.Indented then this value will include newlines.

The fix is to change line 49 of Infrastructure\Client.cs to 

    return JsonConvert.SerializeObject(values, Formatting.None);

This also requires that `getSystemInformation` does not include a newline, which looks to be correct.

**Comment by jaymedavis** [comment]
thanks!

**Comment by wislon** [comment]
Thanks guys! 👍
