### ISSUE TITLE
Set (Cancel_at_period_end) on Subscription Create.

### ISSUE THREAD

**Issue by GautamNagraj** [jaymedavis/stripe.net#685]
We use stripe for payment in our project and it's functionality is also better than other. 

We need to set ( Cancel_at_period_end : true or false ) at the subscription create and subscription update time. 

How it's possible ?

**Comment by jaymedavis** [comment]
If you want to cancel the subscription on period end, you need to call the subscription services cancel method. You will need to pass that your customer and subscription id, and then use the cancelAtPeriodEnd flag (set it to true). You can do this even when you create your sub/customer - just don't forget the flag. 👍
