### ISSUE TITLE
Stripe Api Issue

### ISSUE THREAD

**Issue by Avinash1992** [jaymedavis/stripe.net#687]
I m not able to fetch stripe access token using api key

**Comment by jaymedavis** [comment]
What version/platform/line of code you're using?

**Comment by jaymedavis** [comment]
Are you trying to fetch the key server side? Client side is probably what you want. Checkout server.js or checkout.net

**Comment by jaymedavis** [comment]
I'm assuming you got this worked out, reopen if not. Would love any feedback for others to learn from. :)
