### ISSUE TITLE
Jayme,

### ISSUE THREAD

**Issue by Logismico** [jaymedavis/stripe.net#688]
Jayme,

The .List returns all subscriptions or just the active ones like the API works?

Also, what the best way to get the latest active subscription for a customer?

Great job man,
Thanks.

**Comment by jaymedavis** [comment]
Most list return everything, unless you filter them with an options object. Otherwise, you just need to be aware of paging. I think the subscription is on the customer, but I could be mistaken.

**Comment by Logismico** [comment]
Dude, your support is amazing!!!

I know about StripeListOptions but this is only for paging.
The Stripe API has an optional parameter "status" to filter.
By default it returns only active subscriptions.

From the API doc:

"By default, returns a list of subscriptions that have not been canceled.
In order to list canceled subscriptions, specify status=canceled. "

status optional

The status of the subscriptions to retrieve. One of: trialing, active,
past_due, unpaid, canceled, or all. Passing in a value of canceled will
return all canceled subscriptions, including those belonging to deleted
customers. Passing in a value of all will return subscriptions of all
statuses.



That's why i want to make sure what .List returns.

Stefanos Tsesmetzis
Logismico LLC
Software Development, IT Consulting & Support

e: stefanos.tses@logismico.com
c: 917-214-0938
w: www.logismico.com

**Comment by jaymedavis** [comment]
Ah, there it is. :)

So it returns the list of subscriptions that haven't been canceled. Stripe.net actually has no hidden logic of it's own - everything just passes through to Stripe and back to the user - I don't generate a single exception on my own. 👍

**Comment by jaymedavis** [comment]
and thanks for the kind words!

**Comment by Logismico** [comment]
Thanks Jayme,

I don't need the cancelled ones but others may need it.


Stefanos Tsesmetzis
Logismico LLC
Software Development, IT Consulting & Support

e: stefanos.tses@logismico.com
c: 917-214-0938
w: www.logismico.com
