### ISSUE TITLE
Not generating invoice automatically after subscription updated

### ISSUE THREAD

**Issue by arielnaveenchopra** [jaymedavis/stripe.net#689]
When I am trying to update the subscription then it is updating it in stripe but the invoice is not generating.
Also When I used the custom code to create invoice for customer then it showing error that "nothing to invoice for customer"

**Comment by jaymedavis** [comment]
I have some tests that wait for it, you might have to do the same thing. This is not something Stripe.net controls though - contact Stripe if it's still not generating.
