### ISSUE TITLE
When passing 3D Secure token with Customer id charges not create getting exception

### ISSUE THREAD

**Issue by periyasamyNATL** [jaymedavis/stripe.net#693]
Hi                   

     Any transactions, we are trying to bring under one customer id. Even though same customer used different card details. We are assigned myCharge.SourceTokenOrExistingSourceId = *tokenId or existingSourceId*;. It is working fine in the normal flow (without 3D secure) while assigning tokenId. In 3D secure case we are assigning the 3D secure response token but the transaction is not mapped with same customer Id. 
If we are pass the customer Id instead of 3D secure response token then 3D secure is not working. In this scenario we are getting the exception Customer cus_9hT82PZ8KTNTAd does not have a linked source with ID tok_19O5rHJSgNCWX74mUs0nXfCJ
Our objective is 3D secure should work properly and one customer’s all transaction should come under one customer id only.

**Comment by jaymedavis** [comment]
Contact stripe support.
