### ISSUE TITLE
Newtonsoft.Json Dependency Error

### ISSUE THREAD

**Issue by eigenheerc** [jaymedavis/stripe.net#694]
When updating Stripe.net nuget package v.6.12.0 it gives me the following error:

Attempting to resolve dependency 'Newtonsoft.Json (≥ 9.0.1)'. 'Stripe.net' already has a dependency defined for 'Newtonsoft.Json'.

I currently have Newtonsoft.Json nuget package v.9.0.1 installed

**Comment by eigenheerc** [comment]
In the meantime I manually updated to Stripe.net v6.11.1 and it worked fine but the most recent version doesn't.

**Comment by Eonasdan** [comment]
yup me too

![image](https://cloud.githubusercontent.com/assets/1006516/21086530/68d0e476-bfeb-11e6-9353-f80df4266d53.png)

**Comment by Eonasdan** [comment]
@eigenheerc looks like my issue might be that I had json.net in both my web project and my service project with different version numbers. Updating the web project's version of json.net looks like it might have fixed it for me

**Comment by eigenheerc** [comment]
I still get the same error...

**Comment by jaymedavis** [comment]
managing this from #697
