### ISSUE TITLE
Passed in livemode API key but authorization code only supports returning test keys

### ISSUE THREAD

**Issue by gdubs** [jaymedavis/stripe.net#696]
Hi,

I suddenly started getting this error even if the site account that I'm using uses the test client and publishable keys and so is my test account that I want to connect to uses test as well.

Error: "invalid_grant"
ErrorSubscription: "Passed in livemode API key but authorization code only supports returning test keys"

I also tried resetting my secret and publishable keys as well on test. But it still does the same thing. 

Thoughts on this?

**Comment by jaymedavis** [comment]
Not a stripe.net issue - sorry.

**Comment by dinzy17** [comment]
You are using live keys but Development client id.. check your client id in oauth..
