### ISSUE TITLE
Getting Fingerprint null from token.Card

### ISSUE THREAD

**Issue by JavedAppdevelopment** [jaymedavis/stripe.net#698]
Hey I am getting null fingerprint while create a token using StripeTokenService.

Here is my code that creates a token

       public async Task<CardDetails> TokenizeCardAsync(int expiryMonth, int expiryYear, string     cvv,string cardRawNameCaptured, CreditCardTokenizeSimulationMode mode, string cardNumber = null)
        {
            bool useLivePublishableKey = cardNumber != null;
            StripeConfiguration.SetApiKey(useLivePublishableKey
                ? _securityManager.StripeLivePublishableKey
                : _securityManager.StripeTestPublishableKey);

            StripeTokenCreateOptions option = new StripeTokenCreateOptions
            {
                Card = new StripeCreditCardOptions
                {
                    Number = cardNumber ?? GetTestCreditCardNumber(mode),
                    ExpirationMonth = expiryMonth.ToString(),
                    ExpirationYear = expiryYear.ToString(),
                    Cvc = cvv,
                    Name = cardRawNameCaptured
                }
            };

            try
            {
                StripeToken token = await new StripeTokenService().CreateAsync(option);

                return new CardDetails
                {
                    CardBrand = token.StripeCard.Brand,
                    CardExpiryMonth = int.Parse(token.StripeCard.ExpirationMonth),
                    CardExpiryYear = int.Parse(token.StripeCard.ExpirationYear),
                    ProviderCardFingerprint = token.StripeCard.Fingerprint,
                    ProviderCardId = token.StripeCard.Id,
                    ProviderToken = token.Id,
                    CardLast4 = token.StripeCard.Last4
                };
            }
            catch (StripeException ex)
            {
                throw new PaymentGatewayException(ex.StripeError.Code, ex.StripeError.Message);
            }
        }

 token.StripeCard.Fingerprint is null.

How can I get the Fingerprint?

Thanks in advance.

**Comment by jaymedavis** [comment]
This [test](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net.Tests.xUnit/tokens/creating_a_card_token.cs) passes -

What platform are you using? Environment?
