### ISSUE TITLE
Trying to update to 5.3.0

### ISSUE THREAD

**Issue by cadilhac** [jaymedavis/stripe.net#703]
Because of Stripe wanting me to update an old project (for TLS), I have updated to 5.3.0 (I'm in a .Net 4 project) which is the max version I can update to.
There is only one problematic line:

`myCharge.TokenId = ......;`

myCharge is StripeChargeCreateOptions.
I can't find how I can set the token since this property disappeared. In a more recent project with an up to date Stripe.Net I have SourceTokenOrExistingSourceId, but not in 5.3.0.

Thanks for your help.

**Comment by jaymedavis** [comment]
In that version, I believe you supply `StripeSourceOptions` -

Try:
```
myCharge.Source = new StripeSourceOptions { TokenId = ...... }; 
```

Re-open if that doesn't solve the problem. 👍

**Comment by cadilhac** [comment]
ok I can try that.
However, now that the code can compile, a strange error occurs in VS2010 (MVC3 project).
Just before the compilation, no errors were detected and Stripe.Net classes were underlined in blue. As soon as I compile, errors appear on all Stripe identifiers. Even the "using Stripe" is underlined in red.

I have tried to clean everything, delete bin/obj folders, reinstall the Stripe.Net lib. Nothing works. Any idea?

**Comment by jaymedavis** [comment]
Can you take a lot at the error list window and let me know the reason?

**Comment by cadilhac** [comment]
Nothing explicit:

error CS0246: The type or namespace name 'Stripe' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'StripeCharge' could not be found (are you missing a using directive or an assembly reference?)

The first error is for the "using Stripe;" line. The second error is for an unknown type from your library (since it seems to ignore the lib).

**Comment by jaymedavis** [comment]
>  reinstall the Stripe.Net lib

Can you tell me how you are doing this? Also check your references, Stripe.net probably has a bang or is not listed.

**Comment by cadilhac** [comment]
I remove it from the nuget UI. Then I restart VS. I open the nuget console and run:

Install-Package Stripe.net -Version 5.3.0

Just after than, intellisense seems to show that Stripe is recognized. I can hover the Stripe classes and I get the information. But as soon as I compile, it loses Stripe.
The dll is in the references. It correctly references xxxxxx\packages\Stripe.net.5.3.0\lib\Stripe.net.dll

**Comment by cadilhac** [comment]
I think I get it. By converting the project to VS2015, I see another error message:

The primary reference "Stripe.net, Version=5.3.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".

So it seems that in order to fix TLS I need to grab Stripe>5.1.1 but no version is able to handle .Net 4.0?

**Comment by cadilhac** [comment]
I found earlier posts here where it seems upgrading to .Net 4.5 is the only solution. But it will be very difficult for me, as it breaks many things (I also use other libraries that are difficult to upgrade).
I read from you:

> Feel free to contact me via email if you need to get a version working and cannot upgrade to 4.5.

I don't know what your email is, but is it still possible to get a .Net 4 version of the lib so that I can just fix this TLS thing?

**Comment by jaymedavis** [comment]
.net 4 does not have support for TLS 1.2. I'm afraid upgrading is your only option.

**Comment by jaymedavis** [comment]
Older versions were built with .net 4 - 5.1.1 sounds familiar, but you can cruise through the releases to be sure.
