### ISSUE TITLE
"Destination" Filter Missing In StripeTransferListOptions

### ISSUE THREAD

**Issue by reddyBell** [jaymedavis/stripe.net#704]
The "destination" parameter is missing in [StripeTransferListOptions](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Services/Transfers/StripeTransferListOptions.cs) as per the documentation [here](https://stripe.com/docs/api#list_transfers-destination)

This is blocking for me at the minute as we are in a hurry to only retrieve transfers to bank accounts (this would cause a pagination headache if we don't filter at the Stripe level)

Unfortunately I don't have the environment to send what seems like a quick pull request where I am .

**Comment by reddyBell** [comment]
Wow, the move to .NET Core means I can't even fork the project while awaiting the official patch. Can't reference a .NET Core project from a project using the full framework.

**Comment by reddyBell** [comment]
Ok took me a while but finally figured that a workaround is to create a class inheriting from StripeTransferListOptions with the extra property so that everybody can enjoy christmas.

**Comment by jaymedavis** [comment]
You are all set - as soon as the build server is done, 7.0.1 should be available on nuget. Merry Christmas. :)

**Comment by reddyBell** [comment]
Many thanks, Merry Christimas to you too !
