### ISSUE TITLE
StripeAccountUpdateOptions constructor broken?

### ISSUE THREAD

**Issue by Jarrette** [jaymedavis/stripe.net#713]
I'm getting a null reference error on this line:

Dim thisAccountUpdater As New StripeAccountUpdateOptions 

I'm mystified.

**Comment by Jarrette** [comment]
Sorry, this was a visual studio issue, the error was in the next line but VS told me it was the previous line.

**Comment by jaymedavis** [comment]
no worries. from on vs user to another, we know how it goes sometimes 👍
