### ISSUE TITLE
Get Credit Card Brand?

### ISSUE THREAD

**Issue by kartikbb** [jaymedavis/stripe.net#714]
Can we use Stripe .NET to get the credit card brand of the card without calling the stripe service? 

Like in the Stripe library in Xamarin Component, we can get type by doing this:

`new Card { Number = cardNumber }.Type`

**Comment by jaymedavis** [comment]
This doesn't really fit the mold of stripe.net, so I'm going to punt. :( 

I hope you've found a workaround!
