### ISSUE TITLE
Duplicate [JsonProperty("source")] in StripeChargeCreateOptions

### ISSUE THREAD

**Issue by boraturant** [jaymedavis/stripe.net#716]
Duplicate [JsonProperty("source")] in StripeChargeCreateOptions

couses Json serialization error

[JsonProperty("source")]
public string SourceTokenOrExistingSourceId { get; set; }

[JsonProperty("source")]
public SourceCard SourceCard { get; set; }

**Comment by jaymedavis** [comment]
Duplicate of #648, see response there and let me know if that helps. Hopefully it eliminates your need to serialize. Comment there if not.
