### ISSUE TITLE
StripeAccountAdditionalOwner should support setting/updating the `verification[document]`

### ISSUE THREAD

**Issue by remi-stripe** [jaymedavis/stripe.net#717]
At the moment, the class [StripeAccountAdditionalOwner](https://github.com/jaymedavis/stripe.net/blob/0a41d5b4b92c441acd51883bf7cdc87621efddac/src/Stripe.net/Services/Account/StripeAccountAdditionalOwner.cs) doesn't let you set or update the identity verification document. This needs to be added as in Europe it's fairly common for companies to have additional owners and they need to be verified the same way the account representative has to be verified.

The docs for this parameter are here: https://stripe.com/docs/api#update_account-legal_entity-additional_owners-verification-document

**Comment by jaymedavis** [comment]
additional data for testing:

I think what you need is to test for real with a European account and fiddle with it 
llike create it, see it's asked in `fields_needed` and then explicitly set it as null
and then try to do the same on account creation

**Comment by ffMathy** [comment]
I would love to work on this myself, but I can't until #720 is done.
