### ISSUE TITLE
Allow setting `additional_owners` to null

### ISSUE THREAD

**Issue by remi-stripe** [jaymedavis/stripe.net#718]
In Europe, Stripe always requires that you provide information about additional owners of the company and this is documented [here|https://stripe.com/docs/connect/updating-accounts#additional-owners]. You can have up to 4 additional owners as they need anyone owning 25% or more but you don't always have 4.

You need to explicitly tell to Stripe's API whether you have more (or any). This is done by explicitly indicating this. For example in PHP, you'd update the Stripe account this way:
```
$account = \Stripe\Account::retrieve({CONNECTED_STRIPE_ACCOUNT_ID});
// Indicate that there are no additional owners
$account->legal_entity->additional_owners = null;
$account->save();
```

Behind the scenes, our bindings are explicitly setting `legal_entity[additional_owners]: ""` to tell us to expect none. In the logs for the update (in the connected account's dashboard) you'd see this as a parameter:
```
{
  "legal_entity": {
    "additional_owners": ""
  }
}
```

A similar logic is taken on account creation though you don't pass null and instead explicitly pass the `legal_entity[additional_owners]: ""`. In PHP the code would look like this:

```
$account = \Stripe\Account::create(
  array(
    "country" => "FR",
    "managed" => true,
    "legal_entity" => array(
        "type"               => "company",
        "additional_owners"  => ""
    )
  )
);
```

Stripe.net needs to support something like this to allow users to explicily tell the API that they won't have any additional owners on creation or update.

**Comment by jaymedavis** [comment]
Thanks for the detail! 

A good exercise might be recreating [this test](https://github.com/jaymedavis/stripe.net/blob/ff333215d5e0cec1f0a32ef11129e5ae8769b7eb/src/Stripe.net.Tests.xUnit/accounts/adding_additional_owners.cs) but omitting the values in the AdditionalOwners - something like this:

```
var newAccount = new StripeAccountService(_stripe_api_key).Create(
                new StripeAccountCreateOptions
                {
                    Email = $"koop@ajah.com",
                    Managed = true,
                    LegalEntity = new StripeAccountLegalEntityOptions
                    {
                        AdditionalOwners = new List<StripeAccountAdditionalOwner>
                        {
                            new StripeAccountAdditionalOwner { }
                        }
                    }
                }
            );
```

This code might not work, but it could be the target code so it matches the other bindings. This would be an empty list of additional owners just to flag this as no additional owners. If the goal is to tell Stripe you have no additional owners, I would think the api could handle sending the empty string for you via a property. The alternative is to write something like this, and document it:

var newAccount = new StripeAccountService(_stripe_api_key).Create(
                new StripeAccountCreateOptions
                {
                    Email = $"koop@ajah.com",
                    Managed = true,
                    LegalEntity = new StripeAccountLegalEntityOptions
                    {
                        NoAdditionalOwners = true
                    }
                }
            );
```

This is more intuitive, imo, but it's off the beaten path.

**Comment by ffMathy** [comment]
I would love to work on this myself, but I can't until #720 is done.

**Comment by agentcoops** [comment]
Hi @jaymedavis, I have a PR in preparation for this bug that uses the following syntax:
```
LegalEntity = new StripeAccountLegalEntityOptions
{
       AdditionalOwners = new List<StripeAccountAdditionalOwner> { }                        
}
```

I'll go ahead and submit the PR for review if that seems reasonable to you!

**Comment by jaymedavis** [comment]
Sure @agentcoops - thanks

**Comment by agentcoops** [comment]
Hi @jaymedavis, I pushed up the PR which you can find at https://github.com/jaymedavis/stripe.net/pull/746. Let me know if you have any questions or suggestions with respect to my approach.

**Comment by jaymedavis** [comment]
I left some comments/requests - great work. I'll close this and we will finish this task from that PR.
