### ISSUE TITLE
Ability to Add Orders with Order Items to cusotmers

### ISSUE THREAD

**Issue by flauckner** [jaymedavis/stripe.net#719]
Not an issue, a feature request.
Is there a plan to include Stripe Orders and OrderItems to stripe.net?

**Comment by jaymedavis** [comment]
Yes, there is. I'm in the process of working on a new tool that wraps Stripe.js into a couple of lines you copy and paste - hoping that application can help fund more time on stripe.net. 👍

**Comment by jaymedavis** [comment]
this will be handled from another PR (existing orders/skus/etc)
