### ISSUE TITLE
Detail how to set up the project for development?

### ISSUE THREAD

**Issue by ffMathy** [jaymedavis/stripe.net#720]
I think `README.md` should contain instructions on building the project locally.

I tried with Visual Studio 2015 with Microsoft Build Tools 2015 installed, Visual Studio 2017 RC, Visual Studio Code, all with latest .NET Core SDK, and I still get compilation errors that don't seem easy to fix at first glance.

I really want to fix some issues in this repository, but I can't get it working in the first place.

**Comment by ffMathy** [comment]
@jaymedavis do you think this is something you could take a look at?

**Comment by jaymedavis** [comment]
There is a script to build it and run the tests locally. Also, appveyor is the build server and has the information available as well. Review the build doc inside the .psm in the build folder.

**Comment by jaymedavis** [comment]
dotnet build/dotnet restore/dotnet pack/dotnet test .. lmk what errors you are getting. I use 2015 with Update 3.

**Comment by ffMathy** [comment]
See attached. 
![image](https://cloud.githubusercontent.com/assets/2824010/22073708/51fbdfde-dda6-11e6-95e4-0e26e19ee822.png)

**Comment by jaymedavis** [comment]
Ah - you probably installed the latest version of net core and don't have this version. I can update the library, it should be small. Give me a few, i'll try to release this along with another fix shortly.

**Comment by ffMathy** [comment]
Great - my point was also that if a specific version of the tooling is required, that should be documented too.

**Comment by jaymedavis** [comment]
can you run `dotnet --version` and share the output?

**Comment by jaymedavis** [comment]
You might need to install VS Update 3 - if this fixes it, I will get it in the readme. I see your point. 👍

**Comment by ffMathy** [comment]
`dotnet --version` returns `1.0.0-preview4-004233`. I have the latest SDK installed.

As for Visual Studio 2015, it is fully updated. The "about" dialog shows `14.0.25431.01 Update 3`.

**Comment by jaymedavis** [comment]
This is in the global.json file now, to specifiy preview 2 and the version I am using. It should force anyone building the project to use this version, or throw an error they don't have this version.

**Comment by ffMathy** [comment]
But why not use a later version? Wouldn't it make sense to bump the .NET version instead?

**Comment by jaymedavis** [comment]
I tried. xproj is deprecated and dotnet migrate is not working right now. I'd say I learned my lesson on the bleeding edge.

**Comment by ffMathy** [comment]
Ah yes I read about them removing it and switching back to csproj. I didn't see that coming either. 

But csproj will come for stripe.net?

**Comment by jaymedavis** [comment]
Yes, it will. I wish sooner rather than later, as I love working on my mac. But I already burned a day trying to get all of these pieces together.

**Comment by jaymedavis** [comment]
Preview 5 is supposed to have a solution migrator. I'm hoping that comes with a working migration.
