### ISSUE TITLE
No custom StripeListOptions for Subscriptions to support API 2016-07-06 changes

### ISSUE THREAD

**Issue by shizik** [jaymedavis/stripe.net#722]
The API version 2016-07-06 introduced the ability to view canceled subscriptions by specifying `status=canceled` or `status=all` when listing subscriptions. I assume there should be a `StripeSubscriptionListOptions` class instead of the generic one to support this. 

I can implement this and issue a PR, but wanted to make sure that I am not missing something.

**Comment by jaymedavis** [comment]
A `StripeSubscriptionListOptions` does need to be added. I see [quite a few options](https://stripe.com/docs/api#list_subscriptions) for this. A PR would be fantastic - my ask would be that you mark the existing List methods for sync and async obsolete, and the signature should change from `string customerId, StripeListOptions listOptions = null, StripeRequestOptions requestOptions = null` to `StripeSubscriptionListOptions listOptions = null, StripeRequestOptions requestOptions = null`. There's no reason customer needs to be a parameter on it's own. When possible, I try to stick to parameters being the required values, and the options classes being the optional arguments.

**Comment by shizik** [comment]
Hi Jayme, is there anything else I should do to get the pull request merged in?

**Comment by jaymedavis** [comment]
You can go ahead and create the pull request - I will leave comments there 👍 

To make it easy for me to bump, mark the version 7.0.next - it's in the appveyor file and the project.json for the project (sorry about the two places)

**Comment by shizik** [comment]
I already did, few days ago. But will update it with the version number now as you suggested.

**Comment by jaymedavis** [comment]
Sorry about that - I've had a lot of github notifications recently. I will review this as soon as I can... I am working on a product as well, and this has to be set to the side temporarily. I will comment on items in the PR asap.
