### ISSUE TITLE
Charge support for sourcetype bitcoin and alipay

### ISSUE THREAD

**Issue by mvanhalen** [jaymedavis/stripe.net#723]
Great wrapper. When we tried to add bitcoin and alipay I source the sourcetype enum does not contain bitcoin and alipay as options. Is that correct or am I doing something wrong? It´s when making the charge from a returned token . The response in stripe indicated that the type is set 
` "status": "consumed",
      "type": "bitcoin",
      "usage": "single_use",`

Thanks

**Comment by jaymedavis** [comment]
Good time for you to ping! I am looking for Bitcoin support soon for my own product, so that will be coming. Let me know what your needs are as well, and I can account for them. Do you need alipay? It seems the Source endpoint will eventually replace them all individually

**Comment by mvanhalen** [comment]
No problem, glad to help. For us it helps to be able to identify the charge coming in on the web hook. Since we enabled Alipay and bitcoin we expect to get charges for that. Now we just log them as Stripe payment but it would be cool to log it as Alipay payment or bitcoin payment in our own systems. We do not need the specific details of the payment type. Just the type. If there is another way to identify it on the charge.succeeded event that would help too.

Let me know if you need any testing or help.

**Comment by jaymedavis** [comment]
That's awesome you accept bitcoin. I feel ashamed I haven't built it yet considering I love crypto-currency. :)
Do you mind my asking which company/project you are working on, and your stack?

**Comment by mvanhalen** [comment]
Yes you may. Our company is [https://iGenApps.com](https://iGenApps.com) we have a web app platform and Apps in the App Stores to make your own App. We run in Azure and use .Net for our backend and server platform. We want to add bitcoin so more people in more countries can use our services.

**Comment by sheretovev** [comment]
Hi Guys,
As far as I understand this also related to iDeal payment type, right?
Charging with a source of iDeal type.
Could you please let us know when you plan to release this functionality?
thanks for your job!

**Comment by jaymedavis** [comment]
I've been slowly cranking away at these sources as they come in. Haven't forgot about you guys 👍

**Comment by jaymedavis** [comment]
I did not see any documentation for alipay. Bitcoin and Ideal are now on master and will ship with the next version 👍
