### ISSUE TITLE
Received unknown parameter: default_for_currency (StripeRequestor)

### ISSUE THREAD

**Issue by PaulARoy** [jaymedavis/stripe.net#727]
Hi there !
I am using Stripe.Net and first of all: thank you very much. This is an amazing library.

I am trying to update cards, and for this I add the card the user send me (through the token), but unfortunately I have an exception:
```
Stripe.StripeException:
   at Stripe.Requestor+<ExecuteRequestAsync>d__16.MoveNext (Stripe.net, Version=6.9.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Stripe.StripeCardService+<CreateAsync>d__15.MoveNext (Stripe.net, Version=6.9.0.0, Culture=neutral, PublicKeyToken=null)
```

The error message is `Received unknown parameter: default_for_currency`

Here is the code I use to reproduce the bug:
```
// create new card
var newCard = new StripeCardCreateOptions();
newCard.SourceToken = *MYTOKEN*;
newCard.DefaultForCurrency = true;
var card = await cardService.CreateAsync(*USERID*, newCard);
```

What I don't get is that I thought I tested this…
But it happened in production.

Do you have any idea why?

Best regards,

**Comment by jaymedavis** [comment]
Is there something here around you charging in a different country? Or the account setup in a different country?

I'm not sure on this one. Since it works in test, I assume your code is fine - maybe just missing a setting? I would contact Stripe support for this one - irc freenode #stripe or support@stripe.com. I'll leave this open if you wouldn't mind leaving an update for other passers by. :)

**Comment by PaulARoy** [comment]
I re-tested and it fails in development too.

I think it was tested without DefaultForCurrency and that it was added directly in production without tests.

So basically DefaultForCurrency doesn't work :)

**Comment by jaymedavis** [comment]
Did you see the comments for this property?
```
Only applicable on accounts (not customers or recipients). This indicates whether or not this card is the default external account for its currency.
```

Are you using this on a managed account? It only works on managed accounts.

**Comment by PaulARoy** [comment]
Hi Jayme,
Thanks for your feedback. It is indeed clear in their latest API Reference that default_for_currency is only for managed accounts, so my bug is irrelevant.

I don't know why I didn't see this before, my bad.
