### ISSUE TITLE
StripeCustomerService Update and UpdateAsync return null

### ISSUE THREAD

**Issue by CYBERRRR** [jaymedavis/stripe.net#728]
Hi Jayme, great work!

I was testing updating a user's card with a token returned by Checkout and on Stripe's dashboard the new card replaces the previous one and the api call (through Fiddler) returns all good with the new card as the default source but both Update and UpdateAsync return null :(

```
var options = new StripeCustomerUpdateOptions
{
    SourceToken = stripeToken
};

var customer = await new StripeCustomerService().UpdateAsync(stripeCustomerId, options);
//or
var customer = new StripeCustomerService().Update(stripeCustomerId, options);
```
Am I doing something wrong or is there a problem with the lib?

Thanks in advance!

**Comment by CYBERRRR** [comment]
Apparently the method works fine, VS on the other hand, was transforming that to null don't know why. Got suspicious, changed the variable name and it worked (variable name was unique in the scope). Sorry about that :(

**Comment by jaymedavis** [comment]
No worries. Visual Studio can be a bit needy sometimes. :)

**Comment by domialex** [comment]
On the same subject, not wanting to open another issue because this might be intended:
When updating a customer with **ExpandDefaultSource** to true, DefaultSource is there, but the BankAccount and Card are null.
