### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by rapPayne** [jaymedavis/stripe.net#729]
Documentation says ...
myCharge.SourceTokenOrExistingSourceId = *tokenId or existingSourceId*;
but should say 
myCharge.Source = *StripeSourceOptions*
and then describe what is a StripeSourceOptions

Documentation says for "Updating a Customer" -- "With a card:" ...
    // setting up the card
    myCustomer.Source = new SourceCard()
but there is no such a thing as a SourceCard class. It should be
myCustomer.Source = new StripeSourceOptions()
   {
        Object = "card",
        Number = "4242424242424242",
        ExpirationYear = "2022",
        ExpirationMonth = "10",
        AddressCountry = "US",                // optional
        AddressLine1 = "24 Beef Flank St",    // optional
        AddressLine2 = "Apt 24",              // optional
        AddressCity = "Biggie Smalls",        // optional
        AddressState = "NC",                  // optional
        AddressZip = "27617",                 // optional
        Name = "Joe Meatballs",               // optional
        Cvc = "1223"                          // usually required
    };

Same thing for "Creating a Customer" -- "With a card:"

**Comment by jaymedavis** [comment]
This is old code. What version are you on?

**Comment by rapPayne** [comment]
Okay. You're right, Jayme. I thought I was on the latest version. You're currently on 7.0.3. I'm on 5.3.0. That would explain it.

**Comment by jaymedavis** [comment]
No worries :) -- you can always shoot github back to an old commit to see the documentation for your version.
