### ISSUE TITLE
When creating a managed account: Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by KennyKaplanHP** [jaymedavis/stripe.net#730]
Getting the error noted when trying to create a managed account. Just migrated from 6.4 to 7.0.3 and this is one of our key uses. Creating a customer works just fine.

Here's how we're calling it:
`
                var newAccount = new StripeAccountCreateOptions
                {
                    Email = user.Email,
                    Managed = true,
                    Country = "US",
                    DefaultCurrency = "USD",
                    TosAcceptanceDate = DateTime.Now,
                    TosAcceptanceIp = ip,
                    TosAcceptanceUserAgent = agent,
                    LegalEntity = new StripeAccountLegalEntityOptions
                    {
                        Type = "individual"
                    },
                    TransferScheduleInterval = "daily",
                    TransferScheduleDelayDays = "5"
                };
                return await _stripeAccountService.CreateAsync(newAccount);
`

Stacktrace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Stripe.Infrastructure.Requestor.BuildRequest(HttpMethod method, String url)
   at Stripe.Infrastructure.Requestor.GetRequestMessage(String url, HttpMethod method, StripeRequestOptions requestOptions, Boolean useBearer)
   at Stripe.StripeAccountService.<CreateAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Service.Stripe.StripeService.<CreateAccount>d__14.MoveNext() in C:\_Dev\Service\Stripe\StripeService.cs:line 97

**Comment by fscahill** [comment]
same problem. Awaiting response....

**Comment by jaymedavis** [comment]
If someone could build a PR or branch with a test reproducing this, that would help me out. Alternatively, just add a project reference to the library directly, and let me know the values being passed at the time of the exception. There's a visual studio plugin to break on any CLR exceptions that might come in handy.

* To setup a test

1) Clone the library
2) [This code](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net.Tests.xUnit/test.cs) looks for an environment variable called "stripe_test_secret_key" so set that up with your Stripe secret key (for test running)
2) Run [this batch file](https://github.com/jaymedavis/stripe.net/blob/master/src/build-and-test.bat) in the repo to build, pack, and run all the tests. I'd recommend removing the first test run call in the batch file, as that's the mspec library and takes awhile (~800 tests). 
3) Create a test to replicate this in Stripe.Tests.xUnit, there are some examples in there. Basically, you can copy/paste the code from the OP

**Comment by jaymedavis** [comment]
I tried to look into his yesterday, but I had to uninstall the visual studio update from Feb 1st, as it makes the .xproj no longer compatible (I installed VS2017 which doesn't help either). Anyway, I kicked off the rollback last night, so hopefully I can find an answer this weekend.

**Comment by fscahill** [comment]
Jayme,

Any word on this problem?

scott
