### ISSUE TITLE
StripeCharge doesn't have subscription

### ISSUE THREAD

**Issue by intergleam** [jaymedavis/stripe.net#731]
when receiving `StripeEvents.InvoicePaymentSucceeded` there is no subscription on `StripeCharge` object.  If I look at JSON object I can see 
```
  "period_end": 1485863586,
  "period_start": 1485863586,
...
  "subscription": "sub_A24K41EzGeniEb",
```

**Comment by intergleam** [comment]
ok, found it in 

```
                var subscriptionId = stripeCharge.Invoice.SubscriptionId;
                var periodStart = stripeCharge.Invoice.PeriodStart;
                var periodEnd = stripeCharge.Invoice.PeriodEnd;

```

**Comment by intergleam** [comment]
nope, `Invoice` object is null

**Comment by intergleam** [comment]
the info i need is actually in lines - data

**Comment by jaymedavis** [comment]
I can't do anything about the data on events coming to you. Nothing more sophisticated has been built for webhooks.
