### ISSUE TITLE
Allow decimal type in property amountOff of coupon

### ISSUE THREAD

**Issue by avallebarco** [jaymedavis/stripe.net#732]
I create a coupon with the property AmountOff = 10.00
Then, when I make a couponService.Get from that coupon I get 1000
what am I doing wrong?

**Comment by jaymedavis** [comment]
Amount off is probably in your lowest currency (pennies/pence). Percent off is for percent. 

AmountOff is an integer only, so I'm not sure how it even worked, unless something was casted.

Hope this helps!

**Comment by bhumikaTechnomads** [comment]
Please visit this link
https://stripe.com/docs/currencies#zero-decimal

**solution**
$price = 1000; // your coupon amount that you got from stripe
echo number_format($price/100, 2, '.', ' ');

// output : 10.00
