### ISSUE TITLE
trial_end gets populated even if I set it to NULL

### ISSUE THREAD

**Issue by douglascarey** [jaymedavis/stripe.net#735]
When I use the api in .Net to change a plan for customers, sometimes the trial_end variable gets set to a random date even if I set it to NULL. I triple-checked this in my code and it happens for most customers. I look in my code and trial_end is NULL. But when I go to the Stripe dashboard, the trial_end is populated with some random date. It makes it so that I cannot use the api at all to change a customer's plan. This is a serious problem for me because now I can never update customers' plans with a new plan.

**Comment by jaymedavis** [comment]
Can you provide some code samples? There's not much to go on here. 

Are you setting the trial_end on subscription, perhaps? That will override the plan. Setting it to null and sending it won't do anything. Stripe.net ignores null values. Re-open if you have steps to reproduce or this didn't help solve the problem.
