### ISSUE TITLE
Multiple plans for subscription supported?

### ISSUE THREAD

**Issue by jamesfarr1993** [jaymedavis/stripe.net#748]
When I call the get subscription method for a customer with a multi-plan subscription:

`StripeSubscription stripeSubscription = subscriptionService.Get(customerId, subscriptionId);`

It returns an Error:

{"Error converting value {null} to type 'System.Int32'. Path 'quantity', line 84, position 18."}

I can't load a list of customers either:

`IEnumerable<StripeCustomer> response = customerService.List();`

It returns an Error:

"Error converting value {null} to type 'System.Int32'. Path 'subscriptions.data[1].quantity', line 197, position 24."

Stripe.net version 7.0.4.0

Am I missing something simple here?

**Comment by jaymedavis** [comment]
Subscriptions was just reworked, you should be set. Sounds like your customer code is something else entirely. Re-open if the newest version doesn't have you squared away.

**Comment by bluezee** [comment]
I'm getting a similar null quantity error when getting a customer with a multi-plan subscription:

`var customer = customerService.Get(customerId);`

Returns:

`Error converting value {null} to type 'System.Int32'. Path 'subscriptions.data[0].quantity', line 114, position 24.`

Stripe.net version 7.1.2.0

Please help!

**Comment by bluezee** [comment]
I might be wrong but it appears Stripe.net doesn't yet support multi-plan subscriptions as announced here:

https://stripe.com/blog/multiplan-subscriptions
https://stripe.com/docs/subscriptions/multiplan

The JSON for a multi-plan subscription is slightly different to a normal single-plan subscription. It has a parent subscription with a plan and quantity of null, and then an items array containing each of the child subscriptions (which have plans and quantities set to non-null values as you would normally expect).

Here's an example (I haven't wrapped this in code tags as it removes the line breaks):

{
  "id": "sub_ACBjeXoNzYQGh5",
  "object": "subscription",
  "application_fee_percent": null,
  "cancel_at_period_end": false,
  "canceled_at": null,
  "created": 1488197522,
  "current_period_end": 1490616722,
  "current_period_start": 1488197522,
  "customer": "cus_ACBic2IEhylAtY",
  "discount": null,
  "ended_at": null,
  "items": {
    "object": "list",
    "data": [
      {
        "id": "si_19rnME2RjIq0xYbx3qQCzXsn",
        "object": "subscription_item",
        "created": 1488197523,
        "plan": {
          "id": "starter",
          "object": "plan",
          "amount": 1800,
          "created": 1488197471,
          "currency": "gbp",
          "interval": "month",
          "interval_count": 1,
          "livemode": false,
          "metadata": {
          },
          "name": "Starter",
          "statement_descriptor": null,
          "trial_period_days": null
        },
        "quantity": 1
      },
      {
        "id": "si_19rnmL2RjIq0xYbx01nGkU82",
        "object": "subscription_item",
        "created": 1488199142,
        "plan": {
          "id": "pro",
          "object": "plan",
          "amount": 3000,
          "created": 1488199126,
          "currency": "gbp",
          "interval": "month",
          "interval_count": 1,
          "livemode": false,
          "metadata": {
          },
          "name": "Pro",
          "statement_descriptor": null,
          "trial_period_days": null
        },
        "quantity": 1
      }
    ],
    "has_more": false,
    "total_count": 2,
    "url": "/v1/subscription_items?subscription=sub_ACBjeXoNzYQGh5"
  },
  "livemode": false,
  "metadata": {
  },
  **"plan": null,
  "quantity": null,**
  "start": 1488199141,
  "status": "active",
  "tax_percent": 0.0,
  "trial_end": null,
  "trial_start": null
}

Looks like some fairly significant reworking is going to be needed to accommodate this new structure. 

I can understand why you got caught about by this (if you have and I'm not missing something). Multi-plan subscriptions are a great feature and work really well, but Stripe announced it out of the blue, and I don't see any mention of the API changes in the update log. It's almost like it's been snuck in under the radar as it doesn't affect existing subscriptions, but of course if you do create a new multi-plan subscription it won't work with an existing integration (such as Stripe.net) that isn't aware of the new multi-level JSON structure.

**Comment by jaymedavis** [comment]
I'm not really sure how their API upgrades are structured, but you are correct that lots of things just get applied without an API update. This needs investigation - reopening.

**Comment by bluezee** [comment]
Awesome, thanks Jayme. We've only got two customers on this (just started dipping our toe in). I'll flip them back to the usual multi-subscription setup for now and look forward to further updates as and when. Thinking about it I imagine this will affect how invoices are returned as well. Quite a rash change on their part really and seems to have completely bypassed the API versioning!

**Comment by eddyfice** [comment]
Any idea if/when stripe.net will be updated to reflect the new API?
