### ISSUE TITLE
StripeChargeCreateOptions.Destination property doesn't match the Stripe API spec

### ISSUE THREAD

**Issue by davidxcheng** [jaymedavis/stripe.net#752]
## The Issue
The `Destination` field in `StripeChargeCreateOptions` is currently a `string`:
```c#
[JsonProperty("destination")]
public string Destination { get; set; }
```

But [the API documentation](https://stripe.com/docs/api#create_charge) states that it should be a dictionary.

## Suggested fix
Change the `Destination` property to:
```c#
[JsonProperty("destination")]
public Dictionary<string, string> Destination { get; set; }
```

I hope to submit a PR soon but neither VS2015 nor VSCode agreed on opening the solution/run the code on the first attempt.

**Comment by blowndiffuser** [comment]
Just noticed this too. However, based on how similar properties are set in other options classes it might be more like:

```csharp
[JsonProperty("destination[amount]")]
public int? DestinationAmount { get; set; }

[JsonProperty("destination[account]")]
public string DestinationAccount { get; set; }
```

Of course as I understand it, these are exclusively for Destination type charges and would not be used for Direct charges so anyone using this would need to understand that. Maybe there should be shared options that includes the common  properties and then Destination and Direct options classes that inherit from them with their unique respective properties.

**Comment by jaymedavis** [comment]
Interesting. I was wondering how this breaking change might work, since destination works as is. This may be the way to get them to live in harmony together? I would guess setting anything on the hash would kill any value set to destination directly though.

**Comment by jaymedavis** [comment]
This was fixed recently, forgot to close. See release notes.
