### ISSUE TITLE
Could not install package 'Stripe.net 7.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

### ISSUE THREAD

**Issue by goodyes** [jaymedavis/stripe.net#753]
What happnes, trying to install via nuget on vs2015 on a website targetting 4.0 or 4.5 I get this shit error "Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Stripe.net 7.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
"

What is the solution to ?

**Comment by goodyes** [comment]
PUTA BASURA

**Comment by jaymedavis** [comment]
👍
