### ISSUE TITLE
this is a shit, solution it does not even load correctly under vs2015

### ISSUE THREAD

**Issue by goodyes** [jaymedavis/stripe.net#754]
Please resolve this piece of shit
Opening the latest code on vs2015 "Stripe.net.sln" gives vs the inhability to load all projects, this is a shit
I cannot also download from nuget from a vs2015 project or website.

**Comment by SharpeRAD** [comment]
Comments like this have no place in the .net community! While my personal coding style may differ to the maintainers I'd like to publicly thank him for this project and his continued work in providing **FREE** support to its users.

Thank you Jayme Davis.

**Comment by jaymedavis** [comment]
This is probably a relic from the .xproj file and preview 2. If you look at global.json, it has the version listed you should have installed. Can  you tell me if you have that version installed?

**Comment by jaymedavis** [comment]
By the way, did you install Visual Studio 2017?

**Comment by jaymedavis** [comment]
I assume this is resolved, since you closed your other issue trying to use this in asp.net 4.0. Reopen if not.

**Comment by drewid** [comment]
Trying really hard not to make extremely derogatory comments against the @#$ named goodyes.  His ignorance and stupidity..... signing off.

**Comment by goodyes** [comment]
This makes no sense. Sorry for my words, But we use vs2015. I do not understand why anyone need to use an unreleased version (vs2017). So I think you must list at least, what project / version last, work with a default std install of vs2015 and framework 4.5 or 4.6.1

**Comment by jaymedavis** [comment]
You don't need to use vs2017. I was asking if you installed it. That is what broke my project references as you described. Do you have it installed at all? Have you installed anything netcore related? Run dotnet --info.

This does work with 4.5. It also works with netcore, Xamarin, and even Xbox. Keep in mind it's designed to work with many platforms and not just *yours*.

**Comment by jaymedavis** [comment]
Talked to @goodyes over IRC about this. It was a misconfigured setting in his web.config for anyone passing by that might have this issue.
