### ISSUE TITLE
Period timezone issues

### ISSUE THREAD

**Issue by niemyjski** [jaymedavis/stripe.net#759]
I think there may be an issue with utc periods:

<img width="515" alt="screen shot 2017-02-27 at 7 02 01 am" src="https://cloud.githubusercontent.com/assets/1020579/23371051/d39c9be0-fcba-11e6-9310-ee0507976a9b.png">
<img width="600" alt="screen shot 2017-02-27 at 7 02 13 am" src="https://cloud.githubusercontent.com/assets/1020579/23371055/d6a7ae42-fcba-11e6-8947-475e891987b7.png">

**Comment by jaymedavis** [comment]
I'm not understanding the issue here

**Comment by niemyjski** [comment]
Stripe says the period is the previous day (bottom image) the time returned from the call says utc but it's different). I was expecting them to line up.

**Comment by jaymedavis** [comment]
Yeah, I would expect your End to have the same time as the dashboard as well. Is this via a web hook?

**Comment by jaymedavis** [comment]
A recent push changed the datetime to use invariant culture when processing Stripe responses - I think this may be related. Reopen if you are still seeing this.

**Comment by niemyjski** [comment]
No, this is not via a web hook, this is from pulling it back from the api. I'm using the latest client as of a week ago.
