### ISSUE TITLE
JsonReaderException thrown in StripeChargeService.Create when charge outcome.rule is an object

### ISSUE THREAD

**Issue by samcic** [jaymedavis/stripe.net#763]
After upgrading from Stripe.net 7.0.4 to the latest version 7.1.2, we saw a `JsonReaderException` thrown on our production systems when a charge was being made. The exception relates to the "outcome.rule" property of the charge object, which for version 2016-07-06 of the Stripe API is noted to be an "expandable" property. It seems that Stripe.net is not expecting that the value might be an object, so trying to parse the property fails with the exception message "Unexpected character encountered while parsing value: {. Path 'outcome.rule'".

If we understand correctly (and based on the Stripe.net documentation), we should only be expecting StripeExceptions to be thrown from service calls. This makes us think that this result represents a bug.

Unfortunately we don't have access to the Stripe production account related to the error, so we're not quite sure how this is reproduced. The owner of the Stripe account did however say that the charge successfully completed (which in our case was somewhat dangerous, because we showed a generic error on our side in response to the JsonReaderException and they repeated the charge attempt, which ended up charging them a second time). Based on the fact that the charges are actually successful and that an "outcome.rule" is involved, a potential reproduction might be a matching radar ["allow rule"](https://stripe.com/docs/radar/testing). We'll see if we can reproduce it on a test account and update this post if we're successful.

After I post this I'll have a browse of the changes since 7.0.4 to see if I notice any potential cause for this error.

Stack trace:

`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'outcome.rule', line 28, position 13. at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType) at Newtonsoft.Json.JsonTextReader.ReadAsString() at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Stripe.Mapper`1.MapFromJson(String json, String parentToken, StripeResponse stripeResponse) at Stripe.StripeChargeService.Create(StripeChargeCreateOptions createOptions, StripeRequestOptions requestOptions)`

**Comment by samcic** [comment]
So it looks like it's related to the commit https://github.com/jaymedavis/stripe.net/commit/43cb5c8018b96c4ac332fedbf99ed0de1e966d9f, which explains why we only saw the problem after upgrading.

Specifically, the "Outcome.Rule" property is listed as a string, which based on our experience is not necessarily correct - it may well be an object.

**Comment by jaymedavis** [comment]
If you have a copy of the code running locally, could you just comment out the below property[1] and share your StripeResponse value? That way I can see the json that comes back on a live instance.

1. ```[JsonProperty("rule")]  public string Rule { get; set; }```

**Comment by samcic** [comment]
I'll see if I can get access to a production Stripe account where I can play around with the rules, charge my own card (refunding it afterwards) and get this info for you. I'll paste it here when I get it...

**Comment by samcic** [comment]
Ok, so I managed to reproduce this relatively easily with a live gateway. It just involves setting up an "allow" rule in the Stripe dashboard and then making a charge which matches that rule. The rule I setup here was "amount_in_aud < 1", which is visible in the `predicate` property below.

Here's the StripeResponse JSON. The `outcome.rule` is the one I guess we're interested in. Note that I've masked sensitive strings (ids, cardholder name etc) with 'xxx'.

```json
{
  "id": "ch_xxx",
  "object": "charge",
  "amount": 50,
  "amount_refunded": 0,
  "application": null,
  "application_fee": null,
  "balance_transaction": "txn_xxx",
  "captured": true,
  "created": 1488796756,
  "currency": "aud",
  "customer": "cus_xxx",
  "description": "description",
  "destination": null,
  "dispute": null,
  "failure_code": null,
  "failure_message": null,
  "fraud_details": {},
  "invoice": null,
  "livemode": true,
  "metadata": {},
  "on_behalf_of": null,
  "order": null,
  "outcome": {
    "network_status": "approved_by_network",
    "reason": null,
    "risk_level": "normal",
    "rule": {
      "id": "ssr_xxx",
      "action": "allow",
      "predicate": ":amount_in_aud: \u003C1"
    },
    "seller_message": "Payment complete.",
    "type": "authorized"
  },
  "paid": true,
  "receipt_email": null,
  "receipt_number": null,
  "refunded": false,
  "refunds": {
    "object": "list",
    "data": [],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/charges/ch_xxx/refunds"
  },
  "review": null,
  "shipping": null,
  "source": {
    "id": "card_xxx",
    "object": "card",
    "address_city": null,
    "address_country": null,
    "address_line1": null,
    "address_line1_check": null,
    "address_line2": null,
    "address_state": null,
    "address_zip": null,
    "address_zip_check": null,
    "brand": "Visa",
    "country": "AU",
    "customer": "cus_xxx",
    "cvc_check": "pass",
    "dynamic_last4": null,
    "exp_month": 7,
    "exp_year": 2018,
    "fingerprint": "dxxx",
    "funding": "credit",
    "last4": "1234",
    "metadata": {},
    "name": "Realname Hidden",
    "tokenization_method": null
  },
  "source_transfer": null,
  "statement_descriptor": null,
  "status": "succeeded",
  "transfer_group": null
}
```

**Comment by jaymedavis** [comment]
Well that looks easy enough. It's three strings instead of one. Where I have a property decorated with rule, we could create a StripeRule object with three string properties. Decorated with json attributes and the values above. It might be beneficial to find if there's any other properties that come back in other situations, but this is a great start.

Thank you for doing the testing/work here.

**Comment by samcic** [comment]
Hmmm...actually I just noticed a relevant change in the Stripe API changelog:

https://stripe.com/docs/upgrades#2017-02-14

Version 2017-02-14: 

> Charges that have been blocked by Radar rules will now render the ID of the rule that blocked them under the outcome field instead of the full Rule object. You may expand this property to render the full Rule as before.

I assume this change also holds for the case involving _allow_ Rules as well (i.e. the case I tested).

Long story short: thanks to your recent API version upgrade https://github.com/jaymedavis/stripe.net/commit/7056cbe2c79dea0cc581e664935df0269e260887 this should be solved and you can keep it as a string (at least until the developer community screams that they need the expanded Rule object, which I'm guessing could then be optionally requested using StripeChargeOptions or similar, causing a relevant expand parameter value in the raw charge request).

To double check my assumption above, I'll redo my test with respect to your API version upgrade. I'll let you know if it comes back as a string in the same scenario, and if it does I'd suggest we can close this.

**Comment by jaymedavis** [comment]
Well, I could leave the ID, rename it to OutcomeId and make it expandable. I just didn't know what it expanded into.

That test would help a lot - thanks!

**Comment by samcic** [comment]
Here's the result of the same test with Stripe.net 7.3.0. Note this is without setting any of the `Expand*` properties on the `StripeChargeService` object (i.e. all set to false). Seems to suggest that the outcome/refunds/source properties are expanded by default, but the outcome.rule isn't. 

````json
{
  "id": "ch_xxx",
  "object": "charge",
  "amount": 50,
  "amount_refunded": 0,
  "application": null,
  "application_fee": null,
  "balance_transaction": "txn_xxx",
  "captured": true,
  "created": 1488817696,
  "currency": "aud",
  "customer": "cus_xxx",
  "description": "test charge",
  "destination": null,
  "dispute": null,
  "failure_code": null,
  "failure_message": null,
  "fraud_details": {},
  "invoice": null,
  "livemode": true,
  "metadata": {},
  "on_behalf_of": null,
  "order": null,
  "outcome": {
    "network_status": "approved_by_network",
    "reason": null,
    "risk_level": "normal",
    "rule": "ssr_xxx",
    "seller_message": "Payment complete.",
    "type": "authorized"
  },
  "paid": true,
  "receipt_email": null,
  "receipt_number": null,
  "refunded": false,
  "refunds": {
    "object": "list",
    "data": [],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/charges/ch_xxx/refunds"
  },
  "review": null,
  "shipping": null,
  "source": {
    "id": "card_xxx",
    "object": "card",
    "address_city": null,
    "address_country": null,
    "address_line1": null,
    "address_line1_check": null,
    "address_line2": null,
    "address_state": null,
    "address_zip": null,
    "address_zip_check": null,
    "brand": "Visa",
    "country": "AU",
    "customer": "cus_xxx",
    "cvc_check": "pass",
    "dynamic_last4": null,
    "exp_month": 7,
    "exp_year": 2018,
    "fingerprint": "xxx",
    "funding": "credit",
    "last4": "1234",
    "metadata": {},
    "name": "Test Name",
    "tokenization_method": null
  },
  "source_transfer": null,
  "statement_descriptor": null,
  "status": "succeeded",
  "transfer_group": null
}

````

**Comment by samcic** [comment]
For completeness, I did another charge on a live system with a matching rule, this time with all the Expand* properties set to true. Response is below.

Importantly, it seems that Stripe doesn't expand the Rule object in this case either (I guess that would require an ExpandRule property in Stripe.net?).

Long story short: as long as you're using Stripe.net > 7.2.0, the Rule property is never an object, and hence there won't be any JSON parser exceptions.

I'm closing this now because I consider v7.2.0 as having fixed it. If I'm missing something, please reopen it.

````json
{
  "id": "ch_xxx",
  "object": "charge",
  "amount": 50,
  "amount_refunded": 0,
  "application": null,
  "application_fee": null,
  "balance_transaction": {
    "id": "txn_xxx",
    "object": "balance_transaction",
    "amount": 50,
    "available_on": 1489708800,
    "created": 1489139720,
    "currency": "aud",
    "description": "test charge",
    "fee": 31,
    "fee_details": [
      {
        "amount": 3,
        "application": null,
        "currency": "aud",
        "description": "GST",
        "type": "tax"
      },
      {
        "amount": 28,
        "application": null,
        "currency": "aud",
        "description": "Stripe processing fees",
        "type": "stripe_fee"
      }
    ],
    "net": 19,
    "source": "ch_xxx",
    "status": "pending",
    "type": "charge"
  },
  "captured": true,
  "created": 1489139720,
  "currency": "aud",
  "customer": {
    "id": "cus_xxx",
    "object": "customer",
    "account_balance": 0,
    "created": 1489139719,
    "currency": null,
    "default_source": "card_xxx",
    "delinquent": false,
    "description": null,
    "discount": null,
    "email": null,
    "livemode": true,
    "metadata": {},
    "shipping": null,
    "sources": {
      "object": "list",
      "data": [
        {
          "id": "card_xxx",
          "object": "card",
          "address_city": null,
          "address_country": null,
          "address_line1": null,
          "address_line1_check": null,
          "address_line2": null,
          "address_state": null,
          "address_zip": null,
          "address_zip_check": null,
          "brand": "Visa",
          "country": "AU",
          "customer": "cus_xxx",
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 7,
          "exp_year": 2018,
          "fingerprint": "xxx",
          "funding": "credit",
          "last4": "1234",
          "metadata": {},
          "name": "xxx xxx",
          "tokenization_method": null
        }
      ],
      "has_more": false,
      "total_count": 1,
      "url": "/v1/customers/cus_xxx/sources"
    },
    "subscriptions": {
      "object": "list",
      "data": [],
      "has_more": false,
      "total_count": 0,
      "url": "/v1/customers/cus_xxx/subscriptions"
    }
  },
  "description": "test charge",
  "destination": null,
  "dispute": null,
  "failure_code": null,
  "failure_message": null,
  "fraud_details": {},
  "invoice": null,
  "livemode": true,
  "metadata": {},
  "on_behalf_of": null,
  "order": null,
  "outcome": {
    "network_status": "approved_by_network",
    "reason": null,
    "risk_level": "normal",
    "rule": "ssr_xxx",
    "seller_message": "Payment complete.",
    "type": "authorized"
  },
  "paid": true,
  "receipt_email": null,
  "receipt_number": null,
  "refunded": false,
  "refunds": {
    "object": "list",
    "data": [],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/charges/xxx"
  },
  "review": null,
  "shipping": null,
  "source": {
    "id": "card_xxx",
    "object": "card",
    "address_city": null,
    "address_country": null,
    "address_line1": null,
    "address_line1_check": null,
    "address_line2": null,
    "address_state": null,
    "address_zip": null,
    "address_zip_check": null,
    "brand": "Visa",
    "country": "AU",
    "customer": "cus_xxx",
    "cvc_check": "pass",
    "dynamic_last4": null,
    "exp_month": 7,
    "exp_year": 2018,
    "fingerprint": "xxx",
    "funding": "credit",
    "last4": "1234",
    "metadata": {},
    "name": "xxx xxx",
    "tokenization_method": null
  },
  "source_transfer": null,
  "statement_descriptor": null,
  "status": "succeeded",
  "transfer_group": null
}
````
