### ISSUE TITLE
Missing implementation of SubscriptionItems

### ISSUE THREAD

**Issue by TVNielsen** [jaymedavis/stripe.net#764]
Thanks for a great wrapper for Stripe.  I came across the need to make subscriptions with multiple invoice items on, say a base subscription with something addon. Specifically extra users.
Stripe supports this https://stripe.com/docs/api/curl#subscription_items
However it's not in stripe.net

Actually i pulled the repos and added that functionality, currently in the process of figuring a way to pass it back to the stripe.net project :)

Uploaded initial solve to https://github.com/TVNielsen/stripe.net, missing async stuff though

**Comment by jaymedavis** [comment]
I am trying to move towards the StripeBasicService<Generic>, which cuts a lot of the cookie cutter parts out of the services. A couple small things - the List entities can just inherit from StripeListOptions, as most List(s) inside Stripe have starting_after, limit, and ending_before. The last piece you were missing was the date time converter, so it's not epoch time.

Take a look at this commit specifically I wrote today - you were very close! https://github.com/jaymedavis/stripe.net/commit/3afe69351fa2f2f8e571ed29ef4d98141b241676

I still need to test this, but it should work 🤞

**Comment by TVNielsen** [comment]
Thx, meanwhile got further with actually using git from commandline when developing, much smarter :)

Integrated your comments and will push changes if code still runs in my the_required_stripe_functionality_poco_system if possible :)

**Comment by jaymedavis** [comment]
The cmd line is a must-learn to get you out of a bind. I like the github client for mac a lot, but I have to return to the cmd line for anything serious!

This is now part of the library. It may or may not be slightly different, I'd certainly appreciate your feedback if you want to review the commits. Thanks again!

**Comment by TVNielsen** [comment]
Hi Jayme

 

I’m still a bit wandering aimfully about without wits with regards to GITHUB, so please have patience if i don’t go about things correcty.

 

I’ve initiated a pull request if that is the way to do that, reason being that there are some changes between my fork and what you included. Explicitly they are that my fork includes the review changes that you’ve suggested and the master does not.

 

I see it here: https://github.com/jaymedavis/stripe.net/pull/770 

 

I’ll try to locate commit ;)

 

/Thomas
