### ISSUE TITLE
Updating from 6.11.1 to newer version

### ISSUE THREAD

**Issue by mattetom** [jaymedavis/stripe.net#769]
Hi,
I'm using your library to connect to stripe from a Xamarin mobile app for iOS and Android.
Untill version 6.11.1 all is ok and working correctly.
When I try to update to versione > 6.11 I get this error:

`Could not install package 'Stripe.net 7.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0`	

How can I solve my problem?
Thanks.

**Comment by jaymedavis** [comment]
Do you have a copy of the code locally? 

I'm wondering if changing project.json to this might help.
```
    "netstandard1.2": {
      "imports": [ "netcoreapp1.0"*, "portable"* ],
      "dependencies": {
        "NETStandard.Library": "1.6.1"
      }
```

**Comment by jaymedavis** [comment]
You can review this as well. https://oren.codes/2016/07/09/using-xamarin-forms-with-net-standard/

Would appreciate an update :)
