### ISSUE TITLE
Charge customer for managed account

### ISSUE THREAD

**Issue by FlashDeath** [jaymedavis/stripe.net#777]
Thought I'd share an issue I recently encountered to maybe help others.
I created a customer on a managed account using the stripeRequestOptions.  But when I went to try and charge the customer on behalf of the managed account I couldn't get it to work.

I've tried:
    StripeChargeCreateOptions charge = new StripeChargeCreateOptions();
    charge.Amount = amount;
    charge.Currency = "usd";
    charge.Description = description;
    charge.CustomerId = customerId;
    charge.Destination = companyAccountId;

    // Charge the credit card
    StripeCharge charge = new StripeChargeService().Create(charge);

But it gives me a "No such customer" error

So I thought maybe I need to have the stripeRequestOptions in charge so I tried:
    StripeChargeCreateOptions charge = new StripeChargeCreateOptions();
    charge.Amount = amount;
    charge.Currency = "usd";
    charge.Description = description;
    charge.CustomerId = customerId;
    charge.Destination = companyAccountId;

    // Charge the credit card
    return new StripeChargeService().Create(charge, new StripeRequestOptions { StripeConnectAccountId = companyAccountId });

But I get "The 'destination' param cannot be set to your own account" Error.
So then I realized that I needed to get rid of the destination parameter of the charge and just use the stripeRequestOptions.  Since it took me quite a while to figure this out I hope this helps someone else.

**Comment by jaymedavis** [comment]
Just to clarify - the last code sample is right when you remove the destination being set on the charge. So what is happening, is you are charging the customer FROM the account in the request options, not your own account.

Thank you very much for sharing @FlashDeath!

**Comment by FlashDeath** [comment]
Yes. I updated the post so it's more clear.
