### ISSUE TITLE
Unable to serialize StripeChargeCreateOptions to json

### ISSUE THREAD

**Issue by Tochemey** [jaymedavis/stripe.net#778]
Whenever I tried to serialize the StripeChargeCreateOptions I got the following issue:
JsonSerializationException: A member with the name 'source' already exists on 'Stripe.StripeChargeCreateOptions'. Use the JsonPropertyAttribute to specify another name.

Any idea?

**Comment by Tochemey** [comment]
I just read one of your solution to the issue and it seems you are not ready to amend it. Cool. However can you then provide a ToString method to get what was sent to the Stripe API? if you want I can do a PR

Thank you

**Comment by jaymedavis** [comment]
Go for it. There is a StripeResponse now which shows you exactly what was returned, I would love to have a StripeRequest or something like that to show what was sent. 

Brownie points for showing that same request as a curl request!
