### ISSUE TITLE
Exception when creating managed account - System.Diagnostics.DiagnosticSource ver 4.0.0.0 reference

### ISSUE THREAD

**Issue by pileo** [jaymedavis/stripe.net#784]
I'm getting following exception: 
System.IO.FileLoadException on System.Diagnostics.DiagnosticSource ver 4.0.0.0 reference

Investigating further, workaround 1 from [http://stackoverflow.com/questions/41550563/system-net-http-nuget-package-4-3-0-reference-generates-system-io-fileloadexcept](url) seemed to have solved the issue for me.  I added the assembly binding information to the MVC project App.config, this appears to have worked.

I'm using VS 2017 and Stripe.Net version 7.5.0

**Comment by jaymedavis** [comment]
Thanks for sharing!
