### ISSUE TITLE
Issue creating managed accounts

### ISSUE THREAD

**Issue by Magrangs** [jaymedavis/stripe.net#787]
There seems to be an issue creating managed accounts and when trying to supply additional owners information in the legal entity object. When creating an account I want to send up no additional owners. I have tried sending null and I have tried sending an empty list however on the stripe dashboard it says I need to supply this information. I have emailed stripe support and this was the response:

"...Unless you explicitly tell us there are no additional owners on account creation, we will always ask you to confirm. The idea is to send the value as null..."

I dont want to use the update method directly after the create method to send up null, I would rather be able to supply null in the create option to explicitly tell them that there are no additional owners.

Many thanks

**Comment by jaymedavis** [comment]
Pass it like [this test](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.Tests.XUnit/accounts/when_creating_additional_owners_empty_list.cs).
