### ISSUE TITLE
Instant Payments available_payout_methods

### ISSUE THREAD

**Issue by smh974** [jaymedavis/stripe.net#793]
On the external accounts object in the stripe api documentation there is an option to check the card method type that option is called available_payout_methods. It seems to be missing from the StripeCard object.

Here is a description of what it is from the api and a link to the api where it is located.

Thanks for the help in advance!

available_payout_methods 
array containing strings 
A set of available payout methods for this card. Will be either ["standard"] or ["standard", "instant"]. Only values from this set should be passed as the method when creating a transfer. 

https://stripe.com/docs/api#account_card_object

**Comment by jaymedavis** [comment]
can you share your code for where you expect this to be populated? are you creating a card directly or creating an account with an external account?

**Comment by smh974** [comment]
Sure, In my case I would like this to be off the StripeCard Object that is on the External accounts. This would also apply to Customer Stripe Cards as well I am sure. 


                  StripeAccountService accountService;  
                  StripeAccount stripeAccount;

                  stripeAccount = await accountService.GetAsync(User.ConnectId);

                   foreach (Source source in stripeAccount.ExternalAccounts.Data)
                   {
                        if (source.Card != null)
                        {
                            source.Card.available_payout_methods

                        }                          
                    }

Let me know if you need more information

**Comment by jaymedavis** [comment]
Nope, perfect. 👍 

Waiting on the build to finish here, but this should be an easy one. Will be part of the next release as well.
