### ISSUE TITLE
Deleting a Stripe Connect Account's external_account (card)

### ISSUE THREAD

**Issue by smh974** [jaymedavis/stripe.net#794]
I don't believe this question was properly answered. 

https://github.com/jaymedavis/stripe.net/issues/502

It appears that there is no way to delete a Stripe Connect Account's External_account.
Using the StripeCardService.Delete
expects a customerId or a recipient id. In this case there is no Customer or recipient id since you are deleting the External_Account (card in my case)

I attempted this but this will not work...

stripeUpdateAccountOptions = new StripeAccountUpdateOptions();                                                
stripeUpdateAccountOptions.ExternalCardAccount = null;

stripeAccountService = new StripeAccountService();
await stripeAccountService.UpdateAsync(User.ConnectIdThatIsNotThePlatform, stripeUpdateAccountOptions);

Please give me some direction on how to remove external accounts from a connected account.
This Connect account is a managed account.

**Comment by jaymedavis** [comment]
Looks like you are right. [External Accounts](https://stripe.com/docs/api#external_accounts) needs to be implemented as a service here. The recent commit on the payouts branch is an idea of what needs to happen here. How are you adding the account? Setting DefaultForCurrency to true when you create the account?

**Comment by smh974** [comment]
I am adding/ editing using a comment you entered for a previous issue
Deleting seems to be the only issue.

Issue:
https://github.com/jaymedavis/stripe.net/issues/670
Commit you are were talking about.
https://github.com/jaymedavis/stripe.net/commit/39ca17ffe870b85c62d44043eaeeff29dfa690a4

Your comment for the case that helped me figure out the add/update

Ok, check out this commit, I wrote a test that shows you how to do this properly. The tricks are this:
1.When you set the currency, you need to set this on you token, not on the account update. The only thing you want on your account update is the TokenId.
2.You have to use a debit card.

You should be all set!

**Comment by jaymedavis** [comment]
I added the ```Delete``` method to the ```StripeExternalAccountService```. More work is needed to finish this off, but it should take care of your need. It will be available on nuget as soon as you see the next commit with a ship 👍

**Comment by smh974** [comment]
Thank you for this. Thank you for a great library as well! It has helped me tremendously.

**Comment by jaymedavis** [comment]
Glad to hear it! Thanks for reporting these issues.

**Comment by skatar** [comment]
@jaymedavis I can delete a bank account using StripeExternalAccountService but how do I delete a debit card associated with a stripe account?
StripeCardService accepts customerid and card id, whereas I have account id and card id
