### ISSUE TITLE
Unable to update customer metadata

### ISSUE THREAD

**Issue by ricktheartist** [jaymedavis/stripe.net#795]
Since the last upgrade (currently running 7.6.0), I have been unable tp perform an update to a customer's metadata. The code that was previously working is below. I now get "Object reference not set to an instance of an object" on line 2 of what you see below:

`Dim customerUpdate As StripeCustomerUpdateOptions = New StripeCustomerUpdateOptions()`
`customerUpdate.Metadata.Add("Address", address)`
`customerUpdate.Metadata.Add("City", city)`
`customerUpdate.Metadata.Add("State", state)`
`customerUpdate.Metadata.Add("Zip", zip)`
`customerService.Update(stripeCustomerID, customerUpdate, reqoptlive)`

**Comment by jaymedavis** [comment]
You are not initializing metadata as a new dictionary...

In C#, you have to do:
```
                Metadata = new Dictionary<string, string>()
                {
                    { "some-key", "some-value" }
                }
```

You are getting this error because you are trying to add keys to a null object.

**Comment by ricktheartist** [comment]
Thank you. Odd that I did not have to do that with the prior version of Stripe.NET that I was using (I do not recall what version that was).
