### ISSUE TITLE
File upload verification fails

### ISSUE THREAD

**Issue by smh974** [jaymedavis/stripe.net#802]
I am getting an error when attempting to upload a document to a managed Connect account. 
I am using Xamarin Forms I did have my code inside of the pcl for uploading the document but I moved it into a dependency service for android to see if that was the problem but I still was getting the following message.

{System.ArgumentException: boundary
  at System.Net.Http.MultipartContent..ctor (System.String subtype, System.String boundary) [0x00062] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/System.Net.Http/System.Net.Http/MultipartContent.cs:72 
  at System.Net.Http.MultipartFormDataContent..ctor (System.String boundary) [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/System.Net.Http/System.Net.Http/MultipartFormDataContent.cs:41 
  at Stripe.Infrastructure.Requestor.ApplyMultiPartFileToRequest (System.Net.Http.HttpRequestMessage requestMessage, System.String fileName, System.IO.Stream fileStream, System.String purpose) [0x00098] in <177b41da76dc498dad3cd7f6eee7bd8d>:0 
  at Stripe.Infrastructure.Requestor.PostFileAsync (System.String url, System.String fileName, System.IO.Stream fileStream, System.String purpose, Stripe.StripeRequestOptions requestOptions, System.Threading.CancellationToken cancellationToken) [0x0000e] in <177b41da76dc498dad3cd7f6eee7bd8d>:0 
  at Stripe.StripeFileUploadService+<CreateAsync>d__4.MoveNext () [0x00032] in <177b41da76dc498dad3cd7f6eee7bd8d>:0 

This is on an android device

Here is what my code looks like

MediaFile is from 
jamesmontemagno/MediaPlugin 
https://github.com/jamesmontemagno/MediaPlugin
It just allows users to use Camera Settings for Cross platform and use System.IO in your pcl

         internal async Task UploadImage(MediaFile image, User user)
         {
              StripeFileUploadService fileService;
              StripeFileUpload file;
              StripeRequestOptions requestFileOptions;
              Stream streamImage;

            if (image != null )
            {
                requestFileOptions = new StripeRequestOptions();

                fileService = new StripeFileUploadService();
                requestFileOptions.StripeConnectAccountId = user.ConnectId;

                streamImage = image.GetStream();
                file = await fileService.CreateAsync("verify.jpg", streamImage ,     StripeFilePurpose.IdentityDocument, requestFileOptions );
      }

Let me know if you have questions.
Here is a image of the stream from the debugger.

![stream_li](https://cloud.githubusercontent.com/assets/7681254/24484660/05b96dca-14c5-11e7-9c96-6ca9b5bbc56a.jpg)

**Comment by jaymedavis** [comment]
Here's the relevant part of stripe.net that handles this: https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Infrastructure/Requestor.cs#L191-L212

This could should be fine - doesn't end in a whitespace, etc. Not sure why the boundary appears to be an issue.

It looks like your code is ok. Couple things to try, to help isolate:  1) try without async. 2) try this in a console application in debug mode vs android. The media file shouldn't matter, as long as you give stripe.net a stream it's happy.

**Comment by smh974** [comment]
I will look into your suggestions this evening. I will let you know what I come up with. Worst comes to worst i will get a copy of the stripe.net solution an play with the requestor.

**Comment by jaymedavis** [comment]
Awesome. Let me know if you figure it out, i'll get the solution merged into the main package. I'll leave this open in case anyone else has ideas right now 👍

**Comment by smh974** [comment]
I believe I have figured it out. I pulled the stripe.net solution and started debugging. 
where you were pointing me to 

https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Infrastructure/Requestor.cs#L191-L212

This block of code when changed 

from this

            var multiPartContent =
                new MultipartFormDataContent($"----------Upload: { DateTime.UtcNow.Ticks.ToString("x") }")
                {
                    { new StringContent(purpose), "\"purpose\"" },
                    fileContent
                };
To this
            var multiPartContent =
                new MultipartFormDataContent($"----------Upload:{ DateTime.UtcNow.Ticks.ToString("x") }")
                {
                    { new StringContent(purpose), "\"purpose\"" },
                    fileContent
                };          

The key is there is a space in between the string interpolation and the datetime so if we change this piece of code 
from
                $"----------Upload: <space here right now> { DateTime.UtcNow.Ticks.ToString("x") }")
To no space
                $"----------Upload:{ DateTime.UtcNow.Ticks.ToString("x") }")

I am actually scratching my head on how this worked at all. Although I am sure that it did. Code it funny like that sometimes. For me that space is causing the boundary problem.

**Comment by jaymedavis** [comment]
Sorry about that - I even mentioned earlier it doesn't end in a white space... and it did. Whoops. 

Thanks, I'll get this fixed. 👍  I'm shooting for a release tomorrow for 2 or 3 things, I'll get this in there too.
