### ISSUE TITLE
payment method SOFORT payment

### ISSUE THREAD

**Issue by andreaslorenz** [jaymedavis/stripe.net#811]
do you have any plan to intergrate SOFORT payment?
https://stripe.com/docs/sources/sofort

**Comment by andreaskibk** [comment]
that would be perfect!!

**Comment by jaymedavis** [comment]
it looks like the only thing to do here is add type='sofort' - then you need to be able to pass the country and the statement descriptor. Is there anything else that's needed?

I can inspect the payloud to see what comes back to populate the entity.

**Comment by jaymedavis** [comment]
this is on master, and will go out with the next 🚢
