### ISSUE TITLE
StripeRefundListOptions - StripeDateFilter?

### ISSUE THREAD

**Issue by mishapinky** [jaymedavis/stripe.net#819]
Is there a way to get a list of refunds for certain dates? I'm able to use the StripeDateFilter with charges, transfers, and balance transactions, but not with refunds.

**Comment by jaymedavis** [comment]
It would be nice to be able to pass the created time, but it doesn't appear like that's a feature: https://stripe.com/docs/api#list_refunds. I'll see if this can be implemented, or perhaps just missing from the docs

**Comment by mishapinky** [comment]
Yeah for now I'm having to make separate API calls. The first is against the charges and if it's a refund I make another call to the refunds with that specific charge ID.

**Comment by jaymedavis** [comment]
I pinged stripe about this one. It's not on the radar right now, but they recognize it would be helpful. If they add it, I will 👍

**Comment by mishapinky** [comment]
Thanks! I had contacted them as well. This was their response.

Hi mishapinky,

Adding date filters to the refunds endpoint is a completely fair ask, I'll make sure the suggestion gets passed along, it is certainly something we'll consider for future updates to the API!

Best,
D

**Comment by jaymedavis** [comment]
Awesome. Anyone else that stumbles upon this can write in as well, the more it's requested... :thumbs-up:
