### ISSUE TITLE
BankAccountService.Verify Unrecognized URL //

### ISSUE THREAD

**Issue by brenden735** [jaymedavis/stripe.net#821]
Unrecognized request URL (POST: /v1/customers//sources/ba_1XXBvXXRhq4rtXXAdm8GR2XX/verify). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.

customers**//**sources

**Comment by jaymedavis** [comment]
are you passing a customer id? sounds like it's probably null - have you checked the value?
