### ISSUE TITLE
Need to access whether a StripeAccount is registered for tax

### ISSUE THREAD

**Issue by roberthchapman** [jaymedavis/stripe.net#822]
Hi, in order to know whether to add VAT tax in to a subscription we need to know whether the account offering the plan for this subscription is VAT registered - if they are then we need to add VAT, if not we can leave as is.  But this does not seem to be exposed.  There is a property BusinessVatId on the StripeCustomer object that I was expecting to find in StripeAccount.  When you create an account manually on Stripe you do enter this info but it looks like it is hidden.  Understand the Id itself should not necessarily be available so can a boolean property be added along the lines of HasBusinessVatId?

Then it becomes simply:
if(account.HasBusinessVatId){  subscription.taxPercent = 20;} else { subscription.taxPercent = 0;}

Thanks,
Rob

**Comment by jaymedavis** [comment]
this will go out with the next release. the property is account.LegalEntity.BusinessVatIdProvided. Fwiw, I agree with the pattern of HasXXX or IsXXX for bools. I just went with the same name to not confuse anyone comparing the stripe docs. 👍

**Comment by roberthchapman** [comment]
Thanks for the quick response and action Jayme!
