### ISSUE TITLE
Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by mleader1** [jaymedavis/stripe.net#824]
Hi,

I want to store the returned StripeAccount object in JSON format in database. Currently it serializes into JSON without problem, however if I try to retrieve it from DB and deserialize the JSON, it will throw an error: 

> Cannot perform runtime binding on a null reference

I have tried many different ways but couldn't solve the problem.  Just to be sure - I also did an immediate Deserialization after the serialization - it also fails directly:

`JsonConvert.SerializeObject(stripeAccount).JsonDeserialize<StripeAccount>()
`

Can you help please?  

Thanks.

**Comment by jaymedavis** [comment]
Use the StripeRespobse property on the object to store the value. Check towards the top of the readme - hope this helps!

**Comment by mleader1** [comment]
thanks @jaymedavis  - stupid me jumped into the coding work too quickly! :) that certainly solved my problem...  cheers

**Comment by jaymedavis** [comment]
No worries, we all do it. :)

**Comment by elikooobelikooo** [comment]
ssxasxax
