### ISSUE TITLE
Versoning header

### ISSUE THREAD

**Issue by ga630sf** [jaymedavis/stripe.net#827]
Hi Jayme

Are there any plans to provide the Optional stripe Version header

This allows you to use a particular Stripe API Version on Charges etc

regards
Steve

**Comment by jaymedavis** [comment]
Hello :)

No - this is something that stripe.net targets. For example, the latest version is designed so payouts and transfers are broken up. If I allowed the user to flip the version, it would be a toss up of what works and doesn't work - it would be easier to convert your code to work on the latest version, imo.

**Comment by ga630sf** [comment]
Hi Jayme

It's more about keeping the version of stripe.net in my software in sync with a specific version of the Stripe API. So I know any breaking changes in the Stripe API will not affect my software.

I have users of my software who will sign up for Stripe to use optional features in my software
In say a years time, Stripe may release a new API version which is incompatible with the stripe.net version in my software.
When my users joins stripe I assume they are automatically assigned the latest Stripe API on their account
Hence the stripe.net version may not work correctly with their Stripe API

I would need to keep up with changes to Stripe API and corresponding updates to your stripe.net

With Versioning I would have more time to release a software update with a newer version of Stripe.net to target a newer version of the Stripe API

regards
Steve

**Comment by xt0rted** [comment]
I thought the readme used to have a blurb about this (or maybe I read it on stripe's site). What I recall reading is stripe.net sets the version it supports and stripe's api uses that no matter what version the account is set to (newer or older). The version your account is set to then only affects your webhooks and any api call you make without a version set.

**Comment by ga630sf** [comment]
You are correct

I just found where the stripe version is set in stripe.net StripeConfiguration.cs
Currently set to '2017-04-06'

So problem solved

Thanks for that

regards
Steve

**Comment by xt0rted** [comment]
@jaymedavis The bit on the api/account version was removed from the readme in https://github.com/jaymedavis/stripe.net/commit/ef68b7e0618d148e0e6e4f732d1abe5991dbcc79#diff-0730bb7c2e8f9ea2438b52e419dd86c9

**Comment by jaymedavis** [comment]
Sorry, I didn't understand the question - thanks @xt0rted.

It's always locked to a version, and I'll always tell you if it changes in the release notes. :)

**Comment by ga630sf** [comment]
Hi Jayme

I understand now

Thanks

regards
Steve
