### ISSUE TITLE
Creating a token for a certain credit card on certain shared customer

### ISSUE THREAD

**Issue by PK-ByTE** [jaymedavis/stripe.net#831]
Hi, found following guide (https://stripe.com/docs/connect/shared-customers).
The guide shows how to generate a single use token (stored credit card) for shared customer. But i'm not getting any success creating same scenario using the stripe.net library. Especially the second step.

What parameters should I pass to StripeTokenService.Create method via StripeTokenCreateOptions?
-CustomerId
-Card? -> StripeCreditCardOptions does not have source id field

in addition i pass in StripeRequestOptions() with StripeConnectAccountId set.

Does anyone have any remedy to this problem?

**Comment by jaymedavis** [comment]
I need to refactor this class out. However, use TokenId - you can pass a source id there, I believe you can pass a source there, the name just doesn't make it seem like it. Let me know if this works.

**Comment by PK-ByTE** [comment]
Thanks, that did work. Created a charge with no problems.
