### ISSUE TITLE
Question: Is BalanceTransaction.SourcedTransfers obsolete?

### ISSUE THREAD

**Issue by mvolodin** [jaymedavis/stripe.net#832]
I was trying to map ```py_***``` ids that I receive in transfer.paid event for connected accounts to original charge ```ch_***```. I got all transactions related to proper transfer id and expect ```SourcedTransfers``` property to be filled with original transfer (source transfer) and needed me info. But ```SourcedTransfers``` always empty, the question is, do you use somehow ```SourcedTransfers``` because I didn't find any info in stripe api about this data or it is obsolete?

**Comment by jaymedavis** [comment]
Did you recently upgrade Stripe.net? Perhaps a recent change in the payout/transfer split caused this. I'm not sure if there's anything I need to fix here or not. Contact Stripe support about this one, and let me know if there is anything I need to fix.

**Comment by mvolodin** [comment]
Thank you for reply. But I meant that you have SourcedTransfers property mapped to "sourced_transfers" field in returned json. But in stripe documentation for balance transactions https://stripe.com/docs/api/curl#balance_transaction_object there is no such field.

**Comment by jaymedavis** [comment]
I'll see if I can find out where this went.

**Comment by mvolodin** [comment]
thanks

**Comment by jaymedavis** [comment]
yes it is obsolete - https://stripe.com/docs/upgrades#2017-01-27

I'll remove it - thanks for reporting this.

**Comment by jaymedavis** [comment]
this is on master and will go live with the next :ship: 👍
