### ISSUE TITLE
Cannot use StripeDateFilter on Listing Payouts

### ISSUE THREAD

**Issue by mishapinky** [jaymedavis/stripe.net#833]
I updated to the new API to be able to use the new payout/transfer split up however I am not able to use StripeDateFilter on it. I noticed it is of type DateTime? instead of StripeDateFilter.

Payout
<img width="513" alt="screen shot 2017-04-19 at 9 22 13 pm" src="https://cloud.githubusercontent.com/assets/20478832/25212257/898a46a6-2546-11e7-97e5-d4332272aa44.png">

Charge
<img width="552" alt="screen shot 2017-04-19 at 9 23 10 pm" src="https://cloud.githubusercontent.com/assets/20478832/25212274/998ec266-2546-11e7-9373-a2f1710a5b56.png">

**Comment by jaymedavis** [comment]
You are correct - this should be a StripeDateFilter - will fix.

**Comment by jaymedavis** [comment]
It will work now, however - just only for the exact datetime

**Comment by codecadwallader** [comment]
This package is awesome, and thanks for all your hard work.  +1 for hoping this can be expanded to support a full StripeDateFilter.

**Comment by codecadwallader** [comment]
As a helper for anyone else in the meantime.. an easy workaround for grabbing all transactions this year is to wrap your code with something like this:

```csharp
for (var date = new DateTime(2017, 01, 01); date < DateTime.UtcNow; date = date.AddDays(1))
```

**Comment by jaymedavis** [comment]
this will be on master soon via #894. in addition to created, ArrivalDate was able to become a StripeDateFilter as well. This will go live when you see the :ship: 

Thanks for the kind words!

**Comment by codecadwallader** [comment]
Great, thank you! :)

**Comment by mishapinky** [comment]
Thanks!
