### ISSUE TITLE
No StripeResponse populated on StripeError

### ISSUE THREAD

**Issue by robin-o** [jaymedavis/stripe.net#836]
Even though StripeError inherits from **StripeEntity**, the StripeResponse property is not populated in a StripeException. The documentation seems to imply that it should be:

>  The StripeResponse object is a property (with the same name) attached to all **entities** in Stripe.net when they are returned from a service call.

**Comment by n1schal** [comment]
think i'm facing a similar issue(?) i'm using this with Xamarin.iOS
