### ISSUE TITLE
Platform fees not collecting  while creating destination charges using the platform

### ISSUE THREAD

**Issue by johnykifle** [jaymedavis/stripe.net#837]
Even though stripe fee is collected by stripe. the application fee is not collected by the platform when using the destination charge method. 

  _charge = new StripeChargeCreateOptions
                {
                    Amount = 85000,
                    Currency = "NOK",
                    Description ="Test",
                    SourceTokenOrExistingSourceId = stripe.Token,
                    Destination ="{CONNECTED_STRIPE_ACCOUNT_ID}",
                    DestinationAmount = 78625
                };

**Comment by jaymedavis** [comment]
mind sharing the solution? it would sure help others in the future :)

**Comment by johnykifle** [comment]
Thanks for the amazing job Jayme.

I got a response from stripe saying 
"The amount specified in destination.amount will be automatically transferred to the destination.account, the rest will be kept in your platform balance. With this option, no application_fee object will be generated."

**Comment by jignesh-tps** [comment]
@johnykifle what about stripe charge? How stripe collect their fee from amount ?

**Comment by remi-stripe** [comment]
@jignesh-tps I'd recommend talking with our support team directly for questions like this [here](https://support.stripe.com/email) but the fee is taken out of the platform balance if you charge via `destination`. You offset this by simply keeping a portion of the charge and sending less to the connected account.

**Comment by omkarkhalipe** [comment]
How does the exact same thing work with subscription? 
Means the rather than creating charge, I want to create subscription

**Comment by remi-stripe** [comment]
@omkarkhalipe It works similarly and you can read the docs about this here: https://stripe.com/docs/connect/subscriptions
