### ISSUE TITLE
StripeBalanceService List and ListAsync should return StripeList<StripeBalanceTransaction>

### ISSUE THREAD

**Issue by nicodenzl** [jaymedavis/stripe.net#838]
According to https://stripe.com/docs/api/curl#balance_history List all balance history returns a paged result.
It looks like a change very similar to #816 could be implemented for StripeBalanceService to allow for paging.

**Comment by jaymedavis** [comment]
this [branch](https://github.com/jaymedavis/stripe.net/tree/838-attempted-fix), will probably do the trick. If you can test it, that would be helpful as well. Do you only use nuget for packages?

**Comment by nicodenzl** [comment]
Thanks, I'll give that go and let you know how it goes! I am actually just getting started on a project but yes, I was planning on using nuget.

**Comment by jaymedavis** [comment]
thanks for the tip to #816 - it was the same thing but a different class (and some other small details)
