### ISSUE TITLE
Does not stop charging card after (x) number pf payments are processed

### ISSUE THREAD

**Issue by kimdobranski** [jaymedavis/stripe.net#843]
### Unless I don't understand, isn't interval count supposed to tell stripe how many times to charge the card then stop? If is used the plan below, the card is charged indefinitely.

 Dim myPlan = New StripePlanCreateOptions()
        myPlan.Id = "plan-" & GenRandomInt(10000000, 90000000).ToString()
        myPlan.Amount = amount / numberofpayments '           // all amounts On Stripe are In cents, pence, etc
        myPlan.Currency = "cad" '        // "usd" only supported right now
        myPlan.Interval = "month" '       // "month" Or "year"
        **myPlan.IntervalCount = 3 '**   Ignores?
        myPlan.Name = itemdesc '
        myPlan.TrialPeriodDays = 0 '// amount Of time that will lapse before the customer Is billed

        Dim planService = New StripePlanService()
        Dim response = planService.Create(myPlan)

        Dim subscriptionService = New StripeSubscriptionService()
        Dim StripeSubscription = subscriptionService.Create(StripeCustomer.Id, myPlan.Id)
        Return ChargeCCErrorCodes.Success

**Comment by jaymedavis** [comment]
I'm not sure how this works exactly - you will need to contact Stripe. Please leave a blurb of what the solution is, i'm sure it will help others. 👍
