### ISSUE TITLE
Unset Additional Owners

### ISSUE THREAD

**Issue by rajtechsupport** [jaymedavis/stripe.net#849]
Receiving this error from the Stripe API

legal_entity.additional_owners
Please provide the required information to re-enable the account. Charge creation may be disabled for this account in 8 days if the information is not provided.

However, there are no additional owner required for this account.  Stripe told us:

"I've done some digging on this topic and found some good news. At times, this parameter will show as needed for verification, but if you've confirmed that there are, in fact, no additional owners - you can go ahead and update this parameter to be `null`."

So we set the parameter to null and we still received the error.  Stripe told us:

I do understand that that seems counterproductive. But as it's outlined in our documentation, if the `additional_owners` parameter is showing as required yet there are no additional owners - then that parameter needs to be "unset". There's a certain syntax for the unsetting of parameters in each of the supported languages for Stripe's official libraries. [1] As I've mentioned before, you're currently using the C# port of the Stripe library written by Jayme Davis, so I'm unsure as to the syntax for "unsetting" a parameter in C#.

I've done a search in the repository to try and figure out what the process of unsetting a parameter is, but could only turn up this search result. [2] While that result is referencing the unsetting of the `metadata`, the process may be the same for `legal_entity[additional_owners]`. 

Could someone please help me understand how I can "unset" this parameter?  I have tried

 account.LegalEntity.AdditionalOwners = new List<StripeAccountAdditionalOwner>();

It feels like we need a new method on the LegalEntity to override the default implementation and send something specific as outlined in [1]

[1] https://stripe.com/docs/connect/updating-accounts#additional-owners

[2] https://github.com/jaymedavis/stripe.net/blob/24969258c20184521b3011f577e699248b7dbbf5/src/Stripe.Tests.XUnit/accounts/when_creating_additional_owners_empty_list.cs

**Comment by jaymedavis** [comment]
The 2nd reference link should work here. You are sending it a reference to tell it to not use anything. That is the syntax for specifying no additional owners. 

Did you try that?

**Comment by rajtechsupport** [comment]
Thanks for the response.  I have tried:

account.LegalEntity.AdditionalOwners = new List<StripeAccountAdditionalOwner>()

But now we are getting a different message so Im not sure if it fixed it or rather is masking some other issue.  I'll post in here again if that does not fix the problem.

**Comment by jaymedavis** [comment]
Be sure to send the list with the generic parameter just like the test. That should take care of it - reopen if not.
