### ISSUE TITLE
Source creation with bancontact payment

### ISSUE THREAD

**Issue by sheretovev** [jaymedavis/stripe.net#855]
https://stripe.com/docs/sources/bancontact

Bancontact requires a statement descriptor before the customer is redirected to authenticate the payment. By default, your Stripe account’s statement descriptor is used (you can review this in the Dashboard). You can provide a custom descriptor by specifying bancontact[statement_descriptor] when creating a source. Bancontact statement descriptors support a maximum of 35 characters.

```
source = Stripe::Source.create({
  amount: 1099,
  currency: 'eur',
  type: 'bancontact',
  owner: {
    name: 'Jenny Rosen'
  },
  redirect: {
    return_url: 'https://shop.example.com/crtA6B28E1'
  },
  bancontact: {
    statement_descriptor: 'ORDER AT11990',
  },
})
```

**Comment by sheretovev** [comment]
Hi Jayme,
thanks for quick reaction,

I think the same changes should be done for Giropay:
https://stripe.com/docs/sources/giropay

```
 giropay: {
    statement_descriptor: 'ORDER AT11990',
  },
```

**Comment by kurtik40** [comment]
I have an issue making stripe for bancontact, I have stripe for mastercard, but here is bit different, can someone help me?  It works with sources like you mention above..I need it for IOS
