### ISSUE TITLE
StripeEvents payout.reversed

### ISSUE THREAD

**Issue by Morgan0018** [jaymedavis/stripe.net#860]
I can't find the "payout.reversed" event in the Stripe API. There is, however, a "payout.canceled" event that isn't referenced in the StripeEvents class. I have been implementing webhooks and cannot receive that one.

**Comment by jaymedavis** [comment]
This is an open PR now. In your implementation, you can just pass the string "payout.canceled" until the next release drops 👍

**Comment by Morgan0018** [comment]
Thanks! Your library is making my life so much easier.

**Comment by jaymedavis** [comment]
Forgot to close this, you're all set. Thanks for the kind words!
