### ISSUE TITLE
Why has object "Product" has been deleted?

### ISSUE THREAD

**Issue by ljmasague** [jaymedavis/stripe.net#862]
Hello, I was using the object Product to create the invoice lines, suddently this object does not exist anymore, and can't seem to find a substitute. Is there one that i'm missing? I really need the concept of "product" stripe has, since i wasn't storing that data on my database...

**Comment by jaymedavis** [comment]
Can you share code please?

**Comment by ljmasague** [comment]
Hi, ty for the rapid response, here's the code where i was using this class.
public static void AddInvoiceItem(string customerId, StripeProduct product)
        {
            var myItem = new StripeInvoiceItemCreateOptions();
            myItem.Amount = product.Skus.Data[0].Price;
            myItem.Currency = product.Skus.Data[0].Currency; 
            myItem.CustomerId = customerId;
            myItem.Description = product.Description;
            
            StripeInvoiceLineItem response = _invoiceItemService.Create(myItem);

        }

**Comment by jaymedavis** [comment]
In this context, product is your own variable and I can't see how it is formed. However, StripeProduct is alive and well and hasn't gone anywher. Did you recently upgrade?
