### ISSUE TITLE
Unable to do instant payout even though there is debit card setup 

### ISSUE THREAD

**Issue by pujanzaverchand** [jaymedavis/stripe.net#865]
Card id  - card_1AFnMPBc3L3uvhdVLVCxq2yo

Unable to do instant payout even though there is debit card setup.
method  ='instant', currency = 'usd', amount is setup for paymentoptions. when trying to set destination - its not taking this id and when trying to do a payout its giving error that payout cannot work with bank_account

**Comment by jaymedavis** [comment]
I'm not a stripe employee, so I don't have access to your data. You'll have to contact them. :(
