### ISSUE TITLE
Missing ConstructEvent on .NET Core branch

### ISSUE THREAD

**Issue by Dooskington** [jaymedavis/stripe.net#868]
Hi,

Without the StripeEventUtility.ConstructEvent() function on the .NET Core branch, how would I verify an event I have received via webhook?

Do I have to manually do it as is discussed [here](https://stripe.com/docs/webhooks#signatures)?

Thanks.

**Comment by jaymedavis** [comment]
What version are you using? This should be available.

**Comment by Dooskington** [comment]
@jaymedavis I'm using .NET Core 1.1, and Stripe.net 7.6.1. Is there a more up to date version that I'm missing?

**Comment by jaymedavis** [comment]
Yes, the current version is 8.4.0. This work was introduced in 8.3.0, so I would upgrade. Checkout the releases in this repo for a summary of each upgrade.
