### ISSUE TITLE
Update Subscription Unrecognized request

### ISSUE THREAD

**Issue by avallebarco** [jaymedavis/stripe.net#873]
Good moorning,

I want to updated a subscription but i have this error
Unrecognized request URL (POST: /v1/subscriptions/). Please see https://stripe.com/docs or we can help at https://support.stripe.com/

this is my code:

var mySubscription = new StripeSubscriptionUpdateOptions();
mySubscription.EndTrialNow = true;
                
var subscriptionService = new StripeSubscriptionService();
StripeSubscription stripeSubscription = subscriptionService.Update(***SubscriptionID***, mySubscription);

What it is happen? can you help me?

Thanks

**Comment by jaymedavis** [comment]
[this works fine for me](https://github.com/jaymedavis/stripe.net/commit/3539384405b4b23f4b60e3b064ca305bf4aa075b). Make sure your SubscriptionID is not null.
