### ISSUE TITLE
Need to add Discount to a particular Subscription.

### ISSUE THREAD

**Issue by HilalRather** [jaymedavis/stripe.net#875]
There is nothing like Coupon in subscriptionCreateoption as we have requirement to add Coupon to a particular subscription.There is a property CouponID when assigned a value to this it doesn't work as per documentation.It doesn't get associated to the same subscription as discount.After checking it ,In coupon detail it shows the Active redemptions as the mailID of Customer.

Need Quick response/fix.

**Comment by jaymedavis** [comment]
I think this is probably a misunderstanding with how Stripe processes the discount and the coupon. Plan and Coupon (CouponId) are both supported on creating a subscription, which is what the [documentation](https://stripe.com/docs/api#create_subscription) shows. I would contact Stripe to see if this is doing what you expect it to be doing.
