### ISSUE TITLE
Critical error - Could not load type 'Stripe.StripeSourceOptions' from assembly 'Stripe.net, Version=8.3.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by pujanzaverchand** [jaymedavis/stripe.net#877]
When trying to run the application we are getting this error.

**Comment by jaymedavis** [comment]
Do you have any code you have written? Was this previously working? Have you upgraded to the new 9.0 yet?

I'm not sure what 'run the application' means in context?
