### ISSUE TITLE
Question: How to assign a timeout value?

### ISSUE THREAD

**Issue by n1schal** [jaymedavis/stripe.net#880]
Sorry if it's already been answered before but I couldn't find one!

How do I assign a timeout value to the requests I make?

I'm using it in a Xamarin app.

Thanks in advance!

**Comment by jaymedavis** [comment]
I don't think this has been asked! 👍

Are you using a custom handler?

**Comment by jaymedavis** [comment]
If you are or aren't, I think I could probably add an HttpClient.Timeout = *timeSpan* to the Requestor. Then, I could add a ```StripeConfiguration.HttpMessageTimeout``` property that you could pass a `TimeSpan` to?

**Comment by n1schal** [comment]
Not using a custom handler yet. Was waiting for an answer from here to take any further steps.

That addition would be wonderful! Hoping it arrives soon :)

**Comment by n1schal** [comment]
@jaymedavis any news on when this will be rolled out?

**Comment by jaymedavis** [comment]
Pretty sure this is all you will need. https://github.com/jaymedavis/stripe.net/compare/http-timeout?expand=1

Are you setup to work with another branch, or are you only working from nuget?

**Comment by n1schal** [comment]
@jaymedavis Only from Nuget at the moment

**Comment by jaymedavis** [comment]
this is on master now - once you see the :ship: commit, it will go live to nuget (most likely 9.0.1) 👍

**Comment by n1schal** [comment]
@jaymedavis thanks!

**Comment by n1schal** [comment]
@jaymedavis  just updated to the version with HttpTimeSpan but upon setting 

`StripeConfigurationOptions.HttpTimeSpan = new TimeSpan(0,1,0);`

I don't get any response.

This is how I'm doing my calls :

`async Task<StripeCustomer> GetCustomer(string cId)
		{
			AppLog.WriteLogD(TAG, "Getting Customer...");
			var customerService = new StripeCustomerService();
			StripeCustomer stripeCustomer = null;
			try
			{
				Task<StripeCustomer> getCustomerTask = customerService.GetAsync(cId);
				stripeCustomer = await getCustomerTask;
				//Console.WriteLine(stripeCustomer.StripeResponse.ResponseJson);
				AppLog.WriteLogD(TAG, "Customer: " + stripeCustomer.Description, "(" + stripeCustomer.Email + ")");
				//AppLog.WriteLogD(TAG, "Default Source:" + stripeCustomer.DefaultSourceId);
			}
			catch (StripeException e)
			{
				HideProgress();
				AppLog.WriteLogD(TAG, "Error Type:" + e.StripeError.ErrorType);
				AppLog.WriteLogD(TAG, "Message: " + e.StripeError.Message);
			}
			return stripeCustomer;
		}`

and then calling this like so :

**Comment by n1schal** [comment]
@jaymedavis I turned off the internet on the device, set StripeConfigurations.HttpTimeSpan = new TimeSpan (0,1,0); but when making a request with the internet still turned off, I don't seem to get any response and my progress keeps spinning.

How I'm making requests :

```
async Task<StripeCustomer> GetCustomer(string cId)
		{
			AppLog.WriteLogD(TAG, "Getting Customer...");
			var customerService = new StripeCustomerService();
			StripeCustomer stripeCustomer = null;
			try
			{
				Task<StripeCustomer> getCustomerTask = customerService.GetAsync(cId);
				stripeCustomer = await getCustomerTask;
				//Console.WriteLine(stripeCustomer.StripeResponse.ResponseJson);
				AppLog.WriteLogD(TAG, "Customer: " + stripeCustomer.Description, "(" + stripeCustomer.Email + ")");
				//AppLog.WriteLogD(TAG, "Default Source:" + stripeCustomer.DefaultSourceId);
			}
			catch (StripeException e)
			{
				HideProgress();
				AppLog.WriteLogD(TAG, "Error Type:" + e.StripeError.ErrorType);
				AppLog.WriteLogD(TAG, "Message: " + e.StripeError.Message);
			}

			return stripeCustomer;
		}
```

```
Task.Run(async () =>
				{
					ShowProgress();
					var Customer = await GetCustomer(CustomerId);
HideProgress();
					if (Customer != null)
					{...}else{...}
```

**Comment by n1schal** [comment]
@jaymedavis Hi, any updates on this? Can you take a look at the code above and let me know if I'm doing something incorrectly? Cheers.

**Comment by jaymedavis** [comment]
What were you expecting to see? This should just change the timespan alloted for your call, turning off your internet would only make it spin for a minute before it fails.

**Comment by n1schal** [comment]
@jaymedavis I get no response and the spinner goes on spinning forever. Shouldn't it throw some sort of exception so that I can display a message saying the call timed out?
