### ISSUE TITLE
Question: get Card (fingerprint) using card token

### ISSUE THREAD

**Issue by EmmaHansson** [jaymedavis/stripe.net#881]
I have a problem and rather hard to resolve it.
I use checkout form to make a payment:

 ```
<form action="/Api/paymentCheckout" method="POST">
                            <p>
                                <div class="row">
                                    <div class="span4 offset4 text-center">
                                        <script id="stripeCheckout" src="https://checkout.stripe.com/checkout.js"
                                                class="stripe-button"
                                                data-email=@Model.Email
                                                data-allow-remember-me="false"
                                                data-label="Subscribe"
                                                data-key="@Model.StripePublicKey"
                                                data-amount="@Model.StripeAmount"
                                                data-name="@Model.StripePlanName"
                                                data-description="@Model.StripeTrialPeriod"
                                                data-locale="auto">
                                        </script>
                                    </div>
                                </div>
                            </p>                            
                        </form>
```

Tn result in the Api controller I have a request containing unfortunately only TokenId, but without Card info.
But my task is to bind existing card by fingerprint to the payment if exists, or create new card and pay if no such fingerprint found.
May be it possible to recognize fingerprint using card_token?

Advice needed.

**Comment by jaymedavis** [comment]
Hello - 

Do you do the fingerprint check on your server? If you fetch the customer/card, it does have a fingerprint property you could look for.

p.s. be sure to have a look at http://www.checkoutnet.com - this is a credit card form that is done for you (MVC) - curious if this interest you? I'm thinking of just sharing the necessary parts to build via a MVC view and server side code - for cheap. :)

**Comment by EmmaHansson** [comment]
Again. Scenario is easy like a corner of the house. When user pays using token it creates everytime new cardId (and card) with same fingerprints. I want to use this fingerprint, yes at backend, without creating new card wasting customers multiply cards. Only if I haven't such fingerprint I want create a new card.

A form I posted posts only tokenId. I thought I can use it before binding card to a customer.

**Comment by EmmaHansson** [comment]
It seems I can't do it at server. I must catch callback response and using it's data make a POST to the server instead of Form post :( (<form action="/Api/paymentCheckout" method="POST">) . That's sad.

**Comment by EmmaHansson** [comment]
Seems everything is worse. Only way to make a finger print his when I bind a card to a customer. I can't  having a fingerprint for a card during validation. 

Seems it's mega bug for stripe.com

**Comment by tangentmind** [comment]
@EmmaHansson when you create the charge you get a token back. using that token, can't you retrieve the generated customer ID from stripe and then store that ID along with the email address used by the person? then the next time they go to checkout (assuming they are logged in), you can use the Stripe customer ID that you saved from before and simply create the charge from your server (instead of using Checkout or Elements): https://stripe.com/docs/charges

**Comment by jlomas-stripe** [comment]
@EmmaHansson You can do this by [retrieving the Token by ID](https://github.com/jaymedavis/stripe.net#retrieving-a-token) on the server side, and then comparing the `token.card.fingerprint` against the existing Customer's Card fingerprints.

**Comment by EmmaHansson** [comment]
@jlomas-stripe Thanks. Your approach is exactly what I need. Works like a charm.

**Comment by muhkhan-nisum-com** [comment]
Helllo there ? can you anybody still guide me through @jlomas-stripe implmentation. since url is redirecting to whole repo. I am having this issue where I dont want to add the card if the card is already exist against customer

**Comment by remi-stripe** [comment]
@muhkhan-nisum-com This issue is almost 7 years old. Based on your question I'd recommend working directly with our support team for 1:1 support instead: https://support.stripe.com/contact
