### ISSUE TITLE
Limit invoices to a specific subscription

### ISSUE THREAD

**Issue by jchristyler** [jaymedavis/stripe.net#883]
The package currently does not provide for constraining an invoice list to those for a subscription, but the API does allow for this. It's easy to work around, but maybe you'd like to include this in the code. (not sure if I should do this as a pull request; I'm new to github)

All that's needed is a SubscriptionID property on StripeInvoiceListOptions with a JsonProperty of "subscription". I solved this in my code by creating a child class:
(vb.net)
`Public Class StripeInvoiceForSubscriptionListOptions`
`    Inherits Stripe.StripeInvoiceListOptions`
`    <JsonProperty("subscription")>`
`    Public Property SubscriptionID As String`
`End Class`

**Comment by jaymedavis** [comment]
this will be on master when #893 is merged in and will be in the next release
