### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by kwalsh446** [jaymedavis/stripe.net#884]
Hi.. I updated to 9.0 and now am getting a permission error when hitting endpoints with the test access  token.
"The provided key 'sk_test_********************IOVG' does not have the required permissions for this endpoint on account 'U3xn...........'. Having more permission would allow this request to continue."}

I get this error now if i disconnect our app from stripe and then reconnect starting the oauth flow and getting a new token, this new token now gets permission denied.   Did something change on your end

**Comment by thecaptainXgod** [comment]
How did you fix it?
