### ISSUE TITLE
No Metadata with List all charges with StripeConnectAccountId option

### ISSUE THREAD

**Issue by hsmith825** [jaymedavis/stripe.net#885]
List all charges does not provide meta data if I use the StripeConnectAccountId.  Here is my code:
 var chargeService = new StripeChargeService();
var response = chargeService.List(new StripeChargeListOptions
                {
                     Limit = 5,
                }, new StripeRequestOptions() { StripeConnectAccountId = stripe_account });
The only thing I see missing in the response is the metatdata.

If I remove the StripeConnectAccountId option as shown in the code below I get the metadata.
var chargeService = new StripeChargeService();
var response = chargeService.List(new StripeChargeListOptions
                {
                     Limit = 5,
                };

Thanks!
Howard

**Comment by jaymedavis** [comment]
In this case, this is because the metadata is probably attached to your account, on your charges. The first code sample is basically impersonating another user - and my guess is those charges for that user don't have the metadata.
