### ISSUE TITLE
TLS 1.2 error from Stripe, even after updating to Stripe.net v9.0.0

### ISSUE THREAD

**Issue by trufun202** [jaymedavis/stripe.net#887]
Hi there,

I have a app that fetches Payouts (formerly called Transfers) on a nightly basis.  This worked well for a while, but Stripe started returning the following error message:

"Stripe.StripeException: Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later."

So, per their documentation, I upgraded to Stripe.net v9.0.0 and refactored my code to use the new PayoutService instead of the TransferService.

When debugging locally, I am able to call _PayoutService.List() and it works perfectly.  However, when I deploy the app to a different server, I get the same "Stripe.StripeException: Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later." error.

I double-checked to make sure that the last exe, app.config, and Stripe.net.dll were all deployed successfully.

Any ideas on why I'm still getting this error?

Thank you!
-Chris B.

**Comment by remi-stripe** [comment]
@trufun202 This likely indicates that your server is not able to negotiate TLS 1.2 requests at all. You might need to reach out to your host provider to discuss the situation and see if they can help upgrade the server.

If it worked before and stopped working though you might want to reach out to our support team directly from [here](https://support.stripe.com/email) to better understand what caused this to fail.

**Comment by trufun202** [comment]
@remi-stripe What changes need to be made on the server itself?  It's an AWS instance running Windows Server Datacenter SP2.  Can this be fixed with a service pack update?

**Comment by remi-stripe** [comment]
@trufun202 I'm not really familiar with Windows development so I'm not sure which version of Windows that represents. You might need to look into your server to find the exact Windows version you're running and should be able to google this afterwards. Otherwise I'd recommend contacting our support team as it's not really an issue with the Stripe.net library.

**Comment by jaymedavis** [comment]
What version of IIS? Is your app a portable app or net45?

**Comment by trufun202** [comment]
@jaymedavis IIS 7 and this is a plain ol' net45 console app.  I'm going to try running Windows Update and hopefully that helps.

**Comment by jaymedavis** [comment]
Which version of windows server? Have you tried something like this? https://tecadmin.net/enable-tls-on-windows-server-and-iis/

**Comment by trufun202** [comment]
@jaymedavis It's an AWS instance running Windows Server Datacenter 2007 SP2.  I tried doing the Registry edits, but that didn't work, unfortunately.  Fingers crossed for Windows Update.

Thanks for your help

**Comment by jaymedavis** [comment]
At the bottom of [this link](https://community.spiceworks.com/topic/589388-enable-tls-1-2-and-tls-1-1-on-a-2008-server), there is a reference to a tool called IISCrypto. It states it only works with 2008+, but it might be worth a try. 

It is possible that a 2007 version is not capable of TLS 1.2 😞  ... something else to try if your updates don't work.

**Comment by tangentmind** [comment]
Try setting the protocol in your code (this worked for my console app):
``ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12``

**Comment by jaymedavis** [comment]
Stripe.net attempts to set the ServicePointManager for you as well - https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Infrastructure/Requestor.cs#L139. 

Closing, as I don't think there's anything to be done from Stripe.net - re-open if you find otherwise!
