### ISSUE TITLE
Missing metadata property in StripeDisputeUpdateOptions.cs

### ISSUE THREAD

**Issue by mvolodin** [jaymedavis/stripe.net#889]
Missing metadata property in StripeDisputeUpdateOptions.cs
Api reference: https://stripe.com/docs/api#update_dispute-metadata

**Comment by fred-stripe** [comment]
Looks like it should be a small addition to add this to:

https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Services/Disputes/StripeDisputeUpdateOptions.cs

Something like this?

```
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata { get; set; }
```

**Comment by mvolodin** [comment]
@fred-stripe yes, you are totally right 👍

**Comment by jaymedavis** [comment]
all of the entities (returned data from stripe) inherit from a class called `StripeEntity` - this is so they will have a `StripeResponse` (raw json data from stripe) property attached to them. In the case of metadata and common properties like this and `LiveMode`, there are probably classes that could be created to save some time typing them everywhere. The only base classes right now are `StripeEntity` and `StripeEntityWithId`. If we knew every object had LiveMode, MetaData, and an Id, we could create a `StripeEntityWithMetaData` or something like that. This class would inherit from StripeEntity, thus we wouldn't have to add this to these classes ever again as one-offs.

If we can find all objects that have a set of properties in common, we could create a base class for them with those properties, and have that class inherit from `StripeEntity`. Then, that option class would inherit from the new class, and automatically have a default set of properties.

Something to think about.

**Comment by jaymedavis** [comment]
this is on master - it will be available via nuget when you see the :ship: commit. 👍

**Comment by fred-stripe** [comment]
Thanks for the explanation and quick fix, @jaymedavis! That seems like a sensible direction for future development. There is a limited set of things that can have metadata applied in the Stripe API, and this seems like a good approach for cleanly representing that in the class hierarchy.

**Comment by jaymedavis** [comment]
I think one of the easier ones would be `LiveMode`. If this is available on every object Stripe returns, we could move that property to StripeEntity and delete it from a couple dozen places? 

I'm not sure what other properties fall in the paradigm along with metadata/live_mode, but I imagine we could get creative with this and simplify things a bit. Thanks!
