### ISSUE TITLE
Remove customer coupon

### ISSUE THREAD

**Issue by AlenaMonson** [jaymedavis/stripe.net#89]
Hi!
I have tried to use this code to remove customer coupon.

var newSubscription = new StripeCustomerUpdateSubscriptionOptions();
newSubscription.CouponId = null;
new StripeCustomerService().UpdateSubscription(stripeCustomer.Id, newSubscription);  

But it doesn't remove coupon.
Empty string coupondID doesn't work too.
newSubscription.CouponId = "";

Is it any chances to remove customer coupon? 
I can do it in the stripe backend so i think it can be possible in lib.

Thank you so much

**Comment by bluee** [comment]
As the previous commit was not merged, can we re-open this issue as it's still not possible.
