### ISSUE TITLE
Just need some clarification on this library

### ISSUE THREAD

**Issue by xplatsolutions** [jaymedavis/stripe.net#895]
I can use it in my Xamarin iOS or Android application creating a custom View to gather the credit card information right? I know it can be done I'm just trying to find out if I'm not breaking any policy etc because there are Xamarin iOS/Android components (https://github.com/xamarin/XamarinStripe) but really old so trying to understand they way to go.

**Comment by jaymedavis** [comment]
Yes, this will work in your app. Don't publish your secret key! 👍 

There is a branch on stripe.net with work started to move this library into the Xamarin store. The nugget package will work fine, though. There are many Xamarin users using stripe.net.

**Comment by xplatsolutions** [comment]
@jaymedavis I used the library from my iOS project to test it out in combination with Stripe iOS SDK and it worked like a charm, I moved the actions needed in a web service now using Stripe.NET and everything works good, thank you for the library.

**Comment by jaymedavis** [comment]
great, thanks @xplatsolutions!
