### ISSUE TITLE
Get callback from user authorization

### ISSUE THREAD

**Issue by saboehnke** [jaymedavis/stripe.net#900]
I have created the button used to allow a user to create a stripe account / login to their account. This should then call back giving me object data such as the StripeUserId (according to the documentation). How do I get this callback data? I have an HttpGet function that is called on the Uri return link so is there an object already created that I use to bind in the GET? Otherwise I'm not seeing where I grab the returned data.

**Comment by tangentmind** [comment]
I believe your answer is in step 4 of the **Connect** example shown in Jayme's documentation

**Comment by saboehnke** [comment]
@tangentmind That just says that you get a code returned from the link. I am trying to figure out how you receive that code when it is passed back in order to get the StripeUserId.

**Comment by saboehnke** [comment]
I'm obviously not seeing something that everyone else is as others have this working fine. @jaymedavis  Do you have a pointer on this?

**Comment by jaymedavis** [comment]
It looks like you had a question regarding the return uri. From memory, that sounds correct to me. What does your button look like? Is it calling your server back where you specified in the return_uri?

**Comment by saboehnke** [comment]
@jaymedavis Yes it does call the link I provided in the return URI. I am just needing to see what object I use to bind when that URI is called so I can get the code that is returned.

**Comment by tangentmind** [comment]
@saboehnke since Stripe issues a simple GET to the redirect URL (e.g. https://localhost:44300/Stripe/Connect?scope=read_write&code=ac_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx), I just pulled the **code** value out of the query string. My test MVC function that handles the redirect looks something like this:
```
Function Connect(Optional ByVal code As String = "", Optional ByVal scope As String = "", Optional ByVal state As String = "") As ActionResult

	' default options
	Dim stripeOptions As New StripeRequestOptions()
	With stripeOptions
		.ApiKey = CLIENT_SECRET
	End With

	' get the OAuth token for future requests (https://github.com/jaymedavis/stripe.net#stripe-connect)
	Dim tokenService As New Stripe.StripeOAuthTokenService()
	Dim tokenOptions As New StripeOAuthTokenCreateOptions() With {
			.ClientSecret = CLIENT_SECRET,
			.Code = code,
			.GrantType = "authorization_code"
		}

	' call Stripe to get a token
	Dim stripeToken As StripeOAuthToken = tokenService.Create(tokenOptions, stripeOptions)

	' store this for future "Connect" requests...
	Dim userId As String = stripeToken.StripeUserId

	Return View()
End Function
```
You could also pull the value directly from the request:
```
Dim code as String = Request("code")
```
Does that answer your question?

**Comment by jaymedavis** [comment]
Thanks @tangentmind!

This is correct, it's just a couple of URL parameters you can grab from querystring: https://stripe.com/docs/connect/standard-accounts#redirected

**Comment by saboehnke** [comment]
Thanks @tangentmind  and @jaymedavis. That is exactly what I needed.
