### ISSUE TITLE
Payments

### ISSUE THREAD

**Issue by EmmaHansson** [jaymedavis/stripe.net#901]
It could be really cool to retrieve payment for a customer:

https://dashboard.stripe.com/payments?customer=cus_lkmsdolfmoeirmfo

At least I couldn't find in Wiki this method.

**Comment by tangentmind** [comment]
Is that the same as retrieving the list of **Charges** for a customer by passing in the **CustomerId** as part of the **StripeChargeListOptions**?

**Comment by EmmaHansson** [comment]
Oh I simply get confused. Thanks for a hint.
