### ISSUE TITLE
StripeEvent.Parse failing for all webhooks for 25-5-17 API version

### ISSUE THREAD

**Issue by zrilo** [jaymedavis/stripe.net#908]
@jaymedavis Stripe.net will is no longer working when attempting to parse JSON to a StripeEvent object on the latest 25-5-17  version. Anyone using Stripe.net with the latest version for webhooks will be unable to process them using the library.

StripeEventUtility.ParseEvent(jsonContent) will currently fail due to latest api change:
**"Event objects (and webhooks) will now render a request subobject that contains a request ID and idempotency key instead of just a string request ID."**

Hope you can address this asap

Thanks

**Comment by jaymedavis** [comment]
This will be addressed soon. Before it is, you can have Stripe downgrade your API version to match the one Stripe.net uses (in StripeConfiguration.cs)

**Comment by TomGullen** [comment]
Can confirm this, rolled our Stripe API back to 2017-04-06 but am still using Stripe.net 9.0.0 and it's working fine.  Will wait before upgrading Stripe API.

**Comment by EmilBechMadsen** [comment]
For anyone interested; this is fixed in the 10.0.0.0 release.
