### ISSUE TITLE
Publishable key sent, but only secret keys can be used

### ISSUE THREAD

**Issue by saboehnke** [jaymedavis/stripe.net#909]
Any idea why I would be getting this error even though I am passing in the test secret key that I get from stripe? "Publishable key sent, but only secret keys can be used"

    `var stripeOAuthTokenService = new StripeOAuthTokenService();
     var _stripeOAuthTokenCreateOptions = new StripeOAuthTokenCreateOptions()
     {
         ClientSecret = ConfigurationManager.AppSettings["StripeSecret"],
         Code = response.Code,
         GrantType = "authorization_code"
     };

     StripeOAuthToken stripeOAuthToken = stripeOAuthTokenService.Create(_stripeOAuthTokenCreateOptions);`

It happens when I try to create the stripeOAuthToken object above.

**Comment by tangentmind** [comment]
@saboehnke I think I had to set my API key as well. Try adding the following just before your code:
```
StripeConfiguration.SetApiKey(ConfigurationManager.AppSettings["StripeSecret"]);
```

**Comment by saboehnke** [comment]
@tangentmind I only need to set the api once so I do it earlier. It happens in the first view that is loaded. The code that gets the stripeOAuthToken is in a different view all together. Do you think that matters?

**Comment by tangentmind** [comment]
@saboehnke I'm not certain. But what I found helpful was to run Fiddler (http://www.telerik.com/fiddler) so that I could see what my application code was sending to the Stripe servers and what I was getting back from them. I think you will have your answer once you see what your application is sending to the servers.

**Comment by jaymedavis** [comment]
What's the first five characters of *StripeSecret* in your config?

**Comment by jaymedavis** [comment]
If it doesn't start with sk_live, then you are probably sending the wrong key as the error states. Fee free to re-open if that doesn't fix it!

**Comment by saboehnke** [comment]
@jaymedavis it is the test key so it starts with sk_test.

**Comment by jaymedavis** [comment]
I'm with @tangentmind on trying fiddler. It's a very useful tool for working with stripe.net in general too. Make sure the right key is showing in fiddler. (sk_test should be correct to my knowledge)

**Comment by saboehnke** [comment]
@tangentmind @jaymedavis I still need to look into using fiddle but I am not really sure how much it will help here if I know what code it is sending. It can't be sending a different code when I am passing in a specific one.

**Comment by saboehnke** [comment]
@tangentmind @jaymedavis I gave fiddler a shot and I see that there is no call made after I get the response code back. So fiddler doesn't show anything with the call to create the stripeOAuthToken. Any ideas?

**Comment by jaymedavis** [comment]
What was the issue with the key? Was it sending what you were not expecting?

Is your code the same as above? I would step through it with your debugger and make sure that Create call is firing.

**Comment by saboehnke** [comment]
I'm saying that I only see where I get the response code back. I don't see anything from when I actually try to get the stripeOAuthToken. So I can't see what key it is sending. Either way I have no idea how it could be sending any other key than what I am giving it, which is my test secret key. I have no idea why it is not accepting my secret key.
