### ISSUE TITLE
Question: getting api keys.

### ISSUE THREAD

**Issue by EmmaHansson** [jaymedavis/stripe.net#910]
I need to retrieve public api keys in program way using my secret key.
Is that possible?

P.S. https://dashboard.stripe.com/account/apikeys

**Comment by remi-stripe** [comment]
@EmmaHansson This is not something you can do, the API keys are only available from the dashboard and you have to manually go in the dashboard and copy paste those in your code.

**Comment by MatthewGabriel** [comment]
> paste those in your code
Should be stored somewhere a bit safer than in your code?

**Comment by remi-stripe** [comment]
@MatthewGabriel Sure you can put those in environment variables for example for improved security. I was just explaining how to get started here where getting your API keys would be one of the first step when building your integration from the beginning but it's a good idea to mention this upfront.

**Comment by EmmaHansson** [comment]
That's very very sad. About public key. Sure it's secure do not have a secret key by request. But I don't think it's secure  spreading pubic key by applications and disallowing spread it through your REST service.

**Comment by EmmaHansson** [comment]
Sniffing stripe.com usage - they have public key at the page using ajax GET call. So I don't thing it's so secure also.
