### ISSUE TITLE
if we create a customer with different current culture than US stripe return an error for a decimal.

### ISSUE THREAD

**Issue by jobou363** [jaymedavis/stripe.net#911]
I receive an error, like the one bellow, I know it's because stripe.net do a conversion to string and use the culture of my application that is fr-CA so the decimal with toString() are converted with a comma and send to stripe that way. 

**Failed to create stripeCustomer: Stripe.StripeException: Invalid decimal: 14,97500**
   at Stripe.Requestor.ExecuteRequest(HttpRequestMessage requestMessage)
   at Stripe.Requestor.PostString(String url, StripeRequestOptions requestOptions)
   at Stripe.StripeCustomerService.Create(StripeCustomerCreateOptions createOptions, StripeRequestOptions requestOptions)

So in the create option, for the taxe percentage, I use a decimal of 14.75 that is converted to a string "14,75".
https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Services/Customers/StripeCustomerCreateOptions.cs

[JsonProperty("tax_percent")]
public decimal? TaxPercent { get; set; }

I'm wondering how we should modify stripe.net so that I don't have to modify my application current culture just to create the customer?

**Comment by jaymedavis** [comment]
what version of stripe.net are you using? this has came up before in #801
