### ISSUE TITLE
Express accounts login link

### ISSUE THREAD

**Issue by crono009** [jaymedavis/stripe.net#913]
I might be missing something, but is there a way to create the login link for connected express accounts so they can access their stripe dashboard or is this functionality not added yet for this library? I can't seem to find a login_link object/service.

For more information visit this link:
https://stripe.com/docs/connect/express-dashboard

**Comment by tangentmind** [comment]
Have you tried creating a simple link that points to https://dashboard.stripe.com/login ?

**Comment by remi-stripe** [comment]
@crono009 I've just submitted a PR for this feature so we can hopefully have it merged after review in a few days: https://github.com/jaymedavis/stripe.net/pull/924

**Comment by jaymedavis** [comment]
this will go out when you see the :ship: commit - it's on master now
