### ISSUE TITLE
Implementing manual Payout in Stripe Connect using Stripe.net

### ISSUE THREAD

**Issue by AnandarajS** [jaymedavis/stripe.net#918]
Hi Friends,
                  In my application, I have created a platform and then added connected accounts to that platform. I made amount transfer from a customer card to that connected account. My application is a Dot Net MVC one.  The problem is I have to implement an Escrow like functionality. For that, I have to hold the entire amount paid by the customer in the platform account and then transfer to the connected account upon completion of a job. For this functionality, I need to make use of Manual Payout functionality. Can I use this manual payout functionality in Stripe Connect using Stripe.net. If so, Can u please provide me some guidance?

**Comment by remi-stripe** [comment]
@AnandarajS For questions like this, you should talk to our support team directly. You can contact them from our [contact form](https://support.stripe.com/email).

In your situation, you can hold funds for up to 90 days in the connected account and you'd simply switch that account to [manual payouts](https://stripe.com/docs/connect/payouts#payout-schedule). You would call the [Account Update API](https://github.com/jaymedavis/stripe.net#updating-an-account) and set [TransferScheduleInterval](https://github.com/jaymedavis/stripe.net/blob/1ae242b308c601a31a062ffb61c8873bffac5782/src/Stripe.net/Services/Account/StripeAccountSharedOptions.cs#L96) to `manual`.

**Comment by AnandarajS** [comment]
Thank you @remi-stripe !!!
