### ISSUE TITLE
How do i get "CustomerId" for bank account

### ISSUE THREAD

**Issue by paterninaisf** [jaymedavis/stripe.net#920]
Hey, thank for your library is awesome

Currently, i'm updating a Bank Account of a **Connected Account** and i'm using this code:

```
var bankAccountService = new BankAccountService();
CustomerBankAccount bankAccount = bankAccountService.Update(*customerId*, *bankAccountId*, myBankAccount);
```

but I don't know how I a get the `customerId`, it's directly from stripe account dashboard or any other place?

I'm not sure if that is the correct code for update the **Bank Account of a Connected Account**
not of **Customer account**

Thanks!

**Comment by remi-stripe** [comment]
@paterninaisf You wouldn't use that API call as it updates a bank account set on a customer. Instead, you would update the account itself and set a new bank account token to replace the existing bank account by a new one. This is done in the tests [here]()

	var myAccount = new StripeAccountUpdateOptions()
        {
                ExternalBankAccount = new StripeAccountBankAccountOptions
                {
                    TokenId = "btok_XXXXX";
                }

        };

	var accountService = new StripeAccountService();
	StripeAccount response = accountService.Update("acct_XXXXX", myAccount);
