### ISSUE TITLE
Upgrading Stripe API version

### ISSUE THREAD

**Issue by NeoHub** [jaymedavis/stripe.net#921]
Hey guys!

I'm thinking to migrate the API version from my stripe account to the latest one (2017-06-05), but I have a very old version and I'm afraid that what I have `Live` could break. According to what says here: https://stripe.com/docs/upgrades#api-changelog, I could test the new version passing the `Stripe-Version` header to the requests I made without actually upgrading the API. Do we have a way to pass that header in Stripe.net?

**Comment by remi-stripe** [comment]
@NeoHub Stripe.net always force a specific API version in the code. Recently, the library moved to `2017-05-25` so any API request you make using the latest version of Stripe.net would use that API version automatically.

The only caveat is that events (for webhooks) are generated using your account's API version and you wouldn't be able to easily parse those via Stripe.net.

**Comment by jaymedavis** [comment]
Stripe.net is on 2017.06.05. You can find the current version [here](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Infrastructure/Public/StripeConfiguration..cs).

You can override this setting if you want, but I would recommend going through the release notes on this site instead. It explains every change in every release.

**Comment by remi-stripe** [comment]
@jaymedavis oh I missed that you upgraded to the latest!

If you override the version, wouldn't the code break on breaking changes?

**Comment by jaymedavis** [comment]
Yes it would - I would never recommend changing that setting, but a few have wanted it. That's why it's public but not documented.

**Comment by darshitgandhi** [comment]
@jaymedavis  Could you please answer my doubt - Is there any version specified in stripe.dll?

**Comment by ob-stripe** [comment]
@darshitgandhi Yes, the stripe-dotnet library is pinned to a specific API version: https://github.com/stripe/stripe-dotnet/blob/7cb8daa0e826ea2a150329759952f29e4fa00a1f/src/Stripe.net/Infrastructure/Public/StripeConfiguration.cs#L10

**Comment by AmitaKhatri** [comment]
@ob-stripe The latest stripe API version is "2018-02-28" and we want to upgrade our account to it. Would it be ok if the dlls is communicating with the account with "2018-02-06" version? Will it generate an exception?

**Comment by ob-stripe** [comment]
@AmitaKhatri If you use the stripe-dotnet library, it will use its pinned API version, not your account's default API version. So it's safe to upgrade your account's default API version to 2018-02-28, but your requests emitted with stripe-dotnet will still be executed as 2018-02-06.

**Comment by AmitaKhatri** [comment]
Thanks, @ob-stripe !!

I was under impression that once I upgrade the API version in my Stripe account, I would not be able to request with lower API version. 

Is there any limit of the lowest version I can request with on the Account with API version "2018-02-28"?

**Comment by jaymedavis** [comment]
@ob-stripe It used to be the case that a mismatch api version between what’s pinned and what the user chose could cause issues with webhooks. Is that not the case anymore?
