### ISSUE TITLE
SourceToken property is missing

### ISSUE THREAD

**Issue by haf** [jaymedavis/stripe.net#923]
https://github.com/jaymedavis/stripe.net#creating-a-customer

<img width="573" alt="screen shot 2017-06-11 at 13 47 57" src="https://user-images.githubusercontent.com/193115/27010760-9dd21334-4eac-11e7-945a-850a3a15d7cb.png">

**Comment by remi-stripe** [comment]
@haf This property exists but it's part of the `StripeCustomerUpdateOptions` or `StripeCustomerCreateOptions`, it doesn't live directly on the Customer. It's hard to know for sure without reading your full code here. Otherwise, it's possible that you're on a version too old of Stripe.net before this property was added.

**Comment by haf** [comment]
I'm just following the README. https://github.com/jaymedavis/stripe.net#customers And there's such a property.

How do I write these two lines of code with this API?

```
        customer = stripe.Customer.create(
            email=request.form.get('stripeEmail'),
            source=request.form.get('stripeToken')
        )

        stripe.Subscription.create(
            customer=customer.id,
            plan="base-plan"
        )
```
?

**Comment by remi-stripe** [comment]
Creating a customer would look like this:

	var myCustomer = new StripeCustomerCreateOptions();
	myCustomer.Email = "example@email.com";
        myCustomer.SourceToken = "tok_XXXXX";

	var customerService = new StripeCustomerService();
	StripeCustomer stripeCustomer = customerService.Create(myCustomer);

Creating the subscription would look like this:

	var subscriptionService = new StripeSubscriptionService();
	StripeSubscription stripeSubscription = subscriptionService.Create(stripeCustomer.Id, "base-plan");

You need to make sure that you are on the latest version of Stripe.net if you're just getting started.

**Comment by haf** [comment]
Thank you!
