### ISSUE TITLE
Business Name not work for Legal Entity

### ISSUE THREAD

**Issue by paterninaisf** [jaymedavis/stripe.net#925]
Hey @jaymedavis Hello!

I updating the option **Legal Entity** for **Connected Account** in stripe, specifily the **Bussines Name** and I using the code bellow:

`accountOption.LegalEntity.BusinessName = "Business name"`

and this other 

`accountOption.BusinessName = "Business name"`

But none works, the field Name is _Not provided_ in stripe board, any recommendation, please?
![image](https://user-images.githubusercontent.com/19295280/27038986-3872cdc0-4f52-11e7-82a9-dc61cc475697.png)

**Comment by remi-stripe** [comment]
@paterninaisf This is not an issue with Stripe.net but an issue with Stripe's dashboard. I've confirmed that setting both details doesn't affect the dashboard even though it should. I'll work with our engineering team to work on a fix for this on our end.
