### ISSUE TITLE
updating account - Invalid request (check your POST parameters)

### ISSUE THREAD

**Issue by stephen1977** [jaymedavis/stripe.net#926]
trying to update account using the following code

```
StripeAccountEntityFromSql stripeAccountDetails;
            StripeLegalEntity stripeLegalEntity;
            _smartStripeService.LoadTheStripeDetailsFromTheClubDatabase(context.Message.ApiKey, out stripeAccountDetails, out stripeLegalEntity);


            if (string.IsNullOrWhiteSpace(stripeAccountDetails.StripeAccountId))
            {
                return;
            }

            if (stripeLegalEntity == null) throw new NoStripeLegalEntityDataSetupException(context.Message.ApiKey);

            var stripeAccountToUpdate = _smartStripeService.MapUpStripeUpdateEntity(stripeAccountDetails, stripeLegalEntity);

            var accountService = new StripeAccountService();

            try
            {
                
                var response = await accountService.UpdateAsync(stripeAccountDetails.StripeAccountId,stripeAccountToUpdate);
                if (response.Id == null)
                {
                    throw new CouldNotUpdateStripeAccountException(context.Message.ApiKey);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw new CouldNotUpdateStripeAccountException(context.Message.ApiKey, ex);
            }

        }

```
getting the following exception. 

Stripe.StripeException: Invalid request (check your POST parameters): unable to determine value for parameter: external_account. For assistance, please email support@stripe.com.
   at Stripe.Infrastructure.Requestor.<ExecuteRequestAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stripe.StripeAccountService.<UpdateAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by remi-stripe** [comment]
@stephen1977 I'd recommend contacting support directly for this so that we can look into your logs. It's hard to read this code because we're missing key information (What you're really sending in each property) so make sure to also include more details about your code so that our support team can help!

You can contact them here: https://support.stripe.com/email

**Comment by HongLouWang** [comment]
You are zero for them, that's how they do businese.
