### ISSUE TITLE
Updating the charge call to send multiple destinations

### ISSUE THREAD

**Issue by KennyKaplanHP** [jaymedavis/stripe.net#927]
The Stripe API now allows multiple destinations when creating a charge. When is that likely to be available via Stripe.Net?

**Comment by remi-stripe** [comment]
@KennyKaplanHP The charge doesn't need to be updated. What your integration needs to do is create a charge on the platform and then later transfer funds to  one or multiple connected accounts using `transfer_group` as documented here: https://stripe.com/docs/connect/charges-transfers

This feature already exists in Stripe.net today and can be used as is.

**Comment by KennyKaplanHP** [comment]
Why bother with this process? Stripe doesn't want us to use transfers for more than 10% of our charge transactions and we're a marketplace that sells items on behalf of many sellers. To enable a true shopping cart that pays each seller the optimal way is to use the multiple destinations on the charge so that it's a single transaction tied to the payment instead of maintaining a separate payout.

**Comment by remi-stripe** [comment]
@KennyKaplanHP That's not exactly true anymore. Splitting charges is now allowed beyond 10% of your volume in some countries (though not all). The `transfer_group` parameter allows you to tie together one (or multiple) charges to one (or multiple) transfers to connected accounts making the flow compliant. This is covered in details in the new documentation that we published and that I shared above: https://stripe.com/docs/connect/charges-transfers

I would recommend contacting our support team directly to discuss your business model and whether splitting charges is allowed in your country. You can talk to them here: https://support.stripe.com/email

**Comment by KennyKaplanHP** [comment]
Thanks for the info. Glad to know that's the supported route!
