### ISSUE TITLE
Updating invoice with coupon Id fails

### ISSUE THREAD

**Issue by AnuranPal** [jaymedavis/stripe.net#928]

**Comment by AnuranPal** [comment]
var stripeInvoiceUpdateOptions = new StripeInvoiceUpdateOptions();
                stripeInvoiceUpdateOptions.CouponId = "xxxxxxx";
                var invoiceService = new StripeInvoiceService();
                StripeInvoice response = invoiceService.Update("xxxxxxxxxx", stripeInvoiceUpdateOptions);
The above code throws an exception saying that coupon is not a valid parameter.

**Comment by remi-stripe** [comment]
@AnuranPal Our Update Invoice API does not support the `coupon` parameter as documented here: https://stripe.com/docs/api#update_invoice

You can not set a coupon on an invoice, the coupon has to be part of a subscription or the customer object.

**Comment by jaymedavis** [comment]
CouponId is on StripeUpdateInvoiceOptions. Reopening this for it to be removed.

**Comment by jaymedavis** [comment]
this will be handled when #931 is merged
