### ISSUE TITLE
Add a source without replacing the existing one under a customer

### ISSUE THREAD

**Issue by jsgoupil** [jaymedavis/stripe.net#934]
I am unable to add a source under an existing customer without deleting the default card associated with this customer.

I am trying to add a bitcoin source under a customer.

The following code will erase the source:

    new Stripe.StripeCustomerService(this.stripeApiKey).Update('customerId', new StripeCustomerUpdateOptions
                {
                    SourceToken = 'new-source-id'
                }))

Request is done as such:
POST /v1/customers/cus_ArLPysgKPIV6Er
source=src_1AVcj3Hp6ceJshIcTVCwuP8z

However, if the request were done like this:
POST /v1/customers/cus_ArLPysgKPIV6Er/sources
source=src_1AVcj3Hp6ceJshIcTVCwuP8z

My source would be correctly added.

**Comment by remi-stripe** [comment]
@jsgoupil You can use the Creating a card [API](https://github.com/jaymedavis/stripe.net#creating-a-card) and pass the source as the `SourceToken` and it will just work as expected.

**Comment by jsgoupil** [comment]
This workaround is working... Definitely not the first thing it would come to people's mind.
Thanks.

**Comment by jaymedavis** [comment]
Is there anything to fix here @remi-stripe? Is the purpose of source on a customer to be set only when there's not an existing source?

What error/exception did you receive @jsgoupil?

**Comment by jsgoupil** [comment]
No exception here, I guess "replacing" the default source might be the right thing when attaching the SourceToken on the customer, albeit quite obscure.
However adding a bitcoin source via the Card API to a customer does not make much sense to me.

**Comment by jaymedavis** [comment]
```StripeSourceService``` should have what you need?

**Comment by jsgoupil** [comment]
That doesn't make a connection to a customerId in Stripe.

**Comment by jsgoupil** [comment]
@jaymedavis so what is the proposition? To use the card API for bitcoin source ?

**Comment by jaymedavis** [comment]
If you want to create a bitcoin source, you do that via the StripeSourceService. When you have your source id, pass the source id to the card api as Remi stated.

**Comment by jsgoupil** [comment]
Alright. Quite confusing then. Thanks.

**Comment by last1here** [comment]
I too wouldn't have thought to do this without finding this issue. Possibly add the process to the docs?
