### ISSUE TITLE
Error when applying application fee to charge

### ISSUE THREAD

**Issue by saboehnke** [jaymedavis/stripe.net#936]
I am attempting to apply an application fee to a charge that is being made on behalf of a customer. Currently when I try to do this I get the following error: `Can only apply an application_fee when the request is made on behalf of another account (using an OAuth key, the Stripe-Account header, or the destination parameter).`

When the customer accounts are initially created I get the StripeOAuthToken and I then save the customer's Stripe UserID in my database so I can access it later for charges to be made on their behalf. If there is no issue with doing that then I really don't have any idea what could be going wrong here.

Here is a snippet of my code: 

```
var myCharge = new StripeChargeCreateOptions();
 myCharge.Amount = Convert.ToInt32(paymentForm.Amount * 100);
 myCharge.Currency = "usd";

 string[] tokens = paymentForm.Expiration.Split('/');

 myCharge.SourceCard = new SourceCard()
 {
        Number = paymentForm.CardNumber,
        ExpirationYear = Convert.ToInt32(tokens[1]),
        ExpirationMonth = Convert.ToInt32(tokens[0])
 };

 myCharge.ApplicationFee = Convert.ToInt32((paymentForm.Amount * 100) * Convert.ToDecimal(.025f));
 myCharge.Capture = true;

 StripeRequestOptions options = new StripeRequestOptions()
 {
       ApiKey = ConfigurationManager.AppSettings["StripeApiKey"],
       StripeConnectAccountId = "StripeUserIDFromDatabase"
 };

 var chargeService = new StripeChargeService();
 StripeCharge stripeCharge = chargeService.Create(myCharge, options);
```

**Comment by remi-stripe** [comment]
@saboehnke That error usually indicates that the value you put in `StripeConnectAccountId` is your own account id and not one of your connected accounts. The solution is to create a new Stripe account in Test mode so that you can go through the OAuth flow again with that account and get a different account id than your own.

**Comment by saboehnke** [comment]
@remi-stripe  So in that case I assume that I need to make an account for each customer when I create the customer then? Is that correct? Right now I am just creating a customer.

**Comment by remi-stripe** [comment]
@saboehnke you're mixing `Customers` which represent the person who pays for a service with `Connected Accounts` which represents the recipient of the funds. I'd recommend talking to our support team directly [here](https://support.stripe.com/email)

**Comment by saboehnke** [comment]
@remi-stripe That is why I have come back here. I talked to the support team and we have been going back and forth on this. A breakdown of what I am doing is I offer services to institutions. Each institution subscribes and pay a monthly fee to me to use the services. I create a StripeCustomer for each of these institutions. Once subscribed, each institution can users that use the services that they offer. So a user will eventually pay an institution for the services on my site. I need to be able to accept the payment on the customer's behalf and apply an application fee to it.

**Comment by remi-stripe** [comment]
@saboehnke Stripe.net offers a way to use Stripe's API in .Net. The issues on the repository should be limited to technical issues with the library itself. Here, that's not the issue, you should talk to our Support team and someone will help you work this out since it's a confusion on how to use Connect and a question about the implementation and not a bug in the library itself.
