### ISSUE TITLE
How can i change/update the subscription with new plan and change/update the customer with new plan

### ISSUE THREAD

**Issue by arunp90** [jaymedavis/stripe.net#939]
I was seen the code for update the subscription and customer.
when creating the customer or subscription you are passing the plan parameter.
when change/update the customer or subscription you aren't using the New plan

**Comment by remi-stripe** [comment]
@arunp90 To update a subscription you simply follow the documentation outlined [here](https://github.com/jaymedavis/stripe.net#updating-a-subscription). It takes an optional `StripeSubscriptionUpdateOptions` and the code is [here](https://github.com/jaymedavis/stripe.net/blob/83d280441218c45833682f05fdfd0445ca7e261d/src/Stripe.net/Services/Subscriptions/StripeSubscriptionUpdateOptions.cs).

You can always refer yourself to the Test suite to find examples on how to call that API, for example [this one](https://github.com/jaymedavis/stripe.net/blob/d726890e7da65b345c448fbbc364e1abaeaf3f52/src/Stripe.net.Tests/subscriptions/when_updating_a_subscription.cs) changes the subscription's quantity.

If you have follow up questions, I'd recommend talking to our support team [here](https://support.stripe.com/email) and share your existing code and they can help you fix this.

**Comment by Claytonious** [comment]
None of the links in that answer work.

**Comment by jlomas-stripe** [comment]
If you're seeing a '500 Server Error', then that's just Github having some kind of issue.  I just had that happen, but they appear to be working now.
