### ISSUE TITLE
StripeLoginLinkService not found

### ISSUE THREAD

**Issue by crono009** [jaymedavis/stripe.net#941]
I'm currently trying to manage express accounts and I would like to be able to give our users access to their express dashboard. This has been added in recently by user "remi-stripe".  I've updated my Stripe.net package and am currently on version 10.0.0.0

However, while following the readme instructions, I tried to create the loginlink by utilizing the Entity "StripeLoginLink" and Service "StripeLoginLinkService" with the following lines of code:

`var loginLinkService = new StripeLoginLinkService();`
`StripeLoginLink loginLink = loginLinkService.Create(*accountId*);`

I then receive the error "StripeLoginLinkService could not be found". Am I having a brain fart or is there a solution for this?

**Note:** I'm sure this is unintended, but not sure if this is related or causes issues, but while looking through the code, I expected to find a folder for "LoginLink" in the services folder, however it is instead inside the Cards folder under services.

**Comment by jaymedavis** [comment]
This has not been shipped yet. I will take care of this tomorrow. Thanks much for pointing this out so I can move it to the services folder.

**Comment by crono009** [comment]
I see the newest version is 10.1.0. How long does it normally take for Nuget to update to that version?
