### ISSUE TITLE
Version 10.1.0 not on Nuget yet?

### ISSUE THREAD

**Issue by crono009** [jaymedavis/stripe.net#945]
I'm not sure if I'm updating the package incorrectly, but I can't seem to get the latest version of Stripe.net from Nuget. What is the average time for the nuget version to get updated or is there a better way I should stay up to date with Stripe.net?

**Comment by jaymedavis** [comment]
I believe the build file is missing the artifacts now that the nuget provider looks for. It should have pushed immediately, I'm working on this now.
